### ISSUE TITLE
Move kuma to the mdn org

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#5612]
In Portland, 2019 work week decided to move kuma (this repo) from the `mozilla` org to the `mdn` org. 

- [x] Send out a communication about this
- [x] Do the actual transfer
- [x] Make sure TravisCI works
- [x] Email out instructions for people with local checkouts (e.g. `git remote set-url ...`)
- [ ] Check that Jenkins (Groovy) code still works
- [ ] [Edit mentions of `github.com/mozilla/kuma` in the repo code (e.g. rst, and code comments)](https://github.com/mdn/kuma/pull/6019)
- [ ] Find out what kind of enterprise account "mozilla/kuma" is on in Travis and if using "mdn/kuma" instead would make our resource usage of Travis drop. 
- [x] Edit "Repository URL" on https://readthedocs.org/dashboard/kuma/edit/

**Comment by callahad** [comment]
- [ ] Trawl through the first few pages of results for searching `kuma site:mozilla.org` and update where possible.

**Comment by peterbe** [comment]
>     * Trawl through the first few pages of results for searching `kuma site:mozilla.org` and update where possible.

Well, technically the search is `github.com/mozilla/kuma site:mozilla.org` and today it shows up a LOT of bugzilla tickets. Those will have to be left as is. GitHub.com will be responsible of redirecting those.

**Comment by tobinmori** [comment]
Diminished Benefits now that Zenhub works across orgs-

Might help with 
- team cleanup
- organizational cleanup

**Comment by escattone** [comment]
See https://github.com/mdn/kumascript/pull/1260

**Comment by escattone** [comment]
I also updated the link to Kuma in `README.md` of https://github.com/mozilla-l10n/mdn-l10n

**Comment by escattone** [comment]
I also updated all of the references to the Kuma repo within the strings within https://github.com/mozilla-l10n/mdn-l10n (see https://github.com/mozilla-l10n/mdn-l10n/commit/ce89753afd110de259d822935292f64664f537c8).
