### ISSUE TITLE
Connect Sentry to Kuma GitHub issues

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#5650]
I could set it up now. (I think, assuming the relevant permissions)

<img width="770" alt="Screen Shot 2019-08-16 at 12 05 37 PM" src="https://user-images.githubusercontent.com/26739/63181546-3d35d200-c01e-11e9-89b8-9ad944d15da7.png">

Let's do this once we've [moved to `mdn`](https://github.com/mozilla/kuma/issues/5612).

**Comment by tobinmori** [comment]
wait until Kuma is moved on this one.

**Comment by peterbe** [comment]
Unable :(

<img width="1616" alt="Screen Shot 2019-10-21 at 8 20 02 AM" src="https://user-images.githubusercontent.com/26739/67204551-bc0f0880-f3db-11e9-86ad-2dc9f6b54f81.png">

**Comment by peterbe** [comment]
Note-to-self; [Staga](https://sentry.prod.mozaws.net/settings/operations/mdn-stage/issue-tracking/) and [Prod](https://sentry.prod.mozaws.net/settings/operations/mdn-prod/issue-tracking/)

**Comment by tobinmori** [comment]
Waiting for answer from CloudOps.

**Comment by peterbe** [comment]
This has been set up now.
