### ISSUE TITLE
JavaScript that can be deferred should be deferred

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#5672]
We have JS that loads like `<script src="/static/react-stuff.sj">` but we might benefit from adding `defer` and load them the `<head>` instead. 
E.g. https://flaviocopes.com/javascript-async-defer/

**Comment by Shivansh2407** [comment]
Can You please clearly mention out the file we need to look in for this issue?

**Comment by peterbe** [comment]
There are a couple of places. First, the files that use `{% javascript '...' %}` in various `*.html` jinja files. 
Then, in the `PIPELINE_JS` there's the option for `extra_context` (I think it's called) that needs to have `defer: True` or something.

**Comment by ankiiitraj** [comment]
@peterbe  I want to contribute in this issue, can you assign me this issue. Thanks

**Comment by peterbe** [comment]
> @peterbe I want to contribute in this issue, can you assign me this issue. Thanks

We don't do that unless you're a core contributor. Make a pull request and hope that your PR came in first.

**Comment by Shivansh2407** [comment]
Can You please list all the files so that I can work and complete this issue....Please let me know soon

**Comment by ankiiitraj** [comment]
@peterbe Thanks for the help.

**Comment by ankiiitraj** [comment]
Hi @peterbe little help. How to do changes on {% javascript '...' %} in various *.html jinja files.

**Comment by peterbe** [comment]
The `{% javascript 'some-thing' %}` tag in a Jinja template basically corresponds to what's in `PIPELINE_JS` in `kuma/settings/common.py`. 
For example, look at: https://github.com/mozilla/kuma/blob/f28dd92eab09dd3fbabc927b0e15da9ea8d98229/kuma/settings/common.py#L953-L963

What this means it the key is `banners` so you'd type: `{% javascript 'banners' %}` and would turn that into `<script src="/static/build/js/banners.js" async></script>`

So in your case wouldn't use `'async': True` but `'defer': True` instead.

**Comment by ankiiitraj** [comment]
Hi @peterbe I see that some of these has been deferred but some are not, like 'main', 'jquery-ui', 'payments'. These are not meant to be deferred or I should defer them.
How to know which should be deferred and what shouldn't?
Thanks.

**Comment by peterbe** [comment]
I'm sorry that this is so tricky. But one learns from doing what's *not* easy.
Before it was like this:

```
<script src="a.js" defer></script>
<script src="b.js"></script>
<script src="c.js" async></script>
<script src="d.js"></script>
<script src="e.js" defer></script>
<script src="f.js" async></script>
```
Indpendent of *where* in the DOM these are, this is the expected exection order:
1. b.js
2. d.js
3. c.js (maybe!)
4. f.js (maybe!)
5. a.js
6. e.js

Actually, when c.js and f.js executes is 100% unreliable. They executes when it feels like it's ready. You basically can't guarantee that their order. Not even between themselves. 

All the ones that don't use `async` are executed in the order they appear from top to bottom. 
The question is, for each and every file, **Is it OK to execute it AFTER the DOM has been downloaded, parsed, and built?**

For example, imagine you had this:
```
<script src="a.js"></script>
<script src="b.js"></script>
```
And
```javascript
// a.js
var div = document.createElement('div')
div.id = 'foo'
document.body.appendChild(div)
```
```javascript
// b.js
console.log(document.querySelect('#foo').textContent);
...
```
If b.js requires that a.js is loaded first. So what happens if you put a `defer` on `<script src="a.js"></script>`?

**Comment by ExE-Boss** [comment]
If you put it on both `a.js` and `b.js`, then it will be fine, but for `a.js`, `document.body` might be `undefined` when it executes, unless they both do that in a `DOMContentLoaded` event listener.

Note that `DOMContentLoaded` event listeners are executed in the registered order, so `b.js`’s event listener would be called before `a.js`’s if only `a.js` has `defer`, which would still break things.

**Comment by peterbe** [comment]
You're ruining the exercise by giving away the answer @ExE-Boss  :)
