### ISSUE TITLE
Can *some* CSS be inlined and the rest lazy loaded?

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#5673]
Getting the near-perfect "critical CSS" out of our large bundle is non-trivial. But perhaps, it's possible to break up the bundle into the files are definitely necessary on every page and those we might be able to serve inline rather than having them as blocking CSS. 

The task here is to find a way to experiment with this so it can be tested.

**Comment by peterbe** [comment]
Actually, another option is to just break up the CSS bundle (aka. `react-mdn.css`) into smaller "sub-bundles". Either as multiple little bundles or some important and some not important and then see if that helps perf.

**Comment by Gregoor** [comment]
Wondering what good way to achieve given our architecture, pretty sure there's nothing out-of-the-box for this as all the webpack plugins that help with critical CSS extraction want control over the HTML (which is with Jinja in our case).

Do we prerender all the document pages? I guess another option would be running a tool such as [critical](https://github.com/addyosmani/critical) on every single html file, if that's the case.

**Comment by atopal** [comment]
Yes, we do pre-render all document pages for a quick first start.

What would it take to move away from Jinja (assuming that's the only reason we can't do this at the moment)

**Comment by Gregoor** [comment]
We'd have to move most of the assset management over from Django to Webpack, it seems doable to me, but that might be because I'm lacking context. cc @peterbe @escattone 

Alternatively we could call a slim node service that runs osmani's critical on the generated documents.

So I guess the question is: More or fewer layers?

**Comment by peterbe** [comment]
> Yes, we do pre-render all document pages for a quick first start.

I'm not sure what you mean by that. We pre-render the kuma Wiki content into a big blob of HTML. It's the `Document.body_html`. I think it contains the sidebar. But we don't store the whole rendered HTML document. In a sense, we "store" it in the CDN but that's not something we can manipulate. 

There are two ways to extract the minimal CSS. With tools like [`minimalcss`](https://github.com/peterbe/minimalcss) you just give it a URL and it tells you the minimal CSS. That tool automatically figures out what CSS is being used and you don't need to know the exact versions of files. 
Tools like [`critical`](https://github.com/addyosmani/critical) works statically (and  MUCH faster) and you need to supply the HTML as a file on disk. So, not a URL nor HTML as a string. You also need to extract all the external CSS which I guess you could do with some regexes on the HTML. 

Whichever way you figure out the critical/minimal CSS you shouldn't do this a thing that blocks because it's bound to be slow and might be fragile too. So if you run it as an async worker step you need to figure out a way to then change the whole HTML document. That isn't easy with the way Kuma and CDN works today. 

One option would be to trigger a post-render signal that does all of this stuff, in its own time, on a worker process and then it updates the wiki document so that the next time it renders it'll have the crtical CSS during runtime.

**Comment by peterbe** [comment]
There are ways. They are all possible. But they sure aren't easy. Not that they're rocket science hard but they're pretty big projects. Especially since it involves many variables and constraints such as scale, CDN, and the need to not break horribly if something goes wrong. I'd love to work on this but it'll take several days and involve reviews from multiple people. 

The current stumptown-renderer doesn't yet have a solution but it's a static site generator so for every possible URL you have an `index.html` file on disk which means you can easily process them in place using lots of different tools and these things can be done before you involve a CDN.

**Comment by Gregoor** [comment]
Thanks for the context, Peter, that helps me a lot!

Wrt critical, I think it already extracts the CSS from the given HTML, so supplying more CSS should be optional / not needed in our case?

I agree that we shouldn't build something that blocks at runtime, I was hoping for a way to do that at compile time.

Not meaning to unwind history, just trying to understand it wrt Emotion: It does make critical style extraction simpler than what we're looking at here (though with similar runtime costs I gather). Did we not look further into that because there were too many critical styles outside of emotion?

**Comment by peterbe** [comment]
> just trying to understand it wrt Emotion

I think it would be a different world if EVERYTHING was in css-in-js (e.g. Emotion). We still have so much "foundation CSS" in the form of the SCSS files. 

I don't know if it's even realistic to consider porting ALL stylsheets into Javascript. All the grid, fonts, typographic margins, etc. 
Something like Emotion would be able to smartly NOT injecting `<style>` tags for `<div>`s that don't get included but that wouldn't constitute a large amount. 

In reminds me of the something in `minimalcss`. It doesn't support "above-the-fold" and I worried about that. But usually, a page consists of `somebloatedframework,css` plus a handful of `<div>` tags. If you can avoid 90% of the `somebloatedframework,css` it means many many kbytes. But avoiding the overrides for a handful of `<div>`s it doesn't mean much.
