### ISSUE TITLE
Can we remove `customcss.scss`?

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#5693]
We have a Sass file that is served to the new frontend as well as the `wiki` domain that references a macro called CustomCSS. The macro no longer exists but, from the sound of it(comment below), the code that used to live in this macro was added to this file.

The intent was always to go back and clean this file up and eventually get rid of it.

```
/*

Copied from the custom CSS macro template CustomCSS
This file was added to by the contributors as part of the redesign migration, it contains:
- legacy classes in use from old versions of the MDN
- new classes created to when contibutors needed something the devs did not provide
- fixes for bugs filed that the dev team did not get to

In a perfect world we go through the contents of this file and integrate it with the dev team's CSS files
eventually emptying this file.

********************************************************************** */
```

With the new frontend, I wonder if we can go ahead and remove it. The file in question is here:

`kuma/static/styles/components/wiki/customcss.scss`

## Potential Savings

```
+--------------------------------------------------------------+
| Size         | 12.09 KiB                                     |
|--------------------------------------------------------------|
| Gzipped      | 3.88 KiB                                      |
|--------------------------------------------------------------|
```

**Comment by ruchikabgosain** [comment]
Hello @schalkneethling I would love to take this up as my contribution to this repository! Is this available? 🤔✨

**Comment by schalkneethling** [comment]
> Hello @schalkneethling I would love to take this up as my contribution to this repository! Is this available? 🤔✨

Hey @ruchikabgosain, thank you for your interest. I still need to investigate whether we can actually remove this file but I will keep you posted.

**Comment by ruchikabgosain** [comment]
Ah, alrohhty! Looking forward to it 🙇

**Comment by schalkneethling** [comment]
> Ah, alrighty! Looking forward to it 🙇

Hey there, do you have the project running locally on your machine? If not, that would be a good first task. Instructions can be found here:

https://kuma.readthedocs.io/en/latest/installation.html

**Comment by ruchikabgosain** [comment]
@schalkneethling starting with this right away!
