### ISSUE TITLE
Implement Newsletter integration to track opt-ins (without Salesforce for now)

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#5792]
**Parent Issue:**
https://github.com/mdn/sprints/issues/2044

**Email Design comps are here:**
https://github.com/mdn/sprints/issues/1814

**Technical Overview**:

We'll be using the Mozilla Basket API to implement this:
https://github.com/mozmeao/basket

We do not have to support Subscription management. Once a user has subscribed they can unsubscribe via a link at the bottom of the email. 

Contact @tobinmori for Dev API URL and credentials. 

**Tasks & Acceptance criteria:**

- asked @atopal for context as to where the subscription actually occurs.
- create an API endpoint in Kuma that (that uses our own Basket API key) wraps Basket's subscription creation
- no need to handle unsubscribe (this will be handled by user via unsubscribe link at bottom of email)
- need to get API key for staging to test
- be aware that Staging Basket API subscriptions go to prod Salesforce (so actual Salesforce subscriptions are created)

**Comment by atopal** [comment]
The subscription occurs on sign-up: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/screens/368129372/comments

**Comment by tobinmori** [comment]
Flag the opt-in the database. The Mozilla marketing team has changed priority can no longer can work with us on this.

**Comment by tobinmori** [comment]
@atopal Gregor brought up a good point. What should we do with users who already have an MDN acct? Will they have any opportunity to sign up for a subscription?

**Comment by tobinmori** [comment]
Note: we'll track users who have signed up by storing their Basket UID in the Django user obj.

**Comment by Gregoor** [comment]
Oh I guess this is only an issue for the backend, where as https://github.com/mdn/kuma/issues/6040 is for the frontend?
There's also a design for updating subscriptions in there, so that answers that question.

What I didn't find in the designs is a link for managing subscriptions over at mozilla.org. Or is that the subscription-"tab" on the side?

**Comment by Gregoor** [comment]
@atopal do we want a manage-subscription link anywhere on MDN or are we fine with it just being in the emails? This affects how we use the salesforce API, as we don't need API keys if we don't need to show that link (and we'd then also just store a flag in the db for subscription status, instead of a token).

**Comment by Gregoor** [comment]
Chatted with the basket engineer and the https://www.mozilla.org/en-US/newsletter/ endpoint will be deprecated soon, in favor of the http://basket.mozilla.org/subscribe/ endpoint. It should be drop-in replacement.

**Comment by tobinmori** [comment]
> Oh I guess this is only an issue for the backend, where as #6040 is for the frontend?
> There's also a design for updating subscriptions in there, so that answers that question.
> 
> What I didn't find in the designs is a link for managing subscriptions over at mozilla.org. Or is that the subscription-"tab" on the side?

I think for the first iteration. "Subscription mgmt" is just the 'unsubscribe' link on the email. :)

**Comment by atopal** [comment]
Hey, please keep in mind that we need to send a message when they subscribe and another one when they unsubscribe: the screens are here: https://mozilla.invisionapp.com/share/6GUVS9DH9V5

**Comment by Gregoor** [comment]
From my understanding email contents, like sign-up/unsubscribe confirmation are configurable through Salesforce, though design options might be limited there.

@pmclanahan can you point us to the right person that can help us getting our custom messages into salesforce?

**Comment by pmac** [comment]
The welcome email messages are indeed handled by the email team in Lifecycle Marketing. Best thing is to probably ask about these in the #email channel on slack. I'm not aware of any "unsubscribe" emails that we send, and in fact it may not be legal to send anyone email after they've specifically told us that they don't want anymore email. The email team would know best though.

**Comment by tobinmori** [comment]
This is currently blocked by our lack of a SF instance:
https://bugzilla.mozilla.org/show_bug.cgi?id=1562678

Workaround: 
Create a flag in the DB that indicates that a user has opted in to email subscription.

**Comment by tobinmori** [comment]
@atopal can you send me and @Gregoor the contact info for SF Instance setup?

**Comment by atopal** [comment]
@tobinmori The contact is Heather Crince
