### ISSUE TITLE
Fix uploaded file attachments in MDN.

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#5798]
https://bugzilla.mozilla.org/show_bug.cgi?id=1110801

This can and has bit us. If attachments are served via Django it can kill our server.

Currently attached files land in EFS and Django is forced to serve these files (a process killer); if the uploaded files landed in S3, they could be served by S3. 

The offending code is here:
https://github.com/mozilla/kuma/blob/4e84a8c2a0d1fd59c736a4f88fbecc80e1b01cb6/kuma/attachments/views.py#L46

- [ ] Not using EFS, but using S3 instead
- [ ] Fix the CloudFront TTL to something other than 15min (much less important)
- [ ] Migrate existing EFS content from EFS to S3

**Comment by jmswisher** [comment]
To be continued

**Comment by jmswisher** [comment]
@callahad-zenhub What is this waiting on?

**Comment by callahad** [comment]
@jmswisher There's a checklist in the first comment on the associated pull request (https://github.com/mdn/kuma/pull/5998). The main blocker is (https://github.com/mdn/infra/issues/336).

**Comment by tobinmori** [comment]
Can i close this one out @callahad?
