### ISSUE TITLE
Survey looks weird if localStorage is blocked

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#5816]
Steps to reproduce:
Open a Private browser session and open Preferences and search for "storage" and click "Manage permissions". Then type in `beta.mdn.localhost:8000` and press "Block"
<img width="1645" alt="Screen Shot 2019-09-12 at 4 34 35 PM" src="https://user-images.githubusercontent.com/26739/64818982-406ba180-d57b-11e9-8929-f32afe7823dc.png">

Now view the home page:
<img width="1645" alt="Screen Shot 2019-09-12 at 4 35 48 PM" src="https://user-images.githubusercontent.com/26739/64819066-6d1fb900-d57b-11e9-9174-625a57e3f263.png">

**Comment by schalkneethling** [comment]
@peterbe We are no longer running this survey so, I wonder whether it would be ok to close this issue?

**Comment by peterbe** [comment]
> We are no longer running this survey so, I wonder whether it would be ok to close this issue?

What if we revive it? Or morph to be about a different survey URL?

**Comment by schalkneethling** [comment]
> > We are no longer running this survey so, I wonder whether it would be ok to close this issue?
> 
> What if we revive it? Or morph to be about a different survey URL?

Oh for sure, definitely not something we should forget about. It is just going to be very hard to justify any work on it now. I reckon keeping it open does not hurt anyone :)

**Comment by peterbe** [comment]
Truth be told, perhaps we should just make an audit of running the whole react site with `localStorage` blocking. It might tease out other errors where it *assumes* that `localStorage` works.

**Comment by peterbe** [comment]
> Truth be told, perhaps we should just make an audit of running the whole react site with `localStorage` blocking. It might tease out other errors where it _assumes_ that `localStorage` works.

Oh. We have that: https://github.com/mozilla/kuma/issues/5815
