### ISSUE TITLE
[L10n] avoid hardcoded puncture marks in the page content

### ISSUE THREAD

**Issue by petercpg** [mdn/kuma#5819]
Hi, 

In the latest batch of page contents exposed to l10n, the string `newsletter-privacy-input` is broken into `I’m okay with Mozilla handling my info as explained in this `, `Privacy Policy` with hyperlink, and a hard-coded period[1].

Please avoid such situation, due to a) in some languages, the link might not always in the end of sentence b) the full stop of a sentence might not be a half-width dot like English. It applies to other puncture marks too.

We should probably a) break this into multiple segments with appropriate comment so localizers can notice, or b) merge in to one like what we have previously. See the old version[2] here for an example.

Thanks!

[1] https://github.com/mozilla/kuma/blob/d4572628db6dcac43dcb0340d62d0ef33e51a565/kuma/javascript/src/newsletter.jsx#L282

[2] https://github.com/mozilla-l10n/mdn-l10n/blob/f9e3bbe67d68738db5c11a4f79b27f2881da7885/zh_TW/LC_MESSAGES/django.po#L342

**Comment by peterbe** [comment]
I think we have precedence for doing `gettext` strings that contain HTML. In Jinja it would look like this:
```
      {% trans url="/docs/MDN/Contribute/HowTo/Do_a_technical_review" %}
        Technical - code samples, APIs, or technologies. <a href="{{ url }}">Can you help?</a>
      {% endtrans %}
```

In `l10n.js` there's an `interpolate` function you can use.

**Comment by peterbe** [comment]
@Gregoor Would you mind taking a look at this one? 
Peter pointed out one line there in newsletter.jsx but I don't know how to audit all other places where this might happen. Perhaps we just start with `newsletter.jsx` and keep a mental note of it happening again.

**Comment by Gregoor** [comment]
yup, already on it. Will need to add something like `interpolate` that works for React elements.

**Comment by jmswisher** [comment]
@peterbe @Gregoor What's the status of this? Is it Done? Moving forward into Queen Latifah?

**Comment by peterbe** [comment]
> @peterbe @Gregoor What's the status of this? Is it Done? Moving forward into Queen Latifah?

Yes. Move forward. We lost momentum and arguably instead of this solution we should perhaps redirect our attention to https://github.com/mozilla/kuma/issues/5886 which means that we won't need this solution.
