### ISSUE TITLE
Disable Akismet spam classification

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/kuma#5827]
**Summary**
The spam classification of Akismet is just terrible and I suspect only a few people actively uses it.
Instead of ignoring it and letting it stale, I suggest turning it off if not removing the corresponding code/configuration.
URLs: 
* https://bugzilla.mozilla.org/show_bug.cgi?id=1537954#c2
* admin/wiki/documentspamattempt/

**Rationale**
Reducing useless data footprint on the database.
Reducing a 15mn per day process of checking revision and, 98%, of the time, choosing "Ham"
For foreign languages edits, even after months of classification, the rate is just terrible.
Receiving first time edits in mail is much more effective than Akismet to catch spam.

**Audience**
Admins. Maybe @chrisdavidmills and @jswisher

**Proposal**
Remove Akismet classification system

**Additional context**
I spend around 15minutes each morning going through all of the unclassified spam attempts, mostly for nothing. I suspect I'm the only one doing so and I don't want to leave a system get stale by doing nothing.
Imagine triaging 50 PRs at the beginning of the day, just so that you can close them.
This was already filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1537954

**Comment by tobinmori** [comment]
@chrisdavidmills can you weigh in on the importance of this?

**Comment by chrisdavidmills** [comment]
As for important - I would say medium. It isn't blocking us doing work, but it is annoying and a bit of a time waster.

I've filed a card in the MDN content team dev papaercuts trello: https://trello.com/c/S2rWhtsY/11-disable-askimet-spam-classification

**Comment by bensternthal** [comment]
Closing as akismet looks to have been removed many moons ago.
