### ISSUE TITLE
Show user avatar in header on step 2

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#5830]
**Summary**

To clearly show the user which personal avatar will be associated with their account, update the avatar in the header from the default Dino, to the relevant avatar pulled from the auth service they are signing up with.

See below screenshots

## Step 1

![Screenshot 2019-09-16 at 11 35 20](https://user-images.githubusercontent.com/10350960/64947872-2df0b100-d876-11e9-8d6a-eaf0751e390a.png)

## Step 2

![Screenshot 2019-09-16 at 11 35 30](https://user-images.githubusercontent.com/10350960/64947886-35b05580-d876-11e9-9c7a-5863d4a6031a.png)

**Audience**

Users signing up for a new account

**Rationale**

See Epic https://github.com/mdn/sprints/issues/1857

**Workaround**

N/A

**Proposal**

See summary

**Additional context**

N/A

**Comment by schalkneethling** [comment]
@escattone For this one, I am going to need access to the avatar pulled from Github. Is this already exposed to the frontend? Note that this is not React, but Jinja. Thanks!

**Comment by escattone** [comment]
> @escattone For this one, I am going to need access to the avatar pulled from Github. Is this already exposed to the frontend? Note that this is not React, but Jinja. Thanks!

Sorry for the delay! I'm not sure off the top of my head, so I'm going to have to look into this and get back to you.

**Comment by escattone** [comment]
@schalkneethling No, it appears that we're not using the GitHub avatar at all yet, and it's not yet available to Jinja. I created #5848.

**Comment by schalkneethling** [comment]
@escattone Just tried to use `get_avatar_url(user)` in `https://github.com/mozilla/kuma/blob/master/kuma/users/jinja2/socialaccount/signup.html` but I get the following error:

```
File "/app/kuma/users/jinja2/socialaccount/signup.html", line 18, in top-level template code
web_1            |     {% set github_connect_url = provider_login_url('github', process='connect', next=request.session.sociallogin_next_url|default('/')) %}
web_1            |   File "/app/jinja2/react_base.html", line 105, in top-level template code
web_1            |     {% block content %}{% endblock %}
web_1            |   File "/app/kuma/users/jinja2/socialaccount/signup.html", line 71, in block "content"
web_1            |     <img src="{{ get_avatar_url(user) }}" alr="{{ _('Create MDN Profile') }}" />
web_1            |   File "/app/kuma/users/templatetags/jinja_helpers.py", line 23, in get_avatar_url
web_1            |     for account in user.socialaccount_set.filter(provider=provider):
web_1            |   File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 239, in inner
web_1            |     return func(self._wrapped, *args)
web_1            | AttributeError: 'AnonymousUser' object has no attribute 'socialaccount_set'
```

I am guessing this means we do not have access to the avatar until the user has *actually* created their account?

**Comment by peterbe** [comment]
This happens because you're allowing `<img src="{{ get_avatar_url(user) }}"` to happen in the template before checking that the user is NOT `user.is_authenticated`.

**Comment by schalkneethling** [comment]
> This happens because you're allowing `<img src="{{ get_avatar_url(user) }}"` to happen in the template before checking that the user is NOT `user.is_authenticated`.

Yup but, this issue relates to showing the user's avatar even before they have created their MDN account so, in between the time they returned from Github and before clicking "create account".

The error will not happen if I only call this for an authenticated user, but that also means we will not be able to show the user's Github avatar at this stage of the signup process.

**Comment by peterbe** [comment]
@schalkneethling I'm still a noob with how SocialAccount works but I guess there's something between the OAuth callback (and the access token usage for teching the github profile) and the eventual storage in our database. I fear you're going to have to dig into that. I can help if you like.

**Comment by escattone** [comment]
@schalkneethling I understand. Let me look into this, and get back to you.
