### ISSUE TITLE
Firefox Dev Ed wipeout after restart to update to version 70.07b

### ISSUE THREAD

**Issue by oligraph** [mdn/kuma#5850]
Restart after update to version 70.07b resulted in a error-window that popped up and disappeared after a second. Deleted the «update» files in Library and reinstalled a fresh version, which solved the issue.
![Firefox-WD-Error-after-latest-update](https://user-images.githubusercontent.com/9936382/65248324-4967f000-daf2-11e9-98ce-6340b269add0.png)

**Comment by peterbe** [comment]
What URL is that?

**Comment by MatonAnthony** [comment]
This is a bug on the beta channel related to Firefox packages with locale.

I think we could close this or if the bug is still present for this person redirect her to bugzilla though I am pretty sure it’s already fixed.
