### ISSUE TITLE
putting an emoji on a h3 title may cause the problem

### ISSUE THREAD

**Issue by Hwan-Woong-Lee** [mdn/kuma#5864]
the following line in the source code may be the cause of trouble uploading my source code.

`<h3 id="말되는_대항_말_안되는_격자_시스템">말 되는 🆚 “말 안되는” 격자 시스템</h3>`

I hope you should try changing the emoji with "VS". 
I hope it'll help you out.

**Comment by peterbe** [comment]
What URL is that? What is the problem that it's causing?
