### ISSUE TITLE
Break up the CSS bundle

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#5867]
The only reason for having CSS bundles is old-school thinking from an era before we had HTTP/2. It used to be best practice to minimize the *number* of requests. With HTTP/2 it's actually the other way around. Now, with one open TCP pipeline we can instead download multiple files in parallel which can mean the complete CSS bytes can travel from the server to the client in a shorter absolute time. 

Another advantage of less big bundles is that one single change to any 1 of those files means that the whole bundle gets a new filename (with a hash digest in it) which means all browser caches are void in the next release.

Bundling in SCSS is a bit more complex. Similar to how bundling in ES6 is a bit more complex compared to the olden days where the `window` global became the "dumping ground" for functions/modules to reach each other. 

[Our current isn't a massive about of files (7 to be exact)](https://github.com/mozilla/kuma/blob/51f0abfd5359e88705e3350bada07fc430f993b3/kuma/settings/common.py#L694-L708) but some of those don't need to be together in one bundle. 

Wherever we're currently doing `{% stylesheet 'react-mdn' %}` that needs to be broken up to look more like this:
```django
{% stylesheet 'react-main' %}
{% stylesheet 'react-document' %}
{% stylesheet 'react-prism' %}
{% stylesheet 'react-bcd' %}
...
```

Lastly, another advantage of breaking up the bundle is that we can potentially conditionally load things. For example:

```diff
{% stylesheet 'react-main' %}
{% stylesheet 'react-document' %}
{% stylesheet 'react-prism' %}
-{% stylesheet 'react-bcd' %}
+{% if has_bcd_table %}
+  {% stylesheet 'react-bcd' %}
+{% endif %}
...
```

**Comment by schalkneethling** [comment]
Thanks for filing this @peterbe. I am actively working on this so, I am going to assign this one to me.
