### ISSUE TITLE
Copying content from one page and pasting on another is losing the class attribute

### ISSUE THREAD

**Issue by a2sheppy** [mdn/kuma#5878]
When copying content from the editor for one article and pasting it into the editor for another page, the value of the `class` attribute is lost. This is a fairly recent problem though I cannot pin down an exact date for you. But it's causing styling to be lost when trying to use one page as a template for another, which is a serious problem since it's a standard part of our usual workflows. I believe we do this more often than we write pages entirely from scratch.

Unless we actually specifically notice the problem, this introduces sometimes subtle flaws in our content (for example, the hidden text above compatibility tables that tells contributors how to update them becomes visible to readers, the classes of `<pre>` blocks get lost, causing loss of syntax coloring, loss of the `syntaxbox` styling, and so forth. Those are subtle enough that they can be easily missed while working on an article. Things like the loss of the `note` and `warning` classes are much more visible and more likely to be caught during the writing and editing process.

**This needs to be fixed sooner rather than later (despite, IMO, our focus being on getting migrated off of Kuma).** We are getting who knows how many pages with sometimes subtle (and sometimes blatant) errors that need to be fixed. This is particularly common when it happens to a contributor not as familiar with our style guide.

I'm trying very hard not to file bugs against Kuma's current contribution front end right now because of the transition we are planning, but I feel this one is substantial enough and risks introducing enough hard to spot flaws (in addition to being a huge aggravation while writing even and perhaps especially if you're aware of this issue) that it should be addressed.

**Comment by a2sheppy** [comment]
At least in Safari (which I've been using for about a week now due to Firefox crashes), copying text in the editor is (incorrectly) copying both the content styles *and* the editor's styles. This may be why the `class` attribute is stripped, although it would be nice if only the bad classes were removed...

**Comment by peterbe** [comment]
### Source

Note to self, I wrote this manually and copied into my clipboard and pasted it with "Source" option on https://developer.allizom.org/en-US/docs/Mozilla/Using_the_Mozilla_symbol_server$edit
```html
<table class="foo">
  <tr>
   <td>Cell</td>
  </tr>
</table>
```

It was left untouched by CKEditor and the server post-processing after Publishing. 
https://developer.allizom.org/en-US/docs/Mozilla/Using_the_Mozilla_symbol_server

Next I paste in this:
```html
<pre class="foobar">This is a pre tag</pre>
```
and after publishing it became this:
```html
<pre class="foobar line-numbers language-html"><code class=" language-html">This is a pre tag<span aria-hidden="true" class="line-numbers-rows"><span></span></span></code></pre>
```

So, as a starting point, it's quite possibly not a matter of some bad Python post-processing inside Kuma that strips the class names. 

### HTML copy

Next up, I used the mouse to select what I see when I open https://developer.allizom.org/en-US/docs/Mozilla/Using_the_Mozilla_symbol_server and I select an area that contains the "Cell" and the "This is a pre tag" text. 
Then, on https://developer.allizom.org/en-US/docs/Mozilla/Using_the_Mozilla_symbol_server$edit without using the "Source" I just paste it into the editor. 

That worked too. The `class` attributes were preserved. 

### CKEditor to CKEditor

I opened one CKEditor in one tab https://developer.allizom.org/en-US/docs/MDN/Getting_started$edit and pasted it into another. No raw source anywhere. Just the mouse ⌘-c and ⌘-v in another editor window. 

This worked too. Those `class="note"` seems to have stuck on https://developer.allizom.org/en-US/docs/Mozilla/Using_the_Mozilla_symbol_server

**Comment by peterbe** [comment]
Would it be possible for you to record some short screencasts @a2sheppy where you demonstrate it happening? 

Do you think it's related to the browser used? I'm using Firefox Nightly exclusively. On macOS.

**Comment by a2sheppy** [comment]
I strongly suspect this is related to using Safari. I am not currently able to use Firefox to edit MDN as it crashes pretty much constantly due to a conflict with the macOS Catalina graphics driver for my computer. But the timing fits; I started having this issue at about the same time I switched to doing everything in Safari.

I will try to get those screen recordings today; if not today, then tomorrow.

**Comment by peterbe** [comment]
Sorry to hear about a buggy Firefox. Is that Nightly or Release you're using? 
Either way, if it is browser-specific it definitely sounds like a matter of CKEditor. 

A worry I have is that we might "never" be able to solve it if it's a matter of CKEditor and Safari being combined. If it was some bad Python post-processing on the server it'd be a different story.  I just don't know if we have the headspace to debug CKEditor and/or upgrade it. Realistically.
