### ISSUE TITLE
Object.assign(...) is working in IE 11

### ISSUE THREAD

**Issue by hasanbaloch** [mdn/kuma#5879]
Hi,

The official documentation says "Object.assign()" is not supported in IE browser. However, I am able to use this function and it works as expected, without any exceptions. Did you forget to update the documentation? Following are my IE settings:

Version: 11.678.17763.0
Update Versions: 11.0.140

Hasan.

**Comment by tobinmori** [comment]
Hi @hasanbaloch,

Which documentation do you suggest needs updating? 

Can you give us a link to it? 
Thanks,
Tobin

**Comment by ExE-Boss** [comment]
Maybe it’s the compat table: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility

That has its own repository at: https://github.com/mdn/browser-compat-data
