### ISSUE TITLE
Icon in search box does not have responsive size

### ISSUE THREAD

**Issue by vabrell** [mdn/kuma#5881]
**Summary**
_What is the problem?_
The SVG search icon is not responsive for mobile view so it covers part of the search text and is partly placed outside the search box.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Go to [https://developer.mozilla.org/](https://developer.mozilla.org/)
2. Change to the browser to mobile view

**Actual behavior**
_What actually happened?_
The search icon does not change size when the search box changes size on mobile view.

**Expected behavior**
_What did you expect to happen?_
The search icon to be responsive to the page size.

**Screenshot**
![search](https://user-images.githubusercontent.com/2067439/65754276-fa811280-e110-11e9-992a-75d532f3c006.png)

**Comment by tobinmori** [comment]
hi @vabrell,

Can you let us know which browser, browser version, platform you used so that we can try to reproduce this? 

I was unable to reproduce this on OSX using latest FF/Chrome using responsive mode. 

thanks!
Tobin

**Comment by vabrell** [comment]
Normally I run Firefox Developer Edition (70.0b9) that is where the screenshot is from.
I have checked in both Chromium (77.0.3865.90) and Firefox (69.0.1) which seem to have the same issue but not exactly the same, but rather on the border of the search box.
![firefox-chromium](https://user-images.githubusercontent.com/2067439/65883210-dcc4df00-e396-11e9-81c4-36aa3173facb.png)
I am running Arch Linux as OS.

**Comment by ankiiitraj** [comment]
@vabrell  This happened on my Firefox on Ubuntu. 
I want to contribute to this issue. Can you assign me this issue and guide me in this issue.

**Comment by peterbe** [comment]
> Can you assign me this issue and guide me in this issue.

As mentioned elsewhere, we don't assign issues to contributors. Sorry. Your best course of action is to make a pull request.
