### ISSUE TITLE
Can't trust non-en-US gettext strings

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#5886]
We currently have at least 2 places where we want to mix HTML markup with the English text. 
One is in here: https://github.com/mozilla/kuma/pull/5598 where it tries to do this:

```javascript
gettext(' .... towards our goal of providing <b>100% real values</b> to the developer community.')
```
[Implied in the example](https://github.com/mozilla/kuma/pull/5598/files#diff-efcc02937c2680e0552417e0f939917eR504) is the fact that that string has to be inserted with trust into the DOM and not as an escaped string. 

Another example that came up was:

```javascript
I’m okay with Mozilla handling my info as explained in this <a href={PRIVACY_POLICY_URL}>Privacy Policy</a>
```
I'm simplifying the example but here's the original issue: https://github.com/mozilla/kuma/issues/5819 which @Gregoor tries to solve with a clever regex hack here: https://github.com/mozilla/kuma/pull/5872/files

How can we ever have HTML markup in the English strings that we ask Pontoon to translate if we can't trust injecting them as-is into the DOM? 

For React, [`@fluent/react`](https://www.npmjs.com/package/@fluent/react) offers a solution so you can make the English strings have markup looking tags and still be injected into the DOM in a safe way. 

The problem is that; we can't trust the non-en-US strings. Pontoon is awesome but it's scarily out of our reach and control. Even if it has some provisions to prevent rogue translations (that actually aren't translations). What if someone deliberately manages to sneak in something like `'</script><script>alert('xss')` or `vårat mål är att ge ut <b<100% riktiga värden</i>` or `<img src=https://rogue/goatse.png>`.

What we can and should do is make sure those nasty HTML tags don't break our site. Be that for security (e.g. theft), breakage (e.g. corrupt markup), or vandalism (e.g. nasty stuff).

**Comment by peterbe** [comment]
I actually don't know how to simulate this. Our Django reads in the `locale/**/LC_MESSAGES/*.mo` files which are binary and just an optimized version of the `locale/**/LC_MESSAGES/*.po` files. 
Does anybody know how to mess with those files to demonstrate a sample rogue gettext string?

**Comment by peterbe** [comment]
@callahad and I discussed a very simple remedy that we think would get us a lot of mileage: CSP. That would only really protect us from bad `</script>...` attacks but also maybe from loading assets (e.g. images) from untrusted domains. It wouldn't solve the problem of a "innocently corrupt" translation like this: `vårat mål är att ge ut <b<100% riktiga värden</i>`.

Also, fully enabling CSP on Kuma isn't trivial as it stands today since a lot of code would need to be refactored. 

A possibility for a *much* simpler solution is to lint the i18n string catalogs. We use [django-statici18n](https://django-statici18n.readthedocs.io/en/latest/index.html) to generate the `/static/jsi18n/fr/javascript.js` and `/static/jsi18n/fr/react.json` files. We could override that to vet the strings with a `bleach` whitelist or something. If we do that simply trying to run `make compilejsi18n` and `make compile-react-i18n` crash with non-zero exits.

**Comment by peterbe** [comment]
Note-to-self; We have a `./scripts/compile-mo.sh` that might be possible to use to created rogue `.mo` files for simulation.

**Comment by peterbe** [comment]
By way, another (lesser) option would be a new `gettext` function that, in run-time, does the bleaching. Then you could, if you really have localized strings, opt for the slower but safer version. E.g.

```javasacript
import {gettext, gettextBleached} from './l10n.js';

domNode.innerText = gettext("Hi there!");
otherDomNode.innerHTML = gettextBleached("<b>100%</b> raw meat", {whitelist: ['b']});
```

My feeling at the moment is that if this exact same problem can be caught early in the Jenkins/Docker build process, it's the better place.

**Comment by peterbe** [comment]
Hey @flodolo
@mathjazz  suggested you might have some clever ideas about this. Sorry if it's out-of-context, but I can explain with an executive summary.

**Comment by flodolo** [comment]
> The problem is that; we can't trust the non-en-US strings. Pontoon is awesome but it's scarily out of our reach and control.

That comes right after the Fluent mention, but it's not applicable to Fluent, is it?

Is the problem only for en-US strings explicitly using HTML, in which you use `innerHTML`, or does that apply to any strings?

I cannot think of many sane solutions beyond sanitizing the strings. At some point, SUMO was using [this package](https://github.com/willkg/dennis) to do static checks, and maybe it could be extended for that, but the reality is that filing bugs doesn't solve the issue immediately.

P.S. I think @pike might be the one with better ideas in our team on this kind of topic.

**Comment by Pike** [comment]
What we're doing in Fluent is effectively bleaching at runtime. We're not doing that at translation time, as the specs on how to do that differ between React and DOM. We still need to figure that out.

For server-side rendering, this is tricker still, as you can't really tell if you're in an attribute or content, unless you're doing it at runtime. Some folks advertise conventions, like if an ID ends with `_html`, process HTML, otherwise enforce text. But that's really just convention, I think.

I'd suggest to wrap the localized string in a bleach, and make them safe that way. If that needs to be condensed to a single API is more a Jinja question, I guess?

It'd be nice to have comments on the strings that are going through this process, so that we possibly can warn on the pontoon side at some point about bleach violations.

**Comment by peterbe** [comment]
> That comes right after the Fluent mention, but it's not applicable to Fluent, is it?

Not really. We know what using `@fluent/react` would be better for other reasons. E.g. for localizing `Check out <a href="%(privactpolicyurl)s">privacy policy</a>` since I think this'd become `Check out <link>privacy policy</link>` instead. 



> Is the problem only for en-US strings explicitly using HTML, in which you use `innerHTML`, or does that apply to any strings?

Only when used in HTML and DOM, yes. Kuma is today a mix of Jinja templates, vanilla/jquery JavaScript, and React JavaScript. In all those contexts it might be that we want to have strings that contain markup (e.g. `<b>` or `<a href>`)

**Comment by peterbe** [comment]
Also, thanks for the great suggestion of using [dennis](https://github.com/willkg/dennis) since it can clearly catch other things too as exemplified by mythmon's bugzilla ticket there. 

I'm more and more convinced about doing this kinda of bleaching early in the process and at build time is right. Not entirely sure how to distinguish between warnings and stop-the-presses errors. Also, not entirely sure what's next for us in terms of extending `django-statici18n` or redirect the investment into `dennis`. 

But thanks you both! Much appreciated.

**Comment by tobinmori** [comment]
Timebox to 1 day.
