### ISSUE TITLE
jQuery-UI ~ What happens if we remove it?

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#5890]
We have two bundles related to jQuery-UI inside `common.py`:

```
'jquery-ui': {
    'source_filenames': (
        'js/libs/jquery-ui-1.10.3.custom/css/ui-lightness/jquery-ui-1.10.3.custom.min.css',
        'styles/libs/jqueryui/moz-jquery-plugins.css',
        'css/jquery-ui-customizations.scss',
    ),
    'output_filename': 'build/styles/jquery-ui.css',
}

...

'jquery-ui': {
    'source_filenames': (
        'js/libs/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js',
        'js/libs/jquery-ajax-prefilter.js',
        'js/moz-jquery-plugins.js',
    ),
    'output_filename': 'build/js/jquery-ui.js',
}
```

It is being used in the following files:

```
kuma/kuma/dashboards/jinja2/dashboards/revisions.html
kuma/kuma/users/jinja2/users/ban_user_and_cleanup_summary.html
kuma/kuma/users/jinja2/users/ban_user_and_cleanup.html
kuma/kuma/users/jinja2/users/user_detail.html
kuma/kuma/users/jinja2/users/user_edit.html
kuma/kuma/wiki/jinja2/wiki/create.html
kuma/kuma/wiki/jinja2/wiki/edit.html
kuma/kuma/wiki/jinja2/wiki/move.html
kuma/kuma/wiki/jinja2/wiki/translate.html
```

## The purpose of this issue

Determine answers to the following:

1. How badly does the above break if we remove jQuery-UI?
1.1 How much work would it be to fix what breaks?
2. Where can we safely remove it? (here I am especially interested in everything inside `/users/`

If we cannot entirely remove jQuery-UI, we might want to look at upgrading it as the legacy version of this library is currently set to `1.11.4` and we are on `1.10.3`.

Some of this is related to `wiki` editing which will go away at some point in 2020 but, `dashboards` and `/users/` is unrelated and will still live on for some time(years?)

## Next steps

Research
Share thought, comments, ideas

**Comment by evanplaice** [comment]
**Notice: This is a WIP, more specifics will be added as they're discovered**

Here's what I've found from my research so far...

-----------

> How badly does the above break if we remove jQuery-UI?

The following would need to be replaced

- autocomplete inputs
- datepicker inputs

> 1.1 How much work would it be to fix what breaks?

**Autocomplete**

The autocomplete input is built as a `jquery-ui` custom widget extension

This could be replaced w/ a 100% vanilla solution using `<datalist>` + AJAX fetch but browser compatibility for that element is spotty at best (https://caniuse.com/#feat=datalist)

The source for the autocomplete widget definition is located in [/kuma/static/js/moz-jquery-plugins.js](https://github.com/mozilla/kuma/blob/master/kuma/static/js/moz-jquery-plugins.js)

On evaluation, the widget is attached to the global `$` namespace. It gets called as part of a $ chain, for example...

*/kuma/static/js/dashboard.js*
```javascript
$('#id_topic').mozillaAutocomplete({
    minLength: 3,
    labelField: 'label',
    autocompleteUrl: '/' + currentLocale + '/dashboards/topic_lookup',
    buildRequestData: function (req) {
        // Should add locale value here
        req.locale = getFilterLocale();
        req.topic = req.term;
        return req;
    }
});
```

**Datepicker**

For datepicker input is a built-in feature of `jquery-ui`

It could be replace w/ `<input type="date">` but again, browser support isn't 100% (https://caniuse.com/#search=input-date)

It's called as part of a `$` chain, for example...

*/kuma/static/js/dashboard.js*
```javascript
$('#id_start_date, #id_end_date').datepicker();
```
-----

### kuma/dashboards/jinja2/dashboards/revisions.html

- `#id_topic` - mozillaAutocomplete
- `#id_start_date` - datepicker
- `#id_end_date` - datepicker

*Note: The elements are bound in kuma/static/js/dashboard.js*

### kuma/users/jinja2/users/ban_user_and_cleanup_summary.html

*In progress*

### kuma/users/jinja2/users/ban_user_and_cleanup.html

*In progress*

### kuma/users/jinja2/users/user_detail.html

*In progress*

### kuma/users/jinja2/users/user_edit.html

*In progress*

### kuma/wiki/jinja2/wiki/create.html

*In progress*

### kuma/wiki/jinja2/wiki/edit.html

*In progress*

### kuma/wiki/jinja2/wiki/move.html

*In progress*

### kuma/wiki/jinja2/wiki/translate.html

*In progress*

**Comment by schalkneethling** [comment]
Wow, thanks so much for all of this @evanplaice 👍  really, really appreciate it. I will have a detailed read through all of this.

**Comment by evanplaice** [comment]
Sure thing. It's a lot of fun to dig through git history. I considered linking to relevant commits but it's a bit of a mess; the history goes back 6 years w/ multiple refactors.

I'd start working on the refactor but I had issues getting a local admin login running. Followed the directions to a t but I'm getting '403 Forbidden' when I actually try to login.

**Comment by schalkneethling** [comment]
Hey @evanplaice, could you provide some error logs? Thanks so much

**Comment by evanplaice** [comment]
Here's a screencast of the process
https://youtu.be/n1pp9cBvfzk

Here are the logs
- docker.log is the `docker-compose logs -f` output.
- setup.log shows the CLI out stdout

https://gist.github.com/evanplaice/48838e986cc88f50ee6b2bd530b95fc1

**Comment by evanplaice** [comment]
I managed to login to the SQL container. Looks like the super user account was created successfully.

```sh
mysql> SELECT username, email, password, is_superuser FROM auth_user WHERE username = "evan";
+----------+----------------------+-------------------------------------------------------------------------------+--------------+
| username | email                | password                                                                      | is_superuser |
+----------+----------------------+-------------------------------------------------------------------------------+--------------+
| evan     | evanplaice@gmail.com | pbkdf2_sha256$36000$n5rvnkPrUT3J$Ctut1zMtYBqsrmXHdLl7nUnUJAQ3TBCazSoiGQnqa0s= |            1 |
+----------+----------------------+-------------------------------------------------------------------------------+--------------+
1 row in set (0.00 sec)
```

**Comment by schalkneethling** [comment]
Thanks, @evanplaice, I will have a look.

**Comment by bensternthal** [comment]
Jquery ui removed in https://github.com/mdn/kuma/pull/6446 looks like we did find out what happenes if we removed it :)
