### ISSUE TITLE
Create prism CSS bundle

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#5891]
Create a `prism.css` bundle. It should contain the following:

```
styles/libs/prism/prism.css',
styles/libs/prism/prism-line-highlight.css',
styles/libs/prism/prism-line-numbers.css',
js/prism-mdn/components/prism-json.css',

```

**Comment by ExE-Boss** [comment]
`js/prism‑mdn/components/prism‑json.css` hasn’t existed since #5189 was merged, which happened 8 months ago in February.

**Comment by schalkneethling** [comment]
> `js/prism‑mdn/components/prism‑json.css` hasn’t existed since #5189 was merged, which happened 8 months ago in February.

Yup, I noticed that ;) Somehow it just kept surviving all this time with no pipeline errors :/
