### ISSUE TITLE
Use BCD bundle on new front-end

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#5896]
We currently bundle the BCD specific CSS along with everything else in `react-mdn.css`. A separate bundle for this does exist. As part of the work in #5867 we should remove it from the "main" bundle and use the separate `wiki-compat-tables`, BCD specific bundle.

**Comment by Gregoor** [comment]
Does #5934 address this?

**Comment by schalkneethling** [comment]
> Does #5934 address this?

Indeed it will, so you can add Fixes ... in the PR referencing this one as well. Thanks!

**Comment by tobinmori** [comment]
@schalkneethling can i close this?

**Comment by schalkneethling** [comment]
> @schalkneethling can i close this?

Well, not sure if we are going to merge that PR. If we do not, then this might still be a valid issue, work task. Thanks for checking in @tobinmori

**Comment by atopal** [comment]
@schalkneethling looks like this is done?

**Comment by schalkneethling** [comment]
> @schalkneethling looks like this is done?

Looks like we never merged it so, might still be a thing we do. I will have to look into it to confirm though.
