### ISSUE TITLE
Payments experiment left overs

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#5904]
The payment experiment has been ended and the initial set of code and assets removed a little over 4 months ago:
https://github.com/mozilla/kuma/pull/5432

There are still some pieces left in the codebase though such as:

```
js/components/payments/payments-manage.js
kuma.payments.apps.PaymentsConfig
kuma/payments // a number of files and Python code
```

At what point can/should we remove all of it? @atopal

**Comment by bensternthal** [comment]
Closing as no longer valid.
