### ISSUE TITLE
Provide sensible defaults for user's username and email address on Create MDN Profile page

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#5909]
**Summary**

As a user, I want MDN to default my username and email address to what is used in the auth service I am utilizing so that this process is quick and painless.

**Rationale**

See the summary above.

**Audience**

New MDN Web Docs users signing up for an account

**Proposal**

* Utilize the username from the Github account and display as read-only
* When defaulting to a username, display "Change Username" link next to the read-only field, which would open a text field where they could change it to a custom name
* Default the email address to the primary email address pulled from the auth service, and display as read-only
* Display "Change Email" link next to the read-only email address, which would display all verified email addresses pulled from the auth service as radio options, with the last option being "Other" where they can enter a custom email address.
* If the username pulled from the auth service is already taken on MDN, present the blank field instead of the default username in that instance.

**Additional context**

Design and flow: https://github.com/mdn/mdn-fiori/tree/master/design-files/sketch/accounts

**Comment by schalkneethling** [comment]
@escattone I am working through some of the testing scenarios for the sign-up flow. One of these is for when a user signs up with Github(the only way currently ;)) but, we find that they already have an old account via Persona aka `matching_accounts.exists()`

Looking at the admin view for Social accounts there is a provider field with a select form field but, the only option in there is `Github`. How are Persona accounts identified in the system?

I can test that the UI will display correctly without the above, so it is not a blocker, but it would be nice to test the flow if possible.

The other thing I find a little strange is this piece of code:

```
{% for match in matching_accounts %}
<form method="post" action="{{ url('users.send_recovery_email') }}">
    {% csrf_token %}
    <label>{{ match.uid }}
        <input type="hidden" name="email" value="{{ match.uid }}" />
    </label>
    <button class="positive" type="submit" name="recover">{{ _('Recover my Profile') }}</button>
</form>
{% endfor %}
``` 

So, this suggests that for each matching account it will add a separate form. In the end, the user will just see a couple of buttons all labeled `Recover my Profile` which seems really odd. Would there ever be more than one? It seems unlikely as we have constraints around duplicate usernames and accounts with matching email addresses.

**Comment by schalkneethling** [comment]
@escattone We have the following piece of code inside `signup.html`

```
{# we have to handle this error message here to have access to the request #}
{% if error == form.duplicate_email_error_label %}
  {% trans login_url=url('account_login'), next_url=github_connect_url, provider_name=provider.name %}
  A profile already exists with the selected email address.
  <a href="{{ login_url }}" class="launch-login" data-next="{{ next_url }}">Connect your
    {{ provider_name }} account to it.</a>
  {% endtrans %}
{% else %}
```

I was, however, able to successfully create two users with different usernames but the same email address. How would one go about testing the duplicate email address case or is that perhaps an old code path that we will never go down anymore? Thanks!

**Comment by tobinmori** [comment]
@escattone will check out both these user acct issues: 
(1) 2+ user accts, 
(2) ability to have 2+ users mapped to 1 email address. 

@atopal - is an MDN user supposed to be allowed to have 2+ users mapped to 1 email address?

**Comment by atopal** [comment]
Schalk, can you say what happens when you click the recover my profile button? 

If you see that CTA, you haven't logged in to MDN since we switched over to Github only authentication almost 3 years ago (at least that should be the only time). In which case I'd say we should either just recover the account automatically (assuming it requires no extra effort by the user) or we should now "retire" all accounts that haven't seen a github login in the last 3 years.

In general, I'm not a fan of having two buttons of the same size and color on the page. One should be the clearly preferred next step, but ideally we shouldn't ask users to make choices unless absolutely necessary.

**Comment by schalkneethling** [comment]
> can you say what happens when you click the "recover my profile" button?

To be honest, I have no idea how to legitimately trigger that case. I order to do the styling I simply removed the HTML from the conditional. I believe it sends a recovery email to the email address though. @escattone any ideas?

```
<form method="post" action="{{ url('users.send_recovery_email') }}">
```

> If you see that CTA, you haven't logged in to MDN since we switched over to Github only authentication almost 3 years ago (at least that should be the only time). In which case I'd say we should either just recover the account automatically (assuming it requires no extra effort by the user) or we should now "retire" all accounts that haven't seen a github login in the last 3 years.

I totally agree. If we would actually want to gently nudge the user in the direction of just creating a new account but, keep this recovery functionality, I would switch to using a very neutral color for the button:

**Comment by atopal** [comment]
Okay, let's find out what the button does and then we can decide what action to take.

**Comment by atopal** [comment]
Reminds me a little bit of this: https://www.youtube.com/watch?v=NkeniR-d8H4 ;)

**Comment by jmswisher** [comment]
To be continued in next sprint.

**Comment by schalkneethling** [comment]
For `matching_accounts` and the related `send_recovery_email` we have opened the following research issue: https://github.com/mdn/kuma/issues/6037

For the work here, we will remove this piece of the puzzle and add the functionality back at a later stage should it be determined that there is a value to having this feature and that the maintenance cost is matched or exceeded by the user benefit.

**Comment by schalkneethling** [comment]
@escattone There is no more open question for you’re attention on this issue. 🍵
