### ISSUE TITLE
Suggestion: BCD table "Available but behind a flag" should look a little more imposing

### ISSUE THREAD

**Issue by a2sheppy** [mdn/kuma#5932]
In the BCD tables, we currently present "available but behind a flag" items in the same green as any other "supported" item, with a flag icon to indicate that it's behind a preference. I think we should make this just a little more disconcerting; possibly by adding a subtle red tinge around the inner border of the cell, like this:

<img width="607" alt="image" src="https://user-images.githubusercontent.com/1641439/66167568-70511680-e608-11e9-897d-bd6f1ba61bf4.png">

That way, it pops just a little more in a "this is actually important that you look at this note instead of gliding past it."

**Comment by MatonAnthony** [comment]
I think a yellow or orange colour would look great.

**Comment by a2sheppy** [comment]
as @MatonAnthony says - yellow or orange would work well too.

**Comment by Elchi3** [comment]
Makes sense to me.
I would transfer this issue to KumaScript and label it "bcd", but this repo isn't yet in the mdn Github org.

**Comment by a2sheppy** [comment]
@Elchi3 - I filed this on the mozilla/kuma repo because I thought the style changes needed here would need to be handled on the dev side of things.

**Comment by a2sheppy** [comment]
Glad others agree with me on this thought — it's pretty rare that it's a good idea to use features that are behind prefs in real world code. :)

**Comment by Elchi3** [comment]
Not sure there are kuma style changes needed. I would first look at the cell classes which are determined by the `getSupportClass` function in the macro. It needs to take into account the case "`supportInfo.flags`". https://github.com/mdn/kumascript/blob/master/macros/Compat.ejs#L236.

**Comment by Elchi3** [comment]
[And then tests are also required on the macro side to make sure this is always styled correctly (there are existing tests that test for similar behavior).]
