### ISSUE TITLE
this link is dead after i tried to upload my translation of it.

### ISSUE THREAD

**Issue by Hwan-Woong-Lee** [mdn/kuma#5939]
when i clicked following link to my translation article.
https://developer.mozilla.org/ko/docs/Learn/CSS/CSS_layout/레거시_조판_메서드 

it redirected to 
https://developer.mozilla.org/ko/docs/Learn/CSS/CSS_layout/Legacy_Layout_Methods

then error page pop up. why this happened and keep happening.
please remove that page or reset that page so that i can upload my translation.

**Comment by atopal** [comment]
Hey Hwan, I'm not seeing a redirect? We'll look into the server error. Can you say what "this link is dead" means?
