### ISSUE TITLE
Organize labels

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#5941]
As @callahad has shown in his email, we are drowning in labels ;p I used the tool Dan linked to, to attempt an organization of the existing labels. See below:

![Screenshot 2019-10-07 at 11 05 39](https://user-images.githubusercontent.com/10350960/66300981-8a377580-e8f6-11e9-9fc4-c568690af84a.png)

I then had a stab at cleaning up and color-coding the labels:

![Screenshot 2019-10-07 at 11 28 21](https://user-images.githubusercontent.com/10350960/66301012-9b808200-e8f6-11e9-86c5-6990d23d07e2.png)

In the latter, the bunch of labels on the far right is on the cutting room floor as candidates for removal.

**Comment by peterbe** [comment]
I see a lot of redundant labels that can be merged. 

- [ ] `type: feature improvement` -> `improvement` (or should it be other way around?)
- [ ] `support work` -> `support work`
- [ ] `tech debt` -> `cleanup`
- [ ] `type: refactor` -> `refactor`
- [ ] `type: deploys` -> `deployment`
- [ ] `type: bug` -> `bug`
- [ ] `can we close?` -> `needs answer`

Some make absolutely not sense to *me* but chime in or checkbox off the one that *you* think still actually make sense:
- [ ] `ux`
- [ ] `papercuts`
- [ ] `manual merge`
- [ ] `orphan`
- [ ] `type: deploys`
- [ ] `component: MDN deployment`
- [ ] `mdn-accounts`
- [ ] `25% refactoring`
- [ ] `travis the test engine`
- [ ] `component: MDN website`
- [ ] `contrib`
- [ ] `PR`

**Comment by peterbe** [comment]
A lot of these smell of a mix of personal taste and historic legacy. The legacy we can get away from. (Does GitHub support removing tags as an *option* but leave them intact on existing issues/PRs?)
But the personal taste I don't think we can get away from. People call things different things and trends come and go. 

It is also inevitable that tags *mean* different things to different people as different people particpate in different stages of work. For example, at the inception might call for one tag and the coding another and the deployment another and the QA another. 

All in all, I think we mustn't worry too much about the madness of the quantity of the tags. A little cleaning now and then but generally, let it be a bit messy.

**Comment by jmswisher** [comment]
To be continued

**Comment by callahad** [comment]
I think there are a few more tweaks we could make, but this feels largely complete.
cc: @tobinmori to close?

**Comment by tobinmori** [comment]
yep @callahad closing!
