### ISSUE TITLE
Search json endpoint is not available in new front-end

### ISSUE THREAD

**Issue by Elchi3** [mdn/kuma#5957]
**Summary**
https://twitter.com/klaascuvelier/status/1182203293117886464

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

Go to https://developer.mozilla.org/en-US/search.json?q=array
 

**Actual behavior**
Blank page

**Expected behavior**
JSON is returned like it is now only at https://wiki.developer.mozilla.org/en-US/search.json?q=array

**Additional context**
There might be a few external services, twitter bots etc. that depend on this endpoint.

**Comment by mesqueeb** [comment]
+1

**Comment by peterbe** [comment]
@mesqueeb If you feel strongly for being able to reach that endpoint please let us know your use case. 
The Wiki was split up into a Wiki and a read-only site. 

We probably won't ever re-instate https://developer.mozilla.org/en-US/search.json?q=array but we might turn it into a permanent redirect to https://developer.mozilla.org/api/v1/search/en-US?q=array

**Comment by peterbe** [comment]
Actually, @joedarc is that something you'd like to try? It'd warm you up a bit to how to hook up urls.py stuff.

**Comment by joedarc** [comment]
@peterbe Sure, i can take a look at this. 👍

**Comment by peterbe** [comment]
> @peterbe Sure, i can take a look at this. 👍

I think I know some good tricks. I hope. Take a look but don't venture too deep into a rabbit hole if you don't see an easy out. I think we just need to divorce `rest_framework` from the search entirely.

**Comment by peterbe** [comment]
@mesqueeb That is an excellent response! Thank you. 
I think a better solution is this: https://github.com/klaascuvelier/alfred-mdn/pull/10 
but for the sake of legacy, I think @joedarc has a solution here: https://github.com/mdn/kuma/pull/6029
