### ISSUE TITLE
Spurious finger pointer cursor in compat tables

### ISSUE THREAD

**Issue by a2sheppy** [mdn/kuma#5964]
When mousing across the compatibility tables, the cursor flickers from the normal arrow to the "link" pointing-finger cursor and back again as you mouse past the blue-ish bottom edge of the compatibility table. If you manage to pause at that time, you can stop with the cursor still in finger mode.

Image attached is a photo since screenshot apps don't capture the shape of the cursor reliably:

![mdn-pointer-cursor](https://user-images.githubusercontent.com/1641439/66602737-bbbf7380-eb78-11e9-8559-af2ab8a82592.png)

**Comment by schalkneethling** [comment]
Thanks for reporting @a2sheppy - I suspect the cause is the `Flag as incorrect` link/button has a very wide hit area. I will take a look.

**Comment by schalkneethling** [comment]
@a2sheppy With the new version of BCDSignaling launched can you test and see whether this behavior is still present? Thanks!
