### ISSUE TITLE
data.pluralFunction is always undefined on the client side

### ISSUE THREAD

**Issue by escattone** [mdn/kuma#5968]
**Summary**
We're not sending the `pluralFunction` within the data we encode for the client side within `window._react_data`.

See https://github.com/mozilla/kuma/issues/5958#issuecomment-540868712

**Comment by escattone** [comment]
We could add `data.pluralFunction = pluralFunction;` [here](https://github.com/mozilla/kuma/blob/45586d915cc6b5e68096e27032e2b85fe9ed69da/kuma/javascript/src/ssr.jsx#L38). But I haven't tested it yet, and it only addresses the case when we're doing SSR, not the case when we're only doing client-side rendering. (I know David Flanagan wanted to define the plural function on the server-side to avoid CSP issues in the future.)

**Comment by tobinmori** [comment]
Possible bad outcome wrong plural form.
