### ISSUE TITLE
Possible bug on FileSystemFileEntry.file()

### ISSUE THREAD

**Issue by Netlic** [mdn/kuma#5970]
Hello, it seems, that **FileSystemFileEntry.file()** success callback does not return a file with populated mime type when uploading directory.

For example in drag and drop, when the whole directory tree is being uploaded, every file is "application/octet-stream".

When only files are being uploaded, mime types are correct.

I'm using [webkitGetAsEntry API](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/webkitGetAsEntry) to traverse in directories.

**Comment by schalkneethling** [comment]
> Hello, it seems, that **FileSystemFileEntry.file()** success callback does not return a file with populated mime type when uploading directory.
> 
> For example in drag and drop, when the whole directory tree is being uploaded, every file is "application/octet-stream".
> 
> When only files are being uploaded, mime types are correct.
> 
> I'm using [webkitGetAsEntry API](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/webkitGetAsEntry) to traverse in directories.

Hi there @Netlic, thanks for reaching out. Is this something you read in the docs or an article on MDN? If you can link to the article, I can bring this to the attention of the appropriate people. Thanks!
