### ISSUE TITLE
Use semantic HTML for "Last modified" piece

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#5975]
This is a follow-up to https://github.com/mozilla/kuma/pull/5974

Here's what the HTML looks like:

```html
<section class="contributors-sub"><svg class="icon icon-clock" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 28" aria-hidden="true"><path d="M14 8.5v7c0 .281-.219.5-.5.5h-5a.494.494 0 0 1-.5-.5v-1c0-.281.219-.5.5-.5H12V8.5c0-.281.219-.5.5-.5h1c.281 0 .5.219.5.5zm6.5 5.5c0-4.688-3.813-8.5-8.5-8.5S3.5 9.313 3.5 14s3.813 8.5 8.5 8.5 8.5-3.813 8.5-8.5zm3.5 0c0 6.625-5.375 12-12 12S0 20.625 0 14 5.375 2 12 2s12 5.375 12 12z"></path></svg><header><h4>最后修改：</h4></header><time datetime="2019-10-11T02:30:33.778708">2019年10月11日</time>,<!-- --> <a href="https://wiki.developer.mozilla.org/zh-CN/docs/Web/CSS/linear-gradient$history" rel="nofollow">by MDN contributors</a></section>
```
<img width="411" alt="Screen Shot 2019-10-11 at 11 34 47 AM" src="https://user-images.githubusercontent.com/26739/66664762-2923e080-ec1b-11e9-8124-76ff4b4cf52c.png">

The problem is that `h4` is naturally a block element so it requires CSS to force it to be `display:inline-block`. 

Here's what it looks like in "screen reader" like `links`:

<img width="328" alt="Screen Shot 2019-10-11 at 11 12 35 AM" src="https://user-images.githubusercontent.com/26739/66665034-a94a4600-ec1b-11e9-90ac-7d8f9dcf04ae.png">

All we need is this:
```html
<p class="last-modified"><b>Last modified:</b> Sep 29, 2019</p>
```
Alternatively this:
```html
<p class="last-modified">
  <svg>...</svg>
  <b>Last modified:</b> Sep 29, 2019
</p>
```
so that we can control the svg icon from CSS if we have to. 

In general, in Kuma we use inline `<svg>` which means that we can control the SVGs with CSS if we have to.

**Comment by joedarc** [comment]
I'd be happy to submit a PR for this. However, I think I'd like to see some input from @schalkneethling on this because of his comment [here](https://github.com/mozilla/kuma/pull/5956#discussion_r333352815).

**Comment by joedarc** [comment]
My thoughts on this:

I don't think using a `<b>` tag is a good fix for this because that's supposed to be deprecated in HTML5. It shouldn't be used exclusively for styling purposes. 

Along those lines, I don't believe `<strong>` is correct either because it should really only be used for things that have significant importance.

Currently there is an `<h4>` there, but that gets introduced into the hierarchy for screen-readers. It seems excessive to add a level to the document hierarchy to call out the "Last Modified" label.

Ultimately we're trying to apply a visual styling to this text label that doesn't tamper with the document hierarchy for screen-readers. Being that this is inline text, it seems like there should just be a `<span>` with a class that we can apply the font-weight to. I originally had that in [this](https://github.com/mozilla/kuma/pull/5956/commits/bedb22512d6854f1fe776a08c4fe4e22210636d1) commit.

Thoughts?

**Comment by schalkneethling** [comment]
> I don't think using a `<b>` tag is a good fix for this because that's supposed to be deprecated in HTML5. It shouldn't be used exclusively for styling purposes.

I know, I remembered that as well. Having read a StackOverflow post, and then the WHATWG spec, it does indeed seem that they backtracked and both `b` and `i` are still valid, however, they have been given different semantic meanings from `strong` and `em`.

From the docs for `b`
https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-b-element

> The b element represents a span of text to which attention is being drawn for utilitarian purposes without conveying any extra importance and with no implication of an alternate voice or mood, such as key words in a document abstract, product names in a review, actionable words in interactive text-driven software, or an article lede.

After having thought about this some more, I came to the following proposal.

The current structure is a leftover from when we had more than one item under meta-level information. With that said, and as@peterbe has mentioned on Slack, we might add more at a later stage and then the original structure becomes relevant again.

I, therefore, propose a mix of what we have and some of the suggestions that were proposed.

```html
<section class="document-meta>
  <header class="visually-hidden">
    <h4>Metadata</h4>
  <header>
  <ul>
    <li class="last-modified">
      <p><b>Last modified:</b> <time datetime="2019-09-03T06:01:32.390389">Sep 3, 2019</time>, <a href="https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/box-shadow$history" rel="nofollow">by MDN contributors</a></p>
    </li>
  </ul>
</section>
```

```css
.last-modified::before {
   display: inline-block;
   content: '';
   background: transparent url('svg-url-goes-here') 0 0 no-repeat;
   width: 16px;
  height: 16px;
}
```

Some thinking around the above:

1. I added a class called `visually-hidden` to the header. This allows us to (1) clearly identify the section via a heading, (2) allow navigation to the section via headings when using assistive technologies but(3), does not present the heading visually in other scenarios
2. Marks the content up as a list, which gives us a semantic structure to build on should we add more meta entries later
3. Move the `SVG` icon to a background image as we are not styling it beyond size and positioning. It is also not contained inside an anchor element so, we do not need the ability for it to inherit its color from its parent.

**Comment by peterbe** [comment]
Sorry for butting in but isn't it redundant to have `<li><p>` when `<li>` already is a block element? It's not a paragraph of text. 

Also, I think we have lots of `class="hidden"` in a lot of content. 
For example, on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video open the Web Console and type `[...document.querySelectorAll('.hidden')].forEach(p => {p.style.display='block'; p.style.backgroundColor='pink'} )`. I.e. you might not need to add `.visually-hidden`.

**Comment by schalkneethling** [comment]
> Sorry for butting in but isn't it redundant to have `<li><p>` when `<li>` already is a block element? It's not a paragraph of text.

Yeah, agreed: Just `<li><b>...</b>...</li>` will be sufficient.

> Also, I think we have lots of `class="hidden"` in a lot of content.
> For example, on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video open the Web Console and type `[...document.querySelectorAll('.hidden')].forEach(p => {p.style.display='block'; p.style.backgroundColor='pink'} )`. I.e. you might not need to add `.visually-hidden`.

Oh no, we already have a class called `visually-hidden` and it is different from the `hidden` class. The `hidden` class hides content from all users via `display: none;`, the `visually-hidden` class hides content only from visual users by:

```
// Hide an element visually, but not from screen readers
@mixin visually-hidden {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    /* !important required to ensure element is hidden when mixin is applied */
    position: absolute !important; /* stylelint-disable-line declaration-no-important */
    width: 1px;
}
```
