### ISSUE TITLE
Deal better with failing whoami XHR

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#5990]
Any errors in the `whoami` XHR request, are bound to be an async process so it wouldn't trigger the error boundaries. 

As noted in https://bugzilla.mozilla.org/show_bug.cgi?id=1551214 we're being way too optimistic about the `/api/v1/whoami` always working and always returning valid JSON. 
But it if doesn't, we're not dealing with it gracefully.

To reproduce, put in this into the `whoami` Django function:
```python
    import random
    if random.random() > 0.5:
        from django.http import HttpResponse
        return HttpResponse('badness!', status=502)
```
So there's a 50% chance it fails in a "realistic" way:

Here's what it looks like when it **didn't fail**:
<img width="221" alt="Screen Shot 2019-10-14 at 1 04 33 PM" src="https://user-images.githubusercontent.com/26739/66769453-32af8180-ee83-11e9-87d6-6e07731e7a3f.png">

here's what it looks like when it **failed**:
<img width="288" alt="Screen Shot 2019-10-14 at 1 03 57 PM" src="https://user-images.githubusercontent.com/26739/66769429-2297a200-ee83-11e9-8056-041e158683c3.png">

Note that it doesn't say "Sign in" as a fallback. 

The <Login/> component has 3 possible outcomes. Not just mugshot or "Sign in" link.
If anything goes wrong inside the `UserProvider` context, it will make `userData` falsy and the component returns just null. That's not great. It should probably say "Error happened".

The fact that it failed is likely not the users' fault. Suppose they were unlucky and now they're not logged in and they have no way of knowing other than perhaps reloading the page till the mugshot appears.

**Comment by tobinmori** [comment]
Is there any way for us to figure out how often this happens @peterbe?

**Comment by tobinmori** [comment]
Add an error message/banner on top.
