### ISSUE TITLE
/zh-CN/docs/Mozilla/Accessibility$json 404s

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#5997]
I was trying to scrape to download https://developer.mozilla.org/zh-CN/docs/Mozilla/Accessibility to my local docker mysql.
So I ran:
```
docker-compose exec web ./manage.py scrape_document https://wiki.developer.mozilla.org/zh-CN/docs/Mozilla/Accessibility --force
```
But it says:
```
INFO: Scrape progress, cycle 1: 1 Initializing, 1 Gathering Requirements
WARNING: Round 2, Source 1 of 2: document_redirect:/zh-CN/docs/Mozilla/Accessibility errored "status_code 404", with 0 dependent sources.
INFO: Scrape progress, cycle 2: 1 Gathering Requirements, 1 Error
INFO: Scrape progress, cycle 3: 1 Gathering Requirements, 1 Error
WARNING: Dependency block detected. Aborting after 1 second.
```

Why is it 404'ing on https://wiki.developer.mozilla.org/zh-CN/docs/Mozilla/Accessibility$json ??
You can put the `$json` suffix on other URLs like https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/Element/article$json

**Comment by atopal** [comment]
This is because the article has not been localized yet
