### ISSUE TITLE
504 errors in Admin console

### ISSUE THREAD

**Issue by escattone** [mdn/kuma#6002]
**Summary**
Most, if not all, of the BCSignal detail endpoints like https://developer.mozilla.org/admin/wiki/bcsignal/1764/change/ return 504

**Steps To Reproduce (STR)**
Visit https://developer.mozilla.org/admin/wiki/bcsignal/1764/change/

**Actual behavior**
504 error

**Expected behavior**
Should show the content of that `BCSignal` model instance.

**Comment by peterbe** [comment]
I can kinda reproduce this locally. 
I have 18 entries on http://mdn.localhost:8000/admin/wiki/bcsignal/ and clicking any of them takes a loooong time to load. 3-7 seconds. 
For example, according to django-querycount I get this on an extreme one:

```
web_1            | http://mdn.localhost:8000/admin/wiki/bcsignal/13/change/
web_1            | |------|-----------|----------|----------|----------|------------|
web_1            | | Type | Database  |   Reads  |  Writes  |  Totals  | Duplicates |
web_1            | |------|-----------|----------|----------|----------|------------|
web_1            | | RESP |  default  |    7     |    0     |    7     |     1      |
web_1            | |------|-----------|----------|----------|----------|------------|
web_1            | Total queries: 7 in 33.0516s
```

**Comment by peterbe** [comment]
Here's why...
<img width="1297" alt="Screen Shot 2019-10-18 at 11 46 30 AM" src="https://user-images.githubusercontent.com/26739/67108685-0787a380-f19d-11e9-851b-09200fe26536.png">

It's selecting every single Wiki document. I think it's potentially related to the filtering options not being defined so it creates filtering options automatically based on the struct of the ORM models.

**Comment by peterbe** [comment]
We just need to make this not a drop-down of every single possible document:
<img width="1460" alt="Screen Shot 2019-10-18 at 12 11 19 PM" src="https://user-images.githubusercontent.com/26739/67110324-774b5d80-f1a0-11e9-899d-8880462c58f4.png">

**Comment by tobinmori** [comment]
prioritization question - do you know who uses this Django admin screen?

**Comment by atopal** [comment]
Less than 10 people all Mozilla staff.
