### ISSUE TITLE
Infinite scrolling

### ISSUE THREAD

**Issue by tiancihe** [mdn/kuma#6004]
OS: MacOS Mojave 10.14.6
Browser: Chrome 77.0.3865.120
Scroll doesn't stop while reaching top or bottom of pages, appearing blank spaces.

**Comment by tiancihe** [comment]
![image](https://user-images.githubusercontent.com/36734012/66974692-82ce5400-f0ce-11e9-8465-8e3939651df8.png)

**Comment by schalkneethling** [comment]
> OS: MacOS Mojave 10.14.6
> Browser: Chrome 77.0.3865.120
> Scroll doesn't stop while reaching top or bottom of pages, appearing blank spaces.

Thank you so much for reporting this problem. If you are comfortable doing so, could you share some of the extensions you have installed? Also, have you tested this in say, Safari or Firefox? Does it show the same behavior?

**Comment by tiancihe** [comment]
I just visited mdn, seems like the issue is solved

**Comment by schalkneethling** [comment]
> I just visited mdn, seems like the issue is solved

Thanks so much for letting us know @tiancihe 🍕
