### ISSUE TITLE
Logging out does not redirect to landing page

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#6007]
**Summary**

There is a well-established pattern on the web where, when you log out of a service, they redirect you to the home page of said service. We probably did this in the past on MDN as well but, with the new login widget, we no longer do.

For the most part it is a jarring experience to click on signout and not be redirected, which is not good because we break the user's expectations.

However, if you are on the profile edit page for example, and click sign out, you get directed to a permission denied page.

![Screenshot 2019-10-17 at 14 10 23](https://user-images.githubusercontent.com/10350960/67007554-f2047200-f0e7-11e9-9642-adfb05da677d.png)

While the critter surely makes me smile, it is probably not the user experience we want :) Wow, that was a long way for me to say

**Steps To Reproduce (STR)**

- Log into MDN Web Docs 
- Log out
- You remain on the same page you were on
- There is no indication that you logged out successfully unless, you look at the top right hand corner of the page

**Actual behavior**

You remain on the same page, or get a permission denied page

**Expected behavior**

You should be redirected to the landing page

**Comment by atopal** [comment]
I think it's fine to stay on the article page you are on, when you sign out (assuming that was deliberate). What's the concern that we need to address here? I sometimes sign out, because I want to see what the page looks like for anonymous users. 

The case we should certainly address is where you sign out and a get permission error. In those cases we should redirect to the start page.

**Comment by schalkneethling** [comment]
> What's the concern that we need to address here?

I find a little jarring. I believe it is because all that changes is the little widget, and mentally I expect to be redirected or for the page to reload. I am thinking we should add a fade-out message banner that confirms that the user has logged out successfully. Super simple, nothing fancy. Just a little bit of user feedback.

> The case we should certainly address is where you sign out and a get permission error. In those cases we should redirect to the start page.

💯

**Comment by tobinmori** [comment]
@atopal sounds like this is your call since you're our UX pro tempore. Let us know what you'd like to do here/if keep it as is, is fine.

**Comment by atopal** [comment]
Let's do the fade out banner, and redirect to the home page for pages where we'd show a permission error otherwise.

**Comment by schalkneethling** [comment]
> Let's do the fade out banner, and redirect to the home page for pages where we'd show a permission error otherwise.

I agree, sounds good to me @atopal
