### ISSUE TITLE
Google Auth Workflow: HTML/CSS

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6008]
Implement HTML/CSS for Google Auth workflow.

See the design in this issue:

https://github.com/mdn/sprints/issues/1634

Acceptance criteria:

- [x] sign-in landing page is updated to offer 2 choices for logging in to MDN: Github and Google
- [x] create/update profile page for Google logins:
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/screens/370705985_Create_Account_-_MDN_Profile_-google-

**Comment by schalkneethling** [comment]
** Some Questions**

- If a user already has an MDN Web Docs Account but now signs up with Google, what is the proposed flow?
- The same question but for Google Auth users signing in with Github
- I assume if a user already has an MDN Web Docs account with the Auth provider they choose on the landing page, they will simply be redirected back to the page they originally came from? i.e. skip the signup page completely?
- With that said though, we will now have an intermediary page so the most common flow might something like: `docs page > auth landing page > authenticated`.

Normally we sent the user back to the page they originally came from but, I assume with the new flow we want to go back one more "page" in history if the previous page was the auth landing page? If not, when we redirect to the auth landing page, I assume we will replace the auth provider logos etc. with a simple message confirming that they have authenticated successfully? And for other pages, we will have the "Growl" style banner we have discussed.

**Comment by schalkneethling** [comment]
## For Google auth

- Do we by default present a text input to users signing up with Google? We previously discussed that we might:

1. Strip off the `@gmail.com` portion and use the remainder as the default username or
2. Just present the text input field for users who signup with Google Auth

Have we made a final decision on this one?

**Comment by atopal** [comment]
We should always re-direct to the page they were on before they clicked on "log-in".

**Comment by atopal** [comment]
for Google auth, let's show them the username without @gmail.com if that's a valid username, or an empty field, if not.

**Comment by atopal** [comment]
As to what to do about multiple auth providers: Unfortunately Nick had to leave before we figured that one out. I'm not sure what our technical capabilities are. (How) would we know that they already have the other auth provider? Can we combine accounts later? 

Ideal flow: you try to log in with another auth provider, we recognize it and offer to use the other one, to combine both, or continue and create a second account.

**Comment by Gregoor** [comment]
I don't have any answers in terms of what we SHOULD do, but if I manage to figure allauth out (which we already use for GitHub) we'd have a backend for connecting multiple accounts "for free".

**Comment by Gregoor** [comment]
If we're able to use allauth for Google login, which we're already using for GitHub, at least the backend for having multiple auth providers should be basically "free".
