### ISSUE TITLE
Google Auth Workflow: Backend OAuth Flow

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6009]
Wire up Google OAuth logins.

I would suggest this, but it looks like it does not support 2.7:
https://github.com/googleapis/google-api-python-client

So might have to go with this:
https://pypi.org/project/google-auth/

Front-end HTML/CSS is here:
https://app.zenhub.com/workspaces/mdn-sprint-board-5ab3d23fd0f4ea53b0022a61/issues/mozilla/kuma/6008

To get this work rolling, can this work be started with undesigned pages/no graphics and just links? After the front-end is done, then implementing this on the front-end should be able to happen quickly. 

Acceptance:
- [ ] user can log in with Google Acct
- [ ] handle both cases of profile image showing (1) default anonymous profile image (2) existing profile image. See design comps for this:

no profile pic: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/screens/374829955
has profile pic: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/screens/374095626

**Comment by Gregoor** [comment]
I'm tempted to go with django-allauth instead, since we're already using it for GitHub. Any concerns about that?

**Comment by tobinmori** [comment]
Nope. That sounds good @Gregoor. Thanks.

**Comment by escattone** [comment]
> I'm tempted to go with django-allauth instead, since we're already using it for GitHub. Any concerns about that?

I just read this and was going to suggest the same, thanks @Gregoor!

**Comment by tobinmori** [comment]
@Gregoor can you write up separate issues out for this if you think it will take longer than a sprint to complete? If you don't think it will, then we convert this to a non-sprint.

**Comment by Gregoor** [comment]
It should be ready for review tomorrow EOD. The tests (#6023) should also be done by end of the week, so I don't think this will take longer than a sprint.
