### ISSUE TITLE
Make MDN look OK in old browsers

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6014]
We added some [polyfills](https://github.com/mozilla/kuma/pull/5996) so that now the React error boundaries aren't so eagerly triggered on old browsers. But our CSS doesn't look great. @schalkneethling tells me it's related to grid support in old browsers.

Here's what a document page looks like in Firefox 38:
<img width="1616" alt="Screen Shot 2019-10-18 at 8 09 19 AM" src="https://user-images.githubusercontent.com/26739/67093089-d39d8580-f17e-11e9-9f66-a05eefd474e9.png">
<img width="1616" alt="Screen Shot 2019-10-18 at 8 09 28 AM" src="https://user-images.githubusercontent.com/26739/67093093-d5674900-f17e-11e9-84d0-55e8b929bdbb.png">

Related: https://github.com/mozilla/kuma/pull/5996
Also: https://github.com/mozilla/kuma/pull/5793

**Comment by peterbe** [comment]
@schalkneethling @atopal I don't know how this relates to IE10 and stuff. 
Also, I'm not sure it looks that bad. The worst that happens is that the stuff that's usually floating right in the header is now underneath the document title. And the sidebar is now underneath the content. My screenshots are from a desktop screen with a lot of resolution. I bet people with ancient browsers don't have that so they'd probably be happy for it to be underneath the content.

**Comment by tobinmori** [comment]
I think this relates to the overarching question of "which older browsers do we need to support?"

I spoke with @atopal about this last week, and it seemed like we don't need to offer that much functionality for older browsers, aside from allowing them a reader mode experience, since most of our users use updated browsers. 

I think we should come up with that definitive browser support list and decide on what requires polyfill and what doesn't.

How's that sound?

**Comment by schalkneethling** [comment]
> I think this relates to the overarching question of "which older browsers do we need to support?"
> 
> I spoke with @atopal about this last week, and it seemed like we don't need to offer that much functionality for older browsers, aside from allowing them a reader mode experience, since most of our users use updated browsers.
> 
> I think we should come up with that definitive browser support list and decide on what requires polyfill and what doesn't.
> 
> How's that sound?

I have very strong feelings here. It is a matter of accessibility and a web for all. Let us not just polyfil at will, but instead, progressively enhance. I believe we have defined out browser support grades here pretty well here https://github.com/mdn/kuma/issues/5995#issuecomment-542729702

This needs to be formalized in our style guide so it is easier to reference than a comment on an issue ;) People come to MDN for the content, and this should always be available irrespective of browser or platform. We should also not need to polyfil to make this possible.

We *need* to prioritize a mobile-first design and code implementation and from there progressively enhance for modern browsers and platforms.

**Comment by tobinmori** [comment]
I spoke with @schalkneethling about this, and think the next step is defining a spec on what an acceptable fallback reader-mode version of MDN would look like e.g. baseline functionality supported. 

@schalkneethling you can create an issue for this when you're ready for this.

Once we have that defined, we can create issues/tasks to support a graceful fallback solution.

**Comment by schalkneethling** [comment]
> @schalkneethling you can create an issue for this when you're ready for this.

Will do.

**Comment by peterbe** [comment]
> Once we have that defined, we can create issues/tasks to support a graceful fallback solution.

Isn't that what *this* issue is?

**Comment by tobinmori** [comment]
@peterbe I'm not sure what it will involve but it's probably a bunch of frontend tasks, right? If it's just a single task that takes a couple days we could use this. Otherwise we can turn this into an Epic. (in our effort **not** to have ginormous issues)

**Comment by schalkneethling** [comment]
No, this might be the Epic, but there will be other individual issues for the work. In terms of polyfills, my intent is to avoid polyfills as far as possible and instead progressively enhance both in terms of styling and JavaScript.

**Comment by ExE-Boss** [comment]
Some of&nbsp;the&nbsp;UI could be&nbsp;made using&nbsp;`display: flex;`.
