### ISSUE TITLE
BCSignal instances with all fields empty strings

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6016]
**Summary**

See https://github.com/mozilla/kuma/issues/6001#issuecomment-543820071
Somehow, a `BCSignal` field was saved with all fields completely empty. 

**Steps To Reproduce (STR)**

1. Fill in the BCSignal form with Network panel open.
2. Observe the HTTP POST request
3. Replicate the HTTP POST query with `curl` and attempt to set all field to blank

**Actual behavior**
Somehow someone managed to submit a `BCSignal` with all fields empty. 

**Expected behavior**
Something should have blocked this from being saved.

**Additional context**
I can't tell if this was submitted via curl or via the JavaScript `fetch` which might have a bug.

**Comment by peterbe** [comment]
Actually, it might be something really busted. This prod:
```
>>> BCSignal.objects.filter(explanation=u'').count()
1757
>>> BCSignal.objects.exclude(explanation=u'').count()
22
```

The explanation field is mandatory in the form when you try to use the form in a browser.

**Comment by peterbe** [comment]
I think, to keep things simple, whoever make a PR to prevent these kinds of POST submissions, don't need to add a migration. Basically, once such a PR is in production we can just go into the prod db (django shell) and do something like:

```
BCSignal.objects.filter(explanation=u'').delete()
```

**Comment by atopal** [comment]
Not sure if this is related, but in the Django admin, I can't see individual items. When I click through, it just shows a blank page after a while, not even an error message.

**Comment by atopal** [comment]
Okay, just checked the data. From what I can tell, all entries submitted after October 16, 15:44 (UTC?) do have all the data. I'm pretty sure that coincides with the launch of the new signals tool. Before that we had an implementation that simply didn't have any fields, so those are considered empty then.

**Comment by atopal** [comment]
The bigger question is now: Why so few actual submission? It might be that what we measured before was simply people clicking the button because they were curious, not to report anything. It's too bad we didn't instrument this. We should have :/ We should send events for expanding and each step of the process

**Comment by atopal** [comment]
Removing P1, since it doesn't look like this is a bug

**Comment by peterbe** [comment]
>  simply people clicking the button because they were curious

I know I did. Wasn't it so that it used to be that clicking it would immediately submit. And now it's fancy with a full form.

**Comment by atopal** [comment]
Honestly, now I can't remember anymore whether it was the first or second click, but yeah, didn't require any data entry

**Comment by tobinmori** [comment]
PR #6143 will solve this.

**Comment by jmswisher** [comment]
Is this the same as #6139? Both reference PR #6143; please pick one and close the other.

**Comment by peterbe** [comment]
@jmswisher The PR will close both issues. It's a PR that kills two birds with one stone.
