### ISSUE TITLE
Embedding emoji (🔐) causes publishing to fail with an internal server error

### ISSUE THREAD

**Issue by jcjones** [mdn/kuma#6017]
While publishing https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_3.47_release_notes, we had notated security bugs with a prefix 🔐, which prompts `Internal Server Error`.

It'd be helpful if there was a descriptive error message saying emoji are prohibited rather than an internal server error.

**Comment by peterbe** [comment]
```
OperationalError: (1366, 'Incorrect string value: \'\\xF0\\x9F\\x94\\x90">...\' for column \'content\' at row 1')
```

Sadly our MySQL doesn't support 4-byte unicode characters :(

https://github.com/mdn/kuma/issues/5942
