### ISSUE TITLE
text doesn't wrap on the search results page

### ISSUE THREAD

**Issue by Ocean-ZH** [mdn/kuma#6018]
OS: Windows7
Browser: Chrome 77.0.3865.75
text doesn't wrap on the search results page.

https://developer.mozilla.org/zh-CN/search?q=stopPropagation

![issue-screenshot](https://user-images.githubusercontent.com/20561494/67139795-9ae8d380-f286-11e9-8fcc-92082dbbcb72.png)

and I think you can fix it by adding 
`overflow-wrap: break-word;`
in the container 
![solution](https://user-images.githubusercontent.com/20561494/67139869-7b9e7600-f287-11e9-9c0e-3c5fa96ff3c0.png)

**Comment by peterbe** [comment]
Thanks @Ocean-ZH Would you be interested in helping MDN fix this bug? All you need is `docker-compose`.

**Comment by ankiiitraj** [comment]
Hi, I am in. Will require little help. Thanks.
