### ISSUE TITLE
Legacy namespace documents are indexed/followed in production

### ISSUE THREAD

**Issue by escattone** [mdn/kuma#6022]
**Summary**
Legacy namespace documents, like https://developer.mozilla.org/en-US/docs/User:anonymous:uitest, are given a `robots` `meta` tag of `index, follow`. This may not be important, but I just wanted to record it since it's a deviation from the Wiki view. I discovered this when running the new and improved headless integration tests against production ([the test `test_user_document`](https://github.com/mdn/kuma/blob/b94d91211ed959121b019fc31bf6c63087cac5ff/tests/headless/test_endpoints.py#L126) fails).

**Steps To Reproduce (STR)**
1. Visit https://developer.mozilla.org/en-US/docs/User:anonymous:uitest
2. View the source HTML

**Actual behavior**
<img width="416" alt="image" src="https://user-images.githubusercontent.com/3743693/67247317-d36ae780-f415-11e9-96d0-56a2ac2be996.png">

**Expected behavior**
```
...
<meta name="robots" content="noindex, nofollow">
...
```

**Additional context**
See the [new document template](https://github.com/mdn/kuma/blob/b94d91211ed959121b019fc31bf6c63087cac5ff/kuma/wiki/jinja2/wiki/react_document.html#L15) as opposed to the [Wiki document template](https://github.com/mdn/kuma/blob/b94d91211ed959121b019fc31bf6c63087cac5ff/kuma/wiki/jinja2/wiki/document.html#L41).

**Comment by peterbe** [comment]
The good news is that it's still not mentioned in [the sitemap](https://developer.mozilla.org/sitemaps/en-US/sitemap.xml) but I suspect Googlebot might pick these up because there's no reason not to. 

P1?

**Comment by atopal** [comment]
Yeah, not just that. We are also asking Google to index pages that haven't been localized yet, like https://developer.mozilla.org/de/docs/Mozilla/Add-ons/WebExtensions/API/downloads/BooleanDelta

Can we see how these rules changed? And yeah, I'd pull that into the next sprint as a P1

**Comment by peterbe** [comment]
Hmm... I scraped that one and ran it locally. In the read-only side I get `<meta name="robots" content="noindex, nofollow">` just the same as I get with `wiki.mdn.localhost:8000`. 
Working on it.
