### ISSUE TITLE
Google Auth Workflow: Backend OAuth Flow Tests

### ISSUE THREAD

**Issue by Gregoor** [mdn/kuma#6023]
Depends on #6009 

**Acceptance criteria**
Create a suite of tests that are at least as exhaustive as the ones we have for GitHub OAuth.

**Comment by tobinmori** [comment]
@gregor can you add acceptance criteria for this?

**Comment by Gregoor** [comment]
Sure, I've added a sentence about it. Should it be more explicit? I haven't read the GitHub tests yet, which is why it's so vague.
