### ISSUE TITLE
Sign-In Landing page

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#6024]
**Summary**

We are moving to a new sign-in/sign-up flow where we will be offering two options to users of MDN Web Docs. The first is the existing Github auth and the second new option will be Google Auth.

To facilitate this, we need a new account auth landing page that presents these options to the user(see below):

![Screenshot 2019-10-22 at 15 10 50](https://user-images.githubusercontent.com/10350960/67289216-8b63c780-f4de-11e9-8e41-e5441793b64d.png)

This issue is related to the creation of the new landing page and changing the current account flow to point to this intermediary page, instead of directly sending users to Github.

**Audience**

All new users of MDN Web Docs

**Workaround**

Currently, we offer only one option for sign-up which possibly narrows our reach.

## Acceptance Criteria

- [ ] When a user clicks the `signin` link in the header, they are sent to a new intermediary page as discussed under `summary` above.
- [ ] Page offers the option between our two auth provider i.e. Github or Google
- [ ] Clicking either will send the user to the third party for authentication
- [ ] Show relevant bullet points

**Comment by atopal** [comment]
For now, only use the last bullet point in "benefits of MDN account"

**Comment by schalkneethling** [comment]
I had a chat with @Gregoor on Slack around how we will approach the work for the Google Auth piece. We decided that it would be a good call to do this behind the waffle flag `google-auth`. That means we can open pull requests and land pieces of the work in master without affecting production.

Gregor is still investigating all things oAuth but, this issue will introduce a new flow where a user goes through an intermediary page where they will then choose their Auth provider of choice.

That means that instead of going directly to `github/login` we will now have to first direct a user to the `signup/in` page. Here we will use the waffle flag to conditionally send users to one of the two endpoints, for example:

```
if waffle res.send(signup) else res.send(github/login)
```

**Comment by atopal** [comment]
It seems like adding an actual landing page for this is adding a bunch of overhead. Since we don't have logins from the portal and no content behind log-in, we don't really need a landing page. Would it be easier to use a modal instead?

**Comment by schalkneethling** [comment]
@Gregoor just FYI, I got my wires crossed. I meant I am working on *this* one, and perhaps you can grab the delete account front-end piece once I am done with this. 😄

**Comment by peterbe** [comment]
As agreed, instead of a new issue about what was missed, I should have just reopened this one. 

See https://github.com/mdn/kuma/issues/6297

**Comment by tobinmori** [comment]
Adding to Peter's comment above - this was reopned because it's in need of tests.
