### ISSUE TITLE
Update copy below avatar on edit profile page based on Auth provider

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#6026]
**Summary**

Underneath the avatar on the edit profile page we currently have text that reads:

> Change your avatar at github.com

We need to change this so that it reflects the chosen auth provider

**Audience**

New and existing users of MDN Web Docs

## Acceptance Criteria

- [ ] The copy below the avatar on the profile edit page shows: "Change your avatar on (github||google)" as appropriate

**Comment by schalkneethling** [comment]
I started working on this and I am running into some problems. I am hoping it is merely config related so, here goes.

First off, I have the following in my `.env`

```
ENABLE_RESTRICTIONS_BY_HOST=True
WIKI_HOST=wiki.localhost:8000
ATTACHMENT_HOST=demos:8000
SITE_URL=http://localhost:8000
STATIC_URL=http://localhost:8000/static/
ALLOW_ROBOTS_WEB_DOMAINS=localhost:8000
ALLOW_ROBOTS_DOMAINS=demos:8000
DEBUG=True

...

SITE_ID=3
DOMAIN=localhost.org

MULTI_AUTH_ENABLED=True
```

I have the following in my `hosts` file:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1 localhost demos localhost.org wiki.localhost.org
::1             localhost.org wiki.localhost.org
```

For both Github and Google auth I have the URL and callback configured as something like this:

```
http://localhost.org:8000/
http://localhost.org:8000/users/github/login/callback/
```

Now, when I sign in with Github using `http://localhost.org:8000/` all seems fine. Clicking on `View profile` shows the profile page but, I noticed that this page is not aware that I am signed in:

NOTE: The URL changes to `http://wiki.localhost:8000`

![Screenshot 2020-01-06 at 10 29 01](https://user-images.githubusercontent.com/10350960/71805660-72939880-306f-11ea-9597-c1627594d5ae.png)

When I click back, the "static" site does know as expected so, I proceed to hover over the avatar and then click on `Edit profile`. This results in a Permission Denied page. Clearly this is because the context/page is not aware that I *am* in fact signed in as the user `mdnwebdocs-tester`.

Signing in with Google auth has the same results. I thought that perhaps it has something to do with the fact that both users have the same username i.e. `mdnwebdocs-tester`.

Something else I noticed is that, when signed in and on the `View profile` page, clicking the `Sign In` link does authenticate my successfully with Github, but I am redirected to the following URL:

```
http://localhost.org:8000/users/github/login/callback/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=r8J248zAKpmE
```

With the following error:

```
Account Sign In Failure

An error occurred while attempting to sign in with your account.
Auth Error

{'provider': 'github', 'code': 'unknown', 'exception': None}
```

My OAuth application is configured with `localhost.org` though. Also, even though I states that authentication failed, I am successfully logged in and can now access the `Edit profile` view.

![Screenshot 2020-01-06 at 10 42 57](https://user-images.githubusercontent.com/10350960/71806441-7cb69680-3071-11ea-8e37-e4bc72681cb1.png)


When trying to access `http://localhost:8000/admin` in a separate browser, I am presented with the Django admin sign-in screen. After entering my credentials and pressing enter, I am redirected to a Permission Denied screen with the URL `http://localhost:8000/admin/login/?next=/admin/`

I confirmed that the `superuser` does exist.

@Gregoor any ideas? Thanks!

**Comment by schalkneethling** [comment]
Some, who knows maybe even all, of this might be related to the fact that we are not using the new header with the `whoami` sign in component.

**Comment by tobinmori** [comment]
@Gregoor I've co-assigned this to you, as we may have a bug here. Can you check out what Schalk mentioned above?

**Comment by peterbe** [comment]
I'm confident it's due to `django-allauth` swallowing an error and treating it as "The login failed". 
I wouldn't be opposed to rewriting our authentication and authorization entirely. `django-allauth` 's goal in life is to support all the things and try to make it easy for people to get up and running. But it's a leaky abstraction. We already have our own custom overrides and subclasses. These things aren't that hard to build yourself. And god forbid we one day wanna throw in Yahoo! as another auth provider, it's really not that hard.

**Comment by escattone** [comment]
@schalkneethling There are a few inconsistencies in your `.env` file. The following need to be changed:
```
WIKI_HOST=wiki.localhost.org:8000
SITE_URL=http://localhost.org:8000
STATIC_URL=http://localhost.org:8000/static/
ALLOW_ROBOTS_WEB_DOMAINS=localhost.org:8000
```

Also:
- Confirm, via the Django admin console, that site ID 3 is `localhost.org:8000`
- Ensure that your GitHub and Google social applications have `localhost.org:8000` among their selected sites (it should be highlighted in the `Sites` section of each social application), for example:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/3743693/71858122-eb5e1900-309e-11ea-8595-5e7a039f53af.png">

I think that once these are corrected, you shouldn't have any problems.

**Comment by schalkneethling** [comment]
Thanks, @escattone! Let me give these a go. One of the problems I had though was that I could not access the Django admin ;p Perhaps the inconsistencies in `.env` will resolve that.

**Comment by schalkneethling** [comment]
@escattone The changes to `.env` worked!

So, here are the `.env` entries that need to be present and be exactly as below:

```
ENABLE_RESTRICTIONS_BY_HOST=True
WIKI_HOST=wiki.localhost.org:8000
ATTACHMENT_HOST=demos:8000
SITE_URL=http://localhost.org:8000
STATIC_URL=http://localhost.org:8000/static/
ALLOW_ROBOTS_WEB_DOMAINS=localhost.org:8000
ALLOW_ROBOTS_DOMAINS=demos:8000
DEBUG=True

SITE_ID=3
DOMAIN=localhost.org

MULTI_AUTH_ENABLED=True
```

Then under http://localhost.org:8000/admin/socialaccount/socialapp/ there should be two entries, which should have the following settings:

### Google

![Screenshot 2020-01-07 at 11 22 53](https://user-images.githubusercontent.com/10350960/71884166-73e0c600-3140-11ea-9df0-9cce6e5c7e7a.png)

### Github

![Screenshot 2020-01-07 at 11 24 08](https://user-images.githubusercontent.com/10350960/71884197-7fcc8800-3140-11ea-809b-b22508336879.png)

**Comment by schalkneethling** [comment]
I have restarted work on this but I believe I ran into another problem 😞 

From what I can tell the `User` for the `edit_profile` page is a generic `User` object and does not know much about the authentication aspects. There is a property called `socialaccount_set` but this contains *all* social accounts the user has been authenticated with.

Inside the `edit_profile` page we use a function called `get_avatar_url` to get the user's avatar. This function however does not know which auth provider you used to log in with, instead, it loops over all social accounts for the user and returns the avatar for the first social account that has one.

It also orders the list by date joined and so in a scenario where you authenticated with Github and then at a later stage with Google, it will always return the avatar for Github.

For the work in this issue to be complete, we need a way of knowing which auth provider the user is currently signed in with so that we can get the relevant avatar, and also point them to the correct URL should they wish to change their avatar.

On a side note, something I found strange is that there seems to be code to check whether a user with the same username exists but, I was able to create two accounts with the same username. One using Github and the other using Google as the authentication provider:

![Screenshot 2020-01-07 at 13 24 57](https://user-images.githubusercontent.com/10350960/71892268-38022c80-3151-11ea-8210-82075117fbf7.png)

Technically I should not have been able to do that so, the problem I described earlier may be a symptom of a larger problem 😨 

Thoughts @escattone @Gregoor @peterbe

**Comment by peterbe** [comment]
All of the problems learned from this needs to be put into `configure_social_auth`. 
I'm happy to do the coding if you can extract, from the comments above, what actual mistakes happened that a computer could have figured out. Please please file and issue, detailing what went wrong, and I'll turn it into code.

**Comment by tobinmori** [comment]
@schalkneethling can you list the errs you hit then i can create an issue for this?

**Comment by escattone** [comment]
@schalkneethling Good questions! As far as I know, the social OAuth provider used for the login/sign-in is only available via the `session` object, so for example:
```python
provider = request.session.get('sociallogin_provider')
# The provider will be None if the user is not authenticated.
assert provider in (None, 'github', 'google')
```

Currently, as you already know, we assume that only one avatar will be used for a user, the one associated with the social provider first used for signup (as the [`get_avatar_url` function](https://github.com/mdn/kuma/blob/d8df3099ff60d957607215516e88d19f44954cf6/kuma/users/templatetags/jinja_helpers.py#L19) currently does), so if the user first signed-up via GitHub, and then later signs-in via Google, we'll still show the GitHub avatar (and make that one available to modify).

If we decide to change that assumption, and show the avatar associated with the social provider used to sign-in, it gets messy. We'll have to at least make the following additional changes, as far as I can tell:
- modify [`get_avatar_url`](https://github.com/mdn/kuma/blob/d8df3099ff60d957607215516e88d19f44954cf6/kuma/users/templatetags/jinja_helpers.py#L19) to accept an additional `provider` argument, and only return the avatar URL for that provider, so something like:
   ```python
   def get_avatar_url(user, provider):
       """
       Get the avatar URL of the given user's given social provider. Assumes that
       the user is not None or anonymous. If the user has no social avatar, returns
       the default avatar URL.
       """
       assert provider in ('github', 'google')
       for account in user.socialaccount_set.filter(provider=provider):
           avatar_url = account.get_avatar_url()
           if avatar_url:
               return avatar_url
       return settings.DEFAULT_AVATAR
   ```
- modify [this line](https://github.com/mdn/kuma/blob/d8df3099ff60d957607215516e88d19f44954cf6/kuma/api/v1/views.py#L214) to be something like:
   ```python
   'avatar_url': get_avatar_url(user, provider=request.session.get('sociallogin_provider')),
   ```
- replace [this line](https://github.com/mdn/kuma/blob/d8df3099ff60d957607215516e88d19f44954cf6/kuma/api/v1/views.py#L328) with something like:
   ```python
   data['github_avatar_url'] = get_avatar_url(user, provider='github')
   data['google_avatar_url'] = get_avatar_url(user, provider='google')
   ```
- decide how we handle the use of `get_avatar_url` when the user we're getting the avatar URL for is not necessarily the same as the user that may be logged in (i.e., we can't use `request.session.get('sociallogin_provider')` to pick a provider), for example [here](https://github.com/mdn/kuma/blob/d8df3099ff60d957607215516e88d19f44954cf6/kuma/users/jinja2/users/includes/user_avatar.html#L2) and [here](https://github.com/mdn/kuma/blob/d8df3099ff60d957607215516e88d19f44954cf6/kuma/wiki/feeds.py#L132). Do we show all of the user's social-provider avatar URL's if there are more than one, or just pick one?

**Comment by escattone** [comment]
@schalkneethling 

> On a side note, something I found strange is that there seems to be code to check whether a user with the same username exists but, I was able to create two accounts with the same username. One using Github and the other using Google as the authentication provider:

Wow, that's really unexpected and worrying. We'll have to look into that more.

**Comment by schalkneethling** [comment]
> Currently, as you already know, we assume that only one avatar will be used for a user, the one associated with the social provider first used for signup (as the [`get_avatar_url` function](https://github.com/mdn/kuma/blob/d8df3099ff60d957607215516e88d19f44954cf6/kuma/users/templatetags/jinja_helpers.py#L19) currently does), so if the user first signed-up via GitHub, and then later signs-in via Google, we'll still show the GitHub avatar (and make that one available to modify).

Hmmm, then I am thinking we should remove the text below the avatar on edit-profile because it does not seem like there is going to be a way to know from which provider the avatar was pulled, and thus we will not know where to direct them to change it. Thoughts @atopal?

**Comment by schalkneethling** [comment]
> @schalkneethling
> 
> > On a side note, something I found strange is that there seems to be code to check whether a user with the same username exists but, I was able to create two accounts with the same username. One using Github and the other using Google as the authentication provider:
> 
> Wow, that's really unexpected and worrying. We'll have to look into that more.

Indeed. But note, the screenshot from before is for the social accounts page. As @peterbe mentioned, that is not the main `User` object that is stored and used for say edit-profile. 

With that said, the username for the main `User` object is `mdnwebdocs-tester` and the chosen username when I signed-in/up with Google was also `mdnwebdocs-tester` so, perhaps the code should have picked this up and prevented the user from creating a new account with that username.

Perhaps even prompting the user with something like:

```
An account with `username` already exists. Did you previously sign-up with `other-social-login`?
```
Thank you for the feedback @escattone

**Comment by atopal** [comment]
> > Currently, as you already know, we assume that only one avatar will be used for a user, the one associated with the social provider first used for signup (as the [`get_avatar_url` function](https://github.com/mdn/kuma/blob/d8df3099ff60d957607215516e88d19f44954cf6/kuma/users/templatetags/jinja_helpers.py#L19) currently does), so if the user first signed-up via GitHub, and then later signs-in via Google, we'll still show the GitHub avatar (and make that one available to modify).
> 
> Hmmm, then I am thinking we should remove the text below the avatar on edit-profile because it does not seem like there is going to be a way to know from which provider the avatar was pulled, and thus we will not know where to direct them to change it. Thoughts @atopal?

Let's drop this feature. We can come back to it when it turns out people don't know how to change it.

**Comment by schalkneethling** [comment]
> > > Currently, as you already know, we assume that only one avatar will be used for a user, the one associated with the social provider first used for signup (as the [`get_avatar_url` function](https://github.com/mdn/kuma/blob/d8df3099ff60d957607215516e88d19f44954cf6/kuma/users/templatetags/jinja_helpers.py#L19) currently does), so if the user first signed-up via GitHub, and then later signs-in via Google, we'll still show the GitHub avatar (and make that one available to modify).
> > 
> > 
> > Hmmm, then I am thinking we should remove the text below the avatar on edit-profile because it does not seem like there is going to be a way to know from which provider the avatar was pulled, and thus we will not know where to direct them to change it. Thoughts @atopal?
> 
> Let's drop this feature. We can come back to it when it turns out people don't know how to change it.

Sounds good. I will amend the issue and open a PR.

**Comment by tobinmori** [comment]
@schalkneethling @escattone @atopal - I definitely think we should be bar any duplicate usernames. 
Shall I open a ticket for this? 

I checked my copy of the DB (a couple months old) - and it seems like this hasn't happened in the past, and probably something we don't want to happen going forward.

**Comment by escattone** [comment]
@schalkneethling @tobinmori 

> On a side note, something I found strange is that there seems to be code to check whether a user with the same username exists but, I was able to create two accounts with the same username. One using Github and the other using Google as the authentication provider:
> 
> ![Screenshot 2020-01-07 at 13 24 57](https://user-images.githubusercontent.com/10350960/71892268-38022c80-3151-11ea-8210-82075117fbf7.png)
> 
> Technically I should not have been able to do that so, the problem I described earlier may be a symptom of a larger problem 😨

Oh! Sorry @schalkneethling I should have looked at this more carefully. I didn't notice until now that your screenshot was from the admin console's social-account view. It's showing that it has associated both of your social accounts, from GitHub and from Google, with your `mdnwebdocs-tester` user. In other words, both social accounts map to the same `mdnwebdocs-tester` user. The code I added with https://github.com/mdn/kuma/pull/6213 does that. If you've signed-up with one social account, then sign-in with another social account, and they both share a common verified email address, the new social account will be mapped to the same user that was created from your original social sign-up.

Also, I double-checked and it's impossible to create two users with the same username, since the `User` DB model we use enforces unique usernames.

So unless I'm still misunderstanding something, there's no problem here, and no need to open a new ticket.

**Comment by atopal** [comment]
Thanks for summarizing Ryan. That's how I understand it too.

**Comment by tobinmori** [comment]
thanks for double checking @escattone! the thought of dups was scaring me!
