### ISSUE TITLE
Where should we send people to report content issues?

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6028]
Spawned from https://github.com/mdn/kuma/issues/6013#issuecomment-545426656 by @SphinxKnight 

The "Report a content problem" links to [github.com/mdn/sprints/](https://github.com/mdn/sprints/issues/new?template=issue-template.md&projects=mdn/sprints/2&labels=user-report&title=%2Fen-US%2Fdocs%2FWeb%2FJavaScript%2FReference)
<img width="475" alt="Screen Shot 2019-10-23 at 8 50 26 AM" src="https://user-images.githubusercontent.com/26739/67394454-340f3700-f572-11e9-93ed-d0b9ac3613e4.png">

Is that really right? I'm a bit baffled by this. Why sprints? Is that for scrum sprinting stuff, like epics.

What's an ideal place actually? What do you prefer @chrisdavidmills ?
We often get issues on mdn/kuma that are plainly content-related and we've never had a great strategy to deal with those.

**Comment by schalkneethling** [comment]
Ah, that should go to https://github.com/mdn/sprints/issues/

**Comment by peterbe** [comment]
Then why do we put Epics in there? 
Is there anything more ideal that what we're currently doing? Otherwise, please close this @chrisdavidmills

**Comment by tobinmori** [comment]
What @sneethling said. :)

@peterbe, generally: 
- content work and user stories are in the 'sprints' repo.
- epics and issues (pertaining to Kuma/leading back to user stories) can live in Kuma
