### ISSUE TITLE
Redirect additional MDN pages to Extension Workshop 

### ISSUE THREAD

**Issue by caitmuenster** [mdn/kuma#6034]
Hi there! We need the following pages to be redirected from MDN to Extension Workshop: 

- https://developer.mozilla.org/docs/Mozilla/Add-ons/AMO/Blocking_Process should redirect to https://extensionworkshop.com/documentation/publish/add-ons-blocking-process/
- https://developer.mozilla.org/docs/Mozilla/Add-ons/Third_Party_Library_Usage should redirect to https://extensionworkshop.com/documentation/publish/third-party-library-usage/
- https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/What_does_review_rejection_mean_to_users should redirect to https://extensionworkshop.com/documentation/publish/what-does-review-rejection-mean-to-users/

It would be great if this could happen by end of day October 25, but we have some flexibility.

**Comment by tobinmori** [comment]
Hi @caitmuenster,

Is there any way that can you give us more heads up for these requests?

We're trying to do abide by (Agile) Sprints for planning our work (having things planned a week before we start the actual work), and support tickets are usually weighed against all the other often urgent items in our backlog. 

The other reason, is that we don't usually do deployments on Fridays (in case something goes sideways), and deployments are arduous for us right now (they usually can take a few hours), but we're working on improving that.

Thanks for your patience, 
Tobin

**Comment by caitmuenster** [comment]
Hey @tobinmori, sorry about that! Yes, I can give more lead time for these requests in the future. :) Thanks for scheduling this request for an upcoming sprint!

**Comment by tobinmori** [comment]
Hi @caitmuenster, thanks for your patience while we pushed Python3 over the hump. 

We've finally deployed your request.

**Comment by caitmuenster** [comment]
Thank you so much, @tobinmori, and congrats on the Python3 work!
