### ISSUE TITLE
Block indicator icons are broken on the React‑based frontend

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/kuma#6035]
## Summary
Block indicator icons are broken, and sometimes duplicated, on the React‑based MDN frontend.

## Steps To Reproduce (STR)

1. Go to the React‑based [Indicator sandbox](https://developer.mozilla.org/docs/Sandbox/Indicators) page.
2. Compare with the Django‑based [Indicator sandbox](https://wiki.developer.mozilla.org/docs/Sandbox/Indicators) page.

## Expected behavior
The block indicator icons have the same position and aren’t duplicated.

## Actual behavior
Because the CSS files are compiled in a different order, the block indicator icons on the React‑based frontend have wrong margins, and sometimes are duplicated.

<details>
<summary><strong>Screenshot</strong></summary>

![Screenshot_2019-10-24 Indicator sandbox](https://user-images.githubusercontent.com/3889017/67475877-48792f80-f657-11e9-8a40-9e6c4fd55826.png)
</details>

## Additional context
The duplicate icons can be fixed by adding `!important` to the `display` property in: https://github.com/mdn/kuma/blob/43db78ccea993ad8e5f567154d645d34e006f5d4/kuma/static/styles/includes/_mixins_indicators.scss#L93-L99

This is being done in #6036.

A much better way to do that would be to get rid of the unnecessary `{{*_Inline}}` macro calls in the `{{*_Header}}` macros, which I’m also doing in https://github.com/mdn/kumascript/pull/963, https://github.com/mdn/kumascript/pull/983, https://github.com/mdn/kumascript/pull/984 and https://github.com/mdn/kumascript/pull/987.

**Comment by schalkneethling** [comment]
> The duplicate icons can be fixed by adding `!important` to the `display` property in:

I would definitely not want us to go this route.

> A much better way to do that would be to get rid of the unnecessary `{{*_Inline}}` macro calls in the `{{*_Header}}` macros, which I’m also doing in [mdn/kumascript#963](https://github.com/mdn/kumascript/pull/963), [mdn/kumascript#983](https://github.com/mdn/kumascript/pull/983), [mdn/kumascript#984](https://github.com/mdn/kumascript/pull/984) and [mdn/kumascript#987](https://github.com/mdn/kumascript/pull/987).

Should this by itself solve the problem and remove the need for `!important` I would recommend we go with this solution. Thank you @ExE-Boss

**Comment by ExE-Boss** [comment]
That would remove the need for the whole `display: none` rule.

**Comment by peterbe** [comment]
How come the Wiki doesn't have the problem? Does the wiki already use the rather hacky `display: none !important` trick?

I see 4 monster PRs that might take years to review. Are you sure there's not a way to greatly simplify those into tiny PRs that are more likely going to get review attention @ExE-Boss ?

**Comment by ExE-Boss** [comment]
No, the&nbsp;wiki&nbsp;CSS has&nbsp;the&nbsp;`display: none` and&nbsp;`.<block‑indicator‑with‑icon>::before` rules located after the&nbsp:rules that set&nbsp;`display: inline‑block` and&nbsp;`margin` properties respectively with&nbsp;the&nbsp;same&nbsp;specificity in&nbsp;the&nsbp;compiled stylesheet, and&nbsp;I&nbsp;have no&nbsp;idea how&nbsp;to&nbsp;reorder the&nbsp;mess of&nbsp;spaghetti&nbsp;code that is&nbsp;the&nbsp;MDN&nbsp;SCSS without introducing any&nbsp;more&nbsp;bugs.

**Comment by ExE-Boss** [comment]
@schalkneethling I’ve&nbsp;now&nbsp;extracted the&nbsp;duplicate&nbsp;icon&nbsp;fix into&nbsp;<https://github.com/mdn/kumascript/pull/1264>.
