### ISSUE TITLE
Firefox alert SSL_ERROR_UNKNOWN_CA_ALERT when using client certificate since version 70

### ISSUE THREAD

**Issue by mbordas** [mdn/kuma#6051]
Since I get Firefox updated to 70.0 (on Ubuntu), I can't connect to a site with client certificate. It worked before the update, and it still works with Chromium and Firefox 35 (an old version I keep for tests).
When I try to open the URL https://xxx.yyy.zz I get Firefox alert: SSL_ERROR_UNKNOWN_CA_ALERT

The server is running Apache2 with the following configuration parameters:

```
<VirtualHost *:443>
               ServerName xxx.yyy.zz
               ProxyRequests Off

                <Location />
                        ProxyPass        http://localhost:1080/
                        ProxyPassReverse http://localhost:1080/
                        ExpiresActive On
                        ExpiresDefault "now"
                </Location>

                SSLEngine on
                SSLCertificateKeyFile   /etc/yyy/ssl/xxx.yyy.zz.key
                SSLCertificateFile      /etc/yyy/ssl/xxx.yyy.zz.crt
                SSLCertificateChainFile /etc/yyy/ssl/xxx.yyy.zz.chain

                SSLVerifyClient         require
                SSLVerifyDepth          2
                SSLCACertificateFile    /etc/yyy/ssl/yyy.ca.pem

                <Location />
                        RequestHeader set SSL_CLIENT_S_DN "%{SSL_CLIENT_S_DN}s"
                        RequestHeader set SSL_CLIENT_I_DN "%{SSL_CLIENT_I_DN}s"
                        RequestHeader set SSL_SERVER_S_DN_OU "%{SSL_SERVER_S_DN_OU}s"
                        RequestHeader set SSL_CLIENT_VERIFY "%{SSL_CLIENT_VERIFY}s"
                        RequestHeader set SSL_TOKEN "**********"
                </Location>

        </VirtualHost>
```
And I use a client certificate.

The Apache's configuration has not been changed. The certificates files on server have not been changed. The client certificate I use has not been changed.
In my firm, some encounter the issue, some other do not, and it looks like the Firefox update to 70.0 matters. I guess it's a bug or one security expectation from Firefox that our Apache configuration does not match.
Could some one help please? Thank you.
Mathieu

**Comment by escattone** [comment]
The issues in this repo are for MDN Web Docs (https://developer.mozilla.org/en-US/), not the Firefox browser. Please try posting your issue to one of the support options at https://support.mozilla.org/en-US/products/firefox instead.
