### ISSUE TITLE
Incorrect 'close' button styling on mobile  [BCD signalling]

### ISSUE THREAD

**Issue by mcroud** [mdn/kuma#6060]
The close button on live is a much thicker "X" on a transparent background:

<img width="454" alt="Screenshot 2019-10-17 at 11 03 09" src="https://user-images.githubusercontent.com/42435754/66999389-d42a1380-f0cd-11e9-89dd-588f17c2fb49.png">

On Zeplin, the "X" sits on a white background and appears much thinner:

<img width="456" alt="Screenshot 2019-10-17 at 11 03 19" src="https://user-images.githubusercontent.com/42435754/66999390-d42a1380-f0cd-11e9-9cb4-5964e2d156ff.png">

The left and right text padding on live also seems more than on the designs.

**Comment by jmswisher** [comment]
@tobinmori Bumping this to P1, since you put it in a sprint

**Comment by peterbe** [comment]
That BCD signaling is the old one. It's gone.

The new one doesn't have a close icon. 
<img width="1063" alt="Screen Shot 2020-01-10 at 10 35 24 AM" src="https://user-images.githubusercontent.com/26739/72165199-0c6f8400-3395-11ea-8fd2-bb61c9dd4756.png">

**Comment by mcroud** [comment]
> The new one doesn't have a close icon.

It does when used on a mobile or smaller device.

**Comment by peterbe** [comment]
My bad! Sorry, I didn't know that. I didn't recognize the screenshot.

**Comment by Gregoor** [comment]
@mcroud can you give me access to Zeplin so that I can download the correct cross symbol from there?

**Comment by mcroud** [comment]
@Gregoor added! Thanks!

**Comment by Gregoor** [comment]
Thank you!
