### ISSUE TITLE
Incorrect column widths on Desktop [BCD signalling]

### ISSUE THREAD

**Issue by mcroud** [mdn/kuma#6065]
On desktop (when fully wide), the first column should appear no larger than `377px`. If we want a guideline that isn't as rigid as pixel measurements then let's say `37%` of the width of the whole drawer.

In the image below we see that the live version (top) has a slightly wider first column then the intended design (bottom).

![Untitled-1](https://user-images.githubusercontent.com/42435754/66998230-cd020600-f0cb-11e9-81e2-2e4d10b94628.jpg)

With more width for the main content area, perhaps we can fit the seven icons in a row for desktop users which appears in the design?

**Comment by mindy** [comment]
Wanted to stay consistent with MDN's grid, so changed it to 31.33333%, instead of 37% as specified in the ticket.

**Comment by tobinmori** [comment]
work is in #6063
