### ISSUE TITLE
literally millions of files in storage

### ISSUE THREAD

**Issue by aborrell** [mdn/kuma#6070]
While making a backup copy of my profile folder, I found millions of files under storage/http+++www.facebook.com cache. I had to cut the backup as it never ended. I'm running Firefox Nightly under Debian Sid. I have a small video showing my attempt to delete files from the copy (I cut the removal it was taking to long) but is about 13Gb long. The term in the bottom left corner of the images shows the rm -Rf command output. I also have a small video
Thanks for your help.
![IMG_20191030_000028](https://user-images.githubusercontent.com/910405/67897324-c9d33500-fb23-11e9-8f30-cb354f9f7c5d.jpg)
![IMG_20191030_000031](https://user-images.githubusercontent.com/910405/67897325-c9d33500-fb23-11e9-99e5-f638bb3ac0e0.jpg)

**Comment by escattone** [comment]
@aborrell The issues in this repository are for MDN Web Docs only, not Firefox. I think you want to post your message to Firefox support (see https://support.mozilla.org/en-US/).

**Comment by aborrell** [comment]
Thank you, sorry for the inconvenience

**Comment by escattone** [comment]
@aborrell No worries, cheers!
