### ISSUE TITLE
Newsletter JS should load deferred

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6077]
We're currently loading the newsletter.js bundle with `async`. There's probably no reason to do that. 
Thankfully the script tag for it is far down in the HTML so the chances are smaller that it'll cause harm. 

`async` script tags *execute* as soon as they're ready. Unlike `defer` which always execute after the rendering phase. This means that `async` script tags can cause the rendering to have to pause as it CPU processes the `async` script. 

One common scenario is if you click on a page, then click an internal link. This time, the script tag gets noticed in the HTML and the browser realizes that it has it in the browser cache, so it executes it immediately. This might mean it's blocking other important rendering and DOM event handlers.

**Comment by peterbe** [comment]
There are actually multiple script tags with `'extra_context': { 'async': True, },` in `kuma/settings/common.py`. Many that shouldn't be. From a quick look, many of them are unimportant since they're part of the wiki. But much of the Wiki relies on `window.jQuery` as a global so there might be race conditions lurking there. 
The only one I can see that should remain `async` is the `perf.js` because that one is so important that it's worth stopping the rendering for that. Perhaps I don't understand what `perf.js` but the name seems to imply that it wants to start doing its thing as soon as possible so it can start measuring stuff.

**Comment by peterbe** [comment]
Hmm.. I just occurred to me that the `newsletter.js` is only used on the home page(s). Performance might be unimportant on those.

**Comment by peterbe** [comment]
Landing pages like `/en-US/` and `/zh-CN/` make up about **2% of our page view traffic**.

**Comment by atopal** [comment]
And those landing pages are already the fastest pages on MDN.

**Comment by peterbe** [comment]
> And those landing pages are already the fastest pages on MDN.

Probably because they have less heavy stuff (interactive examples, BCD tables). 
Doesn't mean we should allow it to be worse than it can be.

**Comment by atopal** [comment]
Of course, just pointing that out since there is diminishing returns.
