### ISSUE TITLE
Inclusion of 'bc-signals` JS depends on request.user

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6078]
from `react_document.html`:
```
  {% if waffle.flag('bc-signals') %}
    {% javascript "bcd-signal" %}
  {% endif %}
```
`react_document.html` is ALWAYS executed anonymously. If the flag is dependent on a user being authenticated, it won't ever be true here but it might be true in the `/api/v1/whoami` XHR.

**Comment by escattone** [comment]
For `react_document.html`, we're OK when using `waffle.flag()` for flags that are on/off for everyone, which the `bc-signals` and `developer_needs` flags are, since no user information (like cookies or authentication) is involved.
