### ISSUE TITLE
react-bcd-signal.js loaded on every document page

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6080]
A page like this: https://developer.mozilla.org/en-US/docs/Web/HTML always loads https://developer.mozilla.org/static/build/js/react-bcd-signal.e49be9481ede.js even though that page doesn't even have a BCD table. 

Might be worth doing a quick analysis of all non-redirect `Document`s that have `{{Compat` somewhere in their raw Kuma HTML. If it turns out that 99.9% of documents have a Browser Compat table, then we can just accept that imperfection.

**Comment by tobinmori** [comment]
@peterbe any idea what the perf hit is on this? (trying to size up the priority level)

**Comment by peterbe** [comment]
@tobinmori  hard to tell. Usually excessive JS causes yank but it’s near impossible to tell how much effect (quantitatively) it has on First Input Delay without experimentation.

**Comment by tobinmori** [comment]
thanks @peterbe
