### ISSUE TITLE
MDN web docs Mobile Width Menu Dropdown Does Not Drop Down on Hover or Click

### ISSUE THREAD

**Issue by jesstucker** [mdn/kuma#6087]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update
<img width="528" alt="Screen Shot 2019-10-31 at 3 21 23 PM" src="https://user-images.githubusercontent.com/3093012/67979170-1d13b900-fbf2-11e9-9777-aed43a6f5660.png">

# Details

Menu dropdown works in desktop widths, but not mobile widths.  Hovering or clicking does not expose the dropdown contents within.  Tested on Chrome 78 and Firefox 69 & 70

**Comment by peterbe** [comment]
![35465FDF-9902-4F3D-A03F-6923A8A90C99](https://user-images.githubusercontent.com/26739/68185043-77b56800-ff98-11e9-8bc0-64042ff48ba9.png)
Works fine in Firefox on iOS (which is ultimately the same as Safari iOS). 
Responsive simulation can be tricky.

**Comment by callahad** [comment]
Looks like this report was misunderstood: On Desktop, when the browser is resized to be narrow, the header does not react to clicks.

Somehow, we are only listening for touch events.
