### ISSUE TITLE
Closures page contains a bad gateway to jsfiddle

### ISSUE THREAD

**Issue by KevinvBeek** [mdn/kuma#6088]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures,

When I visited that page and scrolled down I saw this bad gateway message.

![image](https://user-images.githubusercontent.com/47809099/68210040-96cded00-ffcc-11e9-8eed-729537ae9498.png)

**Comment by peterbe** [comment]
It's an iframe that looks like this:
```
<iframe src="https://jsfiddle.net/78dg25ax/embedded/js,result/" width="100%" height="250" frameborder="0"></iframe>
```
Seems jsfiddle.net had a bit of downtime today. Not much to do here. Thanks for reporting!
