### ISSUE TITLE
Style of "read only" badges is unreadable

### ISSUE THREAD

**Issue by a2sheppy** [mdn/kuma#6090]
**Summary**
Currently, the "Read Only" badges (produced by the ReadOnlyInline macro) are white text on a very light grey background. Essentially unreadable:

| |
|---|
| ![image](https://user-images.githubusercontent.com/1641439/68339211-1f728900-00b2-11ea-8793-4d6533fd158a.png) |

**Steps To Reproduce (STR)**
Go to any page which uses the read only badge, such as any of the following;; note the unreadable badges:

* https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent#Properties
* https://developer.mozilla.org/en-US/docs/Web/API/Element#Properties
* (and any number of API pages)

**Actual behavior**
The badges are light grey with white text, so they can't really be read.

**Expected behavior**
Something where you can actually read the badges. Just changing the white text to something closer to black would do.

**Additional context**
Nope. Though this one is pretty obvious and very common, given how much usage this macro gets.

**Comment by schalkneethling** [comment]
Thanks you for reporting @a2sheppy
