### ISSUE TITLE
Fix Firefox Preview detection

### ISSUE THREAD

**Issue by darkwing** [mdn/kuma#6100]
**Summary**
First reported here:

https://github.com/mozilla-mobile/fenix/issues/6175

It seems kumascript (?) is incorrectly detecting Fennec instead of Firefox Preview.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Open Firefox Preview (repo here: https://github.com/mozilla-mobile/fenix)
2. Go to https://support.mozilla.org/en-US/kb/how-clear-browsing-history-firefox-preview

**Actual behavior**
You see a block saying that the user is using an old version of Firefox Mobile

**Expected behavior**
No message.

**Additional context**
I love MDN.

**Comment by atopal** [comment]
Hey David, that seems to be a support.mozilla.org issue? This is MDN.

**Comment by atopal** [comment]
That's https://github.com/mozilla/kitsune

**Comment by darkwing** [comment]
*Sigh*, my mistake.  I'll file there!
