### ISSUE TITLE
Quick links for active list elements should be bolded in the distinguish way for better UX 

### ISSUE THREAD

**Issue by SapereaudeForest** [mdn/kuma#6101]
**Summary**
When user move around the MDN pages and read e.g. tutorial parts, he needs additional effort to localize his place on the website. Of course there is breadcrumb, but main localization component which is `class="quick-links"` doesn't mark user current location in the distinguish way. There is "next" and "previous" CTA, however user wants jump into right section, which can be rooted not in order and this is why bolding with different style than  `li data-default-state` could be beneficial especially when user is in the middle of long articles. (note! CR -Quick Links could be scrollable)

**Steps To Reproduce (STR)**

 Given I'm on the https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash
 When I would like to use Quick Links on the left hand side
 And move to the another page 
 Then I don't know which links is active one and which can lead to next/previous articles.
 And I need to scroll up to see breadcrumb or CTA which makes additional unnecessary effort
 

**Actual behavior**
Current page is not visible via `class="quick-links"`
![obraz](https://user-images.githubusercontent.com/22987864/68782210-4cd2b000-0639-11ea-853b-e4f7de5256bb.png)

**Expected behavior**
Active page is bolded in the distinguish way with different style than  `li data-default-state` 

**Additional context**
Better UX across the page, together with improvement "Quick Links could be scrollable" for long articles could be really helpfull.
https://github.com/mdn/kuma/issues/6102

**Comment by peterbe** [comment]
I agree but I'm not sure how easy that would be. 
I filed [this](https://github.com/mdn/stumptown-renderer/issues/230) which is for a future refactoring how MDN's sidebars work.

**Comment by atopal** [comment]
Agreed. We have that in the reference, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

**Comment by Gregoor** [comment]
Heya @malqinneh, could use your guidance here, if you have the time. Do you have a recommendation how we'd highlight the active page in the sidebar?

**Comment by malqinneh** [comment]
@Gregoor I can certainly try to help / add input on how to improve sidebar navigation. We're currently doing work on an MDN design system, is this something we want to tackle ASAP?

**Comment by Gregoor** [comment]
Thanks for the quick response, I saw that Kadir already gave me a design direction so I quickly removed my comment again (apparently not quickly enough though 🙂). So I think I'm good with that for now!
