### ISSUE TITLE
[CR] Quick Links could be scrollable

### ISSUE THREAD

**Issue by SapereaudeForest** [mdn/kuma#6102]
**Summary**
For long articles it will be nice to see  `class="quick-links"` able to floating together with the user during scrolling. 

**Rationale**
User will not have to scroll up for a seconds to the top to see quick links and select another interesting part.

**Audience**
Anyone, articles on MDN are amazing, abundant in knowledge and therefore long.

**Proposal**
When  `class="quick-links"` will be scrollable then navigating around website will be much easier/quicker

**Additional context**
https://github.com/mdn/kuma/issues/6101

**Comment by peterbe** [comment]
That might be very tricky if the sidebar's own height is more than height of the browser window. Because how else are you supposed to be able to scroll the side bar. And some sidebars get really long.

**Comment by peterbe** [comment]
Also, what does `[CR]` mean?

**Comment by atopal** [comment]
Peter, at that point the side bar itself becomes scrollable. See here: https://docs.microsoft.com/en-us/azure/backup/backup-mabs-protection-matrix

I'm not convinced that that's great UX.

**Comment by jmswisher** [comment]
@tobinmori Bumping this to P1 since you added it to a sprint.

**Comment by atopal** [comment]
Why was this made a P1? I don't see the urgency.
