### ISSUE TITLE
div with inline style that is position:fixed  /zh-CN/docs/Web/CSS/Adjacent_sibling_combinator

### ISSUE THREAD

**Issue by ClassicOldSong** [mdn/kuma#6106]
Check this page: https://developer.mozilla.org/zh-CN/docs/Web/CSS/Adjacent_sibling_combinator

A mysterious translation plugin label appears on the left side of the page, which probably comes from someone who edited the page while using a select-to-translate extension.

![image](https://user-images.githubusercontent.com/10512422/68796010-0d35b380-068d-11ea-97bc-f92c0d0fbaa9.png)

May this be a potential way of XSS?

**Comment by peterbe** [comment]
I'm able to reproduce it locally:
<img width="1113" alt="Screen Shot 2019-11-13 at 2 35 33 PM" src="https://user-images.githubusercontent.com/26739/68797600-e3e03d80-0622-11ea-9024-9c7eed2ddba0.png">

**Comment by peterbe** [comment]
Not an XSS thing. It's just some rather odd content. Someone's just put
```html
<div id="blbt-translation-icon" style="margin: 0px; padding: 0px; font-family: sans-serif; position: fixed; left: 17px; top: 447px; width: 20px; height: 20px; line-height: 20px; color: rgb(255, 255, 255); background-color: rgb(0, 0, 0);">
<div style="margin: 0px; padding: 0px; width: 20px; height: 20px; line-height: 20px; color: rgb(255, 255, 255); background-color: rgb(0, 0, 0);"></div>
</div>
```
into the content. 
It's not insecure. I just don't get why [XiangHongAi](https://wiki.developer.mozilla.org/zh-CN/profiles/XiangHongAi) did it: https://wiki.developer.mozilla.org/zh-CN/docs/Web/CSS/Adjacent_sibling_combinator$compare?locale=zh-CN&to=1540152&from=1469297

I'm not sure what it is or why it's there but it's a bit ugly that the editor allows you to put any inline style into any div which might vandalize the functionality of the page.

**Comment by peterbe** [comment]
[I just removed that weird `<div>`](https://wiki.developer.mozilla.org/zh-CN/docs/Web/CSS/Adjacent_sibling_combinator$compare?locale=zh-CN&to=1590595&from=1540152)
