### ISSUE TITLE
Implement flags in common.py for User Acct functionality

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6107]
We require constance flags that will toggle on/off the User Acct functionality, so that we can merge the FrontEnd code into master, w/o major rebasing hassles.

**Comment by peterbe** [comment]
What is the reasoning for not just using an environment variable (and `settings/common.py`)?
Constance should only be used if there's a genuine need to toggle something global without having to wait for a release.

**Comment by escattone** [comment]
> What is the reasoning for not just using an environment variable (and `settings/common.py`)?
> Constance should only be used if there's a genuine need to toggle something global without having to wait for a release.

I agree. I think we should just use an environment variable and an associated setting in `settings/common.py`.

**Comment by peterbe** [comment]
The "Mugshot or 'Sign in' link" always depend on the XHR fetch of `/api/v1/whoami` so we can add stuff to that in `api/v1/views.py`.

**Comment by Gregoor** [comment]
@peterbe wdyt about rendering required settings into the HTML after SSR? i.e.

```jsx
<script type="application/json">
  {JSON.stringify(pick(settings, 'USE_MULTI_AUTH_', ...)).replace('</', '<\\/')}
</script>
```

**Comment by peterbe** [comment]
I wouldn't be opposed to that. 
Thing is, I'd rather keep `whoami` clean and pure and personal.

**Comment by Gregoor** [comment]
Fixed in https://github.com/schalkneethling/kuma/pull/3

**Comment by tobinmori** [comment]
@Gregoor can we close this one?

**Comment by Gregoor** [comment]
Oh yup, should've done that already!
