### ISSUE TITLE
Please remove the "Take a screenshot" entirely

### ISSUE THREAD

**Issue by marcelduin** [mdn/kuma#6109]
It's useless and people that will want to make a screenshot will know how to do that. Please remove all that stuff. It's confusing.

**Comment by peterbe** [comment]
What URL is that that you're referring to?

**Comment by marcelduin** [comment]
Any, right-click on any page and it says "Take a screenshot". This applies to all context menus.

**Comment by peterbe** [comment]
Thanks for sharing but this GitHub repo is for the Mozilla Developer Network website (aka. MDN) https://developer.mozilla.org
