### ISSUE TITLE
T - Reach out to other JAM-Stackers

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6119]
Acceptance Criteria:
Meetings with the following 
- [ ] Microsoft (MSDN)
- [ ] React
- [ ] Kubernetes

**Comment by jmswisher** [comment]
@atopal This issue is not in the spreadsheet for Ursula Rucker. Is that an oversight, or should it be removed from the sprint?

**Comment by atopal** [comment]
We too this out during sprint planning, because I was over subscribed
