### ISSUE TITLE
Reuse code (de-dupe via pattern lib)

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6123]
Acceptance Criteria:

- [ ] ?

**Comment by schalkneethling** [comment]
? 😕 😸 @tobinmori

**Comment by tobinmori** [comment]
@schalkneethling consider this a placeholder for now! But I think the spirit of this issue will be to investigate how to make the front-end html/css/js nice and organized in the world of yari/stumptown (that best suits the way files are organized in those projects).

**Comment by schalkneethling** [comment]
@tobinmori I am going to close this one. The work on this is kinda happening, but will not happen in Kuma
