### ISSUE TITLE
U - Competitive Analysis - Study other documentation projects' GitHub file organizations

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6124]
Acceptance criteria:

- [x] Provide a document describing how other orgs, organize their Github Files for contributor workflows

**Comment by escattone** [comment]
Sorry, although I've started this work, I haven't had the time I need to complete it with everything else that arose during the sprint (e.g, #6235, #6236, and #6237 among others). Can we moved this into the next sprint?

**Comment by tobinmori** [comment]
Yes, it can @escattone! This is lower priority so moving it over is fine.

**Comment by escattone** [comment]
[Here](https://docs.google.com/document/d/1Iukt7ZenCNwYTA0NlGzXra-xnMwBo1kglUaK53etigw/edit?usp=sharing) is the document that I'm working on. Thanks to @ddbeck for recommending the Kubernetes documentation repo as an important model to investigate.

**Comment by escattone** [comment]
I'm closing this, since I think that's enough research for now.
