### ISSUE TITLE
Fix "This PDF Document might not be displayed correctly" issue

### ISSUE THREAD

**Issue by l-miller** [mdn/kuma#6128]
Hi All!

Here is a valid PDF file (checked up with various methods):
[Example.pdf](https://github.com/mdn/kuma/files/3852353/Example.pdf)

It pops up a print dialogue while opening (expected) and an annoying warning "This PDF Document might not be displayed correctly" (not expected, the screenshot is included).
![screenshot](https://user-images.githubusercontent.com/57762565/68959500-35352c00-07df-11ea-8cd7-b107bb1f9ed0.png)

Please, remove the unneeded warning here.
AFAIK other browsers open this file just fine.

Thank you.

**Comment by peterbe** [comment]
This GitHub repo is about MDN (developer.mozilla.org) not Firefox the browser. 

See https://bugzilla.mozilla.org/
