### ISSUE TITLE
Outbound link tracking regression

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6132]
**Summary**
On October 24 2019 we did something that lead to outbound link tracking dropping to 0. Before that we had about 20000 events per work day. It looks like that's the only event that was affected. 

**Additional context**
The event category is "Outbound Links". We use that to count the number of times outbound links are clicked on.

**Comment by peterbe** [comment]
Note-to-self; start here: https://github.com/mdn/kuma/blob/1abcd6eb5faea79f5e46447ff39d6c5147301be4/kuma/static/js/analytics.js#L138
