### ISSUE TITLE
task completion banner broken

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6133]
**Summary**
The task completion survey banner is visually broken on all pages.

**Steps To Reproduce (STR)**
Not that easy to re-produce since the banner shows up for only 5% of users. I think there might be a waffle url parameter, not quite sure though. Once you can get it to show, scroll to the bottom of the page. The unstyled banner is displayed there.

**Actual behavior**
Banner is displayed at the bottom of the page, instead of the top right corner. It's not styled either. See screenshot

![Array_prototype_forEach___-_JavaScript___MDN](https://user-images.githubusercontent.com/557852/69071286-ec24e800-0a29-11ea-9b55-d56b6413cf19.png)

**Expected behavior**
Show a styled box in the top right corner.

**Additional context**
This is directly impacting our ability to measure our KPI, and is a high priority issue.

**Comment by Elchi3** [comment]
fwiw, it presented itself to me when I was on wiki.developer.mozilla.org today.

**Comment by atopal** [comment]
@Elchi3 you mean the correctly styled version in the top right corner?

**Comment by Elchi3** [comment]
Yes, I can screenshot it next step time if I'm lucky to see it again. I'm using Firefox 70, Ubuntu.

**Comment by peterbe** [comment]
@atopal Your screenshot didn't upload here on the issue description. Can you try attaching it again?

**Comment by atopal** [comment]
Done. Weird though, maybe it's just me? I checked the numbers and if anything we now have more people taking the survey than a month ago.

**Comment by atopal** [comment]
oh, never mind, this is the MDN Web DNA (the needs survey). I was the only user who had it turned on permanently for testing puroposes.

**Comment by peterbe** [comment]
Perhaps I misread this but https://github.com/mdn/kuma/pull/6108 is a solution to this. 
What happened in your case was that the `developer_needs` flag was `True` but when Jinja prepared the page, referencing waffle flags, the `developer_needs` flag was `False`. Clearly a mismatch.

**Comment by atopal** [comment]
Yes, agreed, it's already being tracked. I had assumed we had a new issue.
