### ISSUE TITLE
Retry failed basket requests

### ISSUE THREAD

**Issue by Gregoor** [mdn/kuma#6147]
Depends on #6141 (the PR adding basket) and #5424 (which contains the util function `requests_retry_session`)

Currently basket requests are only tried once but one shall not trust network or external services or software in general. So we should add retries!

**Comment by tobinmori** [comment]
This is currently blocked by our lack of a SF instance:
https://bugzilla.mozilla.org/show_bug.cgi?id=1562678

Workaround: 
Create a flag in the DB that indicates that a user has opted in to email subscription.

**Comment by tobinmori** [comment]
Closing this until we have an SF instance ready to go.

**Comment by tobinmori** [comment]
As of now, this is not super urgent because we're awaiting Salesforce access, but may come back soon.

**Comment by tobinmori** [comment]
Note: Opt-in flag in database has been merged

**Comment by atopal** [comment]
please don't push that to production before the instrumentation for it is in.
