### ISSUE TITLE
Create an updated sample database

### ISSUE THREAD

**Issue by escattone** [mdn/kuma#6148]
**Summary**
Create a new, updated sample database for local development.

**Rationale**
It's been almost a year or more since we've updated the sample database, and since then many things have changed, including the removal of many Kumascript macros that the old documents within the current, outdated sample database still use.

**Due Date**
Early 2020.

**Comment by atopal** [comment]
Elevated to P1 for Sprint Charlie

**Comment by escattone** [comment]
This is done.

https://mdn-downloads.s3-us-west-2.amazonaws.com/mdn_sample_db.sql.gz 

It was a struggle. First I tried running https://github.com/mdn/kuma/blob/master/scripts/create_sample_db.sh (on a production `web` pod and after first exporting a value for `DATABASE_URL`). It ran for 3-4 hours and in the end failed [here](https://github.com/mdn/kuma/blob/6b785e37449649945899b975b4b03d060e538900/scripts/create_sample_db.sh#L70). It seemed that it was unable to scrape at least 5 document dependencies, but the resolution wasn't clear. In the end, I freshly loaded the previous sample DB, ran the migrations, and updated and rendered all of its documents (e.g., none of the documents use the `CommunityBox` macro any longer). I don't think it's worth spending any more time than this. At least the new sample DB is better than the previous one.
