### ISSUE TITLE
When logged in, 404 page uses the header used for logged out users

### ISSUE THREAD

**Issue by dumptyd** [mdn/kuma#6153]
Even when you're logged in, 404 page still shows the option to Sign In.

![image](https://user-images.githubusercontent.com/16368429/69499295-84cdd300-0f16-11ea-8fdd-c60f17df0295.png)

### Steps to reproduce

Visit this URL while signed in: https://developer.mozilla.org/en-US/docs/Web/API/DOMParser/parseFromString

**Comment by peterbe** [comment]
Not only that, but the whole header is wrong. It's the header used for wiki.developer.mozilla.org. 

Technically this issue a dupe but I can't find the original one :)

**Comment by peterbe** [comment]
Found the original issue. Turns out it was accidentally closed so that's why it slipped. 
Closing your issue in favor of https://github.com/mdn/kuma/issues/5623
Thanks for filing!!
