### ISSUE TITLE
TypeError: hrefAttrValue is null

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6154]
**Summary**
`local-anchor.js` assumes that every `<a>` element in the DOM has a `href`. But in `wiki-compat-signal.js` there is a `<a>` without a href:
https://github.com/mdn/kuma/blob/fe06cc4abf710956d74df75491119f159f3f46ed/kuma/static/js/wiki-compat-signal.js#L14

I don't yet know when exactly it happens because I couldn't immediately reproduce it [in prod](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body#Browser_compatibility)

**Comment by peterbe** [comment]
<img width="1500" alt="Screen Shot 2019-11-25 at 8 55 19 AM" src="https://user-images.githubusercontent.com/26739/69546419-b9b34780-0f61-11ea-8c3c-653ca4ca7a4a.png">

**Comment by peterbe** [comment]
@atopal @Elchi3 Can we just delete the old BC signal thing? The one that's only loaded on wiki.developer.m.o. The one that doesn't display a pretty form with actual questions.

**Comment by atopal** [comment]
sure

**Comment by peterbe** [comment]
Actually, it happens every time. 
<img width="1616" alt="Screen Shot 2019-11-25 at 9 00 05 AM" src="https://user-images.githubusercontent.com/26739/69546590-0860e180-0f62-11ea-9b2b-a6bbcda70a2e.png">
