### ISSUE TITLE
Discrepancy between w.d.m.o and d.m.o for embedded live examples with hidden fragments when opening in CodePen / JSFiddle 

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/kuma#6161]
**Summary**
When a live sample has hidden parts (cf. the first live sample of https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout ), clicking "Open in CodePen" (or "Open in JSFiddle") does not produce the same result whether we click from developer.mozilla.org ([this page](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout)) or from wiki.developer.mozilla.org ([this page](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout)).

**Steps To Reproduce (STR)**

1. Open https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout
2. Click on the first "Open in CodePen" button

**Actual behavior**

The embedded pen (in CodePen) does not take into account the `<pre>`s that had `class="hidden"`.
Result from opening from d.m.o on CodePen: https://codepen.io/SphinxKnight/pen/jOOjwLG

**Expected behavior**

* The result in CodePen / JSFiddle should be the same than the one on the MDN page
* Result from opening from w.d.m.o on CodePen: https://codepen.io/SphinxKnight/pen/gOONRGM

* There should not be any discrepancy for live samples between d.m.o and w.d.m.o

**Additional context**
* Reported earlier through https://github.com/mdn/sprints/issues/2376
* Macro: https://github.com/mdn/kumascript/blob/master/macros/EmbedLiveSample.ejs
* Kuma: https://github.com/mdn/kuma/blob/master/kuma/javascript/src/live-examples.js

**Comment by peterbe** [comment]
This is what's happening: https://codepen.io/peterbe/pen/LYEVYxy?editors=1010#0

In jQuery it can merge the text content of multiple DOM nodes. I think it basically does `string1 + string2 + stringN == $element.text()`

**Comment by peterbe** [comment]
Here's the foundation of the solution by the way: https://codepen.io/peterbe/pen/yLyNLXL?editors=1010#0

**Comment by SphinxKnight** [comment]
@schalkneethling / @peterbe Thanks a lot :) (I wish I could "thumbs up" a commit)
I always forget: when approximately will it be possible to test that in prod?

**Comment by schalkneethling** [comment]
> @schalkneethling / @peterbe Thanks a lot :) (I wish I could "thumbs up" a commit)
> I always forget: when approximately will it be possible to test that in prod?

We do not do prod pushes on a Friday so, I would say on Monday?

**Comment by SphinxKnight** [comment]
Thanks :)
