### ISSUE TITLE
[question] resizing editor

### ISSUE THREAD

**Issue by leela52452** [mdn/kuma#6162]
i am fixing URLs and sometimes typos. i am using mobile device. i am having issue with resizing toolbar. it is somewhat difficult for lengthy articles.   it is consuming more than 75% of screen size. my preferred way is to use full screen mode. 

**editor : normal**

![editor -normal](https://user-images.githubusercontent.com/52065244/69695192-5a754480-10d3-11ea-9686-5926fe5e356d.png)

**editor : full screen**

![editor -fs](https://user-images.githubusercontent.com/52065244/69695206-68c36080-10d3-11ea-85eb-e55c1c92a17f.png)

**Comment by atopal** [comment]
Hey Leela, we are currently in the process of moving away from the wiki editor and won't be fixing bugs on mobile. Sorry for the inconvenience here, but hopefully we'll have a better editing experience soon
