### ISSUE TITLE
Thunderbird can't sign in to gmail.

### ISSUE THREAD

**Issue by Gyulank** [mdn/kuma#6164]
I have Ubuntu 20.04 Hu and Thunderbird 60.3.0 (64-bit) En.
When I fill in the data, the net window pops up and then I fill in and then a window pops up to enable Thunderbird and then prints Thunderbird that the username or password invalid. But the new 68.2.2 Hu working, and I tell it to Ubuntu too. Maybe they update it.

**Comment by escattone** [comment]
@Gyulank The issues in this repo are for MDN Web Docs only.
