### ISSUE TITLE
Remove automatic language change function

### ISSUE THREAD

**Issue by wisyr** [mdn/kuma#6166]
Please, it's driving me crazy when with every time I enter on MDN docs I have to manually change from - in my particular case - polish to english language.

Even if polish is my native language I don't want to read docs in polish, since they are usually incomplete and sometimes even deprecated or simply empty. 

I guess most of programmers are familiar with english and they don't really need to read docs in their native language. But if they do, they can change it manually. 

Please consider my request. 
Kind regards, and thank you for such a great library!

**Comment by tobinmori** [comment]
Thanks @wisyr this is on our radar and in our backlog.

**Comment by wisyr** [comment]
@tobinmori Thank you and once again thanks for an outstanding library!
