### ISSUE TITLE
Manually upgrade Python dependencies where possible

### ISSUE THREAD

**Issue by callahad** [mdn/kuma#6173]
Additionally, at least 70 more of our approximately 120 dependencies are outdated.

As part of #6167 we should update our dependencies where possible.

**Comment by callahad** [comment]
As a benchmark, with all of our dependencies pinned at their current version.

```
$ poetry show --all | wc -l
113
$ poetry show --all --outdated | wc -l
71
```

That's where we're starting from:

__71/113 (63%) of our Python dependencies are outdated.__

**Comment by tobinmori** [comment]
@callahad can you give a ballpark estimate on this one? (e.g. roughly, how many weeks/sprints you think this will take?)

**Comment by callahad** [comment]
I'll be able to refine this by the end of the week, once I'm cranking on this work again, but I think end of February is a reasonable goal for completing the epic this is attached to (#6167), taking into account the Berlin All Hands, travel, etc.

Timeliness of reviews is a known unknown, and I suspect at least a few unknown unknowns will pop up in the course of this effort, which could cause it to slip beyond February.

**Comment by atopal** [comment]
I think we need to break this down into meaningful milestones that can be scoped and resourced properly. That might also help address the review issue.

**Comment by callahad** [comment]
I think the Epic is reasonably subdivided already:

- #6172 is for upgrading Django
- #6173 (this issue) is for upgrading everything else, where possible
- #6175 is automating future upgrades to dependencies

I don't see a way to further split this issue, _a priori,_ which wouldn't be artificial or contrived. To wit,  don't know what's changed in our dependencies, and thus how much effort will be required for each upgrade, until I actually do the work.

What I do know is a rough order of magnitude (40-odd outdated dependencies), and a deadline (April, when Django 1.x goes EOL). So if things start tracking too slowly against that target, or if I uncover unexpectedly gnarly upgrades, I can call for help. But until then, it's more of a knuckle-down-and-do-the-work problem than a resourcing problem.

**Comment by tobinmori** [comment]
@atopal this is one of those tasks with a lot of uncertainty - where each upgrade could potentially be a worms or (hopefully) an empty can. Unfortunately, not all dev tasks have certainty associated with them and I think this is one of them. I think at best @callahad could give a estimation range, if he's to answer with honestly (which I think he's trying to do). 

So maybe we can give an estimation range here? (best/worst case)

**Comment by atopal** [comment]
If there is no meaningful breakdown that would yield valuable iterations, I'd still break it down into chunks: Maybe 5 items out of 70 for the next sprint, or something similar, and we can always take in more if necessary.

**Comment by tobinmori** [comment]
@atopal I chatted with @callahad and we came up with a path forward: we'll break this task into 3 phases (generally). We expect each Phase to take around a Sprint (but of course the uncertainty is high here - and becomes increasingly so as Dan reaches the end; so, we'll reevaluate upon completion of Phase 1):

- Phase 1: Reduce outdated dependencies to 25% (#6326)
- Phase 2: Reduce outdated dependencies to 10%
- Phase 3: Reduce outdated dependencies to 5%

**Comment by jmswisher** [comment]
Looks like this is superseded by #6326 (and later phases) and so can be closed. Correct?

**Comment by atopal** [comment]
Thanks Tobin, that makes sense to me.

**Comment by jmswisher** [comment]
@tobinmori @callahad @atopal Or is it now an epic that includes #6326?

**Comment by tobinmori** [comment]
Hi @jmswisher, I'll close this. I attached #6327 to EPIC #6167.
