### ISSUE TITLE
收藏问题

### ISSUE THREAD

**Issue by FYS397** [mdn/kuma#6179]
前段时间还有标题对应的收藏按钮，现在怎么消失了呢，是出错了还是取消了？这个收藏按钮很实用的呀，可不可以恢复，谢谢！

**Comment by callahad** [comment]
(Google Translate)
> Some time ago, there was a favorite button corresponding to the title. How is it disappearing now? Is it wrong or cancelled? This collection button is very useful, can it be restored, thank you!

**Comment by tobinmori** [comment]
Can you check wiki.developer.mozilla.org and see if it's there? Thank you.

**Comment by callahad** [comment]
Oh! @atopal thinks this might be asking about the permalink icons on subheads, e.g.:

![Screen Shot 2019-12-09 at 17 43 55](https://user-images.githubusercontent.com/24193/70459242-a8af1e00-1aab-11ea-9155-63e83bc218e8.png)

**Comment by callahad** [comment]
We'd be happy to accept pull requests re-adding these to the main MDN site.

**Comment by callahad** [comment]
(Removing "good first issue" label... seems like our rendering infrastructure is a bit more complex than I had imagined.)
