### ISSUE TITLE
Purging an empty page with no revision causing ISEs

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/kuma#6191]
**Summary**
A user reported https://github.com/mdn/sprints/issues/2509. I investigate via the admin panel (document ID 246112) and removed the link from the English parent to allow the user to add a translation.

However with this slug (https://wiki.developer.mozilla.org/ko/docs/Learn/CSS/CSS_layout/레거시_조판_메서드 ) I cannot:

* edit without an ISE
* get the history without an ISE
* get the revisions list without an ISE
* move the page without an error

**Rationale**
This would clean the pages' space and free the slug for a potential use

**Due Date**
This is not really urgent but I would appreciate any interest.

**Additional context**
I was not able to add a "shallow" revision from the admin panel

**Comment by peterbe** [comment]
We do get a lot of Sentry errors related to documents that don't have a revision. I don't yet understand why a document wouldn't have a revision but it's definitely related to translated content in some way. It's moderately rare but when it happens it breaks hard.
