### ISSUE TITLE
Write a tool that can reliably render a set of macro calls in a collection of docs

### ISSUE THREAD

**Issue by wbamberg** [mdn/kuma#6192]
Write a tool that can reliably render a set of macro calls in a collection of docs, and write the result back into the Wiki DB.

"render" means that the macro call is replaced with the static HTML it creates.

## Acceptance criteria
We can easily selectively render KumaScript macros for subsets of the Wiki.

**Comment by escattone** [comment]
See https://github.com/mdn/kuma/pull/6372 and https://github.com/mdn/kumascript/pull/1318.
