### ISSUE TITLE
Write a tool that can reliably remove a set of macro calls from a collection of docs

### ISSUE THREAD

**Issue by wbamberg** [mdn/kuma#6193]
Write a tool that can reliably remove a set of macro calls from a collection of docs, and write the result back into the Wiki DB.

"remove" means that the macro call no longer appears in the source doc.

## Acceptance criteria
We can easily selectively remove KumaScript macros from subsets of the Wiki.

**Comment by escattone** [comment]
See https://github.com/mdn/kuma/pull/6372 and https://github.com/mdn/kumascript/pull/1318.
