### ISSUE TITLE
Empty example in at Array.prototype.reduce() page

### ISSUE THREAD

**Issue by davecaos** [mdn/kuma#6197]
https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Array/reduce
![imagen](https://user-images.githubusercontent.com/6124495/70228923-02be8500-1734-11ea-9045-ec9d9090aa63.png)

**Comment by chrisdavidmills** [comment]
This example works fine for me on Firefox and Chrome; what browser are you looking at this in?

**Comment by davecaos** [comment]
It was in Firefox, but when I reached help -> about the browser download the upgrade/restart and now it is working :ok:  ¯\_(ツ)_/¯

![imagen](https://user-images.githubusercontent.com/6124495/70234093-a0b74d00-173e-11ea-9f92-159a218ef4dd.png)
