### ISSUE TITLE
Turn back on instrumentation of MDN header

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6199]
**Summary**
When we switched to the react header, we disabled sending events for usage of the header, the breadcrumbs, login, etc.

**Steps To Reproduce (STR)**
Hover or click on a header item in the wiki, it will send an event, do the same on the developer.mozilla.org and it will not.

**Comment by schalkneethling** [comment]
Here is the list of signals I have identified:

- [ ] Track clicks on access menu items
- [ ] Track clicks on main nav links
- [ ] Track clicks on breadcrumb links
- [ ] Track clicks on Sign In

@atopal Do we get signals from clicks on the new table of contents? Also, are we still getting signals from interacting with the custom language selector in the header area?

**Comment by peterbe** [comment]
Here's what I've found; in the Wiki it triggers a `mdn.analytics.trackEvent` when...

1. You **right-click** on a link in the header sub-menus, a link in the `#nav-access` menu that might not be visible, or any of the links in the breadcrumbs. (independent of further clicks)
2. You **hover, `touchstart`, or focus** on any header-area menu that opens. Including "Technologies", "Tools", your mugshot, the little eye icon, the little cog icon. (But not when hovering over "Sign in" for not-logged in users)
3. **Clicking** the "Sign in" link. 
4. **Clicking** that "Jump to:" bar if it's sticky. 
5. You **right-click** *or* **click** those little "local anchor" (the little chain icon) to the right of `h2` and `h3` tags inside the document.

There are other uses of `trackEvent` scattered around but unrelated to the header. For example, interactive examples or dashboards.

This started out as my own personal notes for being able to do the [PR review](https://github.com/mdn/kuma/pull/6252/files). I think my list is more complete and accurate and I'm now going to analyze if the PR matches this list exactly.

**Comment by schalkneethling** [comment]
> Here's what I've found; in the Wiki it triggers a mdn.analytics.trackEvent when...

Thanks for digging into this further Peter 🍵 

> Clicking that "Jump to:" bar if it's sticky.

This is wiki only so should not be applicable here no?

> You right-click or click those little "local anchor" (the little chain icon) to the right of h2 and h3 tags inside the document.

Again, not header related and not present on the new front end

**Comment by atopal** [comment]
@schalkneethling no, we are not getting events for the TOC, nothing from the language selector either. 

Btw, it's fairly easy to check whether an event is sent or not, just open the network panel of the dev tools and click on something. The event will show up in the list (or not)
