### ISSUE TITLE
U - Research static site generators for use in Stumptown

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6200]
Acceptance criteria:

- [ ] investigate 2-3 popular static site generators such as Gatsby
- [ ] determine whether they can be used instead of site generator part of Stumptown Renderer
- [ ] document learnings

**Comment by callahad** [comment]
Gatsby's clearly the new VC-funded hotness, but I'd strongly recommend considering [Hugo](https://gohugo.io/). I have experience with it and can answer any questions that might arise.

A few pros:

* Renders pages _incredibly_ quickly (typically under 1 ms/page)
* Ships as a standalone binary (easy deployment / maintenance)
    * The binary includes built-in support for Sass, syntax highlighting, asset minification, etc.
* Sustainable community
    * Has successfully navigated a leadership transition
    * 40k stars, 600 contributors on GitHub
    * First released in 2013
* Decent third-party editor support ([Netlify CMS](https://www.netlifycms.org/), [Forestry](https://forestry.io/), [Hokus](https://www.hokuscms.com/))
* Flexible handling of [multilingual sites](https://gohugo.io/content-management/multilingual/)

The initial setup can feel a bit byzantine, and it doesn't have React support built-in (it's really just concerned with generating static websites), but it's ultimately a very flexible and performant platform.

**Comment by peterbe** [comment]
I changed the estimate from a 2 to a 5 because I think this is big. 
The empiricism isn't going to come from reading through the README of these ready-made shrinkwrapped tools. It would require deep-diving and really understanding the product to be able to contrast it with what we want to build in Yari.

**Comment by mindy** [comment]
I have some experience with Gatsby (used it to build a marketing site)-- happy to answer any questions that you might have. 

I hate being the "new" person and commenting without context or historical awareness, but in case this is helpful, this might be worth taking a look: https://github.com/facebook/docusaurus. At the very least, it fits in with the dinosaur theme.

**Comment by callahad** [comment]
> I hate being the "new" person and commenting without context or historical awareness

Do it! Your perspective, unburdened by historical context is super useful here.

To be honest, I'm not super aware of what our needs are, either. There's a very real chance that Hugo is a total non-starter (especially if we need React + SSR), so I think the most useful thing you and I can do right now is raise our hands and say "I know this platform, what do you need to know about it?"

**Comment by tobinmori** [comment]
Thanks for the suggestions/advice @callahad and @mindy.

I'm going to break this story up since it's so potentially huge, into 2-3 points for each site-generator. For now it sounds like Gatsby/Hugo are the contenders.

Any other ones anybody?

**Comment by peterbe** [comment]
> I'm going to break this story up since it's so potentially huge, into 2-3 points for each site-generator. For now it sounds like Gatsby/Hugo are the contenders.

Not needed. The task is an exploration. 

There is no doubt in my mind that you *can* generate a static site (ready to be thrown upon a CDN) with Hugo, Gatsby, Django, Docusaurus, etc. The really important and interesting exploration is to taste how they feel against our context, scale, and legacy. Unfortunately, those things are hard to genuinely answer until you just try to do it fully. Something that takes a lot of time. 

I'm happy to take this time to explore but I don't think we need to break it down much further.

**Comment by atopal** [comment]
I'd strongly suggest breaking it down, so we have some milestones along the way. 5 points is about two weeks straight. What would be a meaningful way marker? A good point to collect feedback?

**Comment by tobinmori** [comment]
@atopal do we want to keep this one alive?

I think in Berlin the dev team concluded that pulling in a site generator would not be terribly painful, after the fact. 

Despite that, I think Hugo is the remaining candidate that can be assessed.

**Comment by atopal** [comment]
Going with our own vs using an existing site generator is a pretty big decision in my book. I'd love to read the argument for either decision or at least have a conversation about it. I would not drop this story.
