### ISSUE TITLE
deleteuser API endpoint

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6206]
Parent ticket: https://github.com/mdn/sprints/issues/1922

In https://github.com/mdn/kuma/issues/6071 there's going to be a UI where the user clicks to delete hes account and then as part of that UI it needs to figure out whether to bother the user asking them the questions that are demonstrated (in the wiki) in these screenhots: https://github.com/mdn/kuma/pull/6149#issue-344684821

Also, that same endpoint should be able to delete the user. With parameters (based on the user's choice) regarding donating contributions or to scrub the profile entirely clean. 

Acceptance Criteria:

- [ ] You can GET to find out about the user (based on your cookie, not by username in the URL!)
- [ ] You can POST with `-d contributions=keep` or `-d contributions=donate` which will hook into the same machinery as https://github.com/mdn/kuma/pull/6149 implements
- [ ] The user is "removed"

**Comment by tobinmori** [comment]
Sounds like we're unsure if this can just be pure backend functionality (w/o need for an API endpoint). So we'll wait until we have a clearer understanding on this from @schalkneethling

**Comment by peterbe** [comment]
@schalkneethling What Tobin said. Can you make this issue blocked by whichever issue implements the new UI? 
I'd suggest we implement the new UI, behind a env var, and land it in master and make it fail on the actual deletion. Then I'll take over from there.

**Comment by tobinmori** [comment]
@peterbe sounds like we won't need an API endpoint for this. Sorry for the false alarm. We will need just a Django object delete, though.

**Comment by peterbe** [comment]
Not going to close the issue though because when we're in Yari there is no Django any more (only JSON APIs). That day we're going to need it but I don't like the thought of building an API just for the sake of building it. So let's leave this open an unassign it.

**Comment by tobinmori** [comment]
Moved it out of the sprint backlog.

**Comment by schalkneethling** [comment]
@peterbe @tobinmori Should we perhaps close or transfer it to Yari as it will not land in Kuma?

**Comment by peterbe** [comment]
It will land in Kuma eventually. But I don't think there's any point starting on it until we have switched off the wiki.

**Comment by peterbe** [comment]
> it will not land in Kuma?

It will. When we "port" the functionality from `kuma.users.views` to `kuma.api.v1.views` we're going to drastically simplify it since there's no point asking about attributions. 

But I think we'll have everyone forcibly donate their attributions to the `anonymous` user so we can properly delete the user without yet having to delete any rows until Yari has taken over all the file attachments as well.

**Comment by tobinmori** [comment]
+1 Aiming for that one day when Kuma will be just an API service!
