### ISSUE TITLE
Post-S3: Decommission EFS storage

### ISSUE THREAD

**Issue by callahad** [mdn/kuma#6209]
Blocked by #5798

Once we're happy with our use of S3 in production, we should remove and decommission our previous EFS storage resources.

**Comment by atopal** [comment]
I guess this is done?

**Comment by escattone** [comment]
The actual decommissioning of EFS depended on more than moving the file attachments to S3. It depended on these as well:
- https://github.com/mdn/infra/pull/418
- https://github.com/mdn/kuma/pull/7170
Those are done now as well, and so all that's left is for the stage and prod EFS instances to be deleted. Let's close this when @limed completes that.

**Comment by escattone** [comment]
@limed has deleted the stage/prod EFS instances (and removed any trace of EFS from our Terraform code -- see https://github.com/mdn/infra/pull/442).
