### ISSUE TITLE
Post-S3: Find a way to decommission the old attachments CDN

### ISSUE THREAD

**Issue by callahad** [mdn/kuma#6210]
Blocked by #5798. This is a wishlist item.

Once we're happy with our use of S3 in production, we should consider removing the old attachments domain, `mdn.mozillademos.org`.

All attachments on Kuma are embedded into the document text as literal URLs which point to `https://mdn.mozillademos.org/files/{file_id}/{file_name}`. Despite appearances, this does not point to a single file. Rather, it points to a single Attachment, which in turn can have many AttachmentRevisions, each with their own file.

In a post-S3 migration world, the only job of this endpoint is to redirect to a permanent URL of a specific AttachmentRevision on our Cloudfront CDN. It'd be great if we could cut out the middle man.

The problem is, all current and old document revisions with attachments contain these URLs in their body. To completely get rid of the CDN, we'd need to search, resolve, and replace that string throughout our database.

...and while we're at it, we should probably get rid of the idea of an AttachmentRevision altogether, as we don't seem to expose any UI for those, and they just needlessly complicate our data model.

Lastly, while replacing these old URLs with their static, Cloudfront equivalents would solve this in the short term, a longer-term solution would likely involve leaving some kind of reference in the document that Django resolves once. Say, at render time.

**Comment by peterbe** [comment]
Once we're in Yari, this'll be a super search `sed` trip across the repo of content and it would be gone. 



> get rid of the idea of an AttachmentRevision altogether

Moot when we're in Yari since the files will just sit in the repo as regular files. If you want to see the history of a file it's just regular git commit history.
