### ISSUE TITLE
Update minor Node version in kuma_base Docker image

### ISSUE THREAD

**Issue by callahad** [mdn/kuma#6214]
Our `kuma_base` image currently pulls in Node 10.16.3:

https://github.com/mdn/kuma/blob/6d51409fd3f0321d99e66fbed4187af36abe1aac/docker/images/kuma_base/Dockerfile#L4

Node 10.17.0 was [released two months ago](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md); we should bump the version.

Note: Node v10 is an LTS release that is [supported until April 2021](https://nodejs.org/en/about/releases/), so no urgent changes needed, but it enters "Maintenance LTS" in April 2020, so we'll want to move to Node v12 some time next year.

**Comment by callahad** [comment]
If nothing else, this would at least give us a better error message for #6195 😁

**Comment by peterbe** [comment]
Do we have any objections to just going for Node 12 here?
