### ISSUE TITLE
Revise CI builds

### ISSUE THREAD

**Issue by callahad** [mdn/kuma#6216]
Our CI builds take a long time before they even begin executing, and the whole suite usually takes over 12 minutes before it completes.

We should look into cleaning up our Travis setup (or moving to GitHub Actions?) to both do less work, and to do it in a more parallel way.

(#6174 also makes this a bit worse for the linting task, but my hope is to first simplify our dependency situation, _then_ worry about optimizing, per this bug.)

**Comment by callahad** [comment]
Here's what our Travis CI scripts do, and roughly how long each step takes:

```
     # Build and boot containers
5:17 | VERSION=latest make build-base
 :58 | VERSION=latest make build-kuma
 :52 | docker-compose up -d

     # Ensure services are ready
 :12 | docker-compose exec -T web urlwait mysql://root:kuma@mysql:3306/developer_mozilla_org 30
 :10 | docker-compose exec -T web urlwait http://elasticsearch:9200 30

     # Build assets
 :01 | docker-compose exec -T web make clean
 :02 | docker-compose exec -T web make localecompile
 :47 | docker-compose exec -T web make build-static

     # Django setup
 :10 | docker-compose exec -T web ./manage.py migrate
 :03 | docker-compose exec -T web ./manage.py makemigrations --check --dry-run

     # Run tests
3:35 | docker-compose exec -T web make coveragetest # 3:35
 :07 | docker-compose exec -T web npm test # 0:07

     # Refresh locales
 :15 | docker-compose exec -T web make localeextract # 0:15
 :05 | docker-compose exec -T web make localetest # 0:05
 :02 | docker-compose exec -T web make localecompile # 0:02
 :01 | git -C locale diff -G "^msgid " templates/LC_MESSAGES # 0:01

     # Upload coverage
 :02 | bash <(curl -s https://codecov.io/bash) # 0:02
```

The two quick wins that I can spot are:

- Moving the `urlwait` calls later (right after building assets) saves ~20 seconds
- Not calling `build-kuma` saves a minute; we don't use it directly. The `ci-python` script notes that the step is done "only to test that the kuma docker image can be built without error, not because it's needed by docker-compose." If we can cache the result of `build-base` we could run `build-kuma` in a separate, parallel job with the rest of these tasks.

Otherwise, the only places we're likely to make significant headway are:

- `docker build` (5:17)
- `pytest` (3:35)
- `build-static` (0:47)

**Comment by callahad** [comment]
And what's taking so much time in our docker build? I ran a build locally with an empty cache and got the following timings for each step in our Dockerfile:

```
 :00 | [internal] load .dockerignore
 :00 | [internal] load build definition from Dockerfile
 :00 | [internal] load metadata for docker.io/library/python:3.8.0-slim@sha256:7df1fd6bb894e03b488c01fd05eaa4dd677f5b57d800c209f7f0af9867137df9
 :11 | [1/14] FROM docker.io/library/python:3.8.0-slim@sha256:7df1fd6bb894e03b488c01fd05eaa4dd677f5b57d800c209f7f0af9867137df9
 :00 | [internal] load build context
 :31 | [2/14] RUN set -x     && apt-get update     && apt-get install -y --no-install-recommends         curl         gpg         dirmngr         libsasl2-modules         gettext         mime-support
 :00 | [3/14] RUN groupadd --gid 1001 node   && useradd --uid 1001 --gid node --shell /bin/bash --create-home node
 :16 | [4/14] RUN ARCH= && dpkgArch="$(dpkg --print-architecture)"   && case "${dpkgArch##*-}" in     amd64) ARCH='x64';;     ppc64el) ARCH='ppc64le';;     s390x) ARCH='s390x';;     arm64) ARCH='arm64
 :00 | [5/14] RUN useradd --uid 1000 --shell /bin/bash --create-home kuma     && mkdir -p app     && chown kuma:kuma /app     && chmod 775 /app
 :00 | [6/14] WORKDIR /app
 :00 | [7/14] COPY --chown=kuma:kuma ./pyproject.toml ./poetry.lock /app/
2:53 | [8/14] RUN pip install poetry~=1.0.0b9     && POETRY_VIRTUALENVS_CREATE=false poetry install --no-root     && rm -rf ~/.cache/pip ~/.cache/pypoetry/cache
 :00 | [9/14] COPY --chown=kuma:kuma ./package.json ./package-lock.json /app/
 :00 | [10/14] RUN mkdir /tools     && chown kuma:kuma /tools     && chmod 775 /tools
 :00 | [11/14] WORKDIR /tools
 :30 | [12/14] RUN ln -s /app/package.json /tools     && ln -s /app/package-lock.json /tools     && npm ci
 :00 | [13/14] RUN find /tools/node_modules/.bin/ -executable -type f -o -type l -exec ln -s {} /usr/local/bin/ ;
 :00 | [14/14] WORKDIR /app
 :06 | exporting to image
```

I did have one run where step `[4/14]` took 1:14. Looked like the PGP keyservers were being slow to respond? Either way, that step is a source of high variability in our build times.

The only things that take any meaningful time are:

- Downloading the base python image (0:11)
- Installing Debian packages (0:31)
- Installing Node (0:16)
  _Note: I had one run where this took over 1:15 due to sks-keyservers.net being slow to respond)_
- Installing Python dependencies (2:53)
- Running `npm ci` (0:30)

Our dependencies don't change _that_ often; we should be able to dramatically speed up builds if we can somehow take advantage of Travis's pip and npm caching from inside our Docker builds.

There might also be a faster / more predictable way to install Node itself.

**Comment by peterbe** [comment]
Is the Keyserver stuff just because we so carefully manually install Node (and npm?) within the Python Docker file? 
I don't know who this nikolaik user is but he seems to be onto something: https://hub.docker.com/r/nikolaik/python-nodejs/
I know CircleCI build their own such combo images: https://circleci.com/docs/2.0/circleci-images/

However, what if we build our own base image. Our very own "https://hub.docker.com/r/mdn/kuma-base/" or something. So instead of `FROM python:3.8.0-slim@sha256:7df1fd6....` we'll do `FROM mdn/kuma@sha256:800c209...`. Woud that mean a PR build on mdn/kuma that just updates some CSS would finish faster if the image is already baked and ready in Dockerhub?
 
I still think we'd still need to do poetry install every time but it could potentially combine the 0:11 + 0:31 + 0:16 + 1:15 (roughly!)

**Comment by peterbe** [comment]
The other major thing would be if we could mount a filesystem for poetry to use as a cache. Not just for local development but if so we could tell travis to cache that directory between tests.
