### ISSUE TITLE
Can't confirm email because it was sent to the wrong one

### ISSUE THREAD

**Issue by Forkest** [mdn/kuma#6218]
I had two emails connected to my GitHub account:
First one was marked Receives notifications (It seems like you can't move this marker manually)
Second one was marked Primary
Actually, I have lost access to the first one long ago, so I added the second one and made it Primary, without removing the first. And it was OK up until today when I tried to register on MDN.

By default MDN suggested me my Primary e-mail address, I accepted, but after that it sent confirmation link to the first one. Now I can't do anything with it. I tried to revoke access from GitHub, but after allowing it again I return to the same state - waiting for e-mail confirmation.

Please purge my account so I can register again (I have removed non-working e-mail from my GitHub account now) and fix the software: you should send confirmation to the selected email.

**Comment by tobinmori** [comment]
Hi @forkest we don't send a confirmation email. we only send confirmation emails for unconfirmed email addresses. 

Can you let us know if you'd like to delete your MDN acct so you can start over?

**Comment by Forkest** [comment]
Yes, that e-mail was unconfirmed on GitHub, but I didn't request an MDN account with that address in the first place. I selected another one that was my Primary and confirmed on GitHub. And now my profile is locked until I'll be able to confirm the e-mail I don't have access to. I don't even have that e-mail on my account anymore, but MDN doesn't bother to check.

Yes, please, delete my MDN account to fix my problem, but that confirmation logic is flawed and should be fixed nonetheless.

**Comment by tobinmori** [comment]
Thanks Forkest. I've deleted your MDN account. I hope the next account creation goes more smoothly!

**Comment by Forkest** [comment]
Thanks, successfully registered now. Although the previously used nickname was unavailable, that is not much of a problem.

You might want to adjust the labels.

**Comment by tobinmori** [comment]
Thanks Forkest.

**Comment by Forkest** [comment]
Sad that you didn't bother to revisit the confirmation logic so that it wouldn't happen to other people in the future.
