### ISSUE TITLE
First example Button Does Not Work

### ISSUE THREAD

**Issue by tomrowbo** [mdn/kuma#6221]
https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Sending_forms_through_JavaScript
Error: Uncaught ReferenceError: sendData is not defined
    at HTMLButtonElement.onclick

**Comment by chrisdavidmills** [comment]
Hi @tomrowbo , and thanks for reporting this. Some errors got introduced into these examples; I've fixed them now. They'll still alert an error, but this behaviour is to be expected, I think.
