### ISSUE TITLE
Redirect "Featured

### ISSUE THREAD

**Issue by caitmuenster** [mdn/kuma#6225]
Hi there! 

Apologies; it looks like we have another page that needs to be redirected from MDN to Extension Workshop. 

AMO Features Extensions policies (https://developer.mozilla.org/docs/Mozilla/Add-ons/AMO/Policy/Featured) should be redirected to https://extensionworkshop.com/documentation/publish/recommended-extensions/. 

This can happen during the next MDN push. 

Thank you!

**Comment by tobinmori** [comment]
Thanks for ticket @caitmuenster, we'll get this out in our next push!

**Comment by escattone** [comment]
This is done!

**Comment by caitmuenster** [comment]
Thank you!
