### ISSUE TITLE
array error

### ISSUE THREAD

**Issue by daflorescom** [mdn/kuma#6228]
when constructing an array with numeric keys and omitting 0, the length of this appears as if there were 3 arrays
![Captura de Pantalla 2019-12-11 a la(s) 3 22 34 p  m](https://user-images.githubusercontent.com/51464050/70657753-6b24cf00-1c2a-11ea-988f-d98ae6108313.png)

**Comment by peterbe** [comment]
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Console
