### ISSUE TITLE
Document Kuma installation, fixes and workaround notes.

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6230]
Reason: existing docs may be out of date and missing developer experience obstacles and their workarounds.

**Comment by mindy** [comment]
This was addressed in the following PRs:
https://github.com/mdn/kuma/pull/6242
https://github.com/mdn/kuma/pull/6284
https://github.com/mdn/kuma/pull/6313
https://github.com/mdn/kuma/pull/6324
