### ISSUE TITLE
Multi Auth - How do we want to switch it on and off?

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#6231]
Hey All,

Now that the Google backend piece has landed, I picked up my front-end work again. I made a couple of small tweaks and I can now successfully sign in with either Github or Google o/\o

The question now is, how do we "dynamically" switch this feature on and off?

One thought I have is the following:

Inside `login.jsx` there is this piece of code:

```
return (
    <a
        href={`/users/account/signup-landing?next=${LOCATION}`}
        data-service="GitHub"
        rel="nofollow"
        className="signin-link"
    >
        {gettext('Sign in')}
    </a>
);
```

Now, if we had access to something like `settings.MULTI_AUTH_ENABLED` we could set a different value for the `href` based on whether it is enabled or not.

Then in the code that binds an event handler to the sign-in link to show the modal, we can essentially do something similar, i.e.

There is this function called `window.mdn.modalDialog.showModal()`. In there we can check for the setting and then return false if the feature is not enabled. That means that when a user clicks on the sign-in link, it will behave as it currently does.

If it is enabled, clicking sign in will trigger the modal from where a user can choose either Github or Google.

Doing this in the `showModal` function is simple as I know how to get at `settings` but, how do we expose those to the React side?

Any other ideas are welcome :)

**Comment by peterbe** [comment]
I first wrote a long suggestion about how you could use the DOM and read from it. 
Or we could have custom settings being passed in from `ssr.py` to `ssr.jsx`. 

A much simpler and better suggestion would be to change `login.jsx` to:
```
return (
    <a
        href={`/users/account/start?next=${LOCATION}`}
        rel="nofollow"
        className="signin-link"
    >
        {gettext('Sign in')}
    </a>
);
```
Then, write a Django function that looks something like this:

```python
def start_signin(request):
    if settings.ENABLE_MULTI_AUTH:
       url = reverse(... that thing that creates '/users/account/signup-landing' ...)
    else:
       url = reverse(... that thing that creates '/users/github/login/' ...)
    
    # TODO
    # some urlparse magic that copies the current query string from the current 
    # request onto this new url

    return redirect(url)
```

The sign in link is not displayed until the `/api/v1/whoami` XHR fetch is complete so if you want to make it depend on a per-user basis (can use waffle Switches) that's an option too.

**Comment by peterbe** [comment]
> There is this function called `window.mdn.modalDialog.showModal()`. In there we can check for the setting and then return false if the feature is not enabled.

I don't understand this at all. What does the modal have to do with this?
When multi-auth is NOT enabled, clicking "Sign in" will take you to github.com's auth screen. When multi-auth IS enabled, clicking "Sign in" will take you to a page of our own, right?

Or, did we have in mind to implement a modal to be ready to use on whichever possible page you're on?

**Comment by schalkneethling** [comment]
> > There is this function called `window.mdn.modalDialog.showModal()`. In there we can check for the setting and then return false if the feature is not enabled.
> 
> I don't understand this at all. What does the modal have to do with this?
> When multi-auth is NOT enabled, clicking "Sign in" will take you to github.com's auth screen. When multi-auth IS enabled, clicking "Sign in" will take you to a page of our own, right?
> 
> Or, did we have in mind to implement a modal to be ready to use on whichever possible page you're on?

So, if you are on a mobile device or, JavaScript is not available(for whatever reason), the link will direct you to a dedicated multi auth landing page.

Should you be on a tablet or desktop device, clicking sign-in will open a modal dialog. See below:

![Screenshot 2019-12-13 at 09 53 13](https://user-images.githubusercontent.com/10350960/70781020-6c6f0c80-1d8e-11ea-917e-2771418ac91d.png)

**Comment by schalkneethling** [comment]
> I first wrote a long suggestion about how you could use the DOM and read from it.
> Or we could have custom settings being passed in from `ssr.py` to `ssr.jsx`.
> 
> A much simpler and better suggestion would be to change `login.jsx` to:
> 
> ```
> return (
>     <a
>         href={`/users/account/start?next=${LOCATION}`}
>         rel="nofollow"
>         className="signin-link"
>     >
>         {gettext('Sign in')}
>     </a>
> );
> ```
> 
> Then, write a Django function that looks something like this:
> 
> ```python
> def start_signin(request):
>     if settings.ENABLE_MULTI_AUTH:
>        url = reverse(... that thing that creates '/users/account/signup-landing' ...)
>     else:
>        url = reverse(... that thing that creates '/users/github/login/' ...)
>     
>     # TODO
>     # some urlparse magic that copies the current query string from the current 
>     # request onto this new url
> 
>     return redirect(url)
> ```
> 

This sounds great! Thanks for the suggestions @peterbe. Do you have any available cycles to open a PR against my PR[https://github.com/mdn/kuma/pull/6094] to add this? Alternatively, @Gregoor do you some time?

> The sign in link is not displayed until the `/api/v1/whoami` XHR fetch is complete so if you want to make it depend on a per-user basis (can use waffle Switches) that's an option too.

I don't think we will need this.

**Comment by schalkneethling** [comment]
It does seem that we are decided on using a `setting` in `common.py` though, correct?

**Comment by Gregoor** [comment]
Happy to take that on (I think it is also still assigned to me). Though I do believe we'd need to handle it on the client-side, given the modal interaction. I'm gonna check if we already make config settings available to the client somewhere.

On an organizational note, we might want to merge this issue with #6107

**Comment by peterbe** [comment]
> It does seem that we are decided on using a `setting` in `common.py` though, correct?

[Ryan has spoken](https://github.com/mdn/kuma/issues/6107#issuecomment-553665528) and I agree. 

Only use Constance or Waffle if there's a solid requirement to be able to turn on/off immediately and without being able to wait for a release. 

Also, although I don't know if it's been practiced, but we can technically toggle an environment variable in Kubernetes without having to wait for a kuma release.

**Comment by peterbe** [comment]
Actually, let's move any discussion about *how* to get the env vars into React components to https://github.com/mdn/kuma/issues/6107

**Comment by tobinmori** [comment]
moved to #6107. closing.
