### ISSUE TITLE
correct number of levels

### ISSUE THREAD

**Issue by s-e1** [mdn/kuma#6239]
"Table
The following table is ordered from highest (20) to lowest (1) precedence."

The table actually has 21 levels.

**Comment by velusgautam** [comment]
@s-e1 Can you be more specific about this bug like URL of the page you are referring or screenshot.

**Comment by s-e1** [comment]
Sorry.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
at the Table section.

**Comment by chrisdavidmills** [comment]
Fixed. Thanks for reporting!
