### ISSUE TITLE
"Sign In" grid item on MDN Web Docs Homepage is obscured by Mozilla Logo for Galaxy mobile phones

### ISSUE THREAD

**Issue by ghost** [mdn/kuma#6245]
On your [MDN Web Docs](https://developer.mozilla.org/en-US/) home page, your "Sign In" grid item is missing the declaration grid-area: L for the .signin-link class. This is especially noticeable when viewing the website using a mobile reponsive smartphone view (Galaxy s9/s9+) with your developer tools and on an actual Galaxy S8.

Sincererly,
Matt
[John 14:6](https://www.biblegateway.com/passage/?search=John+14%3A6&version=NKJV)

**Comment by velusgautam** [comment]
![homepage-s9](https://user-images.githubusercontent.com/8556085/70844802-2b4d2a00-1e6c-11ea-9e20-621b6de2b08f.jpeg)
I can see the "Sign In" in Galaxy S9 can you share your screenshot.

**Comment by matt16v16** [comment]
![Screen Shot 2019-12-14 at 18 32 23](https://user-images.githubusercontent.com/58869249/70855940-f3140e80-1ea0-11ea-8b17-ddb72844f684.png)

This screenshot was taken using firefox's responsive design mode with the Galaxy S9/S9+ option. I also confirmed this bug by actually looking at Mozilla Web Docs on a Galaxy S8 today.

Sincerely,
Matt

**Comment by tobinmori** [comment]
@malqinneh will add a UX epic as a blocker to this issue.
