### ISSUE TITLE
Russian translated page says it's not translated to Russian yet

### ISSUE THREAD

**Issue by kdidenko** [mdn/kuma#6251]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

🤭I have occasionally followed the 🔖bookmark from my handy and suddenly appeared on the 🇷🇺Russian version of the actual article (thought my browser is configured for 🇬🇧 En locale) , which declares itself as it's an English version of the documentation, and that it is missing any translations to the rest of the languages. 

🤔 Well... I guess the message is too tacky and in fact is outdated, so probably, either author of the original text, or the one who wrote the translation must update the content of the warning message according to the actual state of the main article's content. 

**EDIT** URL for the page is: https://developer.mozilla.org/ru/docs/Web/Web_Components/%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D1%85_%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2

**Comment by schalkneethling** [comment]
@Gregoor perhaps you can also take a look at this one? Thanks!

**Comment by peterbe** [comment]
I still believe the translation message thing is for @Gregoor to look at but I was curious and looked it up:
```
>>> d=Document.objects.get(slug='Web/Web_Components/Использование_пользовательских_элементов')
>>> d.id
229759
>>> d.parent
<Document: /en-US/docs/Web/Web_Components/Using_custom_elements (Using custom elements)>
>>> d.locale
'ru'
>>> d.is_localizable
False
```

**Comment by sirartemis** [comment]
Guys!!! I think this is for the same reason that links don't work. Read my issue.

**Comment by Gregoor** [comment]
Thanks for the report and also thanks for the lookup Peter! I'm looking into it now

**Comment by sirartemis** [comment]
![screenshot-wiki developer mozilla org-2019 12 24-02_55_02](https://user-images.githubusercontent.com/24634762/71381600-5834d600-25fe-11ea-80cf-d5d3e30003b9.png)
![screenshot-wiki developer mozilla org-2019 12 24-02_58_27](https://user-images.githubusercontent.com/24634762/71381608-608d1100-25fe-11ea-9b23-2e185020cf7d.png)

**Comment by jmswisher** [comment]
@Gregoor @tobinmori Needs an estimate
