### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/with-errors might be broken

### ISSUE THREAD

**Issue by wbamberg** [mdn/kuma#6258]
I believe https://wiki.developer.mozilla.org/en-US/docs/with-errors is supposed to list pages that generate exceptions, and is used by us sometimes to find places where people are calling nonexistent macros, or macros with the wrong arguments, or...

But I added a call to a nonexistent macro in https://developer.mozilla.org/en-US/docs/User:wbamberg and it's still reporting zero errors.

I wonder if it is because the read-only version of the page (https://developer.mozilla.org/en-US/docs/User:wbamberg) is just showing the un-rendered macro call, while only https://wiki.developer.mozilla.org/en-US/docs/User:wbamberg is reporting an error?

**Comment by peterbe** [comment]
I think that the error message is simply lacking on the read-only site. It's just a matter of there being code in place to display the error. It's actually, for a user, pretty useful and attention-drawing which can explain why you're staring at these strange curly brackets.

**Comment by peterbe** [comment]
Works locally. Hmm...
<img width="851" alt="Screen Shot 2019-12-18 at 4 30 13 PM" src="https://user-images.githubusercontent.com/26739/71124834-b7848780-21b3-11ea-8cd7-a92e2a3fec51.png">

**Comment by peterbe** [comment]
Aha! The reason it's not working is because the `/with-errors` page relies on [`filter_for_list`](https://github.com/mdn/kuma/blob/94b36a861dd0bda3610c936a505af9e92b823df5/kuma/wiki/managers.py#L22) which, as you can see on line 29 excludes slugs like `User:wbamberg`.

**Comment by wbamberg** [comment]
Thank you for looking into this, Peter, and sorry for the false report :(.
