### ISSUE TITLE
T - Add new attachment domains to CSP list

### ISSUE THREAD

**Issue by limed** [mdn/kuma#6260]
For context see: https://github.com/mdn/infra/issues/354 

Kuma now serves attachments from S3 via cloudfront, which means we will need to update the CSP list for stage and prod to include the attachment domains.

**Acceptance Criteria**
- [ ] The following domains will need to be added to CSP:

- https://media.stage.mdn.mozit.cloud
- https://media.prod.mdn.mozit.cloud

**Comment by tobinmori** [comment]
@callahad is this something you can add?
