### ISSUE TITLE
Feature regression: "Advanced" search no longer allows query-less search

### ISSUE THREAD

**Issue by a2sheppy** [mdn/kuma#6265]
Previously, using the advanced search functionality (through the special URLs documented on https://developer.mozilla.org/en-US/docs/MDN/Contribute/Tools/Search) did not require the `q=` term specifying a search term.

This allowed us to do things like use `css_classnames=` to find everywhere a given CSS is used in documentation content, `html_attributes=` to locate every use of a given HTML attribute, and `kumascript_macros=` to find every use of one of a set of one or more KumaScript macros.

These searches were often used during refactoring and cleanup work, as well as when doing style and layout improvements to suites of articles. When we need them, we usually need them pretty badly.

While I have no *immediate*, **urgent** need for these search abilities, when the time comes that I do, it will probably be pretty urgent, so I'm filing this now in hopes of getting a fix for this onto the schedule.

**Comment by tobinmori** [comment]
@peterbe is there a workaround for this? maybe a way to allow an explicit None or Null to the 'q' param, something like that?

**Comment by peterbe** [comment]
> @peterbe is there a workaround for this? maybe a way to allow an explicit None or Null to the 'q' param, something like that?

Not that I know of, no. 

I don't think it'd be hard to enable searching on these things without a `q`. The code that checks that `q` is truthy just needs to be moved to the view that's used by https://developer.mozilla.org/en-US/search instead of https://developer.mozilla.org/api/v1/search/en-US
