### ISSUE TITLE
inline style tags appear before <doctype> on homepage

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6266]
https://github.com/mdn/kuma/issues/6059 made it so that the home page has a bunch of inline `<link/>` tags before the `<!doctype html>`

See view-source:https://developer.mozilla.org/en-US/
<img width="1046" alt="Screen Shot 2019-12-18 at 4 44 11 PM" src="https://user-images.githubusercontent.com/26739/71125954-f1568d80-21b5-11ea-977c-47d8a1d8b539.png">

Here's the commit:
https://github.com/mdn/kuma/commit/e90fd2dcc7e4dbe00aaf73f4de3fdd4c9cd5f583

I actually don't know how it breaks the page. Seems my Firefox is coping fine actually. 
But it's dangerously broken and it might break other browsers. It also has potentially negative effects on the download and rendering order.

**Comment by schalkneethling** [comment]
Nice catch, thanks, Peter. I would not have expected the placement of the line causing to be *before* the doctype though, weird.
