### ISSUE TITLE
auth modal doesn't respect Esc key

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6272]
I'm not a modal expert but it seems counter-intuitive that you can't click anywhere outside the modal to close. Either way, the `Esc` key handler only works if the modal is focused which it won't be unless you click into it. 

Also, in Chrome there's a rather ugly blue border for focus on it. 
<img width="638" alt="Screen Shot 2019-12-20 at 2 51 49 PM" src="https://user-images.githubusercontent.com/26739/71288306-b29d1080-2338-11ea-9c85-3c914ee44728.png">

**Comment by peterbe** [comment]
Interestingly, https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html doesn't close the model if you click ouside the modal. 
I can see the usefulness in that actually. Like, if you've typed a bunch of stuff an accidentally mouseclick outside the modal and it suddenly closes. 

However, their example implementation listens for `Esc` on the body rather than the modal.

**Comment by peterbe** [comment]
@tobinmori I disagree that this is a p5. It's very counter-intuitive that the modal doesn't disappear when you press Escape. Marked as a p5 it's very low chance that it gets done. 
Therefore: https://github.com/mdn/kuma/pull/6296

**Comment by tobinmori** [comment]
fair enough @peterbe. made it a p3.

**Comment by schalkneethling** [comment]
> I can see the usefulness in that actually. Like, if you've typed a bunch of stuff an accidentally mouseclick outside the modal and it suddenly closes.

Yup, this has bitten me many times on some sites. :)

> However, their example implementation listens for Esc on the body rather than the modal.

Makes sense, although, when the modal is opened the focus is also moved to the modal so, the `Esc` key should always work. I would not be opposed to changing it to listening on the body though.

**Comment by peterbe** [comment]
> opened the focus is also moved to the modal so, the `Esc` key should always work.

Not true. After it has opened, click anywhere outside the modal, which isn't unrealistic. Now you can't close it by escape any more. 
I know it's a bit counter-intuitive. If you've clicked outside the modal, it's the user's fault for not having the right focus. But the reality is that a modal is a bit like a pop-up or a banner announcement and the instinct is that Escape should kill it. 
Browsers get it. Type `window.confirm('Sure?')` in the Web Console and the grey dialog box appears. Mouseclick somehere outside the dialog and the Esc key still works.
