### ISSUE TITLE
Grammar issue "nothing happen"

### ISSUE THREAD

**Issue by volter** [mdn/kuma#6276]
https://media.prod.mdn.mozit.cloud/attachments/2016/08/20/13779/66fccb7016e4c5dd189b35649c2bdd9f/HTTPRevved.png -- "nothing happen" in the second graph should probably read "nothing happens" (Used on https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching)

**Comment by peterbe** [comment]
Issue moved to [mdn/sprints #2618](https://github.com/mdn/sprints/issues/2618) via [**ZenHub**](https://www.zenhub.com/)
