### ISSUE TITLE
There are some weird redirects in our database

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6278]
Here's just one example:
```
>>> import requests
>>> r = requests.get('https://developer.mozilla.org/en-US/docs/ARIA/User_Agent_Implementors_Guide')
>>> r.status_code
404
>>> r.history
[<Response [301]>, <Response [301]>, <Response [302]>, <Response [301]>]
>>> from pprint import pprint
>>> pprint([x.headers.get('location') for x in r.history])
['/docs/http://www.w3.org/WAI/PF/aria-implementation/',
 '/docs/http:_www.w3.org/WAI/PF/aria-implementation/',
 '/en-US/docs/http:_www.w3.org/WAI/PF/aria-implementation/',
 '/en-US/docs/http:_www.w3.org/WAI/PF/aria-implementation']
```

Redirects in Kuma is determined by 2 fields in the database model: `is_redirect` (integer 0 or 1) and `html`. 
If the document has a `is_direct==1` it parses the `html` (in runtime, every time!) and redirects based on what it finds in there. For example, the example above, when deconstructed in the Django shell:
```
>>> Document.objects.get(locale='en-US', slug='ARIA/User_Agent_Implementors_Guide').html
'REDIRECT <a class="redirect" href="/docs/http://www.w3.org/WAI/PF/aria-implementation/">http://www.w3.org/WAI/PF/aria-implementation/</a>'
```

There are **thousands** of these documents. 
~~I doubt that they get included in the sitemaps.xml but no guarantee. Just a hopeful feeling.~~ Redirects are never included in sitemaps XML files. 

This stuff matters if we're going to Yari this legacy content.

**Comment by peterbe** [comment]
@a2sheppy @chrisdavidmills @wbamberg  Perhaps you can add some wisdom and history to these and perhaps some thoughts about what it would/should mean as we're trying to port these away from MySQL.

**Comment by peterbe** [comment]
@tobinmori I removed the ` KR: Alternative Github-based solution ` label because I don't think it's perfectly relevant. 
In a Yari world, we still need to support redirects. So it's not any more work to deal with "weird redirects" in Yari. It's just that when working on that I noticed it. 

I think we just need to make a quick decision and we can just execute a mass deletion of documents that match these patterns.

**Comment by atopal** [comment]
There are more than 20k 301 redirects (sometimes more than one in a chain) and about 15k 302 redirects. The 301 redirects are most unproblematic, search engines will remember the 301 after the first crawl, but the 302 redirects suck, a good portion of them are due to missing locales in urls eg developer.mozilla.org/docs; that URL is redirected based on your accept-language, so it can't be a 301.

**Comment by peterbe** [comment]
@atopal I was more concerned about URLs like `/docs/http://www.w3.org/WAI/PF/aria-implementation/` not being a real URL. I could see how perhaps some MDN page now needs to be go to `http://www.w3.org/WAI/PF/aria-implementation/` which would make a whole lot more sense. 

Actually, when you look at https://wiki.developer.mozilla.org/en-US/docs/ARIA/User_Agent_Implementors_Guide$edit it sure seems it's just a bug in how it extracts the URL. 
The document's rendered HTML contains:
```
REDIRECT <a class="redirect" href="/docs/http://www.w3.org/WAI/PF/aria-implementation/">http://www.w3.org/WAI/PF/aria-implementation/</a>
```
and from that it extracts that it should redirect to `/docs/http://www.w3.org/WAI/PF/aria-implementation/` but I think it's plainly a bug and that it should have extracted `http://www.w3.org/WAI/PF/aria-implementation/` instead. 

As a matter of fact, it might be super common pattern that if the URL startswith `/docs/https?://` then just rewrite so it drops the `/docs/` part of the URL.

**Comment by atopal** [comment]
Ah, got it. Running this query

SELECT count(*)
FROM `wiki_document`
where `wiki_document`.`rendered_html` LIKE '%/docs/https:%';

It looks like , we have 768 documents with /docs/http:// and 63 with /docs/https://

**Comment by peterbe** [comment]
Actually, if you ignore the archived pages (e.g. `User:%` and deleted documents etc) this is more accurate:
For `en-US` only...
```
REDIRECTS 37132
WEIRD 313 0.8429387051599698
LOCALE 2603 7.010126036841538
OTHER 34216 92.14693525799849
```
Meaning, 37,132 redirects in total and 0.84% of them have that weird `/docs/http...` thing in them. 

Also, 7% of them are simply swapping `/docs/en/` for `/en-US/docs/` only. So about 2,603 documents could technically be deleted and just put into the global redirects file we have with global patterns.

**Comment by peterbe** [comment]
Also, for the full record, these are the numbers you get if you compute for ALL locales:
```
REDIRECTS 71133
WEIRD 811 1.1401178074873828
LOCALE 35556 49.98523891864536
OTHER 34766 48.874643273867264
```

Yari-content already has a solution for redirects so that this doesn't create 71,133 files since all redirects are lumped together.
However, it would be nice to drop 35,556 documents from the database that could all be captured by 1 single redirect rule.
