### ISSUE TITLE
What's an "MDN profile"?

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6288]
<img width="1083" alt="Screen Shot 2019-12-27 at 11 48 40 AM" src="https://user-images.githubusercontent.com/26739/71525293-06f74180-289f-11ea-82e7-1be315f5d8a1.png">

That second sentence has two flaws:

1. There's a new term being added: "profile". The first line and the page's headline talks about "MDN account" which is a word that makes sense. Introducing this second term I think is just adding confusion. 
2. That second sentence isn't helping me as a user. It's just an unavoidable fact that has no benefit. It adds noise and distracts from pressing the buttons.

**Comment by peterbe** [comment]
Here's what it would look like if plainly removed:
<img width="1127" alt="Screen Shot 2019-12-27 at 11 52 46 AM" src="https://user-images.githubusercontent.com/26739/71525396-75d49a80-289f-11ea-8148-9adab6a1633a.png">

**Comment by peterbe** [comment]
@atopal @malqinneh  say the word and I'll fix it :)

**Comment by tobinmori** [comment]
Good point @peterbe. 

+1 that Account vs Profile is a fine line, implying varied uses. I think of Accts as tied to a single login, whereas Profiles are indicative of 1+ types of user usage. E.g. Netflix - you can have one login tied to several profiles. 

I think it makee sense to stick to the word Account, unless we're planning on rolling out something like Netflix profiles (which I doubt we are!).

**Comment by peterbe** [comment]
I'm vaguely pointing out two somewhat related things:

1. The user might be unnecessarily confused and slowed down having to parse and comprehend the difference between an "account" and a "profile". 
2. The less text, the better. Especially since that sentence I pointed out sounds like a chore too.

**Comment by malqinneh** [comment]
It's common knowledge that without an account; [signing in] would/should
prompt users to create an account. Your suggestion to remove that
additional sentence makes sense to me Peter.

**Comment by atopal** [comment]
Yes, let's go ahead and limit wording to account instead of profile.

**Comment by malqinneh** [comment]
> Yes, let's go ahead and limit wording to account instead of profile.

@peterbe @atopal 

"Sign in to enjoy the benefits of an MDN account. If you haven't already created an account, you will be prompted to do so after signing in."

Does the above copy resolve the issue?
