### ISSUE TITLE
Problem with importing passwords from the Chrome Browser

### ISSUE THREAD

**Issue by k5nwa** [mdn/kuma#6292]
In Windows 10 Firefox V 70 will not import passwords from Chrome, out of 447 bookmark/passwords it only imports about 2 dozen or so.

In Linux, the option to select the importing of passwords is not even present.

I'm trying to migrate from Chrome to Firefox but the lack of so many passwords makes it impractical to switch at this time.

Thanks

Cecil Bayona
cbayona@cbayona.com

**Comment by peterbe** [comment]
I'm sorry to hear that. Go to https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=General and file a bug against Firefox. 
This repo here is about MDN the website https://developer.mozilla.org. 
Good luck!!
