### ISSUE TITLE
Auth login modal appearing for signed in users

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6294]
Originally from: https://bugzilla.mozilla.org/show_bug.cgi?id=1605805

The screenshot they shared wasn't working in Firefox but I managed to open it in Chrome and took a screenshot of the screenshot 🙃
<img width="1468" alt="Screen Shot 2019-12-31 at 2 17 33 PM" src="https://user-images.githubusercontent.com/26739/71631762-6b383f00-2bd8-11ea-807a-16f708d6de86.png">

There's a lot going on here. I don't know why they don't get CSS. But they start on https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Report_a_problem and notice that (in the upper right-hand corner) they are already signed in yet the modal window still appears!

Also, the original cause is that they say they get redirected to the sign in page. I suspect what's going on is that the modal appears "involuntarily" which makes them think "You have to sign in". 

Supposedly related to uBlock Origin.

**Comment by schalkneethling** [comment]
Thanks for logging this and looking into it. I suspect as they are not getting the base CSS the `hidden` class is not available either and thus the modal shows up. Interesting that the modal CSS does load ¯\_(ツ)_/¯

This brings up another point though. Do we know on the frontend that someone is logged in? I know the whoami component knows but does the rest of the Jinja template know? If so, it would make sense to wrap the CSS, HTML, and JS related to the modal in a conditional. Something like:

```
if not logeed_in:
  add code
```

**Comment by peterbe** [comment]
So, if the CSS is failing for some reason, the modal appears. A bit weird, but an explanation. 
If I block CSS (using the DevTools) I get a very very different look. 
Either way, it's got to be related to some particular configuration of uBlock Origin.

**Comment by peterbe** [comment]
> Do we know on the frontend that someone is logged in? I know the whoami component knows but does the rest of the Jinja template know?

The jinja template (aka. the jinja template context) is *always* anonymous. 
If we knew the user was logged in, in the jinja context, we'd be able to do:
```
{% if not request.user.is_authenticated %}
{% stylesheet 'auth-modal' %}
{% endif %}
```
but it'd never be an option.

**Comment by peterbe** [comment]
I only just see problems with the modal. It's rarely used or needed and it's adding a bunch of JS, CSS, and HTML to every page.

**Comment by schalkneethling** [comment]
> I only just see problems with the modal. It's rarely used or needed and it's adding a bunch of JS, CSS, and HTML to every page.

Yup, agreed. It seems like it is causing way more problems than it is solving. I reckon we should stick to just using the new login landing page.
