### ISSUE TITLE
Auth modal focus isn't working on Tab key

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6295]
You have to have `MULTI_AUTH_ENABLED=true` first. Then click "Sign in". 
Press `Tab` on your keyboard and notice how the "close icon" becomes focussed:
<img width="434" alt="Screen Shot 2019-12-31 at 4 18 12 PM" src="https://user-images.githubusercontent.com/26739/71634345-426c7580-2be9-11ea-9eb3-cccfeb93b27d.png">

Press Tab again and now the GItHub button is focussed:
<img width="476" alt="Screen Shot 2019-12-31 at 4 19 13 PM" src="https://user-images.githubusercontent.com/26739/71634359-5617dc00-2be9-11ea-982b-a36f254bbf12.png">

Press Tab again (because I prefer Google mayhaps)
Now, the close icon is focussed. Not the Google button.

**Comment by peterbe** [comment]
Uh? This is behaving differently in Chrome. Clearly something's buggy.

**Comment by schalkneethling** [comment]
@peterbe Tested in Chrome and Safari and works as expected. To get Firefox to behave similarly you need to do the following:

1. Open System Preferences
2. Click on Keyboard > Shortcuts
3. Check the box labeled "Use keyboard navigation to move focus..."
4. I believe you then need to restart Firefox

![Screenshot 2020-01-08 at 12 57 14](https://user-images.githubusercontent.com/10350960/71973318-5894ba00-3217-11ea-9a2e-dbd20534fac3.png)
