### ISSUE TITLE
mistake code in a course

### ISSUE THREAD

**Issue by HALLneufmilles** [mdn/kuma#6302]
Hello!
one mistake at this page:
https://developer.mozilla.org/fr/docs/Learn/JavaScript/First_steps/What_is_JavaScript

<script src="script.js" async></script>

replace async by defer.

Thanks.

**Comment by chrisdavidmills** [comment]
Fixed!

We've got it set as `defer` in the English version ;-)

**Comment by HALLneufmilles** [comment]
Hello,

I m french, will you fixe it on the french version?

best regards


Le sam. 4 janv. 2020 à 12:44, Chris Mills <notifications@github.com> a
écrit :

**Comment by chrisdavidmills** [comment]
> I m french, will you fixe it on the french version?

Sorry for the confusion - I did fix it in the French version; I meant that it  was already correct in the English version, but now I've fixed in the French versiontooo.

**Comment by HALLneufmilles** [comment]
Thanks ! :)

Le dim. 5 janv. 2020 à 15:24, Chris Mills <notifications@github.com> a
écrit :
