### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by AlexandrGerasimenko** [mdn/kuma#6312]
https://prnt.sc/qkk935

**Comment by peterbe** [comment]
Can you describe what the problem is @AlexandrGerasimenko ?

**Comment by AlexandrGerasimenko** [comment]
Write word -"методи", but we can see "меоди".
It's typo.

**Comment by peterbe** [comment]
MDN is a user-contributed Wiki. Anybody can contribute content. All you need is a GitHub account (which you clearly have 😺 ) and then you sign in and click the "Edit in Wiki" ("Редактировать в вики") and then you'll be able to correct the typo. 
Generally, *this* GitHub repo is for the code that powers that ability to edit content. 
Good luck and welcome to the community!
