### ISSUE TITLE
Yari 1 Feasability Assessment 

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6317]
**User Story**

We need to determine the feasibility/complexity of converting the current front-end code (all of the current Sass, CSS, and JS, as compiled and bundled by django-pipeline, as well as the document Jinja template that wraps a React SSR call) into a stand-alone CLI that takes the file-based raw HTML for each document as input and produces finished HTML (i.e., including the header and footer). This is the original idea for the front-end for Yari-1. If this is feasible and relatively simple, we could use it as a way to produce finished HTML documents without initially depending-on the more risky, but fully-new, React-app-based front-end that is the final goal (Yari-2).

**Acceptance Criteria**

- [ ] A written risk assessment, in terms of feasibility and complexity, that includes a detailed break-down of the tasks required (assumes that a rough prototype will be attempted in order to expose the risk in a concrete way).

**Comment by peterbe** [comment]
Should there be an acceptance criteria specifically around the DX of using it locally to do previewing?

**Comment by tobinmori** [comment]
> Should there be an acceptance criteria specifically around the DX of using it locally to do previewing?

@escattone and I talked a about this, and determined that really the main goal here is well-informed study in feasibility (not even a prototype, as that might be too heavy a lift at this point). If this isn't feasible, this will have huge repercussions on our choice between yari 1 and yari 1.5. Also, Ryan's findings will be super valuable fodder for discussion in Berlin! We can talk DX later!

**Comment by escattone** [comment]
### NOTES

#### Templates used 

NOTE: use `nunjucks` npm package to minimize re-factoring

- kuma/wiki/jinja2/wiki/react_document.html
- jinja2/includes/preload.html
- jinja2/includes/style.html
- jinja2/includes/zilla.html
- jinja2/includes/react_google_analytics.html
- jinja2/includes/speedcurve-lux.html
- jinja2/includes/polyfill_scripts.html
- jinja2/includes/config.html
- jinja2/includes/modal.html
- jinja2/includes/auth-modal.html
- jinja2/includes/auth-modal-content.html

#### Template functions/filters needed
- `static` (global)
- `stylesheet` (change from block extension to global function)
- `javascript` (change from block extension to global function)
- `gettext` (i.e., `_`)
- `render_react`
- `favicon_url`
- `url`
- `absolutify` (filter)
- `page_title`
- `soapbox_messages`
- `get_soapbox_messages`
- `provider_login_url`

#### Template context (incoming data)
- `seo_summary = doc.get_summary_text()`
- `seo_parent_title = _get_seo_parent_title(doc, slug_dict, document_locale)`
- `doc_api_data = document_api_data(doc)`
- `document_data = doc_api_data['documentData']`
    - `absoluteURL`
    - `title`
    - `hrefLang`
    - `quickLinksHTML`
    - `tocHTML`
    - `bodyHTML`
    - `lastModified`
    - `parents` (for breadcrumbs)  NOTE: requires shim that extracts this information from the file system
    - `translations`  NOTE: requires shim
    - `slug`
    - `locale`
- robots_meta_content

        def robots_index():
            if fallback_reason:
                return False

            if not doc.html:
                return False

            if doc.is_experiment:
                return False

            if doc.has_legacy_namespace:
                return False

            if request.get_host() not in settings.ALLOW_ROBOTS_WEB_DOMAINS:
                return False

            return True

        robots_meta_content = (
            'index, follow' if robots_index() else 'noindex, nofollow'
        )

- the actual template context:

        # Bundle it all up and, finally, return.
        context = {
            'document_data': document_data,
            'seo_summary': seo_summary,
            'seo_parent_title': seo_parent_title,
            'robots_meta_content': robots_meta_content,
        }
        response = render(request, 'wiki/react_document.html', context)

**Comment by escattone** [comment]
## Tasks Required 

A prototype using the `nunjucks` npm package was used to help understand the feasibility and pieces involved in creating a Yari 1 renderer -- see https://github.com/escattone/kuma/blob/yari-1-experiment/kuma/javascript/src/yari1.js.

A key assumption in Yari 1 is that this it depends on the existing `django-pipeline` and `webpack` configuration and code, or in other words, that `make build-static` has already been run.
 
- Defined file-system organization for the raw document files and their metadata. NOTE: A raw document file is a file of HTML containing un-rendered Kumascript (KS) macros.
- KS "shim" for extracting information like each document's parents, children, and translations
- KS renderer as a JS function (that uses the KS "shim" and takes the raw HTML and renders each of the KS macros contained in the raw HTML)
- Slightly modified versions of the templates listed above (i.e., with changes to things like the way `stylesheet` and `javascript` are called), or a single template that encompasses all of the other templates and their modifications
- JS code to extract the SEO summary, SEO parent title, summary HTML, body HTML, and quick-links HTML from the KS-rendered HTML
- JS code that implements the Jinja filters and functions needed

## Conclusion
This is clearly feasible, relatively simple, and the risk is very low.
