### ISSUE TITLE
Profile - Add new header

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#6322]
**Summary**

Add new MDN Web Docs header

**Rationale**

Currently, the edit profile and view profile pages still uses the old wiki-style header. This causes a disconnect visually between the user-facing front-end UI and the page a user is presented when viewing or editing their profile.

The links from this header also do not link a user back to developer.mozilla.org but instead, links back to pages under wiki.developer.mozilla.org

This is bound to cause a lot of confusion for users and generally leads to negative user experience.

**Audience**

All signed-in users that visit the edit profile page

**Acceptance Criteria**

- [ ] New header is present on edit and view profile pages
- [ ] Navigating to and from reference, edit and view profile pages keeps the user on developer.mozilla.org

**Comment by peterbe** [comment]
One strange thing I noticed was that if I now go to the wiki, 
http://wiki.localhost.org:8000/en-US/ and click "Edit Profile" from there it takes me to http://wiki.localhost.org:8000/en-US/profiles/peterbe/edit but with the read-only site header. 

Can we not make the link to Edit Profile always be hardcoded to the read-only site? And or, redirects if you manually typed in http://wiki.localhost.org:8000/en-US/profiles/peterbe/edit

Also, what about the http://wiki.localhost.org:8000/en-US/users/account/email page??

**Comment by peterbe** [comment]
Perhaps, it's best to not bother with any of the profile page. Leave it ALL behind in the Wiki and let it die a slow death instead of dragging it into the read-only site. 
After all, very soon we'll have a brand new subscription landing page which means we no longer need to put the subscription form/summary on the Wiki anymore.

**Comment by schalkneethling** [comment]
> Can we not make the link to Edit Profile always be hardcoded to the read-only site? And or, redirects if you manually typed in http://wiki.localhost.org:8000/en-US/profiles/peterbe/edit

Good idea, we should do both of those things.

> Also, what about the http://wiki.localhost.org:8000/en-US/users/account/email page??

:+1: One thing at a time :)
