### ISSUE TITLE
Reduce outdated Python dependencies to 25%

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6326]
**Description**

This is Step 1 of a what we're currently estimating will be a 3-part process. We expect steps 2 and 3 will be increasingly challenging upgrades. The completion of these 3 steps will lead the way to a Django version upgrade.

This step involves updating dependencies for our less-tricky Python libraries. 

**Acceptance Criteria:**
- [x] 75% of outdated libraries are updated

**Comment by callahad** [comment]
Done
