### ISSUE TITLE
Autoconfiguration issue

### ISSUE THREAD

**Issue by Linux-Johnston** [mdn/kuma#6333]
The installation of an account from e-mail provider Aikq.de in Thunderbird by autoconfiguration is erroneous. Autoconfig sets both IMAP and SMTP host names to aikq.de.
Both servers correct host name is mail.aikq.de. Due to false autoconfig settings the receiving and sending of mail does not work.

I also discovered incorrect settings for the port numbers when I first installed an Aikq.de mail account in Thunderbird.

You can find specification on the correct settings for mail provider Aikq.de in the following link:

https://support.aikq.de/hc/de/articles/201221722-Wie-richte-ich-aikQ-bei-Thunderbird-ein-

Due to manual costumization based on the link above I am currently able to work with Thunderbird to the full extent and receive and send mails with my Linux system. But there is the same issue going on when setting up an account in the Android App FairEmail which also uses Thunderbird autoconfiguration service with same erroneous settings mentioned above. There is no option to change the host names in FairEmail, so setting up an Aikq.de account there continuing fails to work. The operator of FairEmail has been informed on this issue but refers to a bug in Mozilla's ISPDB.

**Comment by peterbe** [comment]
This GitHub repo is about the code behind the *website* https://developer.mozilla.org
If you need help with Thunderbird, please start on https://support.mozilla.org/en-US/products/thunderbird
