### ISSUE TITLE
Blue rectangular box appears when starts typing on the search bar in developer.mozilla.org (bugzilla 1608616)

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6337]
(In reply to Rishi from comment #0)
> What did you do?
> ================
> 1. Go to the developer.mozilla.org 
> 2. At the top-right search bar when I clicked and start typing a blue rectangular box was appeared
> 
> What happened?
> ==============
> A blue rectangular box was appeared, which doesn't look nice.
> 
> What should have happened?
> ==========================
> When the user clicks on the search bar and starts typing, a blue rectangular box should not appear.
> 
> Is there anything else we should know?
> ======================================
> I want to work on this issue.

**Comment by rishipurwar1** [comment]
I want to work on this issue if no one is working on it.

**Comment by tobinmori** [comment]
Hello @rishipurwar1, 

That would be great. Would you still like to work on this? Let us know!

**Comment by rishipurwar1** [comment]
Hello @tobinmori,
I would like to work on this issue but I want your help in setting up the local environment.
Thank You.

**Comment by mindy** [comment]
Hi @rishipurwar1, 

I went ahead and made this change since it was a small change and I wasn't sure if we would be able to budget time to get your local environment set up, as it can be a bit complicated. Your feedback was very useful and I knew exactly where to look thanks to your comment in Bugzilla, so thank you for that! 

Mindy

**Comment by rishipurwar1** [comment]
Hi @mindy,
It's great! you fixed that.
I am new in open source. So, I wanted someone help to fix that issue.
I will again try to contribute to your organization. Hopefully, I will do some contributions.
Have a nice day!!
Thank You

**Comment by schalkneethling** [comment]
> Hi @mindy,
> It's great! you fixed that.
> I am new in open source. So, I wanted someone help to fix that issue.
> I will again try to contribute to your organization. Hopefully, I will do some contributions.
> Have a nice day!!
> Thank You

Thanks so much for your interest. Have you been able to get the codebase running locally? The steps to follow are here:

https://kuma.readthedocs.io/en/latest/installation.html

Let us know should you experience problems with getting things set-up.
