### ISSUE TITLE
Google OAuth application verification

### ISSUE THREAD

**Issue by escattone** [mdn/kuma#6338]
**Summary**
I believe our Google OAuth applications for stage and prod, primarily for prod, need to go through a verification process by Google (see https://support.google.com/cloud/answer/7454865 and https://support.google.com/cloud/answer/9110914) before we can enable Google login, especially on production due to the user limit ("total new user cap") of 100.

**Rationale**
Avoids the user limit ("total new user cap") of 100.

**Due Date**
This task must be completed prior to enabling Google sign-ups/logins on production.

**Comment by escattone** [comment]
The Google OAuth application UX and process is not intuitive. It says that stage and prod OAuth applications need to be verified because I updated the application logo, and that seems to imply that if I had not updated it (just left it blank) we might be able to avoid the verification process. I'm going to give that a try.

**Comment by tobinmori** [comment]
I reached the same conclusion, but I assume removing the logo didnt work @escattone?

Hmm, I still see the Mozilla logo there for the staging conf screen, though. . .?

In any case, the docs from what I've read, definitely seem to imply that if we remove the logo and just have the redirect URL appear that we should be fine. . .

**Comment by escattone** [comment]
I created new Google OAuth applications **without logos** for both stage and production (see links [here](https://github.com/mdn/kuma/issues/6318#issuecomment-573918455)). I think the removal of the logos, combined with the fact that we're not using any sensitive/restricted scopes, will ensure that we can have both OAuth apps published without the need for verification. Also, @tobinmori made me realize that the user cap of 100 is only for users requesting sensitive/restricted scopes, which we don't allow anyway. So, in short, I don't think there is any need for verification and we're in good shape. We'll know for sure once our apps are published, which can take a few days.

**Comment by tobinmori** [comment]
Do we feel comfortable enough to close this @escattone? Or wait until prod?

**Comment by escattone** [comment]
@tobinmori No, I don't yet. I keep reading the docs, and I just can't come to any solid conclusion. I do know that the button to submit our production (stage as well) OAuth app for verification is disabled, so I don't think we've configured anything that requires a manual verification process that can take weeks. However I think we're considered to be using sensitive scopes (since we're getting users' emails), so I think the 100 user "cap" still applies to us until we're verified via their standard process, which, if I'm understanding all of this correctly, can take 3-5 business days. So I suspect we should wait a few more days, since 5 days from app creation would put us at Tuesday of next week, and hope we're published by then?

**Comment by escattone** [comment]
@tobinmori @atopal @gregor I've come to a conclusion on this issue, primarily based on the fact that if we were using a `sensitive` (or even `restricted`) scope in our OAuth2 Consent Screen, that scope would include a lock icon, which our scopes (the default ones of `email`, `profile`, and `openid` by the way) do **not**. See the two sources below, one from Google and the other from StackOverflow:

#### Google
<img width="881" alt="image" src="https://user-images.githubusercontent.com/3743693/72853472-4e86a880-3c66-11ea-820e-a1087e3d02f7.png">

#### StackOverflow
<img width="766" alt="image" src="https://user-images.githubusercontent.com/3743693/72853170-745f7d80-3c65-11ea-8bb1-e235ad76605b.png">

so we're definitely **not** using any sensitive or restricted scopes. That means we do **not** require verification, and that the user cap limit does **not** apply to our OAuth2 app.

**Comment by tobinmori** [comment]
Thanks @escattone. I assumed the same!
