### ISSUE TITLE
Incorrect value shown for username during signup

### ISSUE THREAD

**Issue by escattone** [mdn/kuma#6347]
**Summary**
While reviewing https://github.com/mdn/kuma/pull/6330, I performed an account signup via Google, and noticed that the value shown for the `username` during account sign-up (`"Ryan Johnson"`):

<img width="354" alt="image" src="https://user-images.githubusercontent.com/3743693/72486098-bfd5df80-37be-11ea-8c12-a357bd557feb.png">

was different from the actual `username` (`"rjohnson"`) shown when I clicked the `change username` button :

<img width="363" alt="image" src="https://user-images.githubusercontent.com/3743693/72486111-cf552880-37be-11ea-853f-22988564abac.png">

It seems that instead of using [`account.get_provider_account()`](https://github.com/mdn/kuma/blob/6c6132a5835fcd3e5697247fe206c2e273060935/kuma/users/jinja2/socialaccount/signup.html#L79) which gets coerced into a string to provide the username, we should be using the [same approach that we do when initially filling-in the signup form](https://github.com/mdn/kuma/blob/6c6132a5835fcd3e5697247fe206c2e273060935/kuma/users/views.py#L571)?

This feels like it should be a P1.

**Steps To Reproduce (STR)**
Attempt a new account sign-up via Google using `/users/google/login/`

**Comment by escattone** [comment]
@atopal @tobinmori @schalkneethling @Gregoor Pinging you all to get your thoughts on this and it's priority.

**Comment by escattone** [comment]
By the way, this issue is not related to #6330. I just happened to discover it during the course of reviewing that PR.

**Comment by Gregoor** [comment]
Good catch, Ryan. Thanks! I'm looking into it now, thinking the change should properly affect those lines
https://github.com/mdn/kuma/blob/6c6132a5835fcd3e5697247fe206c2e273060935/kuma/users/jinja2/socialaccount/signup.html#L79-L82

**Comment by tobinmori** [comment]
Seems pretty confusing, looks like @atopal agrees! Thanks for pointing it out @escattone.
