### ISSUE TITLE
CSS styles goes wrong

### ISSUE THREAD

**Issue by Vardner** [mdn/kuma#6348]
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Map/forEach
![image](https://user-images.githubusercontent.com/36897869/72516333-252ade80-385a-11ea-9a01-bc74d55a6a74.png)

**Comment by peterbe** [comment]
Thank you @Vardner for filing! We appreciate it. 
Actually, https://github.com/mdn/kuma/issues/6310 was filed before and it describes the same exact problem and we're actually actively working on it. And we actually hope to have a fix out in a couple of hours even.
