### ISSUE TITLE
Blazor file input click not working in firefox

### ISSUE THREAD

**Issue by NavinVinayagam** [mdn/kuma#6361]
Hi ,
I am creating a blazor application in which I am using the hidden file input and click() method to open the file picker. It works fine in Chrome, Edge. The file picker is not opening in Firefox. 

Below is my sample code to reproduce the issue.
index.razor:
```
@inject IJSRuntime JSRuntime;
@*File Input is clicked using JSinterop on blazor click event of button*@
<div>
    <button @onclick="OnClick">Select File</button>
    <input type="file" id="fileElem" multiple style="display:none">
</div>


@code{
    private async Task OnClick()
    {
        //Triggers the click event of file Input
        await JSRuntime.InvokeVoidAsync("elementClick", "fileElem");
    }
}
```

JSInterop:
```
window.elementClick = (Id) => {
   // Triggers click event of the element
    document.getElementById(Id).click();
};
```

Is there any work around to resolve the above issue?

FireFox  Version: 72.0.2
Visual Studio : Version 16.5.0 Preview 1.0
DotNet SDK Version: 3.1.100

**Comment by peterbe** [comment]
I'm sorry to hear that your app isn't working in Firefox. I have no idea what Blazor is but hopefully there's a community (mailing list, forum, github, etc) for that project where you can get help in your debugging endeavor. 

This GitHub repo is about the code behind the https://developer.mozilla.org web site.
