### ISSUE TITLE
Make a doc a redirect still indexed in Elasticsearch

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6362]
**Summary**
Suppose you have a page that can be found with search. Then you decide to discard all of its content and make it a redirect to some other page. That act should *remove* the doc from Elasticsearch. But it doesn't. 

**Steps To Reproduce (STR)**

1. Pick a page you're willing to lose, click to edit in Wiki.
2. Put in a word that is unique to it so it definitely shows up in a search. E.g. put in a world like UNIQUEBEARPANDA and make sure you can search and find that one document. 
3. Now edit the document by clicking the Redirect icon in the WYSIWYG (far right, arrow icon)
4. Press "Publish" 
5. Refresh the search you did before.

**Actual behavior**

The page is still there even though that word typed is long gone.

**Expected behavior**

After turning it into a redirect it should remove the doc from Elasticsearch.

**Additional context**

See https://wiki.developer.mozilla.org/en-US/search?locale=en-US&kumascript_macros=jsindex&topic=none for two docs that got stuck in Elasticsearch. Those are redirects now and shouldn't appear in Elasticsearch.

**Comment by peterbe** [comment]
According to [this](https://wiki.developer.mozilla.org/en-US/search?q=&none=none&topic=api&topic=css&topic=html&topic=js&topic=apps&topic=webdev) we have:
*"18696 documents found in English (US)"*

But if I use the `./manage.py shell_plus` and do the same filtering (not `is_redirect` and not all those excluded slugs) we have 18630 en-US docs in MySQL. That means there are 66 too many documents in Elasticsearch. Just for `en-US`. 7 for `fr` and 23 for `ja`.

**Comment by peterbe** [comment]
The solution could either be:

1. Right before the document is about to have `doc.is_redirect = True; doc.save()` we should trigger a signal to delete it from Elasticsearch. But if the indexing is done in a worker thread, how is it supposed to know that it came from `is_redirect==False`?

2. Every now and then, until Yari takes over the Wiki, just manually trigger a massive reindexing. Do you remember how long that takes roughly @escattone ?

**Comment by tobinmori** [comment]
Closing this, and we'll manually re-index periodically.
