### ISSUE TITLE
CSS masking not working on Firefox

### ISSUE THREAD

**Issue by zmalsberg** [mdn/kuma#6363]
I was building a CSS based site intro while working from an example, and had much trouble until I realized it was only Firefox (and likely IE) that would not display masked elements, particularly 'mask-image:(url(...)', so I tried every format. All resources I've found say Firefox should support this feature, but I suspect some bug has halted its support.

Fixes I've tried:

- Both Mac and PC versions of Firefox
- Updating to the latest version
- Pale Moon Browser, a clone of Firefox, and Chrome, which correctly displays the masked elements.
- Converting the mask image from .png to .svg
- All iterations of the CSS masking code, including '-webkit-mask-image:' 'mask-image:' and 'mask:' with every combination of attributes
- Other code examples, such as [( https://codepen.io/kidwm/pen/OoMoGO)] which is broken all the same
- Even the official Mozilla example of mask usage failed to display anything.

**Comment by peterbe** [comment]
If it's a bug in Firefox, consider filing a bug here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox
Please include URLs to demos that demonstrate the bug there. 

This repo is about the code behind the website https://developer.mozilla.org
