### ISSUE TITLE
Drop username from sign-up?

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6366]
**Why bother with the username? How about removing it entirely from the UI?**

First of all, in this particular instance, I signed in with `peterbe@gmail.com` which means it'd want to default the username to `peterbe` but there's already a user with that username, but a different email address. So it becomes this weird blank string. 
For most people it'll suggest `your_email.split('@')[0]` for the username. 

<img width="1293" alt="Screen Shot 2020-01-22 at 3 50 10 PM" src="https://user-images.githubusercontent.com/26739/72933198-46df0680-3d2f-11ea-97c0-e26da948ce73.png">

The username is just noise and friction for signing up. It's not critical or important (unlike the checkbox for terms & conditions). It can lead to confusion and it can lead to maintenance bugs and problems.

**Comment by peterbe** [comment]
The username only matters if you will bother using the Wiki. Not only do we expect a small sliver of folks bothering, but we also are actively planning to remove the Wiki and replace it with something outside of MDN. 
Unless you're intending to "brag" about your Wiki contributions, the username is not used for anything. It appears on your Wiki vanity profile E.g. https://wiki.developer.mozilla.org/en-US/profiles/peterbe
It also appears on the footer ([e.g. scroll to the bottom](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Mozilla_on_GitHub)) and it can appear in the [Wiki revision history](https://wiki.developer.mozilla.org/ar/docs/MDN/Contribute/Howto/Report_a_problem$history).

All of those are slated to be removed within a year. 

And, suppose that we DON'T allow users to pick a username and my username becomes `eh780cf4b6e9` I can, after all, go to https://wiki.developer.mozilla.org/en-US/profiles/peterbe/edit and change it to something more to my liking. 

Less friction and noise makes for better UIs. (And less dev maintenance too)

Here's what it would look like without bothering the sign-upee with these questions:
<img width="776" alt="Screen Shot 2020-01-22 at 3 51 07 PM" src="https://user-images.githubusercontent.com/26739/72933938-bf929280-3d30-11ea-928d-f74d31b42628.png">
(note that the helptext under the two icons no longer makes sense)

**Comment by peterbe** [comment]
**What @escattone and I propose** is that a "random" username (e.g. `eh780cf4b6e9f`) is automatically assigned to your Django user profile and that all and any mention about your username is removed from this screen.

**Comment by schalkneethling** [comment]
One thing to note here is that we *do* want the user's given, and perhaps the family name, as this becomes useful when we send out communication around MDN in general as well as in other instances where the site is personalized in some way.

I do believe we already get that, and so, I would vote for removing the `username` field as it is essentially just an account identifier, and instead be clear and transparent about the fact that we collect the user's name from the Auth provider by surfacing this in the UI during this step.

That way, we also allow the user to edit their given and family name should they wish to keep that anonymous and replace it with a pseudonym.

**Comment by peterbe** [comment]
@malqinneh Does our new, minimal, settings page allow for editing your given/first and last/family name?

I think you're referring to sending emails, for example, that start with `Dear Peter, ...`

I'm curious if it's worth it. We can pick up some user details as part of the default scopes in OAuth  so we can have it and update it if their cookie expires and they sign in again. 

My preference is for the settings page to be minimal. I know what my name is and since my name won't be shown/displayed, I don't see the point with getting involved in it.

**Comment by schalkneethling** [comment]
> I know what my name is and since my name won't be shown/displayed, I don't see the point with getting involved in it.

Fair enough, I would still want to be transparent here and clearly show people what information we have on them, and provide them with the opportunity to amend, or even remove it from the data we have.

**Comment by malqinneh** [comment]
Peter, are you suggesting showing the username but not allowing users the
ability to edit from MDN (similar to the avatar)?

**Comment by peterbe** [comment]
> Peter, are you suggesting showing the username but not allowing users the ability to edit from MDN (similar to the avatar)?

No, I'm suggesting this: https://user-images.githubusercontent.com/26739/72933938-bf929280-3d30-11ea-928d-f74d31b42628.png

Basically, no mention of usernames at all on that screen.

**Comment by malqinneh** [comment]
In that case, we should consider what Schalk mentioned already, we'd want
to be transparent with users and at least display the information we have
of theirs/on file. Any drawbacks if we do that?

**Comment by peterbe** [comment]
Yeah, it would be nice to *mention* (not edit now) that we've picked that up. It could actually appear if this new signed-in user, for some reason, decides to help out contributing on the WIki (before it's replaced with git). 

Can you @malqinneh come up with a version my above screenshot but one that mentions (if it's present) what first and last name we picked up and perhaps a mention that this can be changed later?

But, how about making the sign-up flow *even* simpler and smoother? Why bother A) tell the user which email address they just signed in with? And B) why bother asking them to change it now? It's just more noise and things that can go wrong. 

If I was a car salesman and someone said "I'll buy it", if there are any questions that *can wait* I'll shut up and complete the sell and then maybe *after* say that certain things can be changed when time allows.

**Comment by malqinneh** [comment]
I agree with showing names but not allowing people to change it right then
and there. Having said that, I wasn't involved in the design of the new
sign up flow and I'm probably missing some context here. We should schedule
a quick sync on this issue and take it offline between Kadir, you, and
myself. Will ping everyone on Slack.
