### ISSUE TITLE
Mugshot only shown during submission

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6367]
To explain what's happening...
When I press "Create Profile" it starts submitting the form and you can't see it (in this screencap) but the browser indicates that it's loading. 
Right after pressing that button, the dino head changes to my mugshot from my Google account. Just for a brief moment until the form realizes I didn't fill it in properly so it needs to reload but with the form validation errors highlighted in red. 
![Screen-Recording-2020-01-22-at-4 08 00-PM](https://user-images.githubusercontent.com/26739/72937209-b0aede80-3d36-11ea-94d4-89f14a5064bd.gif)

Perhaps *my* face is NOT supposed to appear on the sign up landing page at all. And only for that split second when I'm submitting form. If so, it's weird because it flashes.

**Comment by peterbe** [comment]
@schalkneethling @atopal @malqinneh I don't know if you guys are monitoring new GitHub issues on this repo, but this is one that I would argue is so weird that it ought to block the release of the new signup flow.

**Comment by schalkneethling** [comment]
> @schalkneethling @atopal @malqinneh I don't know if you guys are monitoring new GitHub issues on this repo, but this is one that I would argue is so weird that it ought to block the release of the new signup flow.

I assume the front-end validation succeeded but then the back-end validation failed? Yeah, that is not ideal. Not a deal-breaker and an easy fix.

**Comment by peterbe** [comment]
Independent of form validation stuff, why isn't my mugshot there immediately after I get back from Google's permission/scope approval screen?

**Comment by tobinmori** [comment]
@schalkneethling can you put an estimate on this?

**Comment by schalkneethling** [comment]
> @schalkneethling can you put an estimate on this?

This is handled in https://github.com/mdn/kuma/issues/6367

**Comment by schalkneethling** [comment]
This was resolved by https://github.com/mdn/kuma/pull/6487
