### ISSUE TITLE
Confusing choice of terms in sign up flow

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6368]
You only see this if you right-click and "Open in a new tab", or if you're on a mobile device, or if you're redirected from a protected page from an old bookmark. 
<img width="1055" alt="Screen Shot 2020-01-22 at 4 58 20 PM" src="https://user-images.githubusercontent.com/26739/72938327-ca512580-3d38-11ea-9211-46858192ac03.png">
"Account, account, account"

Then, after you've chosen GitHub or Google you end up here:
<img width="864" alt="Screen Shot 2020-01-22 at 4 58 10 PM" src="https://user-images.githubusercontent.com/26739/72938443-fbc9f100-3d38-11ea-96a1-7799f6681a06.png">
"Profile, profile, account?"

For the record, both pages' `document.title` is: "Create your MDN Web Docs Account" which is nicely consistent.

**Comment by peterbe** [comment]
The problem is that users get confused which can lead to sadness and users not bothering/caring to sign up which is a shame. The mixmatch of terms leads to thinking which is annoying and friction.

*We* might, internally, know the difference between a profile and account. But they don't. And I dare to say **they don't care**. 
It all started with the user clicking "Sign in". The click "sign in" but now all of a sudden they're told they have to do something else.

**Comment by tobinmori** [comment]
Update 'MDN profile' to 'MDN account'. . .
