### ISSUE TITLE
"I've already authorized with Google?!!"

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6370]
After having authorized MDN to use my account details, I'm redirected back to MDN and confronted with this:
<img width="711" alt="Screen Shot 2020-01-22 at 5 09 33 PM" src="https://user-images.githubusercontent.com/26739/72939030-10f34f80-3d3a-11ea-8cf2-3cea88fc4a7a.png">

To be honest, I still don't think I understand the two icons (one Google and on dino). To start, I think it would make much more sense if there was an arrow or something to indicate progress like a timeline kinda graphic. 

The Google icon says "Authorize with Google". But I already did that! Do I need to do it again? 

Also, "What's the difference between authorizing and signing in?"

(Personal note; I *think* I know what the difference is but even an experienced web developer that's built many auth related things over the years find these terms confusing)

**Comment by atopal** [comment]
Yeah, it's missing the line between the to icons and the numbering as well. Also, the Google icon should be grayed out at this point. Testing this is not easy, is this what we shipped?

<img width="595" alt="MDN_-_Account_Types_Preview_Mode_-_InVision_-_Firefox_Developer_Edition" src="https://user-images.githubusercontent.com/557852/73135722-d6ddc280-4045-11ea-88a4-9e4d0c06938b.png">

**Comment by peterbe** [comment]
> Testing this is not easy, is this what we shipped?

If you want to see what it looks like, you can sign in to https://developer.allizom.org/admin/users/user/ with your previous GitHub account and find your personal Google account and then use the Django admin to delete the user account. Now, next time you try logging in with Google you'll see that what we're shipping is what appears in my screenshot. 

That 1. and 2. and the greying out of the provider auth sounds like a great idea. @schalkneethling Wanna take this one?

**Comment by schalkneethling** [comment]
> Yeah, it's missing the line between the two icons and the numbering as well. Also, the Google icon should be grayed out at this point. Testing this is not easy, is this what we shipped?
> 
> <img alt="MDN_-_Account_Types_Preview_Mode_-_InVision_-_Firefox_Developer_Edition" width="595" src="https://user-images.githubusercontent.com/557852/73135722-d6ddc280-4045-11ea-88a4-9e4d0c06938b.png">

Getting those circles with the line aligned properly and consistently proved a bit of a nightmare. One option would be to use a right-pointing arrow that is center aligned and not directly "attached" to either of the logo/avatars.

I have added:

1. Graying out the auth provider logo,
2. Showing the user avatar on the right instead of the MDN dino

in https://github.com/mdn/kuma/pull/6371

Do we also want to change the copy under the auth provider logo as well as the copy of the intro paragraph?

**Comment by schalkneethling** [comment]
Something like:

![Screenshot 2020-01-28 at 10 19 08](https://user-images.githubusercontent.com/10350960/73247123-e6314d00-41b8-11ea-9721-ad2df5a6fa7a.png)

**Comment by atopal** [comment]
That's okay, can you also make sure that the numbering is in?

**Comment by schalkneethling** [comment]
The items mentioned here that sounded like we want to change/update is taken care of in this PR - https://github.com/mdn/kuma/pull/6371
