### ISSUE TITLE
Dead/unrelated link

### ISSUE THREAD

**Issue by rfxDarth** [mdn/kuma#6390]
There's a link in 
https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Cross-browser_audio_basics

Section "Fallbacks"

> Here's an example using the popular [Wordpress Standalone Player](http://wpaudioplayer.com/standalone/). You'll need to download the files and link to `audio-player.js` and `player.swf` like so:

The website that link leads to has nothing to do with wordpress, and it looks like someone is squatting a defunct domain.

**Comment by chrisdavidmills** [comment]
Oh yes, we don't want to link there anymore!

Thanks for reporting. I've updated the section to remove the link and simplfy it.
