### ISSUE TITLE
Regression: Math (MathJax/MathML) widgets broken in new platform

### ISSUE THREAD

**Issue by a2sheppy** [mdn/kuma#6391]
The new platform (developer.mozilla.org) cannot correctly present the CKEditor math components that work correctly on wikil.developer.mozilla.org. In particular, I'm using Chrome, and while Chrome doesn't support MathML, the platform is able to render matrices using a simplified form that while it's not ideal is quite readable.

On the new platform, though, the underlying Latex source is output (CKEditor uses Latex input and generates MathML or other syntax as appropriate depending on the browser).

This needs to be fixed because it is rendering pages unreadable, including many key pages in the WebXR and WebGL documentation, plus in a couple of places in the WebRTC docs.

**Comment by schalkneethling** [comment]
I believe I hunted this one down once before and there is some CSS and or JS that is missing. @a2sheppy can you please add an example page here? Thank you.

**Comment by a2sheppy** [comment]
Sorry about forgetting to include examples. Here we go:

* https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Cameras#Positioning_the_camera
* https://developer.mozilla.org/en-US/docs/Web/API/XRRigidTransform/matrix
* https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getTransform
* https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateStats/priority
* https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_concepts
* https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translateZ (in the table under "Values")

**Comment by tobinmori** [comment]
put this as a p2 and possibly something for this sprint @atopal?

**Comment by atopal** [comment]
yes
