### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ehererik** [mdn/kuma#6392]
haciendo el primer ejemplo de la pagina https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data
 me tira el sieguiente error en consola: 
"Pedido de origen cruzado bloqueado: La política de mismo origen no permite leer el recurso remoto en file:"

**Comment by peterbe** [comment]
@ehererik Would you mind trying to rewrite that in English?

**Comment by chrisdavidmills** [comment]
@ehererik I've put this through Google translate, and I think I know what your problem probably is. Are you trying to run it directly from the example file locally, or are you running it through a testing server of some kind?

To put it another way, are you following these instructions:

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data#Serving_your_example_from_a_server

?

**Comment by ehererik** [comment]
Thank you all very much! Fixed!
