### ISSUE TITLE
WebCrypto.subtle.wrapKey( RSA-Private, AES-KW ) doesn't work

### ISSUE THREAD

**Issue by spacewrench** [mdn/kuma#6394]
I'm trying to wrap an RSA private key using AES-KW, but I get a "data provided to an operation does not meet requirements" error.  Wrapping the key using AES-CGM works OK (also wrapping an ordinary AES key with AES-KW works OK).

I suspect AES-KW fails on private keys because the PKCS8 data (from an ordinary export) is 634 bytes long -- not a multiple of 64.  However, there doesn't seem to be a mechanism to pad the PKCS8 data out, and AES-KW doesn't do it automagically.

Is there a good way to use AES-KW to wrap an RSA private key?  (AES-KW is convenient because you don't have to store an IV.)
[key-test.html.txt](https://github.com/mdn/kuma/files/4145852/key-test.html.txt)

**Comment by schalkneethling** [comment]
@chrisdavidmills 🏓

**Comment by spacewrench** [comment]
I'm sorry, I spent more time RTFM and found the statement that "To use AES-KW, the input must be a multiple of 64 bits."

It would be nice if AES-KW could pad to 64 bits somehow, but I'll use AES-CGM for now.

OK to close; this was user error.
