### ISSUE TITLE
T - Add system check to verify stripe config validity and reachability

### ISSUE THREAD

**Issue by Gregoor** [mdn/kuma#6405]
As part of #6269 we discussed and implemented tests for the interaction with Stripe itself. I later removed those in favor for tests that mock the stripe wrapping helper functions, thereby allowing them to run without network. Still the point stands that we don't have any checks whether our application can successfully talk with Stripe.

Peter told me about [system checks](https://docs.djangoproject.com/en/1.11/topics/checks/), which could be an alternative to our (deleted) headless test for Stripe. One thing we could check there is whether [a stripe plan can be retrieved](https://stripe.com/docs/api/plans/retrieve). If that call succeeds we know that two of our three config keys for it are correct (`STRIPE_SECRET_KEY` and `STRIPE_PLAN_ID`).

That still leaves the interaction (and related assumptions) with Stripe itself untested, but I think it should cover our most pressing concerns.

cc @escattone @peterbe

**Comment by peterbe** [comment]
I support this plan.

**Comment by peterbe** [comment]
> Peter told me about [system checks](https://docs.djangoproject.com/en/1.11/topics/checks/), which could be an alternative to our (deleted) headless test

I'm sorry if I mumbled that. No, system checks are not an *alternative* to (headless) tests. It complements. System checks check the system. In particular, they would basically validate that the values you've put in for `settings.STRIPE_*` are sane. 

If we had an infinite amount of time we should have mocked unit tests, headless tests with a stage Stripe plan, system checks, and maybe even a system test(*). 

(*) A system test is when you've booted up a built docker image and before telling the load balancer to switch over to it, you do actual headless tests like checks against them.

**Comment by Gregoor** [comment]
I didn't put that great, thanks for the correction. What I was trying to say is: for the particular things we wanted to test it could be an alternative, not a general alternative for all headless use-cases.

**Comment by chinikes** [comment]
Hi @Gregoor , @tobinmori  - What user story / epic is this task related to?

**Comment by tobinmori** [comment]
#6184 is probably the best one. This issue was added after it was closed.

**Comment by Gregoor** [comment]
It was added before it was closed, but I moved it out of the PR addressing the original issue since keeping the PR synced with master was exhausting enough. This issue here is smaller but might (still) take some inner-dev triaging.
