### ISSUE TITLE
E - What to do about Doc_status when going to git?

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6422]
E.g. https://developer.mozilla.org/fr/docs/MDN/Doc_status/API/WebRTC

This page has `<meta name="robots" content="index, follow">` which I find a bit baffling to start with, but here we are. It's also included in [our sitemaps](https://developer.mozilla.org/sitemaps/fr/sitemap.xml)

There are, across all locales, 3,428 pages under `Doc_status`. 236 of them in `en-US`. 

I'm not even sure if the kinda KumaScript it does (the `DocStatus` macro) would even work in Yari because we're not exporting *everything* that we used to have in MySQL. 

We're going to need features like this when we're in Git too. Various dashboards and search tools that help translators. But we'll have to tackle that *after* we manage the most critical work which is to migration from Wiki to Git. 

**Note!** Google hates when you break the web with 404s. A "remedy" to that is to stop Google indexing it in the first place. But, when we switch to Yari, we don't want to have to remove it from sitemaps AND 404 the page on the same day. 
**It would be ideal to slowly phase these kinds of pages out of Google** by making theming `noindex, nofollow` and removing them from the sitemap XML files.

**Comment by jmswisher** [comment]
Note that there are at least two types of Doc_status pages -- en-US and other. The en-US pages are about various types of page hygiene (not all of which may be relevant under Yari); the localized ones are generally about whether pages are translated, and if they are up to date.

In the long term, we should look at what problems these pages are solving, and figure out how to solve them under Yari. 

I agree that getting them out of Google is a good idea. I don't know why they're being indexed, as there's really no need for that.

**Comment by peterbe** [comment]
> I agree that getting them out of Google is a good idea. I don't know why they're being indexed, as there's really no need for that.

I like that idea. What do you think @atopal ?
If they're not `noindex, nofollow` and no longer mentioned in the sitemap, then Google won't get upset if we *don't* migrate these pages to Yari where they quickly cease to make sense. 

The only reason I can imagine keeping it in Google is if a Wiki contributor/translator uses Google to navigate to these pages. 

This whole discussion is actually "repeatedly" applicable to many other things such as some of the dashboards.

**Comment by atopal** [comment]
Agreed, noindex, nofollow and remove from sitemap.

**Comment by atopal** [comment]
I should have said, this is not a high priority, P3.
