### ISSUE TITLE
E - Launch payments for logged-in users on profile

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6428]
# Epic | Milestones 
As an MDN user I want to be able to contribute to MDN, so I can ensure it becomes better over time.

# Acceptance criteria
- [x] Logged in users can set up a stripe subscription on their profile page.
- [x] users get an email about the start of their subscription
- [x] users are informed in email about how they can cancel
- [x] users can cancel their subscriptions from website
- [x] user can read on FAQ about why we are doing this and what to expect (#6582)

# User Stories 
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by chinikes** [comment]
Hi @atopal , @tobinmori - Any further discussions needed regarding the existing user stories under this epic? Do the current set of user stories meet the ACs? Thanks

**Comment by tobinmori** [comment]
@chinikes I don't see any user stories for this epic when i filter by issues for this. should there be user stories for this?

**Comment by chinikes** [comment]
Hi @tobinmori  - Yes there are user stories attached to this epic - #6470, #6471, #6473, #2800, and #6409. If you can spare a few mins for a Zoom call I could show you

**Comment by tobinmori** [comment]
no worries. i see them now. thanks @chinikes

**Comment by atopal** [comment]
With the update of the email user story, I think this epic should be complete.

**Comment by tobinmori** [comment]
@atopal can you let me know if you want an HTML email template or is a text email fine? (I'll create a sep story for building the HTML email template, if that's required). 

Either way, we'll also need to know the textual content of the email.

**Comment by chinikes** [comment]
> (I'll create a sep story for building the HTML email template, if that's required).
Hi @tobinmori - I'll recommend @atopal builds the user story instead with his acceptance criteria. Thanks!

**Comment by atopal** [comment]
I think we should start with a simple text email. This user story can be for that. And yes, please create another user story for the HTML email.
