### ISSUE TITLE
Using deprecated feature of GitHub API

### ISSUE THREAD

**Issue by hwine** [mdn/kuma#6430]
Passing on the email only -- I have no further information:

Hello there!

On February 6th, 2020 at 22:01 (UTC) your application (Mozilla Developer Network) used an access token (with the User-Agent python-requests/2.22.0) as part of a query parameter to access an endpoint through the GitHub API.

https://api.github.com/user

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

Thanks,
The GitHub Team

**Comment by atopal** [comment]
Thanks Hal, we are dealing with the issue here: #6421

**Comment by escattone** [comment]
Just wanted to add that this has been resolved since 4:30pm (Pacific Time) yesterday.
