### ISSUE TITLE
/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype

### ISSUE THREAD

**Issue by alattalatta** [mdn/kuma#6445]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
I was trying to make it redirect to the main `Array` document, but I can't edit it. (404)
Seems like that if the upstream document (`/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype`) is removed, localized ones throw 404 in `$edit`.

**Comment by peterbe** [comment]
It's not the first time we've seen this. The reasons is that https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array is deleted. (aka. soft delete)
<img width="1162" alt="Screen Shot 2020-02-10 at 11 28 30 AM" src="https://user-images.githubusercontent.com/26739/74169130-d2460c00-4bf8-11ea-9e7f-67a391d4bce8.png">

I think a simple solution is to dig into the `$edit` and wherever it looks up its parent, it should also accept that the parent might be (soft) deleted. 
Perhaps also, a warning message somewhere too.

**Comment by peterbe** [comment]
I can reproduce this locally.

**Comment by tobinmori** [comment]
@atopal we've put this as a p3, but feel free to prioritize.

**Comment by peterbe** [comment]
FYI, https://github.com/mdn/kuma/pull/6455 solves the problem. It'll get you back into being able to edit those documents at least.

**Comment by atopal** [comment]
p3 sounds right

**Comment by alattalatta** [comment]
I do see it fixed, but still getting 404 from _submitting_ any edit. That is, fixed for GET, not for POST:
![주석 2020-02-20 012342](https://user-images.githubusercontent.com/9212605/74852307-b9b7bd80-537f-11ea-8ccf-4768c5a2ff2a.png)

(pinging @peterbe)

**Comment by peterbe** [comment]
Yep. I can reproduce it.
