### ISSUE TITLE
T - Upgrade Pytest and related dependencies (coverage.py, etc.)

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6449]

**Comment by callahad** [comment]
Lots of progress over the past few days.

The remaining upgrades are:

- pytest (4.6.9 -> 5.3.5)
- pytest-django (3.4.8 -> 3.8.0)

Pytest is blocked by pytest-django; only versions ≥ 3.5.1 support Pytest 5.
Pytest-django is blocked by failures in our test suite; version 3.5 changes test execution order, which reveals that our elasticsearch tests are order-dependent.

**Comment by callahad** [comment]
Specifically, attempting to upgrade to pytest 5 results in every test failing with:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pytest_django/fixtures.py", line 397, in _live_server_helper
    if "live_server" not in request.funcargnames:
[...]
pytest.PytestDeprecationWarning: The `funcargnames` attribute was an alias for `fixturenames`, since pytest 2.3 - use the newer attribute instead.
```

This is resolved in pytest-django 3.5.1: https://github.com/pytest-dev/pytest-django/compare/v3.5.0...v3.5.1

However, pytest-django 3.5 also introduces a commit which changes the order of test execution:
https://github.com/pytest-dev/pytest-django/commit/5a79fba3705376c3f89f5a9e26b8244937d61768

This causes our test suite to fail, as many tests looks for an elasticsearch connection that does not exist when they execute under the new ordering. Each failing test fails with:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/elasticsearch_dsl/connections.py", line 91, in get_connection
    return self.create_connection(alias, **self._kwargs[alias])
KeyError: 'indexing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/kuma/search/tests/__init__.py", line 49, in setUp
    self.setup_indexes()
  File "/app/kuma/search/tests/__init__.py", line 65, in setup_indexes
    WikiDocumentType.reindex_all()
  File "/app/kuma/wiki/search.py", line 299, in reindex_all
    chord_flow(pre_task, index_tasks, post_task).apply_async()
  File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 640, in apply_async
    return self.apply(args, kwargs, **options)
  File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 804, in apply
    last and (last.get(),), **dict(self.options, **options))
  File "/usr/local/lib/python3.8/site-packages/celery/result.py", line 1033, in get
    raise self.result
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/kuma/core/decorators.py", line 189, in wrapped
    return func(*args, **kwargs)
  File "/app/kuma/search/tasks.py", line 29, in prepare_index
    es = cls.get_connection("indexing")
  File "/app/kuma/wiki/search.py", line 61, in get_connection
    return connections.get_connection(alias)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch_dsl/connections.py", line 94, in get_connection
    raise KeyError('There is no connection with alias %r.' % alias)
KeyError: "There is no connection with alias 'indexing'."
------------------------------ Captured log call -------------------------------
ERROR    celery.app.trace:trace.py:254 Task kuma.search.tasks.prepare_index[b1b2d54d-df3e-4377-892a-26c0f0c16a82] raised unexpected: KeyError("There is no connection with alias 'indexing'.")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/elasticsearch_dsl/connections.py", line 91, in get_connection
    return self.create_connection(alias, **self._kwargs[alias])
KeyError: 'indexing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/kuma/core/decorators.py", line 189, in wrapped
    return func(*args, **kwargs)
  File "/app/kuma/search/tasks.py", line 29, in prepare_index
    es = cls.get_connection("indexing")
  File "/app/kuma/wiki/search.py", line 61, in get_connection
    return connections.get_connection(alias)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch_dsl/connections.py", line 94, in get_connection
    raise KeyError('There is no connection with alias %r.' % alias)
KeyError: "There is no connection with alias 'indexing'."
```

So I need to dig into that and figure out where we set up (and close!) that connection, and how to ensure those specific tests run while it's available.

**Comment by callahad** [comment]
Trying to narrow down the tests that are conflicting, using pytest-django 3.5.1:

- ✅ `pytest kuma/{api,search}`
  130 passed, 1060 warnings

- ✅ `pytest kuma/wiki`
  1039 passed, 1 xfailed, 6764 warnings

- ❌ `pytest kuma/{api,search,wiki}`
  37 failed, 1132 passed, 1 xfailed, 7466 warnings

So now to start bisecting the test corpus in `kuma/wiki/`...

**Comment by callahad** [comment]
All tests pass if `kuma/wiki/tests/test_kumascript.py` is excluded from the test run.

Running `pytest kuma/{api,search} kuma/wiki/tests/test_kumascript.py` is enough to trigger failures: 37 failed, 111 passed, 730 warnings

So now to start narrowing _that_ down.

**Comment by callahad** [comment]
Okay, so either of the following two tests cause breakage:

- [kuma/wiki/tests/test_kumascript.py::test_macro_page_count](https://github.com/mdn/kuma/blob/11a2a36e9520a9f44b353b7b2b3d964eb4d0196c/kuma/wiki/tests/test_kumascript.py#L107-L135)
- [kuma/wiki/tests/test_kumascript.py::test_macro_page_count_en](https://github.com/mdn/kuma/blob/11a2a36e9520a9f44b353b7b2b3d964eb4d0196c/kuma/wiki/tests/test_kumascript.py#L138-L167)

The entire test suite passes if they are skipped:
1964 passed, 2 skipped, 1 xfailed, 11007 warnings

**Comment by callahad** [comment]
I'm going to go ahead and annotate them with `pytest.mark.skip` to move forward with upgrading pytest and pytest-django. Once those are up to date I can go back to fix those tests.

**Comment by peterbe** [comment]
"go back to fix those tests" 
Well, I would argue that the tests are bad, to begin with. First of all, I suspect that the tests naively thinks that indexing stuff over into ES is always synchronous or something. But perhaps there's some way the celery workers trigger and those assume that the ES connection already exists. 

Secondly, mocking Elasticsearch seems like the wrong idea. If there's going to be any mocking, I'd mock something that doesn't depend on details about how ES and `elasticsearch_dsl` works. 

More importantly, from skimming it really quickly, this seems like the kind of test that tests implementation details rather than the important high-level API.  

Perhaps delete the tests? Perhaps see if it's possible to just NOT mock anything but instead just run `kumascript.macro_page_count()` with a real live (inside docker-compose) ES and then talk to ES directly to see if it worked. 

Also, not sure why I'm telling *you* something you already knew :)
For what it's worth kuma is fully of intricate unit tests that tests implementation details (e.g. `response.context` that tests the insides of a django view function intead of its output). We should slowly stamp these out in favor of doing more things that a real QA human would have done, but with Python.

**Comment by callahad** [comment]
For my own reference, this command runs only the affected tests:

```
pytest \
    kuma/wiki/tests/test_kumascript.py::test_macro_page_count \
    kuma/wiki/tests/test_kumascript.py::test_macro_page_count_en \
    kuma/api/v1/tests/test_views.py::SearchViewTests::test_search_basic \
    kuma/search/tests/test_filters.py::FilterTexts::test_get_filters \
    kuma/search/tests/test_filters.py::FilterTexts::test_highlight_filter \
    kuma/search/tests/test_filters.py::FilterTexts::test_keyword_query \
    kuma/search/tests/test_filters.py::FilterTexts::test_language_filter \
    kuma/search/tests/test_filters.py::FilterTexts::test_language_filter_override \
    kuma/search/tests/test_filters.py::FilterTexts::test_no_highlight_filter \
    kuma/search/tests/test_filters.py::FilterTexts::test_search_query \
    kuma/search/tests/test_filters.py::FilterTexts::test_tag_group_filter \
    kuma/search/tests/test_indexes.py::TestIndexes::test_add_newindex \
    kuma/search/tests/test_indexes.py::TestIndexes::test_delete_index \
    kuma/search/tests/test_indexes.py::TestIndexes::test_get_current \
    kuma/search/tests/test_indexes.py::TestIndexes::test_outdated \
    kuma/search/tests/test_indexes.py::TestIndexes::test_promote_index \
    kuma/search/tests/test_indexes.py::TestIndexes::test_there_can_be_only_one \
    kuma/search/tests/test_serializers.py::SerializerTests::test_document_serializer \
    kuma/search/tests/test_serializers.py::SerializerTests::test_excerpt \
    kuma/search/tests/test_serializers.py::SerializerTests::test_filter_serializer \
    kuma/search/tests/test_serializers.py::SerializerTests::test_filter_serializer_with_translations \
    kuma/search/tests/test_serializers.py::SerializerTests::test_search_query_serializer \
    kuma/search/tests/test_serializers.py::FieldTests::test_SearchQueryField \
    kuma/search/tests/test_serializers.py::FieldTests::test_SiteURLField \
    kuma/search/tests/test_tasks.py::TestLiveIndexing::test_live_indexing_docs \
    kuma/search/tests/test_types.py::WikiDocumentTypeTests::test_current_locale_results \
    kuma/search/tests/test_types.py::WikiDocumentTypeTests::test_get_excerpt_strips_html \
    kuma/search/tests/test_types.py::WikiDocumentTypeTests::test_get_excerpt_uses_summary \
    kuma/search/tests/test_types.py::WikiDocumentTypeTests::test_hidden_slugs_get_indexable \
    kuma/search/tests/test_views.py::ViewTests::test_allowed_methods \
    kuma/search/tests/test_views.py::ViewTests::test_api_redirect \
    kuma/search/tests/test_views.py::ViewTests::test_filters \
    kuma/search/tests/test_views.py::ViewTests::test_index \
    kuma/search/tests/test_views.py::ViewTests::test_paginate_by_param \
    kuma/search/tests/test_views.py::ViewTests::test_paginate_too_large \
    kuma/search/tests/test_views.py::ViewTests::test_queryset \
    kuma/search/tests/test_views.py::ViewTests::test_search_filters \
    kuma/search/tests/test_views.py::ViewTests::test_serialized_filters \
    kuma/search/tests/test_views.py::ViewTests::test_tokenize_camelcase_titles
```

Or, currently equivalently,

```
pytest \
    kuma/wiki/tests/test_kumascript.py::test_macro_page_count \
    kuma/wiki/tests/test_kumascript.py::test_macro_page_count_en \
    kuma/api/v1/tests/test_views.py::SearchViewTests \
    kuma/search/tests/test_filters.py::FilterTexts \
    kuma/search/tests/test_indexes.py \
    kuma/search/tests/test_serializers.py \
    kuma/search/tests/test_tasks.py \
    kuma/search/tests/test_types.py \
    kuma/search/tests/test_views.py::ViewTests
```

**Comment by callahad** [comment]
Hey! I fixed the tests! (Kinda; they're still poorly structured / happening at the wrong place.)

The Elasticsearch client mock was was clobbering the entire shared connection pool during teardown, including nuking the default connection configuration. If we more narrowly scope its teardown, everything works.

It's still not _ideal_ (we're overriding the `default` connection, when we should be creating a specially named connection for mocks and passing that around), but doing it "right" would require much more invasive changes to our codebase.
