### ISSUE TITLE
U - Test that Google Auth events added to Auth workflow are landing in Google Analytics.

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6462]
1. Run through Google Auth login workflow
2. Verify events are landing in Analytics dashboard

**Comment by chinikes** [comment]
Hi @tobinmori - Is this task assigned to you?

**Comment by tobinmori** [comment]
Yes, we can keep it assigned to me for now.

**Comment by chinikes** [comment]
Hi @tobinmori , @atopal - This is included in Bravo correct? I think we forgot to add it in during planning

**Comment by atopal** [comment]
yes

**Comment by tobinmori** [comment]
@escattone and I went over this on prod and the events are landing in GA.
