### ISSUE TITLE
U - As the MDN PM, I want specific language in the stripe receipt email to satisfy legal requirements

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6470]
AC:
- [x] Stripe receipt has the following sentence in it: "Cancel any time. To cancel your subscription, please [contact support]. If you have questions, please read the [FAQ] or you can also contact support."

**Comment by atopal** [comment]
see https://stripe.com/docs/recipes/sending-custom-email-receipts

**Comment by tobinmori** [comment]
@atopal I've checked this out more deeply and it looks it would be no small chunk of work to get our own text in the email receipt. Unfortunately, the customization via the Stripe console (which I was hoping would have an easy way to add custom text, but it doesn't) is only for logo and color. 

I'd estimate this is as 3 or 4: we'd have to create an endpoint that sends the custom email, upon receiving a webhook from Stripe (for a successful payment). 

Other possible design dependencies: html email template and text version.

Can you let me know if you want to move forward?

**Comment by atopal** [comment]
Thanks for the heads up Tobin, I asked our legal counsel for advise.

**Comment by atopal** [comment]
Legal counsel has confirmed that the text is mandatory, but we can send an extra email just about that, and leave the Stripe email as is.

**Comment by atopal** [comment]
Tobin, can you estimate it for either options?

**Comment by atopal** [comment]
every receipt (every month) has to have that specific language in it.

**Comment by tobinmori** [comment]
See #6562. Estimated at 4.
