### ISSUE TITLE
U - As a potential subscriber I want an FAQ page to know why MDN wants my money and what will happen with it, so I can make an informed decision

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6471]
AC:
- [ ] FAQ page is accessible to everyone
- [ ] FAQ page text is updated with new text

**Comment by Gregoor** [comment]
The two content pages we want to reuse from the old payment model:

**FAQ**
https://github.com/mdn/kuma/blob/master/kuma/payments/jinja2/payments/payments.html

**Terms**
https://github.com/mdn/kuma/blob/master/kuma/payments/jinja2/payments/terms.html

Terms looks good but FAQ definitely needs a revamp, as we don't support cancellation atm.

**Comment by atopal** [comment]
Cancellation is in the current sprint: https://github.com/mdn/kuma/issues/6473
