### ISSUE TITLE
U - As a paying subscriber I want a link in my profile, so I can cancel my subscription

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6473]
AC:
- [ ] working link on profile that goes to https://wiki.developer.mozilla.org/en-US/payments/recurring/management

**Comment by schalkneethling** [comment]
After speaking with @Gregoor on Slack we have determined that there is still some back-end work required to ensure that the `recurring/management` view works with the new implementation of subscriptions.

As such, it makes a lot more sense for him to roll this issue into that work.

FWIW, here is the HTML I was going to add Gregor 😄 

```
<p><a href="{{ url('recurring_payment_management') }}" class="negative">{{ _('Cancel Subscription') }}</a></p>
    <p>
      {{ _('If you have questions, please read the <a href="%(terms_url)s">FAQ</a> or you can also contact support.', terms_url=url('recurring_payment_initial')) }}
    </p>
```

**Comment by Gregoor** [comment]
Thanks Schalk! Looks like there's already a (to be overly frank) ugly cancel button and a link to the FAQ though.

**Comment by atopal** [comment]
I don't see the button on my profile? Is it really in production already?

**Comment by Gregoor** [comment]
@atopal Not yet, I've asked Ryan and he said we can take it on to staging today though
