### ISSUE TITLE
HTML documentation index coded wrong for the elements

### ISSUE THREAD

**Issue by HarHarFunky** [mdn/kuma#6475]
**Summary**
_in the [HTML documentation index](https://developer.mozilla.org/en-US/docs/Web/HTML/Index), the less than and greater than signs around an element are showing the character entity code instead of the entity itself_

**Steps To Reproduce (STR)**
1. Head over to https://developer.mozilla.org/en-US/docs/Web/HTML/Index
2. look at the listed pages 55 through 217 
3. realize that what should be &lt; and &gt; are &amp;lt; &amp; &amp;gt;

**Actual behavior**
_The &lt; and &gt; signs around any element shows as &amp;lt; and &amp;gt;_

**Expected behavior**
_I expected these to show as &lt; and &gt;, and was sorely mistaken_

**Additional context**
_In the source code of the page, it shows these as &amp;amp;lt; and &amp;amp;gt; meaning it is not a rendering error, but a coding error
I have also attached 2 images of the problem, one of the rendering, and one of the source code_
![Screenshot 2020-02-12 at 10 45 12 AM](https://user-images.githubusercontent.com/60793820/74356975-ce46f500-4d84-11ea-8274-7545d52a503d.png)
![Screenshot 2020-02-12 at 10 45 19 AM](https://user-images.githubusercontent.com/60793820/74356990-d737c680-4d84-11ea-8cc8-32f69c6645cb.png)

**Comment by tobinmori** [comment]
Change to bleach/KS?

**Comment by callahad** [comment]
We definitely updated Bleach around the time that this bug was filed, so I suspect this is a side-effect of that.

That index page is generated by a KumaScript macro which has not changed in years.

**Comment by callahad** [comment]
FWIW, the KumaScript macro emits the left column as:

    <td rowspan="2"><a href='<%=result[i].url%>'><%=result[i].title%></a></td>

And the summary (where things work) as:

    <td><%-result[i].summary%></td>

So `<%=result[i].title%>` versus `<%-result[i].summary%>`

And the difference between those two, from the [EJS docs](https://ejs.co/) is:

- `<%=` Outputs the value into the template (HTML escaped)
- `<%-` Outputs the unescaped value into the template

...which implies that spitting out _unescaped_ values for the title might fix it, despite seeming terrifying? Or should both be escaped, and we somehow fix Kuma's processing of the output to prevent double-escaping?

**Comment by peterbe** [comment]
We rely on...

```jsx
<article
                id="wikiArticle"
                dangerouslySetInnerHTML={{ __html: document.bodyHTML }}
            />
```
...in the read-only site, when rendering so that `document.bodyHTML` better be clean. I don't think that's a place we'd want to change things but rather leave that as is and make sure `document.bodyHTML` is safe as milk.

**Comment by peterbe** [comment]
The bug was in kumascript. I made a PR here: https://github.com/mdn/kumascript/pull/1335
