### ISSUE TITLE
Contextual Menu is Broken

### ISSUE THREAD

**Issue by wpdv** [mdn/kuma#6478]
Dev version 74.0b2 (64-bit)
MacOS 10.15.3

When right clicking, the contextual menu is all blank/messed up. Not sure if related to Firefox or Apple.
![Screen Shot 2020-02-12 at 6 15 03 PM](https://user-images.githubusercontent.com/7375921/74386875-1554da80-4dc5-11ea-97dd-2dd5e9ee5f3f.png)

**Comment by peterbe** [comment]
Is it exclusive to when you visit https://developer.mozilla.org?

**Comment by wpdv** [comment]
No, it's happening on every single website, and only when using FF. I checked Chrome and Safari and the contextual menu works fine.

**Comment by wpdv** [comment]
Must be a conflict with the latest OSX, as the same dev FF version on my older iMac works fine.

**Comment by wpdv** [comment]
The problem seems to have corrected itself as of this morning. Both instances when this occurred over the last few days, my MacBook Air was not plugged in to AC. That's the only thing I can think of. Marking this as solved
