### ISSUE TITLE
testing.py is a misnomer and a potential cause of infinite chaos

### ISSUE THREAD

**Issue by Gregoor** [mdn/kuma#6481]
Just had a call with Peter where we talked about[ the weird code I had to write for system checks to work in Travis](https://github.com/mdn/kuma/pull/6453/#discussion_r377649147). There we discovered that our expectation of the purpose `kuma.settings.testing` should serve is off.

**Our expectation:** It's settings that get used in pytest, to ensure deterministic tests that behave the same in all environments
**Reality:** Yes and
https://github.com/mdn/kuma/blob/3df115a9ba8d3130094a9007f4e9d668a6f274fe/Makefile#L29

Our thinking is to rename `testing.py` to something like `ci.py` or `pytest.py` to restrict the meaing space. Then we need to stop depending on it in our Makefile, which probably will break some/a lot of other assumptions somewhere else (like the newly added stripe system check depending on testing-setting).

**Comment by peterbe** [comment]
For example, as part of the various Django management commands that get started via the Makefile, one of them is `python manage.py merge` which is a l10n related thing. If it's using `settings/testing.py` it'll get settings that are meant purely for `pytest` which might be dangerous. For example, (I don't doesn't actually get used, but it could) https://github.com/mdn/kuma/blob/282bdb3b01b7f20ed92202e6ecc00632de3856e0/kuma/settings/testing.py#L86

**Comment by peterbe** [comment]
Also, there's a `travis.py` file. Quite likely to be unrelated and just a left-over from the days when we didn't use `docker-compose` in TravisCI.

**Comment by Gregoor** [comment]
#6486 just tests if CI fails when we do those renamings and it looks like it's working alright. But there's likely things not being caught here.

Would be curious to hear what you think about it @escattone & @callahad
