### ISSUE TITLE
E - Noindex on /**/docs/MDN/Jobs ?

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6491]
Similar to https://github.com/mdn/kuma/issues/6422
but this time, instead of `/**/docs/MDN/Doc_status` it's `/**/docs/MDN/Jobs`. 

There are only 9 of them in my month old clone of the production DB.

```
mysql> select locale, slug from wiki_document where slug like 'MDN/Jobs%';
+--------+-------------------------------------------------------+
| locale | slug                                                  |
+--------+-------------------------------------------------------+
| en-US  | MDN/Jobs                                              |
| ja     | MDN/Jobs                                              |
| zh-CN  | MDN/Jobs                                              |
| en-US  | MDN/Jobs/Firefox_developer_content_manager_contractor |
| en-US  | MDN/Jobs/MDN_Developer_Researcher                     |
| ja     | MDN/Jobs/MDN_Developer_Researcher                     |
| zh-CN  | MDN/Jobs/MDN_Developer_Researcher                     |
| en-US  | MDN/Jobs/MDN_technical_writer_contractor              |
| ja     | MDN/Jobs/MDN_technical_writer_contractor              |
+--------+-------------------------------------------------------+
9 rows in set (0.00 sec)
```

So can I add it to [`NOINDEX_SLUG_PREFIXES`](https://github.com/mdn/kuma/blob/3df115a9ba8d3130094a9007f4e9d668a6f274fe/kuma/wiki/constants.py#L668)?

**Comment by peterbe** [comment]
@atopal @chrisdavidmills ?

**Comment by peterbe** [comment]
By the way, I'm going to use the `NOINDEX_SLUG_PREFIXES` in Yari's MySQL importer. 
Basically, MySQL documents that have these slug (prefixes) don't get ported to Git. So far I have the following list:

```javascript
const DEFAULT_EXCLUDE_SLUG_PREFIXES = [
  "User:",
  "Talk:",
  "User_talk:",
  "Template_talk:",
  "Project_talk:",
  "Experiment:",

  // The following come from 'NOINDEX_SLUG_PREFIXES' in
  // https://github.com/mdn/kuma/blob/master/kuma/wiki/constants.py#L668
  // We'll have to manually maintain a match between that and this
  "MDN/Doc_status"
];
```

**Comment by atopal** [comment]
Yeah, you can add them, but I don't quite understand why this is important work right now?

**Comment by peterbe** [comment]
> Yeah, you can add them, but I don't quite understand why this is important work right now?

Because in 2020 we said we'd fix the platform.

**Comment by atopal** [comment]
> > Yeah, you can add them, but I don't quite understand why this is important work right now?
> 
> Because in 2020 we said we'd fix the platform.

Yes, and we have a defined process for prioritizing that work. This is not it. If the process is broken, let's fix it.
