### ISSUE TITLE
B - Cancel button doesn't work on the  non-modal view of /<locale>/profiles/<username>/delete

### ISSUE THREAD

**Issue by escattone** [mdn/kuma#6495]
**Summary**
While reviewing #6488 I discovered that the `Cancel` button does NOT work on the non-modal view of `/<locale>/profiles/<username>/delete`.

<img width="528" alt="image" src="https://user-images.githubusercontent.com/3743693/74490003-03823e80-4e7c-11ea-92bb-1040ea763ebc.png">

**Comment by schalkneethling** [comment]
Indeed it does not, there is no modal to close :) - Here we can simply hide it or, it can send the user back to the edit profile page.

I am happy to take this one.

**Comment by atopal** [comment]
I think we should pull this into the next sprint. P2.

**Comment by peterbe** [comment]
How come this has a priority label and *still* has the `needs triage` label?

**Comment by callahad** [comment]
Perhaps because we haven't applied any of the other metadata labels? Shame on us :)

**Comment by schalkneethling** [comment]
Added schalkneethling as reviewer
