### ISSUE TITLE
Private use characters (End user defined characters) not rendering in Firefox browser.

### ISSUE THREAD

**Issue by vulchivijay** [mdn/kuma#6497]
I have web application, end users can create their own fonts through private character editor (EUDC) and saved as "link with all fonts", Those fonts not rending in chrome and Firefox. The same fonts are rending in IE and Edge. Is there a way to fix the issue in Firefox?

![chrome_private_character_rending](https://user-images.githubusercontent.com/17252359/74510485-eb68f880-4f29-11ea-846c-af4473397df9.jpg)
![edge_private_character_rending](https://user-images.githubusercontent.com/17252359/74510495-ed32bc00-4f29-11ea-9ba4-1c5bfcfd0fc6.jpg)
![ie_private_character_rending](https://user-images.githubusercontent.com/17252359/74510496-edcb5280-4f29-11ea-9d38-64c6dc0f2539.jpg)

**Comment by chrisdavidmills** [comment]
Do you have your document's characterset set as utf-8?

Have you got a link to the app so that I can test it?

**Comment by vulchivijay** [comment]
@chrisdavidmills Thank you for quick response. I am using utf-8, i am sharing my use case link 

https://codepen.io/vulchivijay/pen/ZEGbKBg?editors=1100

we can see boxes in chrome/firefox browser, but edge its render properly (because i am testing EDUC created machine)

**Comment by chrisdavidmills** [comment]
Hrm, I'm not sure I can help much more here.

It would probably be more useful for you to file a bug on https://bugzilla.mozilla.org/home and chat to one of the Firefox engineers who *really* know about this stuff ;-)

**Comment by vulchivijay** [comment]
@chrisdavidmills Thank you for spending your valuable time. I will rise the bug in mozilla and chat.

**Comment by chrisdavidmills** [comment]
OK, cool. Closing for now.
