### ISSUE TITLE
No confirmation message after sign-in

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#6499]
Once a user successfully signs up for an MDN account they are redirected back to the page from which they clicked the sign-in button.

There is supposed to be a Growl style message that shows a message to the user confirming successful signup. This message is not always shown, however. For at least one user it leads to confusion and uncertainty:

https://bugzilla.mozilla.org/show_bug.cgi?id=1614273#c7

We should diagnose the reason for this message not being shown consistently.

**Comment by peterbe** [comment]
> shows a message to the user confirming successful signup

What does that mean? What confirming?

**Comment by schalkneethling** [comment]
> > shows a message to the user confirming successful signup
> 
> What does that mean? What confirming?

During the course of my testing I sometimes saw a growl style message show up after one successfully completed your account that said something like:

"Thank you for creating an MDN account. A confirmation email has been sent to you@yourdomain.tld"

I am making up the words, but something like that. Not sure we **need** this, but it did/does exist, it is just wonky :)

**Comment by schalkneethling** [comment]
i.e. would be good to know why it shows up sometimes and not at other times. That way we can understand the mechanics and decide whether we want to fix it so it is consistent or remove it altogether.

Better than having something out there that sporadically shows up for some users :)

**Comment by peterbe** [comment]
Yikes. We'll be working on auth well into Q2.

**Comment by tobinmori** [comment]
Timebox to 1 point.
