### ISSUE TITLE
E - Ready the  "Call to Action" for all visitors

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#6504]
# User story
As a Visitor to the MDN site (non-logged in) , I want a means to make monthly payments to MDN 

# Workflows | Paths | Audiences
- Logged in user 
- Non logged in (with an MDN account) 
- Non logged in (without an MDN account) 
-- Has a google / github account 
-- Doesn't have a google / github account 
- Ref Doc - https://docs.google.com/document/d/1gXjtPEYSl2mOLWWAK1qXbEfAdBUvJ-4orpJqrkTcg40/edit?usp=sharing

# Designs 
- Ref Doc - https://share.goabstract.com/59bcc9ab-4026-44e9-86b4-7c07eed663d1?collectionLayerId=2536d7fc-cd8e-4b9b-9580-615dc1f76e70&mode=design

# Acceptance criteria
- [x] We have a banner that shows up on every MDN wiki page and the MDN homepage that has a "Call to Action" for payment 
- [x] There is an FAQ that has a "Call to Action" for payment 
- [x] The Visitor with an account can log into their account as part of the payment process 
- [x] The Visitor without an account can create an account by authenticating with Google / GitHub as part of the payment process 
- [x] The Visitor without an account can create an account by creating an account with Google / GitHub as part of the payment ** 
- [x] The Visitor can submit their credit card information to process their monthly subscription fee 
- [x] The logged in Visitor can use the Banner to start the payment process 
- [x] There is a "Thank You" page shown on completing payment 
- [x] Flag that allows us to switch the call to action on and off for defined groups

# User Stories 
*If relevant, you can make a checklist for tasks.*

1. - [ ] Implement call to action for logged in users as an audience

**Comment by chinikes** [comment]
Hi @atopal , @tobinmori - We need user stories identified to meet the ACs of this epic. Could we possibly include this as part of our backlog refinement tomorrow? Thanks!

**Comment by callahad** [comment]
I'm a bit confused about this getting scheduled for a work milestone so soon -- that doesn't match the priorities I've heard, which are effectively replacing our legacy platform at all costs (aka, launch Yari). Are we sure we want to be doing the much unrelated feature work in Q1?

**Comment by atopal** [comment]
@chinikes yeah, let's do that.

@callahad that is something that Tobin and I have talked about today and the scheduling is something we are exploring. For Yari our quarterly objective is "Ready implementation plan for yari 1 to move contributions into Github". For subscriptions it's "Launch Paid Membership MVP"

**Comment by callahad** [comment]
@atopal Thanks! Launching subscriptions to _all_ visitors sounds like a milestone _significantly_ beyond an MVP. Could we de-scope this to just staff or, at a stretch, logged-in users?

There are also some significant external risks in March that could blow up this schedule (e.g., if the rest of the Django work doesn't go smoothly, which has a high probability of hitting significant unknown unknowns.)

**Comment by chinikes** [comment]
Hi @tobinmori  - Kadir has fleshed out the user stories for this epic and has prioritized US #6554, #6555, #6559 and #6560 for implementation in Bravo. 

Can you help have these analyzed for solution / any feedback / Qs you may have for Kadir? Thanks!

**Comment by tobinmori** [comment]
I share your same concerns @callahad; I'm scoping it out first to see how disruptive to the Yari roadmap this could potentially will be. Right now, it feels like 2-3 months of work in its entirety, largely front-end. 

@chinikes I just finished a first round of scoping with @escattone's help on the backend aspects, but want to further scope with @schalkneethling on Monday regarding the frontend. I think we'll have a decent grasp and more accurate estimate after that.
