### ISSUE TITLE
JavaScript Demo: JSON.stringify() does not print valid JSON in the live example output window

### ISSUE THREAD

**Issue by SherylHohman** [mdn/kuma#6510]
re page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

The live example demonstrating `JSON.stringify()` does NOT display a valid JSON string.   
It's neither a string, nor JSON. 
This is what the return window displays as the results of 4 `JSON.stringify()` example commands:  

 > "{"x":5,"y":6}"
> "[3,"false",false]"
> "{"x":[10,null,null,null]}"
> ""2006-01-02T23:04:05.000Z""

Clearly, his is incorrect.    
And it's very confusing.   

The double quotes are incorrectly paired.  Each line should be wrapped in single quotes instead.  
Or removed altogether.

It could print:  
> {"x":5,"y":6}
>[3,"false",false]
>{"x":[10,null,null,null]}
>"2006-01-02T23:04:05.000Z"  
so that the quotes properly pair off.

Better yet, it could (should) print the above, but wrap each result in single quotes, to indicate that the result is a string, not an object:  
> '{"x":5,"y":6}'
>'[3,"false",false]'
>'{"x":[10,null,null,null]}'
>'"2006-01-02T23:04:05.000Z" ' 

One has to have a good understanding of `JSON.stringify()` already and then correctly interpret what caused the buggy-looking output, in order to make sense of the bizarre results, as currently displayed.  
Trying to learn about this function from looking at the results of this live example, increases confusion, and hinders learning.   

The routine used to write the output for this window needs to be modified to wrap the results in single quotes instead of double quotes.   

Or, if that cannot be done, 
REMOVE the example RUN window altogether, for this page.  That example output is hurtful, not helpful.   

It's better for visitors to never see this misleading, confusing, live example output.   
Instead they can learn it by reviewing the code later on the page, where the correct format of `JSON.stringify()` results is properly, and clearly, shown in the code comments.

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/sprints #2822](https://github.com/mdn/sprints/issues/2822) via [**ZenHub**](https://www.zenhub.com/)
