### ISSUE TITLE
Signup ~ When to show second check mark

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#6511]
Based on the design for the new signup flow there are two checkmarks that need to be shown next to the two main header images. The first(overlaid on top of the auth provider logo) is shown as soon as the signup page loads.

The behavior of the second checkmark, however, was never really defined. I have experimented with some options but none feels correct. My proposal, therefore, is one of two options

1. Let's not bother with the second checkmark
2. Add the checkmark as soon as the user checks the privacy/terms checkbox

@atopal @malqinneh Thoughts?

**Comment by atopal** [comment]
If I remember correctly, the idea was to show it briefly after they clicked the button to create a profile. It's okay to drop it.

**Comment by schalkneethling** [comment]
Closing based on https://github.com/mdn/kuma/issues/6511#issuecomment-586646118 - We are skipping the second checkmark.

**Comment by schalkneethling** [comment]
Actually no, there is a piece of code that needs to be removed first 😸

**Comment by chinikes** [comment]
Hi @schalkneethling - Wanted to confirm if this is a card meant for Alfa? If so, what user story / epic is still related to?

**Comment by schalkneethling** [comment]
> Hi @schalkneethling - Wanted to confirm if this is a card meant for Alfa? If so, what user story / epic is still related to?

Yes, this is for this sprint. This is also the user story :)

It was a question for Kadir. Now all that remains is to remove a piece of code.

**Comment by schalkneethling** [comment]
In terms of an epic. This can be connected to the user accounts epic.

**Comment by malqinneh** [comment]
@schalkneethling Do you still need input on this? Noticed it was closed/reopened. Let me know.

**Comment by schalkneethling** [comment]
> @schalkneethling Do you still need input on this? Noticed it was closed/reopened. Let me know.

Nope, all good. Thanks, @malqinneh
