### ISSUE TITLE
Step numbers not shown on signup

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#6512]
In the header of the signup page, there is supposed to be numbering next to the two steps of the signup process. These are currently not being shown:

![Screenshot 2020-02-15 at 10 48 30](https://user-images.githubusercontent.com/10350960/74584997-ed41c300-4fe0-11ea-8b60-003b177eb1bf.png)

**Comment by chinikes** [comment]
Hi @schalkneethling - Wanted to confirm if this is a card meant for Alfa? If so, what user story / epic is still related to?

**Comment by schalkneethling** [comment]
> Hi @schalkneethling - Wanted to confirm if this is a card meant for Alfa? If so, what user story / epic is still related to?

Yes, this is for this sprint. This is the user story and can be connected to the accounts/simplified signup flow epic if appropriate.
