### ISSUE TITLE
Remove hidden unnecessary hidden fields from signup.html

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#6513]
In socialaccount/signup.html there are three hidden fields for the username and email fields that unnecessary. These can be safely removed.

**Comment by schalkneethling** [comment]
@escattone While testing this change I noticed that editing the email address actually has no effect :/

BTW, it does not change irrespective of whether those `hidden` fields are present or removed. I had a look at the template code and I am not sure what could be wrong.

On initial load, we essentially show the current email address as a static string with a button that, when clicked, will show the actual input field. The input field that is revealed is created by the following code:

```
<div id="change-email-container" class="hidden">
    <label for="{{ form.email.id_for_label }}" class="visually-hidden">{{ default_email }}</label>
    {{ form.email }}
</div>
```

My initial thought was that perhaps the `name` attribute was not what the backend expected, but with the code above that is clearly not the case. Any thoughts? Thank you!

**Comment by peterbe** [comment]
How about we don't work on this and just use a regular Django form **without any JavaScript** at all. So, go for https://github.com/mdn/kuma/issues/6514 and then change the jinja template to be just this:

```
<form action="" method="post">
{{ csrf_thing() }}
{{ form }}
<button type="submit">Create profile</button>
</form>
```

It's still so fragile.

**Comment by escattone** [comment]
@peterbe I really like your suggestion above. Anything to clarify/simplify what we have, since what we have is confusing.

**Comment by peterbe** [comment]
> @peterbe I really like your suggestion above. Anything to clarify/simplify what we have, since what we have is confusing.

Or, just do away with the username and email entirely. But that'd make the sign up easier.

**Comment by schalkneethling** [comment]
Let's see what the outcome of https://github.com/mdn/kuma/issues/6514 is. It will determine a lot of this.

**Comment by schalkneethling** [comment]
This is all being taken care of in https://github.com/mdn/kuma/pull/6561
