### ISSUE TITLE
Confusing messages when email field is invalid during signup flow

### ISSUE THREAD

**Issue by escattone** [mdn/kuma#6529]
### Summary
When modifying the email field during the sign-up flow, if the modified email is invalid, the original email, which is valid, is shown (and the invalid email is hidden) when displaying the error message. This is confusing.

#### First step -- initial sign-up page
<img width="814" alt="image" src="https://user-images.githubusercontent.com/3743693/74771012-452b3480-5242-11ea-89bb-c7dee5e71c44.png">

#### Modify email with invalid value
<img width="793" alt="image" src="https://user-images.githubusercontent.com/3743693/74771195-89b6d000-5242-11ea-97c5-a6f8a74afc11.png">

#### After clicking `Create profile`, error message is displayed but original valid email is shown and the invalid email is hidden
<img width="771" alt="image" src="https://user-images.githubusercontent.com/3743693/74771271-b0750680-5242-11ea-9208-ee86b6f49fa8.png">

**Comment by schalkneethling** [comment]
Thank you for logging this @escattone. We started addressing this in this PR https://github.com/mdn/kuma/pull/6371 but things just got to 💇‍♂ so we split things out into separate issues.

I agree this flow is very awkward. We can definitely fix/improve it but, I am leaning more towards what is proposed here: https://github.com/mdn/kuma/issues/6514

**Comment by schalkneethling** [comment]
To talk directly to the last screenshot and the behavior. I suspect you were able to submit the form but then the server came back with a validation error. This means that the page has reloaded. At the point, it actually shown the initial state, is it has no way of knowing that you actually wanted to change your email address.

This one is even trickier than what I was referring to above. The JS would basically have to check `onload` whether there are any errors in the error list, and if there are, either show all of the input fields or, "intelligently" try to figure out which field is in error and how it.

**Comment by tobinmori** [comment]
This may be unnecessary once #6514 is completed. So, do not work on this for now.

**Comment by escattone** [comment]
@tobinmori @schalkneethling Agreed, I think #6514 is the way to go, and would eliminate this confusing behavior.

**Comment by tobinmori** [comment]
Closing because of #6514
