### ISSUE TITLE
"Help us translate this document" link not working

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6536]
**Summary**
<img width="1089" alt="Screen Shot 2020-02-19 at 9 29 52 AM" src="https://user-images.githubusercontent.com/26739/74843888-94cd3700-52fa-11ea-9407-d6cefd8651eb.png">

**Steps To Reproduce (STR)**

Try https://developer.mozilla.org/sv-SE/docs/Web/JavaScript/Reference/Functions
You might need to be signed in. 

**Actual behavior**
That the`Snälla hjälp oss att översätta denna artikel från engelska` text is a clicklable link. 

**Expected behavior**
It's not clickable because the `<a>` element lacks a `href`. 

**Additional context**
Seems to happen in FirefoxNightly and latest stable Chrome.

**Comment by peterbe** [comment]
What's curious is that this can happen [if `translateURL` is `null` or `undefined`](https://codesandbox.io/s/relaxed-austin-bppfy). Ok. 
Does that mean it's `null` or `undefined` in runtime only? I think so. 
I looked at the `window._react_data` and it looks like this:
<img width="483" alt="Screen Shot 2020-02-19 at 9 52 14 AM" src="https://user-images.githubusercontent.com/26739/74845918-ac59ef00-52fd-11ea-8119-5b483469b0c7.png">

So, in a sense this smells like a Django area bug. However, this totally breaks the "contract" of Flow that should have caught that earlier but obviously Flow isn't participating in the production bundle. So, ideally, perhaps we should put something like:

```javascript
if (!translateURL) {
    throw new Error('translateURL is falsy so can't make link to translate')
}
```
[somewhere here](https://github.com/mdn/kuma/blob/6dbcef5faafad14fb84175e92e0ebf1382ccf103/kuma/javascript/src/article.jsx#L28)

**Comment by peterbe** [comment]
Actually, there's something stinky about the types and assumptions. The `DocumentData` Flow type says it's [supposed to be a string](https://github.com/mdn/kuma/blob/6dbcef5faafad14fb84175e92e0ebf1382ccf103/kuma/javascript/src/document.jsx#L32) and it's not marked as optional. Right. 
But in the document data on the server, it *can* be null if the document is NOT localizable. See: https://github.com/mdn/kuma/blob/6dbcef5faafad14fb84175e92e0ebf1382ccf103/kuma/api/v1/views.py#L167-L172

So, which one is right? The `document.jsx` or the `api/v1/views.py`?

A quick and filthy remedy is to do something like this in [`article.jsx`](https://github.com/mdn/kuma/blob/6dbcef5faafad14fb84175e92e0ebf1382ccf103/kuma/javascript/src/article.jsx#L24):

```javascript
if (!translateURL) {
    return null;
}
```

**But why is the document not localizable?** 
[It's not dynamically computed but it's a boolean set on the Document.](https://github.com/mdn/kuma/blob/6dbcef5faafad14fb84175e92e0ebf1382ccf103/kuma/wiki/models.py#L235)
So what does that mean? Why is it set to not be localizable?

**Comment by peterbe** [comment]
By the way, [on the wiki](https://wiki.developer.mozilla.org/sv-SE/docs/Web/JavaScript/Reference/Functions) the link is working perfectly fine.

**Comment by tobinmori** [comment]
Child document being checked for is_localizable, when it shouldn't be. Parent doc should be checked.
