### ISSUE TITLE
U - Create designs for mobile-friendly Table Of Contents

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#6540]
# User Story 
As an MDN user on a mobile device, I want a clean header so I can get to the content I'm really interested in.

# Acceptance criteria
- [x] Table Of Contents is optimized for mobile
- [x] Engineering sign off on designs

# Tasks 
1. - [x] Add task into [project doc](https://docs.google.com/document/d/1Fg5hjxgsuG8d6sjaxazGLW_scsMgmPH06MgK63Png8Q/edit?usp=sharing)
2. - [x] Add UI for Table Of Contents in Sketch file
3. - [x] Send designs for engineering sign off

**Comment by malqinneh** [comment]
@schalkneethling @tobinmori 'Table of contents/on this page' on mobile: https://share.goabstract.com/ef1e325d-f6b5-4059-92e2-01634d792eb8?mode=design

Can you give a thumbs up/comment if everything looks good from an implementation POV?

**Comment by schalkneethling** [comment]
> @schalkneethling @tobinmori 'Table of contents/on this page' on mobile: https://share.goabstract.com/ef1e325d-f6b5-4059-92e2-01634d792eb8?mode=design
> 
> Can you give a thumbs up/comment if everything looks good from an implementation POV?

Will take a look. Thanks @malqinneh

**Comment by schalkneethling** [comment]
@malqinneh Look all good to me.

**Comment by malqinneh** [comment]
@schalkneethling great! Feel free to ping me as questions come up once we're ready to break this down into engineering issues.
