### ISSUE TITLE
Delete all Persona accounts with no revisions

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6545]
**Summary**
We have Persona accounts of users who created an account years ago and never created a doc. It's been years since we have removed Persona logins. Users might have forgotten that they created an account years ago and don't use the same email on Github or Google. Deleting those accounts should be fairly straight forward, and limit the number of cases we might have to deal with manually.

**Rationale**
People wanting to use their old username and being confused as to why that is not possible.

**Comment by atopal** [comment]
Elevated to P1 for Sprint Charlie

**Comment by escattone** [comment]
Prior to completing this task, there were **150,289** Persona-only accounts (i.e., MDN accounts created with Persona, and without any other associated social accounts like GitHub or Google). After running [this code](https://gist.github.com/escattone/4e353404faae10dae2fff8754b292fe3), **134,852** (about **90%**) of those accounts had made no contributions and were deleted. Only **15,437** Persona-only accounts remain, and all of them have made contributions.
