### ISSUE TITLE
T - Remove option to *change* email in sign up form

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6548]
Basically, Option 1 in https://docs.google.com/document/d/17FUhSfPQ5uPyA5VvctYFZZ0tPhc205gr4nZM8Nsu2KI/edit#

* No "change username" hyperlink.
* No `<input>` elements at all for email. Hidden or could-be hidden. 
* No form validation of email at all. 
* Remove the last two words on the paragraph line above "... choose username and email." to "... choose username."

Notes-to-self;

* There might be a slight conflict with the necessary work on https://github.com/mdn/kuma/issues/6541 since the form, before save, should display the *correct* email in the form-preview.
* Working on this issue, might "automatically" cover all of https://github.com/mdn/kuma/issues/6513 too.

**Comment by peterbe** [comment]
More note-to-self;
Completeting this will free up the draft of https://github.com/mdn/kuma/pull/6530 since it now doesn't need to worry itself with the email which was the blocker of that PR progress.
Also, the for-loop in https://github.com/mdn/kuma/pull/6496 will not be necessary any more.

**Comment by chinikes** [comment]
Hi @peterbe - Can you confirm an estimated for this task? Thanks!
