### ISSUE TITLE
Problems encountered on https://developer.mozilla.org 

### ISSUE THREAD

**Issue by a73841959** [mdn/kuma#6570]
Hi，

I want to submit a new issue when i saw this. I think this affects the browsing experience of mobile users (in fact, similar things happen when the screen width of other devices is insufficient)
### Summary
When I browse through the default browser of Samsung s9 mobile phone on the homepage of MDN. I found that when I zoomed in the interface, if my finger was in the navigation bar of the webpage, it would open automatically.

### Steps To Reproduce
1. Go to https://developer.mozilla.org in my mobile phone
2. Zoom in on the navigation bar

### Actual behavior
![bug](https://user-images.githubusercontent.com/44235276/75103158-04f8f700-5632-11ea-9b3c-7ea9e595e28b.gif)

### Expected behavior
It only expands when I click on the navigation bar

### Additional context
When I browse two webpages on the computer at the same time, the width for MDN is not enough. When I click the navigation bar, it will not respond. I tried several browsers, such as firefox, chrome. Found that this should not be a browser issue.
![MDN Web Docs - Mozilla Firefox 2020-02-23 12-00-25](https://user-images.githubusercontent.com/44235276/75103332-6f129b80-5634-11ea-8717-d9994b6d5fea.gif)
When the navigation bar is narrowed by the browser, they will not expand no matter how you click the button.

**Comment by peterbe** [comment]
@schalkneethling Can you confirm if https://github.com/mdn/kuma/pull/6544 closes this one?

**Comment by erkde** [comment]
@peterbe I don't think it would have, at least according to caniuse, `:focus-within` isn't event supported by Samsung browser, and is a bit patchy in others as well:

https://caniuse.com/#search=focus-within

I've closed the #6544, but happy to open a new one that changes onTouchStart to onClick in MainMenu, but it does change the way menu's work.

**Comment by schalkneethling** [comment]
@peterbe @erkde I need to discuss my proposal of changing the menu interaction to work consistently across desktop and mobile with Kadir and Mustafa. Once we have the go-ahead we can use one of these issues to attach the work to and dupe the others. Thank you for following up.

**Comment by atopal** [comment]
I can't reproduce any of this anymore. Please reopen, if it's still an issue.
