### ISSUE TITLE
Responsive Web Pages, A problem

### ISSUE THREAD

**Issue by obeka** [mdn/kuma#6571]
Hi there, there is a problem for smaller web pages where I can not see the menu items of the nav's dropdowns. (f.e. technologies, feedback etc)

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body

Try this link in a smaller web window.  When I hover over or click on Technologies on the navbar, I can not see the menu in a 500px wide window.

**Comment by atopal** [comment]
Can't reproduce this one anymore. Please reopen if it's still broken.
