### ISSUE TITLE
"Submit as: Spam" shouldn't be exposed to users

### ISSUE THREAD

**Issue by alattalatta** [mdn/kuma#6573]
**Summary**
_What is the problem?_
The revision dashboard has an Akismet column with "Submit as: Spam" row-buttons. It doesn't work, which implies I don't have permissions to use it. (I saw @chrisdavidmills had marked one for [Getting started with the Web](https://wiki.developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web$history))

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Visit Revision Dashboard without administrative permissions.

**Actual behavior**
_What actually happened?_
Spam tagging buttons are there, and nothing happens when I click. No HTTP requests are initiated.

**Expected behavior**
_What did you expect to happen?_
No spam tagging buttons exposed. (or, do something when clicked)

**Comment by peterbe** [comment]
According to the code, the "Submit as: Spam" row depends on this permission check:
```python
    show_spam_submission = request.user.is_authenticated and request.user.has_perm(
        "wiki.add_revisionakismetsubmission"
    )
```
So, if you see it, you must have permission to add a AkismetSubmission.

**Comment by alattalatta** [comment]
That... is strange. I didn't know I had such permission. Sorry!

For the 'button not initiating any requests' part - there's an error in the console.
`TypeError: mdn.utils is undefined` (it's trying to use `getCookie` function from it)

`mdn.utils` is defined in `js/utils/utils.js` file, which is bundled with `wiki.js`. And dashboard doesn't use `wiki.js`.

I suspect the fix would be to add `js/utils/utils.js` to `common.py`'s `'dashboard'` bundle setting. Should I change this one, or open another issue?

**Comment by peterbe** [comment]
Thank you @alattalatta 
The problem you've stumbled on now is actually the same as https://github.com/mdn/kuma/issues/6550 is about. That issue is a P2 issue so it'll get done very soon. 

Can we close this now? I think so.

**Comment by alattalatta** [comment]
Sure! Thank you for your confirmation.
