### ISSUE TITLE
U - Create tool that can prune 'unneeded' content via NLP and datetime analysis

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6591]
**Description**

Peter already has a small tool that does very simple analysis. This tool needs to be extended and refined so that it can be used to better target unneeded localized content as well as batch prune it.

**Comment by peterbe** [comment]
For the record, I have a tool in the works. 
I just need help figuring out how to complete it in terms of what options and links should appear.

**Comment by tobinmori** [comment]
Cleanup: removing this from Epic, as it may be premature right now.
