### ISSUE TITLE
U - Define replacement features for Doc Status page and other tools used by translators

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6592]
**Description**

This task involves defining what replacement features translators will need to function in a Yari 1 world. We've recognized the need for something to replace the Doc Status page. But are there other tools they need?

**Comment by peterbe** [comment]
Actually, how is this different from https://github.com/mdn/kuma/issues/6600 ?

**Comment by tobinmori** [comment]
Cleanup: removing this from Epic as it may be premature at this point.
