### ISSUE TITLE
U - Outline how the MVP contribution workflow would work for contributors using Yari 1. 

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6600]
# Acceptance Criteria 
- [ ] Document steps (textually or workflow diagram) defining what it would take for a
contributor to contribute to Yari.

# Notes
_IMPORTANT: timebox to 2 ideal days._

It might be good to envision an MVP contributor who's starting from scratch and imagine a rough/high-level step by step guide. Of course not too detailed, but essential something like:

1. User opens MDN website
2. User uses tool X to determine what needs translating
3. User copies document to be translated
4. User translates document
etc. . .

There are EXISTING notes here, but they seem too raw: https://docs.google.com/document/d/1CvxDq7Pe3y3c-ItFoN4qQzQvsVv5dkrA5S9ModV3p3I/edit#heading=h.dqs3g9mxgpcz

Another (graphical) option could be a workflow diagram that shows the same thing.

**Comment by chinikes** [comment]
@atopal, @tobinmori - What are your ACs for this Story? Please add them in. Thanks!

**Comment by peterbe** [comment]
@tobinmori I think we can outline the high level objectives. 
With your translation hat on, you want to find out...
1. Which of my locale pages (e.g. French) are not less updated than their English counterpart it spawned from?
2. Which new pages, in English, haven't even started being translated?

In terms of workflow, you've got to either kick-off or reach a report. Some tool that does that aggregation work for you and presents it in some tabular format. 
My suggestion would be to start with a minimal spec for a CLI based tool within Yari. The input parameter is your locale of choice and the output is some lists of paths plus some metadata "This is 6 days behind".

**Comment by peterbe** [comment]
Actually, how is this different from https://github.com/mdn/kuma/issues/6592 ?

**Comment by atopal** [comment]
Peter, you might be assuming that we would build a contribution workflow for localizers, but the whole reason for us to move to Github is to reduce the amount of tooling we provide and let existing tools handle the contribution process. That user story you linked to is about replicating existing tools in a post yari world, this one is about  "how the contribution workflow would work for contributors posting L10n content using Yari 1". Its much broader and come to very different conclusions.

**Comment by tobinmori** [comment]
> Actually, how is this different from #6592 ?

Echoing what @atopal said. #6592 might be a task/sub-story of this one.

**Comment by Gregoor** [comment]
https://app.lucidchart.com/invitations/accept/7368d52a-da09-4edd-b24e-b42604a7fb8e

(current, pre-PVP decisions, diagram)

**Comment by Gregoor** [comment]
@atopal @tobinmori @peterbe 

I've updated the contribution diagram a little after going through the PVP doc again:
https://app.lucidchart.com/documents/edit/6793e569-98aa-4594-801f-86b5f0f4fc4f/0_0

I was aiming to only capture the surface area of how writers would interact with it. Which might mean that I missed things that you think should be in there. Happy to flesh it out more, if you give me pointers!
