### ISSUE TITLE
Re-render all documents that use the "compat" macro

### ISSUE THREAD

**Issue by escattone** [mdn/kuma#6616]
Since I was already working on https://github.com/mdn/kuma/issues/6532, I decided to also re-render of all of the documents that use the `compat` macro, since that hasn't been done since Jan. 9th (see https://github.com/mdn/kuma/issues/6325).

I run [this gist](https://gist.github.com/escattone/2f1a27a16ebd4233b0f1197a58eb9c0a) within a `./manage.py shell_plus` on a celery-worker pod, and scale-up the api pods and kumascript pods to six (6) pods each before I make the run. It usually takes about 1-2 hours to render about 20K documents.

### Acceptance Criteria
- [x] All documents that use the `compat` macro have been successfully re-rendered on prod

**Comment by escattone** [comment]
@Elchi3 @tobinmori This is done. 20986 documents containing the `compat` macro were re-rendered in 63 minutes with no errors.

**Comment by tobinmori** [comment]
Thanks for the heads up @escattone
