### ISSUE TITLE
toLocaleTimeString method showing 24 hour clock plus time

### ISSUE THREAD

**Issue by kolekaramol** [mdn/kuma#6619]
const currentDate = new Date("2020-02-02T19:15:00Z").toLocaleTimeString("en-in", {
                        timeZone: "Asia/Calcutta",
                        year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: 'numeric',
                        second: 'numeric', hour12: false
                    });

console.log(currentDate)

output:
"3/2/2020, 24:45:00"

**Comment by chrisdavidmills** [comment]
This is not a kuma issue, so I'll move it to our sprints repo.

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/sprints #2882](https://github.com/mdn/sprints/issues/2882) via [**ZenHub**](https://www.zenhub.com/)
