### ISSUE TITLE
Rename all Persona accounts with revisions

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6627]
This is potentially a "joint issue" with https://github.com/mdn/kuma/issues/6545
It's the [second time this has happened](https://bugzilla.mozilla.org/show_bug.cgi?id=1619519) now. The user has come back to us and they used Persona a long time ago and has >0 revisions. 

It's very likely that there are other people like this (and Pomax) who are confronted with the fact that their preferred username is taken don't file an issue/bug about it but have to begrudignly accept `myusername2`.

**Comment by peterbe** [comment]
If you look at https://bugzilla.mozilla.org/show_bug.cgi?id=1619519 and https://developer.mozilla.org/admin/users/user/44905/change/?_changelist_filters=q%3Dmplungjan you can see that the email clearly isn't the same but the username the same. I think our options are:

1. Shut the door on all of them. You're just not going get your preferred username and quit asking. 
2. Donate all revisions of "Persona users" to `Anonymous` so they can all be deleted.
3. Rename every username to `persona_$username` so these kinds of clashes don't happen at all. But accept that users won't be able to see their old revisions. 
4. Not ask or even bother with usernames at all (visually). If it can't be what it is on GitHub or `google_email.split('@')[0]` then simply making it a random string and don't make a big deal about it. After all, you *can* change your username after you've signed up. After all, it only really matters to people who will Wiki contribute a lot and really care about the vanity(*) of their contribution. 


(*) This is not a down-put on vanity. To some, that attribution is directly related to their resume/career.

**Comment by atopal** [comment]
Just in passing: 2 and 3 are not legal options, our license requires attribution.

**Comment by peterbe** [comment]
> Just in passing: 2 and 3 are not legal options, our license requires attribution.

Interesting!
Not that I can understand how renaming someone's username violates that attribution. 

Another non-trivial option might be to build a UI where they can get a chance to recover their old Persona account if there is a username clash. E.g. "Your username was taken. If you think it's you click here to send a verification email to that old email."

**Comment by peterbe** [comment]
@atopal Can you weigh in on this ad hoc singular "hack"? https://bugzilla.mozilla.org/show_bug.cgi?id=1619519#c2

**Comment by tobinmori** [comment]
Let's go with option 1 above.
