### ISSUE TITLE
NoReverseMatch: Reverse for 'wiki.document' not found. On viewing samples

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6629]
https://sentry.prod.mozaws.net/operations/mdn-prod/issues/7415717/

```
Resolver404: {'tried': [[<URLPattern '^media/(?:redesign/)?css/(?P<doc>.*)-min.css$'>], [<URLPattern '^media/(?:redesign/)?js/(?P<doc>.*)-min.js$'>], [<URLPattern '^media/(?:redesign/)?img(?P<suffix>.*)$'>], [<URLPattern '^media/(?:redesign/)?css(?P<suffix>.*)$'>], [<URLPattern '^media/(?:redesign/)?js(?P<suffix>.*)$'>], [<URLPattern '^media/(?:redesign/)?fonts(?P<suffix>.*)$'>], [<URLPattern '^media/uploads/demos/(?:.*)$'>], [<URLPattern '(?i)^(?P<one>.*)//(?P<two>.*)//(?P<three>.*)$'>], [<URLPattern '(?i)^(?P<one>.*)//(?P<two>.*)$'>], [<URLPattern '(?i)^samples/canvas-tutorial/2_1_canvas_rect.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/2_2_canvas_moveto.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/2_3_canvas_lineto.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/2_4_canvas_arc.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/2_5_canvas_quadraticcurveto.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/2_6_canvas_beziercurveto.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/3_1_canvas_drawimage.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/3_2_canvas_drawimage.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/3_3_canvas_drawimage.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/3_4_canvas_gallery.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_1_canvas_fillstyle.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_2_canvas_strokestyle.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_3_canvas_globalalpha.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_4_canvas_rgba.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_5_canvas_linewidth.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_6_canvas_linecap.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_7_canvas_linejoin.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_8_canvas_miterlimit.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_9_canvas_lineargradient.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_10_canvas_radialgradient.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/4_11_canvas_createpattern.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/5_1_canvas_savestate.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/5_2_canvas_translate.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/5_3_canvas_rotate.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/5_4_canvas_scale.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/6_1_canvas_composite.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/6_2_canvas_clipping.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/globalCompositeOperation.html$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/backdrop.png$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/bg_gallery.png$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/gallery_1.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/gallery_2.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/gallery_3.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/gallery_4.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/gallery_5.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/gallery_6.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/gallery_7.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/gallery_8.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/picture_frame.png$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/rhino.jpg$'>], [<URLPattern '(?i)^samples/canvas-tutorial/images/wallpaper.png$'>], [<URLPattern '(?i)^samples/domref/mozGetAsFile.html$'>], [<URLPattern '(?i)^samples/raycaster/input.js$'>], [<URLPattern '(?i)^samples/raycaster/Level.js$'>], [<URLPattern '(?i)^samples/raycaster/Player.js$'>], [<URLPattern '(?i)^samples/raycaster/RayCaster.html$'>], [<URLPattern '(?i)^samples/raycaster/RayCaster.js$'>], [<URLPattern '(?i)^samples/raycaster/trace.css$'>], [<URLPattern '(?i)^samples/raycaster/trace.js$'>], [<URLPattern '(?i)^samples/webgl/sample1$'>], [<URLPattern '(?i)^samples/webgl/sample1/index.html$'>], [<URLPattern '(?i)^samples/webgl/sample1/webgl-demo.js$'>], [<UR...
  File "redirect_urls/middleware.py", line 14, in __call__
    resolver_match = self.resolver.resolve(request.path_info)
  File "newrelic/hooks/framework_django.py", line 600, in wrapper
    return _wrapped(*args, **kwargs)
  File "newrelic/hooks/framework_django.py", line 588, in _wrapped
    result = wrapped(path)
  File "django/urls/resolvers.py", line 567, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})

NoReverseMatch: Reverse for 'wiki.document' not found. 'wiki.document' is not a valid view function or pattern name.
(9 additional frame(s) were not displayed)
...
  File "kuma/core/urlresolvers.py", line 64, in reverse
    return django_reverse(
  File "newrelic/hooks/framework_django.py", line 642, in wrapper
    return execute(*args, **kwargs)
  File "newrelic/hooks/framework_django.py", line 641, in execute
    return wrapped(viewname, *args, **kwargs)
  File "django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)

NoReverseMatch: Reverse for 'wiki.document' not found. 'wiki.document' is not a valid view function or pattern name.
```

**Comment by peterbe** [comment]
Seems to have spiked pretty badly in the last 24h. 
<img width="341" alt="Screen Shot 2020-03-03 at 4 18 05 PM" src="https://user-images.githubusercontent.com/26739/75820597-a38c0300-5d6a-11ea-9736-4e5bce46406a.png">

**Comment by peterbe** [comment]
Reproducible in prod by visiting https://demos-origin.mdn.mozit.cloud/en-US/docs/en-US/docs/Web/API/WebGL_API/By_example/Canvas_size_and_WebGL$samples/canvas-size-and-webgl-source?revision=1588345

**Comment by callahad** [comment]
Hm. So looking at that Sentry report, starting in the middle of the traceback I see:

<img width="636" alt="Screen Shot 2020-03-03 at 22 29 06" src="https://user-images.githubusercontent.com/24193/75826020-6fcad080-5d9e-11ea-878c-227e009547bb.png">

Passing the same arguments locally in a `./manage.py shell` session, I can successfully reverse `wiki.document`:

```
>>> from kuma.core.urlresolvers import reverse
>>> reverse('wiki.document', locale="en_US", args=['docs/Web/API/WebGL_API/By_example/Canvas_size_and_WebGL'])
'/en-US/docs/docs/Web/API/WebGL_API/By_example/Canvas_size_and_WebGL'
```

So I wonder why it can't reverse that in production? Might it have something to do with the origin of that request (`demos-origin.mdn.mozit.cloud`?)

**Comment by callahad** [comment]
Yeah, it's the Host header. See:

```
$ curl -I -H "Host: demos-origin.mdn.mozit.cloud" \
      "https://demos-origin.mdn.mozit.cloud/en-US/docs/en-US/docs/Web/API/WebGL_API/By_example/Canvas_size_and_WebGL$samples/canvas-size-and-webgl-source?revision=1588345"
HTTP/1.1 404 Not Found
Cache-Control: max-age=0, no-cache, no-store, must-revalidate
Content-Length: 11123
Date: Tue, 03 Mar 2020 22:44:20 GMT
Expires: Tue, 03 Mar 2020 22:44:20 GMT
Set-Cookie: dwf_sg_task_completion=False; Domain=developer.mozilla.org; expires=Thu, 02 Apr 2020 22:44:20 GMT; Max-Age=2592000; Path=/; Secure
Vary: Cookie
```

versus

```
$ curl -I -H "Host: developer.mozilla.org" \
      "https://demos-origin.mdn.mozit.cloud/en-US/docs/en-US/docs/Web/API/WebGL_API/By_example/Canvas_size_and_WebGL$samples/canvas-size-and-webgl-source?revision=1588345"
HTTP/1.1 301 Moved Permanently
Cache-Control: public, max-age=0, s-maxage=300
Content-Length: 0
Date: Tue, 03 Mar 2020 22:44:42 GMT
Location: /en-US/docs/docs/Web/API/WebGL_API/By_example/Canvas_size_and_WebGL/canvas-size-and-webgl-source?revision=1588345
```

Both report the following identical headers:

```
Connection: keep-alive
Content-Language: en-US
Content-Type: text/html; charset=utf-8
Server: meinheld/1.0.1
Strict-Transport-Security: max-age=63072000
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
```

**Comment by escattone** [comment]
@peterbe @callahad I've been in non-stop meetings today, so am just catching-up with email and saw this. What's strange here is that this URL is triggering the `needs_redirect` case within the `kuma.wiki.decorators.process_document_path` decorator when I can't see any reason to redirect. The `wiki.document` reversal will fail within the `attachment` domains (`mdn.mozillademos.org` and `demos-origin.mdn.mozit.cloud`) since `kuma/wiki/urls_untrusted.py` is loaded rather than `kuma/wiki/urls.py` due to https://github.com/mdn/kuma/blob/34aeef7f85b294c7392d791b4084a28354f8efc2/kuma/core/middleware.py#L330.

**Comment by escattone** [comment]
Ah! The URL's are messed-up! They have the `<locale>/docs` embedded twice, and that triggers the redirect, which in turn triggers the attempt at a URL reversal of `wiki.document`, which should never happen for code sample URL's. For example:

/**en-US/docs**/**en-US/docs**/Web/API/WebGL_API/By_example/Canvas_size_and_WebGL$samples/canvas-size-and-webgl-source

**Comment by callahad** [comment]
Ah, crap. Maybe I broke it here? https://github.com/mdn/kuma/commit/9a89d2dd3377c52ca407f3c56e89cdc2defc649a?diff=split

**Comment by callahad** [comment]
Or potentially here? https://github.com/mdn/kuma/commit/ce6f64fb02860ec1d00044ef682277f7b57a7fa0?diff=unified

I don't think I've done anything else to touch the redirects.

**Comment by escattone** [comment]
> Ah, crap. Maybe I broke it here? [9a89d2d?diff=split](https://github.com/mdn/kuma/commit/9a89d2dd3377c52ca407f3c56e89cdc2defc649a?diff=split)

@callahad Hm, I don't think so. I suspected that at first, but your code changes seem to work great. I'm baffled at the moment as to the origin of those strange **/en-US/docs/en-US/docs/...** URL's

**Comment by callahad** [comment]
Yeah. It does seem to have coincided with the Django 2 deploy...

**Comment by callahad** [comment]
Or maybe not? We have over 2,100 instances of this error at https://sentry.prod.mozaws.net/operations/mdn-prod/issues/7259753, and which was first seen on February 12th.

**Comment by callahad** [comment]
Oh, this is _old_. Here are another 8,100 events for that same URL, first seen back on November 13th, 2019: https://sentry.prod.mozaws.net/operations/mdn-prod/issues/6659001/?query=url:%22https://demos-origin.mdn.mozit.cloud/en-US/docs/en-US/docs/Web/API/WebGL_API/By_example/Canvas_size_and_WebGL$samples/canvas-size-and-webgl-source%22

**Comment by escattone** [comment]
@callahad Hm, I'm currently suspecting that there's a problem with the `EmedLiveSample.ejs` macro or some other macro involved in the creation of code sample URL's.

**Comment by escattone** [comment]
@callahad and I have concluded that this is NOT a new error caused by the upgrade to Django 2.2. My personal suspicion is that there are documents with bad calls to the `EmbedLiveSample` macro which in turn generate bad code sample URL's like **/en-US/docs/en-US/docs**/Web/API/WebGL_API/By_example/Canvas_size_and_WebGL$samples/canvas-size-and-webgl-source.

**Comment by escattone** [comment]
@callahad @peterbe That's it! Here's the offending document: https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext

It makes the following macro call to embed a live code sample:

```javascript
{{EmbedLiveSample("canvas-size-and-webgl-source", 660,180 ,"" , "/en-US/docs/Web/API/WebGL_API/By_example/Canvas_size_and_WebGL")}}
```

but that last argument to the macro is wrong. It should be a document slug, **not** a document path. The call should instead be:

```javascript
{{EmbedLiveSample("canvas-size-and-webgl-source", 660,180 ,"" , "/Web/API/WebGL_API/By_example/Canvas_size_and_WebGL")}}
```

So this confirms that this issue is **not** related to the upgrade to Django 2.2, but is instead an issue of bad content. In fact, it might be due to this single document and its translations.

**Comment by escattone** [comment]
I fixed the English document.

#### Before

<img width="962" alt="image" src="https://user-images.githubusercontent.com/3743693/75835394-a0494500-5d73-11ea-83d0-318315dfebb1.png">

#### After

<img width="915" alt="image" src="https://user-images.githubusercontent.com/3743693/75835421-b6ef9c00-5d73-11ea-9a8a-96ca2378c320.png">

**Comment by escattone** [comment]
Closing since I think this is due to a bad macro call within a single document, which I've fixed.

This consumed my entire working (non-meeting) time today, as well as some of @peterbe's and @callahad's time, but it needed to be understood as it seemed at first that it could have been related to the Django 2.2 upgrade.

**Comment by tobinmori** [comment]
This error has regressed according to Sentry.
