### ISSUE TITLE
Browser Issue with external stylesheet

### ISSUE THREAD

**Issue by Chri-B** [mdn/kuma#6640]
This issue seems to appear only when an external stylesheet with a font-face declaration is dinamically added to the page.
When i try to rescale browser window (only with FIREFOX - screenshot nr.1 is the starting situation), the new window appears like the screenshot nr. 3.
In the screenshot nr.1 you can see the complete code.
If I try the same action without the script link, the issue doesn’t happen.
At first I thought it was a FontAwesome problem (https://github.com/FortAwesome/Font-Awesome/issues/16267) , but it turned out to happen with other external stylesheets as well.

<img width="1340" alt="screenshot_1" src="https://user-images.githubusercontent.com/59871650/76008766-7c6f3600-5f10-11ea-9e68-61c0b6928574.png">
<img width="967" alt="screenshot_2" src="https://user-images.githubusercontent.com/59871650/76008772-7ed19000-5f10-11ea-9846-69877790f47a.png">
<img width="1145" alt="screenshot_3" src="https://user-images.githubusercontent.com/59871650/76008774-809b5380-5f10-11ea-888d-29f498af5462.png">

**Comment by escattone** [comment]
@Chri-B  The issues in this repo are for [MDN Web Docs](https://developer.mozilla.org/en-US/) only. I think the Firefox team is still using https://bugzilla.mozilla.org/home as the place to report Firefox problems, so you may want to repeat this report there. Cheers.
