### ISSUE TITLE
E - Google Auth integration

### ISSUE THREAD

**Issue by jmswisher** [mdn/kuma#6641]
### Overall owner
Kadir
 
### Rationale
Currently people can only log in with a Github account. That was fine when we expected everyone to be a contributor, but now we expect most people to sign up for reasons not related to contributing, so it’s important to lower that barrier, adding Google auth to Github should cover most people.

### Scoring
- [ ]100% People can choose to use their Google account during account creation

**Comment by tobinmori** [comment]
Moving to Kuma.

**Comment by chinikes** [comment]
Hi @atopal - Can this epic be deemed done now? (it shows as 100% on the OkR doc)

**Comment by peterbe** [comment]
Reopen if I'm wrong.
