### ISSUE TITLE
E - Explore Yari 1 Mitigations: Pre-publication moderation 

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#6642]
# Epic | Milestone
As a ..., I want to ..., so I can ...

*Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.*

# Acceptance criteria

- [ ] This is something that can be verified to show that this user story is satisfied.

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by peterbe** [comment]
I think "Pre-publication moderation" is the wrong term. The term we've been using pretty consistently is "review". I.e. "how to review a content change pull request"

**Comment by tobinmori** [comment]
Closing this, as we'll have a new Yari epic for this in a couple sprints with a diff title that will live in the Yari repo.
