### ISSUE TITLE
Can't show correct HTTP Response Code when access https URL through proxy.

### ISSUE THREAD

**Issue by yaozg** [mdn/kuma#6651]
From screen-shot we can find http code is 200, it is connect http proxy response code, but real http code should 302, because this is response has location header. And Chrome developer tool can show the real 302 http code.
![image](https://user-images.githubusercontent.com/13541585/76064256-41c6d580-5fc4-11ea-86cf-6425c598b550.png)

**Comment by atopal** [comment]
Hey @yaozg that looks like a Firefox dev tools issue. This is the MDN repo. Can you file this here please?  https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools
