### ISSUE TITLE
Tidy up contribution amount and support email

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6654]
<img width="1159" alt="Screen Shot 2020-03-06 at 11 58 13 AM" src="https://user-images.githubusercontent.com/26739/76104685-cce2a400-5fa1-11ea-8d6d-ea9eafd0efda.png">

So there are at least 3 open PRs (at the time of writing) that hardcodes the $5 in jinja templates and JS code. 
But also noticed we have `settings.CONTRIBUTION_SUPPORT_EMAIL` but if you grep for `mdn-support` it appears in two templates and one .jsx file. 

If you know you PR is part of this, please mention it so we can set up blocking relationships.

**Comment by schalkneethling** [comment]
https://github.com/mdn/kuma/pull/6633

**Comment by peterbe** [comment]
@schalkneethling I think your subscription banner closed this by accident. I don't understand how. THere's no mention of this issue in the commit message: https://github.com/mdn/kuma/commit/639a3cae91c4119fca3ece9df64b5ecb21e59889

Any idea?

**Comment by schalkneethling** [comment]
> @schalkneethling I think your subscription banner closed this by accident. I don't understand how. THere's no mention of this issue in the commit message: [639a3ca](https://github.com/mdn/kuma/commit/639a3cae91c4119fca3ece9df64b5ecb21e59889)
> 
> Any idea?

Could it somehow be because of this https://github.com/mdn/kuma/issues/6654#issuecomment-596630990

**Comment by schalkneethling** [comment]
Aha! I think the comment referenced above might have caused this to happen(see the right-hand sidebar)

![Screenshot 2020-03-16 at 22 02 50](https://user-images.githubusercontent.com/10350960/76795472-f38ab100-67d1-11ea-9065-437523cf324e.png)

**Comment by peterbe** [comment]
That's a ZenHub thing, no? Bad ZenHub!

**Comment by peterbe** [comment]
One thing to watch out for is that we have people who set up subscriptions BEFORE we launched this version 2 of money intakes. If we hardcode the number too much and one of these people return we might be lying.

**Comment by peterbe** [comment]
Note what @Gregoor did when was in there changing how the Subscription banner worked:
https://github.com/mdn/kuma/commit/3bd820bb04e0f113ae06073b3e4d0b80b5e65e59#diff-31dcf5c77bbb5f6109cb1de27238ed0cR229
We might want to take this as a cue for all other uses of the $5 amount in any of the JS files.
