### ISSUE TITLE
T - Cache Subscription Info: CC Info and Customer Count

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6662]
- locally 1.5s w/o subscription
- 2.5s w/subscription

**Comment by atopal** [comment]
@tobinmori what is this connected to? storing cc info sounds like something we should talk about.

**Comment by tobinmori** [comment]
None of it is highly sensitive data (you could not charge based off of it), but yes, it's a fair point.

**Comment by peterbe** [comment]
What is the point of this? Where are we using it or intend to use it?

**Comment by tobinmori** [comment]
I think @Gregoor had mentioned that the acct settings page was slow due to the StripeAPI call to get payment info. 

We can _not_ pre-optimize unless this seems like a real problem. So not high priority.

**Comment by peterbe** [comment]
There was https://github.com/mdn/kuma/issues/6665 which was about the Edit Profile page which isn't an important page. It'd be a much better idea to move subscription info into the read-only site. Then you can load the SPA from the server and once it's loaded, an XHR request queries the backend for the subscription info and that'll be a pretty decent experience. Much similar to the mugshot/sign in thingy in the nav header.
