### ISSUE TITLE
Intl wrong es-ES and es-AR number format

### ISSUE THREAD

**Issue by SantiagoIlli** [mdn/kuma#6671]
Hi, i found an error using transloco library that in which locale plugin is based on javascript's Intl API.

You can see that issue https://github.com/ngneat/transloco/issues/248 where you can find a link to a stackblitz page with the issue present in an angular enviroment.

Apart from that i made a codepen that shows a minimal reproduction of the error for a more simple demonstration.

Basically the problem is when you want to format a number in a spanish language (i tried with es-AR and es-ES) and that number is less than 10.000 the format doesn't work properly.

**Current behaviour:** 

new Intl.NumberFormat('es-AR').format(1000),  **returns 1000**

**Expected behaviour:** 

new Intl.NumberFormat('es-AR').format(1000),  **returns 1.000**

https://codepen.io/santiagoilli/pen/qBdxVWG

Notice that it has the same behaviour with es-ES, so it could be present in other spanish languages as well.

**Comment by peterbe** [comment]
Is this a bug in both Firefox and Chrome and Safari? Or only in Firefox it might be better to use https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=General

This repo (`mdn/kuma`) is about the source code behind the *website* https://developer.mozilla.org

**Comment by SantiagoIlli** [comment]
I've test it in Firefox and Chrome with the same result, i don't have an apple device to test it in Safari.

In my opinion, it doesn't look like a browser compatibility problem, more likely an algorithm/config issue.

**Comment by peterbe** [comment]
I honestly don't know where you'd drive a change like that. 
[`Intl.NumberFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) is a spec that gets implemented by all the browser vendors in their JavaScript engines. I'm not familiar at all with what `es-AR` is or its history and national standards. 
I really hope you don't give up your fight for overturning that standard. 
But for now, it's not `kuma` thing so we have to close the discussion here.

**Comment by SantiagoIlli** [comment]
Hi! 

I didn't know that it gets implemented by all the browser vendors in their JavaScript, I came from [this page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) by pressing feedback => Report an issue.

es-AR it's the localization for spanish language in Argentina, which has the same standard as es-ES (spanish-Spain).

I don't know where to report it either, i'll keep looking.

Sorry for the misunderstood, and thanks for your time!
