### ISSUE TITLE
Review HTTP error response pages, and add links to HTTP response code docs (Bug 1366376)

### ISSUE THREAD

**Issue by jmswisher** [mdn/kuma#6672]
Migrated from [Bug 1366376](https://bugzilla.mozilla.org/show_bug.cgi?id=13663760); refer there for previous discussion. 

[Michael Liu writes](https://bugzilla.mozilla.org/show_bug.cgi?id=1366376#c8): 

> Hi, I am looking to work on this as my first bug.
> Can I have some help on how to see changes we made to the HTTP error pages (such as 404)?
> If the DEBUG flag is set to True Django does not show the custom 404 page. but when I set the flag to False, Kuma doesn't run in my local machine.

**Comment by liumichael** [comment]
Hi everyone, Michael here, I would love to get some some mentorship/help for my first bug!

**Comment by peterbe** [comment]
@jmswisher 
<img width="744" alt="Screen Shot 2020-03-12 at 11 10 14 AM" src="https://user-images.githubusercontent.com/26739/76535973-19225e00-6452-11ea-8f8b-0f1db5244058.png">

**Comment by liumichael** [comment]
Hi @peterbe, this is the link to the Bugzilla page: https://bugzilla.mozilla.org/show_bug.cgi?id=1366376

**Comment by peterbe** [comment]
@liumichael We currently can't support contribution work unless contributors are somewhat familiar with Django, docker-compose, and JavaScript. For example, we currently don't have a support forum other than GitHub issues but that should be reserved for feature requests and bug reports. Not questions about how to use it. 

But we love contributions nevertheless. Don't give up! Try to spend some time reading the installation instructions and Googling for the errors and eventually try to figure it out. Trust me, it's very rewarding. 
Another thing that would make for a genuinely valuable contribution is if you can try out pull requests, check them out, and help to verify that it works. 

We have other projects under MDN that you can contribute too. Not everything is Django.
