### ISSUE TITLE
Render all pages that call `{{JsSidebar}}`

### ISSUE THREAD

**Issue by wbamberg** [mdn/kuma#6677]
As part of https://github.com/mdn/sprints/issues/2785, we'd like to delete/archive some pages that are currently linked from the JS sidebar implemented by JsSidebar.ejs.

We would prefer for the sidebar to not have broken links, so in preparation we've merged a PR to the JsSidebar.ejs macro to remove those links: https://github.com/mdn/kumascript/pull/1340. This is not currently deployed. After it is deployed and all pages that call it are re-rendered, then the sidebar will not contain any links to the pages we want to retire, and we'll be able to finish https://github.com/mdn/sprints/issues/2785.

**Comment by escattone** [comment]
@wbamberg This is done. After deploying (see https://github.com/mdn/kuma/compare/f0b68ea...6b785e3), I re-rendered 2834 documents across all locales that use the `JsSidebar.ejs` macro in about 15 minutes. There were no errors.
