### ISSUE TITLE
Add subscription reminder to account cancellation message

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6684]
**Summary**
The account cancellation message should remind people that their subscription will be cancelled too.

**Rationale**
Currently this is implicit, and might surprise a small number of people.

**Audience**
Subscribers who cancel their account.

**Proposal**
Currently we have two messages: 
"Deleting your account loses any preferences you have set." and "Deleting your account loses any preferences you have set, as well as makes your username available for others to use."

Please add this sentence after either one of them: "It will also cancel any MDN subscription you might have."

**Comment by peterbe** [comment]
Note! https://github.com/mdn/kuma/pull/6680 will close this issue.
