### ISSUE TITLE
MediaDevices.getUserMedia()

### ISSUE THREAD

**Issue by koy-tome** [mdn/kuma#6686]
This API MediaDevices. GetUserMedia () when recording the desktop, if the lock screen, will lead to screen recording data loss, does not automatically unlock screen after recording.
I tried to catch the exception, and at first there was no error message.Please help me

**Comment by escattone** [comment]
@koy-tome This repo and its issues are for MDN Web Docs only. I suspect you wanted to log this as an issue for the Firefox team instead?
