### ISSUE TITLE
Optimised breadcrumbs for mobile

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#6687]
**Summary**
Optimize breadcrumbs for mobile

**Rationale**
In general, our mobile experience is terrible 😺 One area that can give us a quick win is fixing up our breadcrumbs. Navigating on a mobile device can be tricky in general so, the more we can do to improve the user experience around this the better.

**Audience**
All mobile users on MDN

**Proposal**
In https://github.com/mdn/kuma/issues/6539 research has been done around various aspects of the layout and a solution has been chosen for breadcrumbs.

![Screenshot 2020-03-17 at 12 54 40](https://user-images.githubusercontent.com/10350960/76849712-9bde5b00-684e-11ea-9fac-037a2c563748.png)

https://share.goabstract.com/ef1e325d-f6b5-4059-92e2-01634d792eb8?collectionLayerId=9dd519b3-7698-482e-8213-d5500cc9e3f4&mode=design

**Comment by tobinmori** [comment]
close as dup
