### ISSUE TITLE
Improve header across viewports

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#6689]
**Summary**
Continued improvement of the mobile experience. This issue focuses on the header.

**Rationale**
Currently, the display of the MDN header is pretty broken and as a result, causes a less than ideal user experience for our users.

![Screenshot 2020-03-17 at 13 04 52](https://user-images.githubusercontent.com/10350960/76850389-f4fabe80-684f-11ea-8c28-3c3b62aa1734.png)

**Audience**
All users of MDN using mobile devices or, users on smaller viewports or, those who simply resize their browser window.

**Proposal**
In https://github.com/mdn/kuma/issues/6539#issuecomment-596606776 @malqinneh proposed improved UX options that are ready for further review and implementation.

## Tablet

![Screenshot 2020-03-17 at 13 08 51](https://user-images.githubusercontent.com/10350960/76850695-9550e300-6850-11ea-9522-e474674cd3dc.png)

## Mobile

![Screenshot 2020-03-17 at 13 08 27](https://user-images.githubusercontent.com/10350960/76850700-9b46c400-6850-11ea-88f3-e9d7fb633586.png)

**Additional context**
We should also seriously consider using a consistent interaction model with regards to the main menu. Currently, menu items are expanded on hover on desktop but, on click on mobile.

There really is very little, if any, benefit to having a different interaction model on desktop. The recommendation is, therefore, to always use click to reveal sub menu items.

**Comment by tobinmori** [comment]
closing as dup.
