### ISSUE TITLE
The newsletter signup is too confusing with accounts signup

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6691]
**Summary**

Mustafa found, in his user research, that several people confused the home page newsletter sign up with accounts sign up. That callout box is just not clear at all that it's about signing up for a newsletter. It totally looks like an account sign up thing. 

**Steps To Reproduce (STR)**

Look at the home page and squint a little. 
<img width="997" alt="Screen Shot 2020-03-17 at 7 34 25 AM" src="https://user-images.githubusercontent.com/26739/76852617-1ba20080-6822-11ea-8719-d1727e06026e.png">

Note that it's in the upper right-hand quadrant of the page. 

**Actual behavior**

I thought it was for signing up a user account. 

**Expected behavior**

Be clear and focused.

**Additional context**

Let's be careful not to "abuse" the word SUBSCRIBE because we're using that word for other important things. 

It's not just about the text on the submit button ("Sign up now") but also the whole callout box is confusing. "Learn the best of web development" isn't what that box is about. Maybe eventually you'll learn the best of web development. As an example "Sign up for our newsletter" is more accurate, deliberate, and honest. Or, "Get the latest and greatest from MDN delivered straight to your inbox." is much better too.

**Comment by tobinmori** [comment]
>> "Sign up for our newsletter" is more accurate, deliberate, and honest.

I'd vote for this. To the point and unequivocal.

**Comment by schalkneethling** [comment]
I agree. Mention of this being a newsletter signup needs to be more prominently mentioned in the title of these callouts.

Some ideas:

Main copy: Sign up for our newsletter and learn the best of web development
Main copy: The MDN Newsletter: A wealth of web development news

Button: Subscribe Today

Following the example from mozilla.org

--

## Love Web Development?
Get the MDN Newsletter and receive a wealth of web development resources right in your inbox.

[ Subscribe Today ]

--

Something like that.
