### ISSUE TITLE
T - Subscriptions: server-side GA tracking (phase 1)

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6698]
Description: This is phase 1 (of possibly several) for implementing server-side GA tracking of Subscriptions. A different task will address client-side GA tracking (steps 1-5). 

6. Measure successful subscription on the back-end (web-hook)
`monthly payments | successful subscription | successful-subscription-back-end | 5`
7. Measure cancellations on the back-end 
`monthly payments | cancellation | web-hook`

**Comment by peterbe** [comment]
@tobinmori I put an estimate on it but I think this'll be the 4th instance now where the dollar amount is hardcoded. We need to pay down some tech debt so I'm making this be blocked on #6654

**Comment by peterbe** [comment]
@atopal ...

Regarding (6), perhaps I'm being very dim but all we have is CATEGORY | ACTION | LABEL.
Also, I think it makes much more sense to call it `monthly payments | subscription created | 5.00`
Note the past tense verb instead. And by using a 2 decimal number we're futureproofing ourselves for currency. It might become, someday, that we decide 5 US bucks but that comes out to EUR 4.87. Not sure if it's relevant but it just feels more sustainable.

Regarding (7), it's not possible to distinguish between the cancellation on the web UI vs the Stripe dashboard. Both trigger the exact same Webhook. 
So, for that reason, the event label doesn't really make a whole lot of sense. At least it's accurate in that the tracked event is happening as part of the webhook. 

You OK with that? Also, Yolo and MVP in mind.

**Comment by peterbe** [comment]
Also, the same I said about the Webhook is applicable with the act of successfully creating/setting up/signing up. If you use the MDN UI to sign up, it triggers a webhook. Or, suppose that someone uses the Stripe dashboard to create or re-enable a subscription it all goes through the Webhook eventually. 

Also, remember the context; god forbid our Webhook fails. Stripe will retry the Webhook if, our AWS cluster is experiencing an unlucky mini-downtime. But the worst that can happen is, and it's very unlikely, that we miss a GA event tracking.

**Comment by tobinmori** [comment]
> Regarding (7), it's not possible to distinguish between the cancellation on the web UI vs the Stripe dashboard. Both trigger the exact same Webhook.
> So, for that reason, the event label doesn't really make a whole lot of sense. At least it's accurate in that the tracked event is happening as part of the webhook.

I guess we could add a GA event, server or client side that says that the user self-unsubscribed, if distinguishing between whether the source Stripe Admin or MDN is important. But I'll leave that to @atopal

**Comment by atopal** [comment]
If I remember correctly we had concluded that in both cases it's a web-hook that does the cancellation, so whether we have the label or not doesn't make much difference. That said, I also don't currently care whether they self cancelled or we cancelled or we cancelled for them. I'll get data for the latter from the support team anyway.

**Comment by peterbe** [comment]
Actually, you can cancel in two ways. 

1. The "MDN subscription management" page on the wiki
2. Via Stripe itself but it has to be done on someone's behalf

In both cases, the "canceled" Webhook event fires. 
In the case of you doing it yourself, you get the "cancel information" immediately. 
So, within the webhook, when it comes to us, you *can* distinguish between if it was done, by the likes of MDN Support, or by the user because if they had done it themselves, you could know that it's already canceled in our DB.
