### ISSUE TITLE
T - Link subscription banner to subscription banner page

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6701]
**Summary**
At the moment, even though not enabled from waffle, the subscription banner looks like this:
<img width="1508" alt="Screen Shot 2020-03-19 at 11 01 58 AM" src="https://user-images.githubusercontent.com/26739/77081462-1800ac00-69d1-11ea-9384-c4b202bb1691.png">

Instead, it needs to look like this:
<img width="916" alt="Screen Shot 2020-03-19 at 11 03 13 AM" src="https://user-images.githubusercontent.com/26739/77081614-48484a80-69d1-11ea-89d2-f6b3012597a1.png">

(does [this url work?](https://app.abstract.com/projects/9decc480-70fc-11e9-9453-4f3fbffea7ce/branches/master/commits/a677dc9aa6d0c6ffc7eacc42be29a77ececb0866/files/96E76C7B-2AF8-4473-A39E-E81890F91955/layers/0DBB5D9A-097E-4D1A-A023-B2C6E48C50F3?collectionId=a8383e98-59b4-4b87-9ad0-6c5750e27743&collectionLayerId=5b7238a1-236e-4f65-8218-a0b7a6f953f6))

And that link of the button needs to go to `/$locale/payments/` (note the trailing slash which is necessary for the subscription management page URL to work)

This also means that the subscription banner no longer needs to require that the user is logged in. Only that the waffle flag says it's ok to display.

**Comment by schalkneethling** [comment]
> This also means that the subscription banner no longer needs to require that the user is logged in. Only that the waffle flag says it's ok to display.

I am still not 100% on this part. Unless things have changed that I am not aware of, I am pretty sure this should still be limited to logged-in users only based on the phased roll-out:

1. Staff on edit profile
2. Staff via the banner(points to /payments/) on all pages
3. Logged in user via the banner(points to /payments/) on all pages (percentage limited via waffle flag)
4. All users via the banner(points to /payments/) (percentage limited via waffle flag)

@atopal Thoughts?

**Comment by peterbe** [comment]
Those are all issued embedded *inside* the Waffle and they're in Kadir's domain. The `/$locale/payments/` page isn't forbidden for anonymous users so it'd be possible and safe to link anonymous users there. 

What I'm arguing is that the banner code should need to double-check things when it would be possible to have just 1 source of truth (the waffle flag).

**Comment by atopal** [comment]
@schalkneethling I'm not sure what the question for me is? We have issue #6557 in the sprint. So the banner should be shown to non-logged in users when that story is implemented, but: it should still be behind a waffle flag, because we will not show the banner to _anyone_ before we are actually ready to launch
