### ISSUE TITLE
Improve responsiveness of footer

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#6711]
**Summary**
Improve the responsiveness of footer

**Audience**
All users of MDN across viewports and devices.

**Rationale**
While researching and working on responsive UX improvements to the header and breadcrumbs for MDN, @malqinneh have also suggested some improvements to the footer(https://github.com/mdn/kuma/issues/6539#issuecomment-596801997) of the site.

This cleans up and compliments the improvements to the other two previously mentioned base components, and as such improves the overall UX of all MDN pages.

**Workaround**
N/A

**Proposal**

## Mobile

![Screenshot 2020-03-20 at 10 34 53](https://user-images.githubusercontent.com/10350960/77147753-aee36c00-6a96-11ea-8078-544ce222a9a6.png)

## Tablet

![Screenshot 2020-03-20 at 10 35 13](https://user-images.githubusercontent.com/10350960/77147762-b440b680-6a96-11ea-8506-4cf27365372d.png)

## Desktop

![Screenshot 2020-03-20 at 10 35 32](https://user-images.githubusercontent.com/10350960/77147776-bd318800-6a96-11ea-8f99-514bc28a3c87.png)

**Additional context**
As part of this work, we can also look into the following tangentially related issue: https://github.com/mdn/kuma/issues/6678

**Comment by tobinmori** [comment]
closed as dup
