### ISSUE TITLE
Fullwidth newsletter form on desktop viewport

### ISSUE THREAD

**Issue by B3nnyL** [mdn/kuma#6713]
**Summary**
I notice the newsletter at document pages is fullwidth on both desktop and small viewports, it is inconsistent with white-space wrapped designs which has been adopted by most other components.

**Steps To Reproduce (STR)**

1.  Go to [web component doc page]( https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots)
2. Scroll down to the footer

**Actual behavior**

<img width="1440" alt="Screen Shot 2020-03-21 at 8 59 10 pm" src="https://user-images.githubusercontent.com/13126965/77224364-f4985580-6bb8-11ea-94ec-8d87ddd40142.png">

**Expected behavior**

The newsletter form should be centred wrapped by 20px margin and adopted with responsive width. 

**Additional context**

N/A

**Comment by schalkneethling** [comment]
We have another report here:
https://github.com/mdn/kuma/issues/6716

I am on it.

**Comment by B3nnyL** [comment]
@schalkneethling great 👍
