### ISSUE TITLE
How about using examples that actually WORK?

### ISSUE THREAD

**Issue by robbpage** [mdn/kuma#6714]
**Summary**
Creating examples that actually work and explaining them in a way that actually makes sense and doesn't assume 25 years of experience.

**Audience**
Literally everyone since there are no other websites out there explaining how to do this shit. Every search result just clones your broken examples that don't work..

**Rationale**
Because there are NO good sites out there to teach people how to use this stuff. Literally every single site just duplicates the broken examples on this website.

**Workaround**
I'd wager they aren't. Or they're writing shitty code.

**Proposal**
Yeah, make better tutorials and examples that actually EXPLAIN how this all works instead of assuming that everyone reading it has a fucking clue what you're talking about. Perhaps hire an actual TEACHER to TEACH people...?

**Additional context**
fix it.

**Comment by robbpage** [comment]
yeah way to "help". sigh.

**Comment by escattone** [comment]
@robbpage If you're serious about improving [MDN Web Docs](https://developer.mozilla.org/en-US/), please submit a new issue that does the following:
- Avoids a disrespectful tone (see https://github.com/mdn/kuma/blob/master/CODE_OF_CONDUCT.md).
- Provides a link or links to pages with examples you think are broken.
- Identifies the examples you think are broken and why.
