### ISSUE TITLE
U - /$locale/payments/* pages on the read-only need a whitelist in the CDN

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6721]
**Summary**
Pages like http://localhost.org:8000/en-US/payments and http://localhost.org:8000/en-US/payments/thank-you depend on waffle flags. That means they depend on the cookie. (for the waffle flag)

But if we launch, in production, they'll go behind the CDN which strips all cookies. 
Thus making those pages broken.

**Rationale**
Pages that depend on the `request.user` and be on the `developer.mozilla.org` domain needs to be whitelisted in the CDN.

**Audience**
Everyone browsing the site. 

**Proposal**
Add it to the list of URLs in the CDN that allows cookies into the backend. 

**Additional context**
Cookies or not, we also want to make sure that private/dynamic pages don't get caught in the (CDN) cache. Generally, things don't get caught in the CDN unless it has  "shared cache-control" or "cache-control" set to something beyond `max-age=0`. 

Usually, we use things like `@never_cache` on views that we want to make sure never gets cached by the CDN. 

So, if pages like `/$locale/payments/` and `/$locale/payments/recurring/management/` and `/$local/payments/thank-you` really want to live in the not-wiki, they should all have the `@never_cache` decorator.

**Comment by chinikes** [comment]
@atopal , @peterbe , @tobinmori - Could we possibly ID the acceptance criteria for this user story on the description? Thanks!

**Comment by peterbe** [comment]
> Could we possibly ID the acceptance criteria for this user story on the description? Thanks!

There's nothing more than waiting for https://github.com/mdn/kuma/issues/6722 to be resolved and hit production.

**Comment by escattone** [comment]
FYI, https://github.com/mdn/kuma/issues/6722 is done.
