### ISSUE TITLE
T - Create pass-through Cloudfront behavior for Subscriptions

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6722]
### Summary
We need to create a new pass-through CDN behavior for the family of endpoints under `https://developer.mozilla.org/<locale>/payments/*`, at least temporarily, since some of the endpoints use the `@waffle_flag("subscription")` decorator, which depends on the `sessionid` (to get the user) and `dwf_subscription` cookies. The current default CDN behavior that handles these endpoints strips all incoming cookies from the request (except for the `django_language` cookie) for caching purposes, but a pass-through behavior will pass-through all incoming cookies and block all caching by the CDN. For additional context see https://github.com/mdn/kuma/issues/6721. 

### Acceptance Criteria

- [x] Create and test pass-through behavior for `*/payments/*` for the primary stage CDN
- [x] Create and test pass-through behavior for `*/payments/*` for the primary production CDN
- [x] Create PR that updates the Terraform code for the primary stage and prod CDN's.

**Comment by peterbe** [comment]
How os this different to https://github.com/mdn/kuma/issues/6721 ?

**Comment by escattone** [comment]
> How is this different to #6721 ?

This is the Sprint task that addresses #6721.

**Comment by escattone** [comment]
This is done. The `*/payments/*` pass-through behavior has been added to the stage and prod primary CDN's (and is currently active), and a PR submitted to update the Terraform to reflect the changes (see https://github.com/mdn/infra/pull/387).
