### ISSUE TITLE
Links in untranslated pages don't work at all

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6727]
**Summary**
Go to https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Generator
That page is "perfectly" translated to Portuguese (Brazilian) which is great but imagine a reader thinking "Hmm... Lemme click on Generator.prototype.next() to learn more about that"

They can't. That link is 
```html
<a rel="nofollow" class="new" title="A documentação sobre isto ainda não foi escrita; por favor considere contribuir!"><code>Generator.prototype.next()</code></a>
```

which means it can't be clicked. 

If you hop over to [the wiki for that document](https://wiki.developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Generator) the link is at least clickable. 
When you click that link it takes you to https://wiki.developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Generator/next which is actually the fallback `en-US` but rendered within the Portuguese (Brazilian) chrome. 

**Steps To Reproduce (STR)**
See above. Go to https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Generator

**Actual behavior**
See above in the summary.

**Expected behavior**
The links should work even if it takes you to the `en-US` version. 

**Additional context**

In the ancient tradition of how a Wiki works, to make a new page you first make a link and when you render that it's a thing that takes to create that page which'll make the link work next time. 
This might be a thing for a wiki but it's definitely not helping us on the viewing of documents. 

Somewhere in the Kuma `content` code we're injecting `class="new"` on those links because `{{jsxref("Generator.prototype.next()")}}` figures out that there is no `pt-BR` page for that slug. What it probably ought to do is the second best which is to link to the `en-US` version of that slug.

**Comment by atopal** [comment]
This is a pretty bad regression.

**Comment by tobinmori** [comment]
Q: find out when this regressed?

**Comment by peterbe** [comment]
Here's the culprit: https://github.com/mdn/kuma/commit/e30fb02821a4851ab19d00f67de9129f0c60b565
It happened [4 months ago in this PR](https://github.com/mdn/kuma/pull/6220).

So the complication is that some links *will* 404 if you follow them. But in the case mentioned here in this document, the link to `https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Generator/next` would have actually worked. 
The reason it "works" is because although there is no document with `{'slug': 'Web/JavaScript/Reference/Global_Objects/Generator/next', 'locale': 'pt-BR'}` visiting that page will use the en-US fallback trick (Portuguese chrome but the actual content from `en-US`). 

So when we the page is already `en-US` any `<a class="new" ...` will indeed 404 (unless you're on the Wiki). 
The simple solution is to drop the JavaScript code in `article.jsx` if the page you're on might use `en-US` as fallback.

**Comment by peterbe** [comment]
Ugh! It's uglier than that. With the above-mentioned fix (not doing this removal thing on non-en-US documents) you still can get into trouble. 

This doesn't easily translate to production but my `docker-compose` mysql has wiki content that exhibits the same problems. As a matter of fact, I analyzed random 50 non-en-US documents I have and looked through the first 10 random `a.new` per page. Then for each and every one of those, I check if a click would have actually worked. 
Out of 186 sample clicks, 75% of those `a.new` clicks actually worked. And 25% leads to a 404. 

So what is worse, opening up 75% `a.new` links that ha their `href` attribute removed, or allowing 25% `a.new` links to lead to a 404?

**Comment by peterbe** [comment]
Now I'm understanding the problem even more. And it seems very infected. 

If you're on a non-en-US page, the `new` class will be on any link that doesn't have a matching locale + slug. Here for example:
<img width="551" alt="Screen Shot 2020-03-31 at 8 41 54 AM" src="https://user-images.githubusercontent.com/26739/78027554-8d527200-732b-11ea-88a6-bdbef1261562.png">
The "Exemples avec MathML" link, gets the `new` class on the link. (Just so we're clear, that gets done in the Python-land after KumaScript rendering and is what gets saved as `rendered_html`) But you can click on it and what happens is this: 
<img width="776" alt="Screen Shot 2020-03-31 at 8 45 19 AM" src="https://user-images.githubusercontent.com/26739/78027807-fafe9e00-732b-11ea-98af-cdb23c3e0d31.png">

What you're seeing is the French chrome but with the en-US content. So it did work, but you did slip into a page that wasn't French. So the redness of the link could, at best, be a warning that you're going to be leaving the comfort of French. 
On the Wiki is almost exactly the same. Except on the Wiki you get that "nice" warning that the page you're reading had to fall back on en-US:
<img width="748" alt="Screen Shot 2020-03-31 at 8 47 32 AM" src="https://user-images.githubusercontent.com/26739/78028435-07cfc180-732d-11ea-81db-f8d2bb3d5702.png">

**Comment by peterbe** [comment]
In fact, I dug a little deeper into my analysis. A lot of those 25% of bad links are caused by sidebars and pages that are horribly outdated and considered archive. 

This time, I took a random 100 non-en-US docs from Prod and re-ran the analysis but ignoring sidebars and indicator boxes. Now the numbers are looking much better. 
89% of `a.new` links would have worked if you let them work. So only 11% of `a.new` links that would lead to a 404. That's about 11% more than 0% which is what we have at the moment.
