### ISSUE TITLE
U - Assign unique subscriber number for users that become monthly subscribers

### ISSUE THREAD

**Issue by malqinneh** [mdn/kuma#6732]
# User story
As a monthly subscriber, I want a unique subscriber number, so I can feel good about supporting MDN

# Design
- [Abstract mock-up of FAQ page(s) for logged in users](https://share.goabstract.com/c29c59d2-0ecb-4428-bcd9-7ce8e1d45047?mode=design) 
- [Abstract mock-up of FAQ page(s) for non logged in users](https://share.goabstract.com/c29c59d2-0ecb-4428-bcd9-7ce8e1d45047?collectionLayerId=bea04b2e-4edf-4de5-ba89-bbf5e0f5c409&mode=design) 
- [Abstract mock-up of FAQ page(s) for non registered users](https://share.goabstract.com/c29c59d2-0ecb-4428-bcd9-7ce8e1d45047?collectionLayerId=444f363a-ec1c-4e91-ba23-5a1175cab818&mode=design) 
- [Abstract collection for Account Settings](https://share.goabstract.com/6cd3285f-90ca-42fa-b641-f3c7d742dd65)

# Acceptance criteria

- [x] As a user considering to subscribe monthly, I can see the unique subscriber number on the [FAQ page] and [account settings] that I will become if I sign up
- [x] As a user that subscribed monthly, I can see my unique subscriber number on the [Thank You page] and my [account settings]

**Comment by peterbe** [comment]
@atopal I suppose the next step is if you to verify and close this. I can't think of anything else that needs to be done now.

**Comment by atopal** [comment]
@peterbe it has to be on staging or production for me to test this, or someone needs to give me a demo. As it is, I can't verify this.
