### ISSUE TITLE
Merge 'subscription' and 'subscription_banner' waffle flags ?

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6738]
**Summary**
We're currently distinguishing between the presence of the Subscription banner and the presence of the Stripe integration (on the Edit Profile page) with two distinct different waffle flags; `subscription` and `subscription_banner`. 

We can't easily write a DB migration that merges them so we'd have to decide which one is best (in the prod DB) and make that the only one used by the business logic in code (e.g. `active-banners.jsx`). And a DB migration ought to delete the one we don't keep. I suggest we delete the `subscription_banner` one.

**Rationale**
Fewer moving parts. Less risk of confusion. Both for dev and for product management. 

The whoami endpoint is slowed down (marginally) for every waffle flag we have to consider. It's not a problem today but not having an eye on the future is not sustainable. 

**Audience**
Devs and PM. 

**Proposal**
Make the `active-banners.jsx` code NOT depend on `userData.waffle.flags.subscription_banner` but on `userData.waffle.flags.subscription` instead.

**Additional context**

**If we do this we will no longer be able to toggle the banner off but have the subscription feature going on.** But generally, waffle flags are supposed to be for soft rollouts. If we decide we don't want something we use git to remove the code.

**Comment by peterbe** [comment]
Note-to-us: We can't act on this yet because the new Stripe integration on the Subscription landing page relies on `subscription_banner`. It's a hack but it makes sense.

**Comment by atopal** [comment]
Hmm, I like the flexibility this provides, but if devs feel strongly about having only one toggle I'd reconsider.

**Comment by tobinmori** [comment]
Note: @atopal need a (3rd) waffle flag to show the banner only on the landing page.
