### ISSUE TITLE
T - Update copy on text email receipt and add receipt attachment. 

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6743]
https://docs.google.com/document/d/1Gx-2cniZlWTPhsbYBNJj7n36lmnvPZ-vNEFOoAA5ksQ/edit?usp=sharing

**Comment by Gregoor** [comment]
@atopal just to be certain that I'm not doing the wrong thing. The title of the issue only asks for copy changes but the gdoc suggests that I should turn the receipt from a link to an attachment. Is the latter wanted as well for this?

**Comment by atopal** [comment]
Yeah, that was not part of the conversation. adding @malqinneh.

@Gregoor can you say how much that would increase the level of effort involved? If it goes beyond 2 points, I'd say let's use the link for this iteration, even if it looks pretty terrible, because it's so long.

**Comment by Gregoor** [comment]
@atopal I was hoping for precedence in the codebase but since there isn't and the mailer code isn't super extendable, I'd say this would double the effort.

**Comment by atopal** [comment]
We'd use this even after going HTML with emails, so I think it's okay to make that investment now. That said, if it becomes larger than a 2 pointer, let's discuss again. Thanks for checking, Gregor!

**Comment by malqinneh** [comment]
@Gregoor my initial understanding was that the receipt is already an attachment. If it's only available as a link, I think it would be OK to keep it as is (link). Thanks!

**Comment by tobinmori** [comment]
@atopal @malqinneh I've told @Gregoor to go with the attachment if it's doable in 2 days or less. If not we can just use a link and add the attachment later when we revisit the HTML version of this later on.

**Comment by atopal** [comment]
Sounds good to me 👍
