### ISSUE TITLE
MS Edge changed their logo

### ISSUE THREAD

**Issue by VFDan** [mdn/kuma#6744]
Microsoft Edge has changed their logo. It is now 
![image](https://user-images.githubusercontent.com/44413950/77587966-4e519600-6ebf-11ea-8cad-a1fc5087c6b3.png)

However, the MDN logo for it hasn't updated.  It still shows 
![image](https://user-images.githubusercontent.com/44413950/77588076-835de880-6ebf-11ea-829d-9294fe5dc942.png)

**Comment by peterbe** [comment]
Whatever we do with this, we need to make sure we're equally implementing it on the `stumptow-renderer` fork of the BCD table.

**Comment by schalkneethling** [comment]
I propose the following version of the logo for use in BCD. Thoughts?

![edge](https://user-images.githubusercontent.com/10350960/77977588-63378a80-7300-11ea-97a2-48d10aee1eb2.png)

**Comment by malqinneh** [comment]
Think that is better suited Schalk. Is this published by Microsoft in their brand guidelines?

**Comment by schalkneethling** [comment]
> Think that is better suited Schalk. Is this published by Microsoft in their brand guidelines?

I cannot find it in their brand guidelines so I made it in Illustrator :)

**Comment by malqinneh** [comment]
Thank you for clarifying Schalk. My recommendation would be to wait until we can get confirmation from someone at Microsoft on a BW variation for us to use. Or is there a reason that would not work?

**Comment by schalkneethling** [comment]
> Thank you for clarifying Schalk. My recommendation would be to wait until we can get confirmation from someone at Microsoft on a BW variation for us to use. Or is there a reason that would not work?

I do not _think_ we have to. None of the existing ones are directly from the various vendors. @atopal Thoughts? Is there someone we can reach out to via the PAB perhaps?

**Comment by VFDan** [comment]
@schalkneethling Seems like a good version, and it fits the color scheme

**Comment by atopal** [comment]
Honestly, I'm not sure why were using the black and white versions, what's the upside compared to using the originals? That said, yes, I'm okay with it.

**Comment by malqinneh** [comment]
> Honestly, I'm not sure why were using the black and white versions, what's the upside compared to using the originals? That said, yes, I'm okay with it.

Not 100% sure but would assume the designer thought it looked better as it is more uniform with the text. Having said that, my main concern would be that MDN is breaking brand guidelines for orgs that did not specify a B&W application of their logo (yet).

**Comment by kypflug** [comment]
Below is the official black & white variation of the Edge logo, which you can use for applications like this. Will that work?
![EdgeAppList targetsize-256_altform-unplated_contrast-white](https://user-images.githubusercontent.com/8116680/78160962-93af1f80-73f9-11ea-8282-9adcbe365aaf.png)

**Comment by atopal** [comment]
Great! Thanks @kypflug

**Comment by schalkneethling** [comment]
I believe there are a couple of reasons:

1. Not having all the various colors makes the already busy interface less distracting
2. Smaller file size per icon as the overall SVG is much simpler
3. Displays better at small sizes

Should we park this one for the moment or proceed with the proposed logo?

**Comment by schalkneethling** [comment]
And as I comment I see we have the official logo. Thanks, @kypflug

**Comment by malqinneh** [comment]
> Will that work?

Thank you!

**Comment by schalkneethling** [comment]
Added Mindy as reviewer
