### ISSUE TITLE
GA instrumentation on clicking "Sign in" doesn't make sense any more

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6747]
**Summary**
In https://github.com/mdn/kuma/commit/865deab60d6a97966e13eff6f1bbf492e1631afe 
https://github.com/mdn/kuma/pull/6252 we re-enabled the same GA instrumentation we used to have on the Wiki onto the read-only site. 
Later we enabled multi-auth. Now, clicking "Sign in" doesn't means you're going to GitHub immediately. No, now it's a modal that appears and the user has to make a choice. 

**Steps To Reproduce (STR)**
Go to http://localhost.org:8000/en-US/ with some GA debugging in web console. 
Press "Sign in" and notice that it sends
```
Running command: ga("send", {hitType: "event", eventCategory: "Authentication", eventAction: "Started sign-in", eventLabel: "GitHub"})
```

Granted, we might someday have an instrumentation event for people who click to see the modal but never follow through. 

**Additional context**

I can't `git revert` [the commit](https://github.com/mdn/kuma/commit/865deab60d6a97966e13eff6f1bbf492e1631afe) because it does so much more.

**Comment by peterbe** [comment]
CC @atopal if you're wondering about those events.

**Comment by atopal** [comment]
Peter, I wish you hadn't removed this. Can you turn it on again and just remove the "github" label? I know the meaning has changed slightly, but this is a metric we have been collecting since before 2015. It's a simple way to see the impact of our design decisions, and I don't think there are any side effects, are there?

**Comment by peterbe** [comment]
The side effect is that I needed that `onclick` for triggering the modal. That way I can use the modal not only in the header but also on the Subscription landing page. So it was in the way. I'll see if I can combine the two.

**Comment by atopal** [comment]
Ah, alright. Thanks Peter!

**Comment by atopal** [comment]
If it's not possible, let me know, we may sacrifice this then.

**Comment by peterbe** [comment]
> If it's not possible, let me know, we may sacrifice this then.

It's possible. I just [made a function](https://github.com/mdn/kuma/pull/6795/files#diff-ad95ab66b0d421a930f76e10485e2418R109) that calls one function at a time. Hopefully, it'll work. 
I'd rather we don't have to do this considering that the old code that got left behind was for something entirely different which is no longer the case. Problem is that I just moved too quickly.
