### ISSUE TITLE
SystemError: <method 'get' of 'dict' objects> returned a result with an error set

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6754]
https://sentry.prod.mozaws.net/operations/mdn-prod/issues/6659909/

```
timeout: timeout
SystemError: <method 'get' of 'dict' objects> returned a result with an error set
  File "meinheld/mlogging.py", line 187, in _access
    'h': environ.get('REMOTE_ADDR', '-'),

SystemError: <method 'get' of 'dict' objects> returned a result with an error set
```

Low priority: 12x in 2yrs, but might worth looking into with spare time.

**Comment by peterbe** [comment]
Steps to *maybe* reproduce: Open http://wiki.localhost.org:8000/en-US/docs/get-documents?term=a
The SQL query is actually not too bad but the response is just WAY to large. That URL above creates a JSON response, on my local docker-compose, that is 4.3MB large.

**Comment by peterbe** [comment]
It's actually somewhat important because triggering that will consume such a large payload that it takes up that whole Python process for a long time. 

A simple solution would be to add some basic pagination. I.e. only the first 100 documents.

**Comment by peterbe** [comment]
Actually, `/$locale/docs/get-documents` is not used anywhere. 
I think we should just delete it. Or at least break it and see who screams.

**Comment by peterbe** [comment]
@a2sheppy Do you know if this is used anywhere?

**Comment by peterbe** [comment]
Actually! I was wrong. It is used in wiki-move.js and wiki-edit.js
So I think the next right thing to do is to use pagination. E.g. only return top 100 matches.
