### ISSUE TITLE
Firefox 74.0 (64-bit) leaking memory

### ISSUE THREAD

**Issue by ebonsi** [mdn/kuma#6764]
Hi, I have been observing Firefox and FirefoxCP Web Content processor Memory going up and as high as 1.2 Gb altering overall system perform. Mac OS Catalina, 10.15.3. At times when I am logged to Facebook, I can see several processors open, each one taking from 119 MB, others 442 MB, 475 MB, and 787.5 MB. That can add up to 1.8 GB.
![Screen Shot 2020-03-29 at 4 48 06 PM](https://user-images.githubusercontent.com/889908/77865048-2d4fb480-71e1-11ea-8ad7-6982470fe050.png)
This last image is just an example shot of the last group of processors.
Welcome to comment on the issue. Thanks!

**Comment by escattone** [comment]
@ebonsi Thanks for your report, but this repo and its issues are for MDN Web Docs (https://developer.mozilla.org/en-US/) only. To submit a bug report for Firefox, use https://bugzilla.mozilla.org/home or https://support.mozilla.org/en-US/products/firefox.
