### ISSUE TITLE
3 separate waffle flags for subscriptions

### ISSUE THREAD

**Issue by Gregoor** [mdn/kuma#6782]
* Have 3 different waffle flags.
  * One for the display of the banner (let's call/keep calling this `subscription_banner`)
  * One for the fundamentals such as Subscription management and `api.v1.views.create_subscription` (let's keep call this `subscription`)
  * One for the form being on the Subscription landing page (let's call this `subscription_form`)

_Originally posted by @peterbe in https://github.com/mdn/kuma/pull/6756_

___

There's also some cross-dependency between those issues, i.e. 1) and 3) require 2) to be on. So maybe we can also enforce that somehow?

**Comment by peterbe** [comment]
You beat me! [Mine](https://github.com/mdn/kuma/issues/6783) came in minutes after yours. 
May I be so bold as to say my issue description has more useful information? I.e. can we close this in favor of https://github.com/mdn/kuma/issues/6783

**Comment by Gregoor** [comment]
Yours is so much better, I'll fold
