### ISSUE TITLE
T - Implement 3 waffle flags to improve control of subscription rollout

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6783]
**Audience**
Devs and a fraction of staff users who have seen the Subscription form at the bottom of the Edit Profile page. 

**Proposal**

Have 3 feature flags. Make a slight distinction between getting new subscribers and existing subscribers. 

1. One feature flag for the fundamentals. E.g. the subscription management page, the ability to cancel. Let's call this `subscription`.
2. One feature flag for the presence of the Subscription banner. Let's call/keep calling this `subscription_banner`. 
3. One feature flag for the subscription form. I.e. the `<SubscriptionForm/>` React component inclusion inside the `<Payments/>` component. Let's call this `subscription_form`.

That way, we can control the "flood gates" with waffle flags but not accidentally get snagged in a catch-22 for people who are already in. 

**Additional context**

I don't know which issue to link to that tells about what should happen to people who are subscribers and return to MDN. As it stands, their only hope is to sign back in and use the signed-in drop-down to go to the Edit Profile page. 
An easy remedy to all of this is to leverage the fact that we know if a user is a subscriber in `<Login/>` and use that to make a link to the Subscription landing page. Once that loads, it should a link to the Subscription management page on the Wiki.

**Comment by tobinmori** [comment]
@tobinmori - sep out user stories (1) flag issue p1, next sprint. (2) refactor stripe to not break DRY

**Comment by peterbe** [comment]
The question is; what should happen to the Subscription landing page if the `subscription_form` is not on for the user? Because this is what happens:
<img width="1589" alt="Screen Shot 2020-04-09 at 4 23 39 PM" src="https://user-images.githubusercontent.com/26739/78937438-8095f280-7a7e-11ea-9e9a-13fc14530687.png">


I.e. the `subscription_banner` was on but this is what I see when I go to the Subscription landing page. 

My immediate reaction is that we drop the "You will be MDN member number: ..." and drop the "Support MDN with a $5 monthly subscription ..."

What do you think @mindy ?

**Comment by peterbe** [comment]
Another question is; What should we do on the subscription form at the bottom of the Edit Profile page? At the moment it's based on the `subscription` banner but that actually wraps two possible outcomes: A) you already had a subscription, B) show the form. 

My inclination is to go deeper into that and make it so that if you *don't* already have a subscription, you don't get the form at all if `subscription_form` is off.

**Comment by tobinmori** [comment]
cc: @malqinneh @atopal

**Comment by mindy** [comment]
> My immediate reaction is that we drop the "You will be MDN member number: ..." and drop the "Support MDN with a $5 monthly subscription ..."

I agree-- I think we should drop those two lines and add some sort of "coming soon" text.

**Comment by atopal** [comment]
> Another question is; What should we do on the subscription form at the bottom of the Edit Profile page? At the moment it's based on the `subscription` banner but that actually wraps two possible outcomes: A) you already had a subscription, B) show the form.
> 
> My inclination is to go deeper into that and make it so that if you _don't_ already have a subscription, you don't get the form at all if `subscription_form` is off.

Yeah, that sounds right to me.
