### ISSUE TITLE
U - Optimize Table of Contents for mobile

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#6785]
# User Story 
As a user, I want an optimize Table of Contents for mobile so that I can have a better experience using MDN on mobile.

# Design 
- [Mobile](https://share.goabstract.com/ef1e325d-f6b5-4059-92e2-01634d792eb8?collectionLayerId=d48ca7c1-8744-462f-a2bd-1ab2b4e45516&mode=design)
![TOC - Mobile - Light](https://user-images.githubusercontent.com/4819906/79573577-dffe8e80-808c-11ea-8848-44ae5ba2e00b.png)

- [Tablet](https://share.goabstract.com/ef1e325d-f6b5-4059-92e2-01634d792eb8?collectionLayerId=05e15d17-45dc-4db2-807d-a98fbe9eb1f3&mode=design)
![TOC - Tablet - Light](https://user-images.githubusercontent.com/4819906/79573587-e260e880-808c-11ea-8267-81d82750c8d1.png)

- [Desktop](https://share.goabstract.com/ef1e325d-f6b5-4059-92e2-01634d792eb8?mode=design)
![TOC - Desktop - Light](https://user-images.githubusercontent.com/4819906/79573594-e42aac00-808c-11ea-974a-f48d7c9a29e9.png)

# Acceptance Criteria 
- [ ] Essential: New responsive table of contents implemented on mobile (only)
- [ ] Non-essential: new responsive table of contents implemented on desktop, tablet
- [ ] [Instrumentation](https://docs.google.com/spreadsheets/d/1plvnK5gBcrpmSwVwaVMFVvPK8ihrDL4LzObhZOtlj2Y/edit?usp=sharing) on [tap] events for table of contents (if applicable events exist on desktop)

**Comment by atopal** [comment]
@malqinneh can you attach the design here and what you consider essential in terms of acceptance criteria?

**Comment by schalkneethling** [comment]
Looking at this again now I want to be sure I am clear on the desktop version.

Currently, on desktop, the TOC looks as follows:

![Screenshot 2020-04-20 at 08 43 28](https://user-images.githubusercontent.com/10350960/79721759-3402b080-82e3-11ea-8369-166f14b0af7d.png)

Am I understanding correctly that we are changing it to the following?

![Screenshot 2020-04-20 at 08 43 28](https://user-images.githubusercontent.com/10350960/79721914-71673e00-82e3-11ea-8dd5-6f41a29cfd55.png)

@malqinneh @atopal

**Comment by malqinneh** [comment]
Thanks for clarifying @schalkneethling!

For now, the desktop UI should be left as is.
