### ISSUE TITLE
U - Implement optimized sidebar for mobile

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#6786]
# User Story 
As a user, I want to access the content sidebar on mobile in a user-friendly way.

# Design 
![79898688-ace43400-83d9-11ea-91c0-13c9ffddd816](https://user-images.githubusercontent.com/4819906/79986269-c6d55380-8479-11ea-9751-38b8fe044acb.jpg)

# Acceptance Criteria 
- [ ] Add [Related topics] hyperlink to the bottom of the [Table of contents] on tablet and mobile resolutions
- [x] UI for sidebar on desktop, tablet, and mobile is added in MDN's Design System file
- [x] Screenshots are provided in this user-story

**Comment by tobinmori** [comment]
**Notes:**

**Google Search Console:**
https://search.google.com/search-console/speed/summary?resource_id=https%3A%2F%2Fdeveloper.mozilla.org%2F&device=2&hl=en

**Speedcurve:**
https://speedcurve.com/mozilla-add-ons/mdn/favorite/?cs=lg&d=7&db=17534&dc=1&de=1&ds=1
in 'options' you can emulate a older phone, like Nexus6 and see that it performs significantly slower. 

**Page for testing**
Array.prototype.forEach() is the recommended page for testing.

Simulate a slow CPU on mobile.

**Comment by malqinneh** [comment]
https://github.com/mdn/kuma/issues/6833#issuecomment-616735342

Added thoughts regarding the sidebar in the design task. 

Recommendation moving forward is to add a link at the bottom of the table of contents section (on tablet/mobile) to take user down to the Related topics section located near the bottom of the page:

![79787339-d5562a80-8314-11ea-8adf-5087e393b3ed](https://user-images.githubusercontent.com/4819906/79898688-ace43400-83d9-11ea-91c0-13c9ffddd816.jpg)

**Comment by chinikes** [comment]
@atopal, @schalkneethling - With all tasks closed, can you verify this story's ACs are met? Can we mark done?

**Comment by atopal** [comment]
yes, confirmed
