### ISSUE TITLE
Subscription landing page can't server-side render

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6790]
**Summary**
Every time you view `/$locale/payments/` it fails to SSR render. 
In `docker-compose` you get this:
```
ssr_1            | POST /ssr/SPA 500 905 - 0.873 ms
ssr_1            | ReferenceError: window is not defined
ssr_1            |     at Ut (/app/kuma/javascript/dist/ssr.js:22:78505)
ssr_1            |     at a (/app/kuma/javascript/dist/ssr.js:22:11084)
ssr_1            |     at Ee (/app/kuma/javascript/dist/ssr.js:22:12102)
ssr_1            |     at e.t.render (/app/kuma/javascript/dist/ssr.js:22:14623)
ssr_1            |     at e.t.read (/app/kuma/javascript/dist/ssr.js:22:14199)
ssr_1            |     at renderToString (/app/kuma/javascript/dist/ssr.js:22:19799)
ssr_1            |     at cn (/app/kuma/javascript/dist/ssr.js:22:94699)
ssr_1            |     at /app/kuma/javascript/ssr-server.js:88:14
ssr_1            |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
ssr_1            |     at next (/app/node_modules/express/lib/router/route.js:137:13)
```

That's because [we accidentally introduced `window` in a non-useEffect](https://github.com/mdn/kuma/pull/6717/files#diff-a4b421470301b7b476090ffe3b905e2fR25)
That PR did't even notice. @mindy and I added that late but didn't notice that it broke SSR rendering :(

Shame on us for not noticing. Double-shame on us for not having test automation notice. 

**Steps To Reproduce (STR)**
Well, we need a Django "unit test" that renders the thank you page and makes sure the value of `settings.CONTRIBUTION_SUPPORT_EMAIL` is in the rendered HTML. 

Open `view-source:http://localhost.org:8000/en-US/payments/` and notice that none of the HTML there matches the DOM. 

**Actual behavior**
When an error happens in SSR, it annoyingly subtly falls back on client-side rendering if ssr rendering fails for any reason. So no hydration and the page would look totally different with or without JS. Because the rendering is usually so fast you often don't notice. 

**Expected behavior**
SSR should work. If you need a piece of data from Django, into the React code, you don't use `includes/config.html` because that relies on `window` (which isn't a thing in SSR). You can only use that for things that only happen in client-side (for the example the presence of the `SubscriptionForm` component which depends on `whoami`)

**Additional context**

The mistake was human. It sucks the way Kuma does SSR. The real problem is that we didn't catch it with test automation.

**Comment by peterbe** [comment]
@mindy We need to fix this. I have a branch started that I think will solve it. Be prepared to do a review soon.

**Comment by mindy** [comment]
Thanks for catching and writing this up-- let me know if I can help. I will take a look at it too.

**Comment by peterbe** [comment]
Fixed by https://github.com/mdn/kuma/commit/7a33bac811c48cc4e451babe2357b4345edc82c2
