### ISSUE TITLE
Баг или нет ?

### ISSUE THREAD

**Issue by jsBong01** [mdn/kuma#6791]
Здравствуйте, простите что пишу по Русски .
Я заметил одну странность при программирование на языке javaScript .
Это касается оператора присваивания -=.
Можете проверить и дать мне ответ баг это или все нормально ? 
Заметил я это используя код :
x = "3" // можно использовать любое число в строке 
y = "2"
x -= y;
На сколько я знаю в "пишется строка" которая не читается как число.
Но данный оператор делает вычисления.
Позже, когда я писал данное сообщение я попробовал это провести и с оператором - и он также провел вычисления.
Прошу прощения, я только начал обучать JS и это мой первый язык.
Изучаю я его на сайте Mozilla и там было сказано что если задать значение в "значение" то оно будет восприниматься как строка, почему тогда я задаю "значение числом в скобках" и оно проводит вычисления ?
Спасибо если найдете время на мое письмо и сможете его прочитать .

**Comment by jsBong01** [comment]
Можете ответить на Английском, я переведу.
Если что то переводит не корректно или я не ясно выразился я могу попробовать объяснить подробнее.

**Comment by peterbe** [comment]
Would you mind trying to write that in English?
