### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by warsambin** [mdn/kuma#6794]
**Summary**
_What is the problem?_

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

see attachment
<img width="1154" alt="Screenshot 2020-04-02 at 14 05 20" src="https://user-images.githubusercontent.com/50590369/78242754-427f5880-74eb-11ea-904c-0892eafe9903.png">

**Comment by warsambin** [comment]
Chrome Version 80.0.3987.149 (Official Build) (64-bit)
MacOS 10.15.3, 
MacBook Pro

**Comment by chrisdavidmills** [comment]
Thanks for reporting. This is a known problem.

@tobinmori, are you collecting these anywhere, or should we close this as a dupe?

**Comment by tobinmori** [comment]
Thanks @chrisdavidmills. Yes, we're tracking this one in another issue, so I'll close this.
