### ISSUE TITLE
Colors for Browser compatibility tables

### ISSUE THREAD

**Issue by pgblu** [mdn/kuma#6804]
**Summary**
The color scheme of Browser Compatibility tables is quite unfriendly to the eye, perhaps prohibitively so for some users. A stronger color contrast between 'Full Support', 'Compatibility unknown', and the background color would be helpful. See for example https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet#Browser_compatibility

**Rationale**
The tables would be easier to read if the color contrast was stronger. See https://webaim.org/resources/contrastchecker/ for more information

**Audience**
This would benefit anyone with difficulty seeing color contrasts

**Proposal**
I'd propose the following colors, but this is just an example!
supported: #2DEE66
unknown: #EE6DFF
background: #57AAAA

**Additional context**
_Is there anything else we should know?_

**Comment by atopal** [comment]
Hey there, we intend to redesign the tables at some point, because they have some very fundamental UX issues, so we're limiting changes for now.

**Comment by WebMechanic** [comment]
I agree with the "more contrast" but maybe less saturated as suggested :-)
Depending on the viewing angle these pastels are hard to catch.
Chewing gum scheme or not, maybe drop (hsl) saturation ~ 60-65% and lightness from 92% to ~ 72-75% would already be helpful.
