### ISSUE TITLE
T - Fix post-sign-ins redirect so that user lands on correct page

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6805]
**Summary**
You're not taken back to where you were when you sign in. At least via the modal and GitHub.

![Screen-Recording-2020-04-03-at-2 31 33-PM](https://user-images.githubusercontent.com/26739/78393569-167dd900-75b8-11ea-9d78-3bf0ca358bb2.gif)

**Steps To Reproduce (STR)**

1. Go to some page other than the home page. Be not-signed in.
2. Click sign in. 
3. Click GitHub and complete your GitHub auth stuff

**Actual behavior**
I ended up back on the home page `/en-US/`. :(

**Expected behavior**
To be taken to the page I was originally on. 

**Additional context**
Pretty sure this is regression but don't know if it started when we switched to a modal.

**Comment by chinikes** [comment]
Hi @peterbe , @tobinmori - What user story is still task implementing?

**Comment by tobinmori** [comment]
@peterbe can we make sure this redirect works for both flows?

- existing user sign in
- user creation, then sign in
