### ISSUE TITLE
Clean away api.v1.views.get_user

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6808]
(We chatted about this on email, so I'm just going to paste that in here)

Ryan added this Nov 15, 2019 and I think it was pre-emptively to suppose some sort of
SPA during the sign up process. I.e. client-side validation of the username you prefer
https://github.com/mdn/kuma/commit/144d8ab40213ec4bbf36c7c940f1d2bf9c54b909

I'm pretty confident we're NOT using it. The sign-up does that username checking based on
allauth.socialaccount.forms.SignupForm which we use here https://github.com/mdn/kuma/blob/20670f94b95b5dfad52165c2483e283f7d7375e5/kuma/users/signup.py

Also, I know all these pieces of data are all available by simply going to
https://wiki.developer.mozilla.org/en-US/profiles/$username
and scrape the HTML.
But given that we have no use for it and when we go to Yari 2, we'll need a new sign up form, we might still not need this because we might just do the same thing there; that you pick a username and HTTP POST submit and if it works it worked.

So any objections to me deleting it?

**Comment by escattone** [comment]
I can't even remember why I add that, so I say dump it! Thanks @peterbe.
