### ISSUE TITLE
Console infinite says "eval code line 1"

### ISSUE THREAD

**Issue by olezhkafp** [mdn/kuma#6811]
If I open firefox console (F12) all console log is cleared and I see every time 2 messages:
> console was cleared ... eval code line 1 > Function:3:1190
> <img> ... eval code line 1 > Function:3:1153

It is refreshed every time, first line is always visible second one updates every 1s (or even ofer)

Screen: [http://prntscr.com/rtzpo1](http://prntscr.com/rtzpo1)

OS: Windows 10 (x64)
Firfox latest version: 74.0.1 (x64)

It happened few days ago, and even after update I still see this issue

**Comment by peterbe** [comment]
@olezhkafp What URL is this happening on?
