### ISSUE TITLE
U - Implement mobile-optimized header.

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6816]
See User Story issue for comps and description: #6784.

# Acceptance Criteria 
- [x] New responsive header implemented on desktop, tablet, mobile
- [x] Instrumentation on [tap] events - desktop instrumentation is on [hover] events, need to make sure we register the same events for [tap]

**Comment by chinikes** [comment]
@atopal - With all tasks completed, can you review and verify your ACs have been met, and this story can be marked done. 
cc: @schalkneethling , @malqinneh , @mindy

**Comment by atopal** [comment]
Let's fix #7146 before we call this done.
