### ISSUE TITLE
T - Investigate how to implement live samples (EmbedLiveSample macro)

### ISSUE THREAD

**Issue by escattone** [mdn/kuma#6819]
### Summary
Explore solutions for handling live code samples (executable examples comprising JS, CSS, and HTML embedded within the document, and constructed using the the `EmbedLiveSample` macro within the same document) in Yari1, and select the most promising one. This could be challenging.

### Acceptance Criteria
- [x] Document, within this issue, the details of the selected approach for handling the `EmbedLiveSample` macro in Yari1.

**Comment by tobinmori** [comment]
@escattone  @tobinmori - make sure we check in with @atopal if we can think of ways to reduce scope / think of alternate ways to implement.

**Comment by escattone** [comment]
### Summary
After detailed investigation into the current approach we're using to handle live samples in Kuma/Kumascript, we've (thanks as well to @tobinmori for his help) arrived at a solution for the GitHub/JAMStack world of Yari. The good news is that it's relatively simple and the tasks involved very well understood.

### Approach
The overall approach will remain the same as Kuma, in the sense that we'll serve live sample pages via HTTP so they can be used within `iframe`'s, CodePen and JSFiddle, and also via the same URL's (e.g., `/<locale>/docs/<document-slug>$sample/<sample-id>`, with the exception that in our case we're **not** using the `?revision=<current-document-revision-id>` query parameter, which is only used to avoid stale caching). What will be different is that we're going to used the JAMStack approach, or in other words, each live-sample page will be pre-built like all of the other document pages, and served locally for development/preview purposes (via `http://localhost:3000`) and via a CDN backed by S3 for production/stage/review purposes.

### Tasks
1. Create a function that takes raw (i.e., macro-laden) HTML as input, and returns an object mapping document URI's to a list of sample ID's to extract (e.g.:
    ```javascript
    { "/en-us/learn/forms/your_first_form/example": ["A_simple_form"] }
    ```
    Note that the document URI is not always the same as the document URI of the raw HTML provided as input, since the `EmbedLiveSample` macro can and often does specify an alternate slug from which to extract the sample ID.
1. Create a function that takes raw HTML and a sample ID, and extracts the JS, CSS, and HTML of that sample ID, as an object:
    ```javascript
    { js, css, html}
    ```
1. Create a function that takes the extracted object from above as well as the live-sample page template, and renders the HTML for a complete live-sample page.
1. Create the code the uses the functions above to build and save the live-sample pages requested as part of the particular build (either an "on-the-fly" build as part of the local preview server, a CLI build like `node content build ...`, or a "watch" build), as well as the local preview server code to serve the live-sample pages locally.
