### ISSUE TITLE
T - Implement mobile-optimized breadcrumbs.

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6822]
See User Story issue for comps and description: #6784.

# Acceptance Criteria 
- [ ] New attribute-based breadcrumb implemented on mobile (only)

**Comment by mindy** [comment]
**Notes for me**
Desktop: stays the same

Tablet and mobile: 
- Show only parent category
- "See" prepended to category
- Blue arrow pointing back 

Breadcrumb guidelines:
https://developers.google.com/search/docs/data-types/breadcrumb
