### ISSUE TITLE
T - Implement GA instrumentation for mobile-optimized experience

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6823]
See User Story issue for comps and description: #6784.

#Acceptance Criteria

- [ ] [Instrumentation](https://docs.google.com/spreadsheets/d/1plvnK5gBcrpmSwVwaVMFVvPK8ihrDL4LzObhZOtlj2Y/edit?usp=sharing) on [tap] events - desktop instrumentation is on [hover] events, need to make sure we register the same events for [tap]

**Comment by tobinmori** [comment]
@atopal - the mobile optimized breadcrumbs will use different CSS than desktop, but will have the same GA events. Do you want new GA events for the mobile optimized breadcrumbs, or will the existing ones work fine?

**Comment by atopal** [comment]
Thanks for the heads up Tobin. I think it's fine to leave them as is. We can segment mobile/desktop in GA

**Comment by tobinmori** [comment]
update: @schalkneethling thinks that no new events should be needed for the mobile header/footer but will check and create a task if needed.
