### ISSUE TITLE
Page Content Displayed With A Mix of Two Different Languages

### ISSUE THREAD

**Issue by geodon203** [mdn/kuma#6824]
Hi,

The documentation page reference given below contains a mix of two different languages. My language setting for the page was English but the initial sections of the page are displayed in Spanish.

https://developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types

**Comment by wbamberg** [comment]
Thanks for filing! This was caused by a translation mistake and has been fixed: https://wiki.developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types$compare?locale=en-US&to=1616282&from=1616229.
