### ISSUE TITLE
T - Track subscription conversion of signed-in & not signed-in users

### ISSUE THREAD

**Issue by Gregoor** [mdn/kuma#6827]
We need two sets of numbers.  
1a. Absolute number of people who clicked on "continue" on the landing page and were already sign in before their current session.
1b. Absolute number of people who successfully subscribed and were in group 1a.

2a. Absolute number of people who clicked on "continue" on the landing page and were not signed in.
2b. Absolute number of people who successfully subscribed and were in group 2a.

That gives us to conversation rates
1b/1a = conversation rate for people who were already signed in when they made the choice to pay

2b/2a = conversation rate for people who had to sign in after they made the choice to pay.

_Originally posted by @atopal in https://github.com/mdn/kuma/issues/6524#issuecomment-610427221_

___

Here's my rewording of it, to make sure nothing is lost in translation:

In the context of users who express an intent to go through the subscription flow (i.e. press continue on the payments landing page), we're looking to subdivide them into two buckets, signed-in and not signed-in. For each bucket we want to know how many were in the bucket to begin with, and how many went through with it and actually created a subscription.

What an implementation could look like:
When a user clicks continue on the payments landing page, we both session-store and send an event to analytics indicating whether they were already logged in.
Once the user successfully creates a subscription, we read from the session-store whether they started of logged-in or not, and send a subscription creation even specific to that to analytics.

cc @peterbe

**Comment by chinikes** [comment]
Hi @tobinmori - What user story is this task implementing?

**Comment by tobinmori** [comment]
> Hi @tobinmori - What user story is this task implementing?

attached to #6834

**Comment by atopal** [comment]
Your description sounds good to me @Gregoor

**Comment by Gregoor** [comment]
Events are showing up in prod analytics, so we're considering this issue resoved
