### ISSUE TITLE
T - make subscription banner NOT depend on being authenticated

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6828]
**Summary**
The presence of the subscription banner should be driven by the waffle Flag, not by the that *and* the user being authenticated. 

**Rationale**
Now that the Subscription landing page theoretically works for anonymous users (the get the auth modal instead of the Stripe modal), there is no technical reason why we can't send anonymous users to the Subscription landing page. 

**Audience**
??

**Proposal**
Remove any mentions of `authenticated` or `isAuthenticated`. 
E.g. https://github.com/mdn/kuma/blob/842f78b2e8cd0520721efee471ba5dd40aa9e2d0/kuma/javascript/src/active-banner.jsx#L226-L228

**Additional context**
The reason it *was* there in the first place was that the call to action was to link to the Edit Profile
page which didn't make sense to link to unless you're signed in.

**Comment by peterbe** [comment]
@chinikes @atopal @tobinmori I doubt this needs to be triaged. It'll take me minutes to just do. But would you mind hooking this up to the appropriate user story?

**Comment by tobinmori** [comment]
@atopal @chinikes @peterbe - reopened #6555 for this, as it turns out it was not complete.
