### ISSUE TITLE
A - Assumption Test:  People are mostly solving L10n with the built in feature of Chrome, and it's good enough

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6841]
# Context
We want to find out if the majority of non-native English speakers, using Google Chrome, that prefer to browse and read MDN in their local language already use Chrome's automatic translation tool and are happy with it.

# Acceptance Criteria
- [x] [research project page completed](https://docs.google.com/document/d/1pPMLezIX-bsg6gbLioPz22Gi0A4dy2tStj-8_cov5Vc/edit?usp=sharing)
- [x] method agreed on
- [x] results documented and shared
- [x] [decision made and documented](https://docs.google.com/presentation/d/1PoQzQA6tWMkggWP1_uFLJFEFNbwPgdpxDd_uKg9KYoA/edit?usp=sharing)

# Possible ways to test this
- [ ] survey on MDN localized into a few language asking who is using it
- [ ] interview a few people about their experience with it (which languages?)
- [ ] use the feature and score MDN pages, with native speaker if necessary

**Comment by malqinneh** [comment]
[🧬 Experiment: Are users solving L10n with Chrome built-in automatic translation tool?](https://docs.google.com/document/d/1pPMLezIX-bsg6gbLioPz22Gi0A4dy2tStj-8_cov5Vc/edit?usp=sharing)

## Results

- Out of 1259 survey participants, 469 users (36%) were non-native English speakers, using Google Chrome, and prefer to browse and read MDN in their local language
- The other portion (511 users or 41%) of non-native English speakers using Google Chrome prefer to browse and read MDN in English
- Out of 469 users, 59-68% said they are likely to use Google’s built-in automatic translation tool when browsing MDN
- Out of 469 users, 59-75% said they are satisfied with Google’s built-in automatic translation tool as it applies on MDN
- Majority of those users are also (generally) happy with the quality of translation
- Users had some suggestions on how might we improve their experience using Chrome’s built-in automatic translation tool: 
- Majority of users said translation quality/accuracy could be improved
- A lot of users requested a convenient feature of seeing both, the original text and translated text simultaneously
- A lot of users requested a convenient feature of specifying which words they wanted translated (vs the entire page)
- A lot of users suggested that technical terms like functions, class names, and code examples remain in their original text

## Decisions

- Fortunately, majority of users interested in L10n are using Chrome’s built-in automatic translation tool and are generally happy with it / find it useful
- There is a strong case for optimizing and maintaining MDN to use various browsers’ built-in automatic translation tools
- The second most popular browser after Google Chrome (for non-native English speakers *potentially* interested in L10n) is Firefox (28%) -- might be useful to share this finding with the Firefox team that L10n is something users do use and want in a browser

**Comment by malqinneh** [comment]
I've added survey results and decisions as a comment in this issue. Will also create a slide deck with these results and decisions to share with the team once ready.
