### ISSUE TITLE
A - Assumption Test:  There are solutions out there, so we don't have to build our own tools

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6842]
# Context

# Acceptance Criteria
- [x] [research project page completed](https://docs.google.com/document/d/1K8NfO3jvKwl7GiGnQwfeFD-4KUbzc-Guv2yJpJr0sXA/)
- [x] method agreed on
- [x] results documented and shared
- [ ] decision made and documented

# Possible ways to test this
- [ ] Meet with L10n team to get state of the art from them
- [ ] talk to known localizers about what their workflow looks like (to see what tools they know of, what they are currently missing or consider essential
- [ ] compile support matrix of our (possible) requirements and the available options

**Comment by atopal** [comment]
Here's something we should check out: https://crowdin.com

**Comment by tobinmori** [comment]
Research Project page:
https://docs.google.com/document/d/1K8NfO3jvKwl7GiGnQwfeFD-4KUbzc-Guv2yJpJr0sXA/

**Comment by atopal** [comment]
Let's have a look at this too: https://lokalise.com/product/crowdin-alternative
