### ISSUE TITLE
Browser compatibility table row headings disappear if you reveal browser notes

### ISSUE THREAD

**Issue by WebMechanic** [mdn/kuma#6845]
The Browser compatibility table row headings (`table.bc-table th`) have a (default) vertical alignment of "middle". 
If the layout of table rows switches from "grid" (narrow page) to "default" (desktop-ish; > 64em) so row headings appear on the left, as a consequence the text inside the `th` disappears when you twirl open a cell to read the browser notes, i.e. flag, bugs etc.

Open this page and make sure the row headings appear _to the left_ of each property as depicted in the first image, that is `min-width:63.9385em` :)
- https://developer.mozilla.org/en-US/docs/Web/CSS/@media#Accessibility_concerns

![image](https://user-images.githubusercontent.com/638340/78991845-2f4b3900-7b3a-11ea-9979-c02d33c65148.png)

Scroll down to "display-mode" as an example (or try `-webkit-device-pixel-ratio` at the end)
If you twirl open the notes for Firefox (47) the row header moves downwards and disappears because the row became higher than the inital 2 lines. The TH's default vertical alignment pushes the text underneath the appearing block.
![image](https://user-images.githubusercontent.com/638340/78991879-3e31eb80-7b3a-11ea-9541-ac0879eeb1d9.png)

Possible fix: add `vertical-align:top`
```css
.text-content table.bc-table th {
    text-align: center;
    vertical-align: middle;
}
```
To my findings this alignment has no effect on the label position in the narrow design using "grid" where row headings appear above the data cells.

Using Win10 with Firefox/74, Nightly/77, Edge/18, ChromeCanary/83 ...

**Addendum for EdgeHTML (Edge/18)**
Also only on wide screens, the position of the twirly triangle is misaligned and appears inside the table cell.
![image](https://user-images.githubusercontent.com/638340/78993662-80f5c280-7b3e-11ea-8059-0df733453170.png)

**Comment by CITguy** [comment]
I just ran into this issue today. Here's a screen capture of the bug in action for the [CSS `position`](https://developer.mozilla.org/en-US/docs/Web/CSS/position#Browser_compatibility) compatibility table.

![bug-mdn-compat-table-expanding-row](https://user-images.githubusercontent.com/545605/79282623-49a74e80-7e7b-11ea-807b-27bf3650f5dc.gif)

**Comment by Elchi3** [comment]
This looks like a recent regression. 
(Also, the descriptions are now centered instead of left aligned. Was that change made intentional?)

@atopal Can you prioritize this issue?

**Comment by atopal** [comment]
Sure, we'll take this into the next triage. Thank you!

**Comment by peterbe** [comment]
> Sure, we'll take this into the next triage. Thank you!

@atopal I put the label back so we don't forget.
