### ISSUE TITLE
U - KS Render can render all macros  in non-archived content 

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6853]
# User Story 
KS Render can render all macros (except the `EmbedLiveSample` macro) in non-archived content.

# Acceptance Criteria 
- [x] The wiki.page API function has been implemented and tested.
- [x] The wiki.getPage API function has been implemented and tested.

**Comment by escattone** [comment]
This is done (see https://github.com/mdn/kuma/issues/6818).
