### ISSUE TITLE
`git status` shows hundreds of modified files on a fresh clone

### ISSUE THREAD

**Issue by mindy** [mdn/kuma#6867]
**Summary**
When doing a fresh clone of mdn/kuma, there are hundreds of changes in asset files related to line endings, which I think can be confusing to new contributors. 

The usual commands to discard local changes are not working: `git restore`, `git stash`, `git reset --hard`, `git checkout .` 

**Steps To Reproduce (STR)**
1. `git clone git@github.com:mdn/kuma.git` 
2. `cd kuma`
3.  `git status` shows lots of files changed: 
```
...
modified:   kuma/static/styles/libs/jqueryui/images/ui-icons_888888_256x240.png
modified:   kuma/static/styles/libs/jqueryui/images/ui-icons_cd0a0a_256x240.png
...
```
5. `git diff` shows: 
```
...
The file will have its original line endings in your working directory
warning: CRLF will be replaced by LF in assets/ckeditor4/build/ckeditor/plugins/icons_hidpi.png.
...
```

**Actual behavior**
Running `git status` lists files that I did not edit. 

**Expected behavior**
Running `git status` should only show changes that I made. 

**Temporary Fix** 
1. Comment out this line in `.gitattributes`: 
`# *	text eol=lf`
2. Run `git status`, should only see one file changed
3. Undo the commenting in `.gitattributes` or run `git checkout .`
4. Run `git status`, should see "nothing to commit, working tree clean"

**Comment by peterbe** [comment]
It's [this PR's](https://github.com/mdn/kuma/pull/6796) "fault". I think we need to revisit it, clearly. 

Perhaps, @mindy , as a "better" temporary fix, we can **revert** [that PR](https://github.com/mdn/kuma/pull/6796) at least. Or, if @Gregoor can pull out some magic, perhaps we can "fail forward" with a solution that works for all Windows users and not causing *this* issue.

**Comment by Gregoor** [comment]
yaiks, sorry for the troubles, Mindy. That's on me as well, I guess WSL behaves differently here than an actual Unix 🤔 I'm going to go with revert for now, as I can't seem to be able to reproduce it.

**Comment by mindy** [comment]
Thanks for fixing @Gregoor! Closing out this ticket.
