### ISSUE TITLE
bug macro is bound to be stale and trouble in yari

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6876]
**Summary**
We should not attempt to include summary and resolution in the rendered HTML based on Bugzilla IDs in the rendered HTML. 
It's inevitably going to get stale quickly and the infra to even do it is causing blockage in Yari 1.

**Audience**
Devs and content.

**Rationale**
The [`bug.ejs` macro](https://github.com/mdn/kumascript/blob/master/macros/bug.ejs) is used like this: `{{bug("1239100")}}` or `{{Bug(561154)}}` (note the case-insensitivity and the mix of quotes and not-quotes on the number) is going to try to go to `https://bugzilla.mozilla.org/rest/bug/...` extract the summary and resolution and inject this into the HTML the macro returns. 

So if you make a Wiki edit on Monday, the bug changes summary or resolution on Tuesday, the rendered Wiki page will not find out until we do a (manual) mass re-render or someone deliberately re-renders the page or makes an actual edit. 

A more ideal thing would be to just turn `{{bug(1239128)}}` into 
```html
<a class="external external-icon" href="https://bugzilla.mozilla.org/show_bug.cgi?id=1239128" rel="noopener">bug&nbsp;1239128</a>
```
and that's it. No attempt to `await MDN.fetchJSONResource('https://bugzilla.mozilla.org/rest/bug/ ...` at all. 

Also, if it's important to have the resolution and summary in the DOM, I think we should fetch that semi-automatically on-the-fly on the client-side. For example, something like:

```javascript
jQuery('a[href^="https://bugzilla"]').on('mouseover', fetchBugDetails);
```

For the record, I **don't** think we should do something like this:

```javascript
// On-load, fetch all bug details
jQuery(function() {
  if (jQuery('a[href^="https://bugzilla"]').length) {
    fetchAllBugzillaDetails();
  }
});
```
It would put tremendous amount of traffic on https://bugzilla.mozilla.org/rest/bug/ since [many of our pages](https://gist.github.com/peterbe/60236c0e2313de5350f49623429a026b) get a LOT of traffic. 

**Workaround**

**Proposal**
Change [kumascript `macros/bug.ejs`](https://github.com/mdn/kumascript/blob/master/macros/bug.ejs) to become much simpler. Get rid of the `await MDN.fetchJSONResource` entirely and proceed with the old code as if the network call had failed. 

If it's important, we put some code into the kuma front-end (e.g. `article.jsx`) that attaches event listeners of `mouseover` on these links.

**Additional context**
[Yari 1 blocked on this](https://github.com/mdn/stumptown-renderer/issues/480)
As described [in this comment](https://github.com/mdn/stumptown-renderer/issues/480#issuecomment-613440420) there are 1,721 (236 en-US) of these calls in the documents that will be exported to Yari 1. 

Here's a list of the top 100 most visited pages that use the `bug` macro: https://gist.github.com/peterbe/60236c0e2313de5350f49623429a026b

**Comment by peterbe** [comment]
By the way, here's another reason why it's probably best to NOT trigger a network fetch to bugzilla.mozilla.org simply by opening the page:
This page, https://wiki.developer.mozilla.org/en-US/docs/Web/SVG/SVG_2_support_in_Mozilla has 44 `document.querySelectorAll('a[href^="https://bugzilla"]')` tags!
36 of them are unique.

**Comment by peterbe** [comment]
By the way, I wrote a script that finds every possible use of `{{bug(...)}}` in the documents that will be exported to Yari. And then, I filtered on all that contain a `,` or ` ` (space) and the only ones I found were:
```
/zh-CN/docs/Web/API/IndexedDB_API/Using_IndexedDB [ '{{ bug(870645)}}' ]
/es/docs/Web/CSS/zoom [ "{{bug(390936, 'summary')}}" ]
```

Now, let's go back to [the source code of `bug.ejs`](https://github.com/mdn/kumascript/blob/1f4b93faf68095f0b69b2d3d0e9e487793bdc18e/macros/bug.ejs) and it seems to me that it doesn't even bother to display the `desc` variable's value. 
...in all but the one single time on [/es/docs/Web/CSS/zoom](https://wiki.developer.mozilla.org/es/docs/Web/CSS/zoom)

**Comment by peterbe** [comment]
Am I reading that right?! Not a single time (except that 1 page) of the to-be-exported-to-Yari slugs, do we actually bother with the outcome of the `await MDN.fetchJSONResource(...)`?

**Comment by atopal** [comment]
Huh, I thought we had already agreed to remove that. Either way: yes.

**Comment by peterbe** [comment]
> Huh, I thought we had already agreed to remove that. Either way: yes.

I can't remove it because it's mentioned in ~1.7k places but I'll definitely simplify it so it doesn't depend on the network. 

If we decide we want something like injecting a fuller `title` tooltip when you hover over the link, we can perhaps implement that in a separate feature request.

**Comment by wbamberg** [comment]
See also https://github.com/mdn/kumascript/issues/751. Also note that in the JS docs we have already rendered out the `{{bug}}` macro and made it a simple link: https://github.com/mdn/sprints/issues/2522.

**Comment by wbamberg** [comment]
> If we decide we want something like injecting a fuller title tooltip when you hover over the link, we can perhaps implement that in a separate feature request.

We just removed that in https://github.com/mdn/kumascript/pull/1330, as part of https://github.com/mdn/sprints/issues/2787, because we were intending to render out these xrefs as simple links, and retire the macros.

**Comment by peterbe** [comment]
I think we can simply close this issue when https://github.com/mdn/kumascript/pull/1355 lands.

**Comment by atopal** [comment]
Oh, I guess I was remembering mdn/sprints#2787

**Comment by peterbe** [comment]
Merged https://github.com/mdn/kumascript/pull/1355
