### ISSUE TITLE
Informe de ortografía en ChildNode.remove()

### ISSUE THREAD

**Issue by nmkdarango** [mdn/kuma#6881]
En español:

La palabra del título síntasix, esta mal escrita:

Debe ser **sintaxis** (revisar además que no tiene tilde).

**Comment by peterbe** [comment]
Are you referring to text on a specific page?

**Comment by nmkdarango** [comment]
Yes, the text, síntasix is bad translated.

**Comment by peterbe** [comment]
What you can do is to create an account on developer.mozilla.org (GitHub or Google) and go to the page that has the bad translation. Then, click the "Edit in wiki" button and proceed. 
Thank you for helping out with the translated content!
