### ISSUE TITLE
T - Welcome emails are outdated and incorrect

### ISSUE THREAD

**Issue by callahad** [mdn/kuma#6883]
Looking at the `WELCOME_EMAIL_FROM` setting from #6878 took me down a rabbit hole:

1. Should we really be sending all of the welcome emails as "Janet Swisher", versus some other more verbose or community alias? Should it be no-reply, or go to some kind of communal inbox? (See [Janet's thoughts here](https://github.com/mdn/kuma/pull/6878#discussion_r409716126).)

2. The welcome emails themselves (see [kuma/users/jinja2/users/email/welcome/](https://github.com/mdn/kuma/tree/d5a5dbbf2ea8868673ffe77a904a4e2d8dc6df02/kuma/users/jinja2/users/email/welcome)) are broken in a few ways:

    - The deep links to Getting Started are broken because the anchors have changed
    - We promise some kind of followup onboarding email, but I don't see any evidence that it exists or that we ever send something like that.
    - We promote the old `#mdn` IRC channel, but Mozilla's IRC network is no longer online. This should point to our Matrix room instead.
    - We specifically name Janet, Chris, Florian, and Will as being people to talk to about writing. This is good, but also really prone to becoming outdated. We, especially, don't see these emails regularly.

**Comment by atopal** [comment]
should also come from an email address that people can reply to.

**Comment by atopal** [comment]
Deep links should be: https://developer.mozilla.org/en-US/docs/MDN/Getting_started#Option_1_I_like_words

https://developer.mozilla.org/en-US/docs/MDN/Getting_started#Option_2_I_like_code

https://developer.mozilla.org/en-US/docs/MDN/Getting_started#Option_3_I_like_both_words_and_code

https://developer.mozilla.org/en-US/docs/MDN/Getting_started#Option_4_I_want_MDN_in_my_language

Sender should be changed to mdn-admins@mozilla.org

**Comment by atopal** [comment]
As Janet mentioned it should end with 

Janet Swisher, MDN Community Lead

**Comment by chinikes** [comment]
Hi @atopal - Wanted to follow up on the status this task as it's marked done on the sheet.

**Comment by atopal** [comment]
This is done.
