### ISSUE TITLE
Private window displays a list of gmail subjects for the gmail account open in a non-private window when typing a word in the address/search bar 

### ISSUE THREAD

**Issue by ktssin** [mdn/kuma#6888]
1. open normal, non private window. login with gmail credentials.
2. open a private window. attempt to search for a word which is in some subjects in the gmail inbox.

drop down displays list of subjects from the gmail account open in the non private window
![ffissue](https://user-images.githubusercontent.com/50448935/79577057-bc196800-80e1-11ea-9dd1-59a2a2a68f26.jpg)

**Comment by peterbe** [comment]
This GItHub repo is about the https://developer.mozilla.org website. 
What you're describing is (an interesting) issue in Firefox. For that please use: https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox
And I bid you good fortune to file it. It seems like a really interesting topic worthy of a good discussion. Firefox is a big project with lots of bugzilla tickets and it takes a couple of minutes to find your way around. Best of luck and THANK YOU for helping Mozilla!
