### ISSUE TITLE
English(US) version is in arabic script. 

### ISSUE THREAD

**Issue by joaofrobalo** [mdn/kuma#6890]
**Summary**
The English version was accidentally changed to (what seems to be) persian. 

**Steps To Reproduce (STR)**

1. Go to https://developer.mozilla.org/en-US/docs/Web
2.  Check the language version is English(US)

![Screenshot of the issue shows English landing page in arabic](https://user-images.githubusercontent.com/19671632/79586038-86b45080-80c8-11ea-9b34-88219dbf56c0.png)

**Comment by peterbe** [comment]
Thanks for noticing! @chrisdavidmills took care of fixing it on April 17 9:27AM (but unfortunately I can never remember what timezone is used on the WIki)

**Comment by peterbe** [comment]
Oops. Failed to paste in the URL: https://wiki.developer.mozilla.org/en-US/docs/Web$history
