### ISSUE TITLE
T - the API to support subscription management

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6892]
The backend pieces needed for https://github.com/mdn/kuma/issues/6703

That way we, can Reactify the subscription management page. 

What we need is to endpoints:

1. Getting your subscriptions (plural but it's probably never more than 1)
2. Cancel a subscription (or cancel them all if that's easier)

**Comment by peterbe** [comment]
I'm thinking we keep `POST /api/v1/subscriptions/` to do what it does today, but add `GET /api/v1/subscriptions/` and `PUT /api/v1/subscriptions/:id` to cancel it.

**Comment by mindy** [comment]
Would you be able to do https://github.com/mdn/kuma/issues/6703#issuecomment-614246571, along with this work? Or should it be a separate issue?

**Comment by peterbe** [comment]
> Would you be able to do [#6703 (comment)](https://github.com/mdn/kuma/issues/6703#issuecomment-614246571), along with this work? Or should it be a separate issue?

Separate issue, since *this* issue is all and only about the v1 api. 
But sure, the user story can have 3 tasks. Please create that one and feel free to assign it to me. Tancs!
