### ISSUE TITLE
U - Report possible refactorings that would improve mobile performance

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6894]
**Acceptance Criteria**

- [x] Document possible fixes for mobile performance improvements

**Comment by chinikes** [comment]
Hi @tobinmori , @peterbe - With #6934 done, can we confirm all acceptance criteria for this story is done? If so can we mark the user story done now?

**Comment by atopal** [comment]
@peterbe and @tobinmori  just a quick note that there are issues here. The AC for this user story requires "Give ballpark estimates for possible fixes", but there is also another user story – that is not assigned to any sprint – that addresses the same milestone in #6895 I think we'll need to clean that up.

**Comment by tobinmori** [comment]
> @peterbe and @tobinmori just a quick note that there are issues here. The AC for this user story requires "Give ballpark estimates for possible fixes", but there is also another user story – that is not assigned to any sprint – that addresses the same milestone in #6895 I think we'll need to clean that up.

Should be cleaned up now. We have a task for documented estimates on possible perf fixes here: #6994

**Comment by tobinmori** [comment]
Final report here:

https://github.com/mdn/kuma/issues/6934#issuecomment-622497603
