### ISSUE TITLE
T - Add 301 redirect to Subscriptions Management page 

### ISSUE THREAD

**Issue by mindy** [mdn/kuma#6898]
`/payments/recurring/management` is moving to `/payments/management`, therefore we need to add 301 redirect in kuma/payments/urls.py

See https://github.com/mdn/kuma/issues/6703#issuecomment-614246571 for context

**Comment by peterbe** [comment]
@mindy I think we've got this the wrong way around. In terms of blocking/blocked by. 
What I think you should do is create a brand new entry in `payments/urls.py` and kinda prentend the old one doesn't exist. 
Even the Django view function name is poor (`recurring_payment_management`). 

So, once you've created a new line in `urls.py` and a new Django view function that wraps the React SPA stuff, then I'll work on *this* issue to make sure the redirect works as expected.

**Comment by peterbe** [comment]
Bha!! I'm an idiot. I misread the blockers. I *thought* this issue was blocking [*your* issue](https://github.com/mdn/kuma/issues/6896). 

But still, I think it would be nice, for me, to work on this if there's a new URL I can redirect to so I'll still keep the new tracking blockage I added.
