### ISSUE TITLE
Sound Bug when alt tabbing in game and mozilla on twitch

### ISSUE THREAD

**Issue by PIONzx** [mdn/kuma#6902]
When i alt-tab between my game (WoW) and mozilla, sometimes the sound of the streamer or the video just become noisy.

I Believe it's a Mozilla problem because i have seen that on streams too.

Please fix this , it's annoying
Thank you.

**Comment by escattone** [comment]
@PIONzx This GItHub repo is for MDN Web Docs (https://developer.mozilla.org).
I suspect you're talking about Firefox? For that please use https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox
