### ISSUE TITLE
Color of next button icon is white

### ISSUE THREAD

**Issue by Abhkblyn** [mdn/kuma#6905]
hey 
I want to tell you that at some pages the color of the button icon is white which is not similar to other pages of the website if this is an issue you may fix this 
thanks

**Comment by peterbe** [comment]
Got an example URL of that?

**Comment by peterbe** [comment]
@Abhkblyn I filed something similar. What do you think? https://github.com/mdn/kuma/issues/6913

**Comment by schalkneethling** [comment]
> @Abhkblyn I filed something similar. What do you think? #6913

Yup, these are the same problem. I am taking a look at it in https://github.com/mdn/kuma/issues/6913 - Thank you for reporting @Abhkblyn
