### ISSUE TITLE
T- Fix github feedback link, to /choose not /new

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6911]
**Summary**
The Wiki and the read-only site has a "Report an issue"
It links to https://github.com/mdn/kuma/issues/new but if you use that it bypasses the nice issue templates and issue don't automatically get the `status: needs triage` label so they're likely to miss our weekly itrage. 

**Audience**
Users of MDN.

**Rationale**
Every now and then we get issues filed that don't have the `status: needs triage` label.

**Workaround**
Do nothing.

**Proposal**
Change URL from https://github.com/mdn/kuma/issues/new
to https://github.com/mdn/kuma/issues/new/choose in both the WIki header and the read-only site header. 

**Additional context**
Perhaps our chooser template thing should have a section for **content**. 
All too often people writing in and complain about something not being right in the content. No problem with doing that. But the so often fail to include a URL of which page they're referring to. If we use a better template we can strongly press for this before we throw the issue over to `mdn/sprints`. 
(I know there's a "Report a content problem" in the Feedback nav but clearly people aren't seeing this)

**Comment by peterbe** [comment]
More fuel for why *this* issue is a P1: https://github.com/mdn/kuma/issues/6925 just came in.

**Comment by peterbe** [comment]
https://github.com/mdn/kuma/pull/6935 takes care of the hyperlink. But the more interesting task is to **talk about content problems** in the choose template. The complicated part is that it's almost too late. They shouldn't have clicked github.com/mdn/kuma/issues/new/choose at all! So how can we tell them, whence on github's UI, that they really should have used github.com/mdn/sprints??

**Comment by tobinmori** [comment]
@peterbe i'm going to talk to Chris about this. when i figure out his needs i'll create a new templatte.

**Comment by peterbe** [comment]
Note that the URL which is behind the "Report a content problem" is: https://github.com/mdn/sprints/issues/new?template=issue-template.md&projects=mdn/sprints/2&labels=user-report&title=%2Fen-US

Perhaps, in a way the best thing would be if the "Feedback" header said "Report a problem" and when you click that a second modal/alert/diaglog pops up that says: "Is the problem related to the content or the functionality of this website?"

**Comment by peterbe** [comment]
I don't know how this was missed but [my PR](https://github.com/mdn/kuma/commit/cf8d901ee7725692ff1a40a000f83ce52b29ba4e) only addressed the link the header on the Wiki.
