### ISSUE TITLE
Prev/Overview/Next buttons "stop working"

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#6913]
**Summary**
Here's what it looks like on https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Tutorial_local_library_website
<img width="765" alt="Screen Shot 2020-04-20 at 10 30 29 AM" src="https://user-images.githubusercontent.com/26739/79763416-0e30d800-82f2-11ea-8db4-5deb94c0117e.png">

But on the ["Next" page](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website) it looks like this:
<img width="728" alt="Screen Shot 2020-04-20 at 10 31 35 AM" src="https://user-images.githubusercontent.com/26739/79763474-2274d500-82f2-11ea-973d-99911d1f730e.png">

**Steps To Reproduce (STR)**
See above

**Actual behavior**
See above

**Expected behavior**
Look the same on all pages with the `PreviousMenuNext` macro

**Additional context**
Looking at the raw source, the KS macro is used the same:
* [grey buttons](https://wiki.developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Tutorial_local_library_website?raw) 
* [not grey buttons](https://wiki.developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website?raw)

**Comment by tobinmori** [comment]
Timebox to 1 ideal day.

**Comment by a2sheppy** [comment]
I've done some research here. The two different looks (unstyled buttons vs styled buttons) use the same macro command  syntax, and I see no reason they should behave differently.

Looking at the generated HTML, the unstyled buttons are using an empty `style` attribute on the innermost span within the button:

```
<div><a href="/en-US/docs/Learn/Server-side/Django/Tutorial_local_library_website" style="float: left; width: 20%; text-align: left;"><span style=""><i class="icon-arrow-left"></i> Previous </span></a>
```

The styled button, on the other hand, looks like this:

```
<a href="/en-US/docs/Learn/Server-side/Django/development_environment" style="float: left; width: 20%; text-align: left;"><span style="display: inline-block; background: #eaeff2; border-radius: 4px; box-shadow: inset 0 -1px #bbbfc2; color: #4d4353; padding: 0.3em 0.8em;"><i class="icon-arrow-left"></i> Previous </span></a>
```

That's a lot more style information.

Looking within the macro itself, we see near the top the declaration of a global variable `buttonStyle`:

```
var buttonStyle = "display:inline-block;background: #eaeff2;border-radius:4px;box-shadow: inset 0 -1px #bbbfc2;color: #4d4353;padding:0.3em 0.8em;";
```

`buttonStyle` is used to style the individual buttons. Note that this is what *should* be appearing within the `<span>` elements in the unstyled version. Something is causing `buttonStyle` to be empty on those pages. Strange.

I continue to investigate.

**Comment by a2sheppy** [comment]
buttonStyle never gets changed anywhere, so something is causing that global to simply not be present when the macro runs.

One obvious change to make to this page is to make use of `const`; it wasn't a thing that existed last time this macro was significantly changed.

**Comment by a2sheppy** [comment]
The right solution here is to simply move `buttonStyle` into a CSS class and use that instead. In a perfect world, this macro would also be updated to use template literals, costants, and so forth. But minimally, probably just move the style to a style sheet would resolve the problem.
