### ISSUE TITLE
T - Run side by side comparison (minimalist vs default kuma) to see understand CSS's performance factor

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6919]
**Description**

As we know from previous investigations CSS could be a big culprit in our performance. Briefly, comparing minimalist CSS vs. existing kuma CSS would shed light on this.

**Comment by schalkneethling** [comment]
Timeboxed to 1 point

**Comment by peterbe** [comment]
@schalkneethling If you help me I can create a test variant (as part of the https://github.com/mdn/kuma/issues/6934 framework) that replaces all the CSS with minimalist. We can make two variants. One that is just a straight-up swap from `/static/build/styles/react-mdn.{hash}.css` to a `/minimalist.min.css` thing. And we we can do another experiment to inline it as critical. It'll probably look a bit broken but we'll be able to see what perf impact a much smaller CSS bundle will be.

**Comment by schalkneethling** [comment]
Will let you know as soon as this is ready.

**Comment by tobinmori** [comment]
Can i close this one then since we're folding it into the test harness?
