### ISSUE TITLE
[Arch Linux] Firefox Download Bug

### ISSUE THREAD

**Issue by 641i130** [mdn/kuma#6930]
When I try to download something in the browser, I'm able to select the location but then once I save it, it fails and I have no idea why. Is there any log information I should provide for this bug? Its happened to me before and I'm not sure why its happening again.

**Comment by peterbe** [comment]
Hi @641i130 
If you think you've found a bug in Firefox, consider using https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox instead.
This repo is about the *website* https://developer.mozilla.org
