### ISSUE TITLE
T - No way to subscribe after canceling Stripe modal

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6931]
**Summary**
On the [payments landing page](https://developer.allizom.org/en-US/payments/), after clicking "continue" the Stripe modal comes up. After canceling the stripe modal means, the "continue" button becomes inactive. Only reloading the page turns it active again.

**Steps To Reproduce (STR)**
1. Open https://developer.allizom.org/en-US/payments/
2. Click the checkbox and then "continue"
3. Cancel the Stripe modal by clicking on the x
4. Click on the "continue" button

**Actual behavior**
"continue" button is inactive in step 4

**Expected behavior**
"continue" button should bring up the Stripe modal again

**Comment by peterbe** [comment]
I was able to reproduce this locally too. 
I clicked "Continue", close the modal, clicked "Continue" again and then took the screenshot:
<img width="1488" alt="Screen Shot 2020-04-22 at 10 16 43 AM" src="https://user-images.githubusercontent.com/26739/79993286-99d96e80-8482-11ea-8c60-eb0da86e69af.png">
