### ISSUE TITLE
Menu dropdown appears underneath content below it

### ISSUE THREAD

**Issue by Charlesbjerg** [mdn/kuma#6942]
**Summary**
_What is the problem?_
Menu dropdown appears underneath content below it, just a simple styling issue.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_
[On this page for example](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-tap-highlight-color)
1. Hover over Technologies
2. 'On this page' aside will appear on top of dropdown links.

**Actual behavior**
_What actually happened?_
Content appeared on top of menu dropdown blocking links from being clicked.

**Expected behavior**
_What did you expect to happen?_
Dropdown to appear on top of the content.

**Additional context**
_Is there anything else we should know?_
I'm running Chrome Version 81.0.4044.92 on Ubuntu 19.10 at 1080P and 1440P

**Comment by peterbe** [comment]
<img width="666" alt="Screen Shot 2020-04-24 at 12 52 46 PM" src="https://user-images.githubusercontent.com/26739/80237316-89fc8e80-862a-11ea-99b3-37293b5a57fc.png">
