### ISSUE TITLE
O - Ready implementation plan for yari 1 to move contributions into Github

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#6949]
# Ready implementation plan for yari 1 to move contributions into Github

# Key Results 
- [ ] Mitigations explored
-- [ ] L10n strategy decisions for Yari
- [ ] Roadmap for implementation of Yari 1.x published
-- [ ] Yari prototype implemented 
-- [ ] Prototype KumaScript Rendering Tool implemented

**Comment by bensternthal** [comment]
Closing as no longer valid.
