### ISSUE TITLE
reporting bugs in #firefox bookmarks

### ISSUE THREAD

**Issue by richardta** [mdn/kuma#6950]
My bookmarks copy themselves continuously in my Firefox browser (75.0 - 64-bit) on iPhone and windows. Until today I have tens of thousands of bookmarks, sometimes up to 10 copies of the same page / bookmark. I can't delete my duplicates without all, and more page / bookmark are coming back in my bookmark library. 
It looks like there is a sync problem between my different devices and Firefox account…
Anyone encountered the same problem? Any suggestion / fix?
Best
Richard

**Comment by peterbe** [comment]
Either a bug in Firefox Sync or Firefox itself. Sorry to hear that. I hope you can help by filing a bug: https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox

This git repo is about the https://developer.mozilla.org website.

**Comment by richardta** [comment]
Hi

What information do you need?

 

Best,

Richard

 

 

 

Sit tight, wash your hands and take care of your fellow human.
