### ISSUE TITLE
UI bug in the Technologies dropdown

### ISSUE THREAD

**Issue by RonDaha** [mdn/kuma#6951]
I noticed a small UI problem on the Technologies dropdown.
On mac os, google chrome version - 81
Image is attached

![Screen Shot 2020-04-27 at 12 23 53](https://user-images.githubusercontent.com/30000700/80356667-6fbced80-8882-11ea-9849-a5e1a1bad53e.png)

**Comment by peterbe** [comment]
Thank you! 
We've already filed it in https://github.com/mdn/kuma/issues/6942 and we're working on it.

**Comment by tobinmori** [comment]
Closed as duplicate.
