### ISSUE TITLE
Result doesn't update correctly on text-decoration-style

### ISSUE THREAD

**Issue by HatimLagzar** [mdn/kuma#6964]
Hi,
On https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style when I click on double it doesn't change until I select another option and back to double.
Step 1. Select double
![image](https://user-images.githubusercontent.com/29899589/80502754-8cc7ee00-8960-11ea-9143-f67128a352f5.png)

Step 2. Select another option
![image](https://user-images.githubusercontent.com/29899589/80502866-ac5f1680-8960-11ea-9877-bb97312af646.png)

Step 3. Get back to double then it will work.
![image](https://user-images.githubusercontent.com/29899589/80503050-e203ff80-8960-11ea-9f93-7651bce99859.png)

Expected Behavior: When I click on double the first time, it should update immediately.

Thanks for this awesome website.

**Comment by peterbe** [comment]
I'm unable to reproduce. 
What browser are you using and do you get any errors in the web console?

**Comment by DevDof** [comment]
Sorry, I am using chrome the latest version of Windows, here are some screenshots ordered.
![image](https://user-images.githubusercontent.com/29899589/80608268-0bd32a00-8a26-11ea-852c-9262fc30535f.png)
![image](https://user-images.githubusercontent.com/29899589/80608276-0fff4780-8a26-11ea-9026-6dab10d038cd.png)
![image](https://user-images.githubusercontent.com/29899589/80608287-14c3fb80-8a26-11ea-8cd2-a78ee3ef16ab.png)
![image](https://user-images.githubusercontent.com/29899589/80608315-1b527300-8a26-11ea-96d7-e700b26993cf.png)

I tried to reproduce the bug on firefox, but, it works there perfectly.

**Comment by peterbe** [comment]
@DevDof Thanks for the detailed report!!

**Comment by DevDof** [comment]
@peterbe You're welcome.

**Comment by DevDof** [comment]
@peterbe It looks like after I select successfully "double" I can't get back **directly** to "solid" unless I select another value(not double) then get back to solid.
Again the issue doesn't appear on firefox and no console errors.

**Comment by atopal** [comment]
I can't reproduce this issue in Chrome. @DevDof maybe an extension in Chrome interfering?

**Comment by tobinmori** [comment]
@Gregoor can you verify and let us know?

**Comment by Gregoor** [comment]
Both @malqinneh and I couldn't reproduce the problem.

@DevDof can you maybe check chrome://extensions/ if there's an extension that's interfering with the page? Does the problem also occur in a private window (where extensions are disabled by default)?

**Comment by DevDof** [comment]
Hi again, sorry for being late to respond.
I just disabled all extension and test on both normal and private window, the problem still appears for me, this is weird. The checked elements inspector, the inline style text-decoration-style: double is applied. 
By the way, I reproduced successfully the problem on 2 other computers and the third failed to reproduce.

**Comment by Gregoor** [comment]
@HatimLagzar since we aren't able to reproduce it yet and given the nature of the problem we're going with the assumption that this is a text-decoration specific Chrome render bug. Since you have a reproduction, would you mind file an issue with the reproduction over there?
https://www.chromium.org/issue-tracking

**Comment by HatimLagzar** [comment]
@Gregoor Yes, I will do.
Thank you for your time.

**Comment by HatimLagzar** [comment]
I did file an issue on the Chromium project website with the details and liked them for this discussion for more details about the problem.

**Comment by Gregoor** [comment]
Great, thanks for that!
