### ISSUE TITLE
/en-US/docs/MDN/Feedback

### ISSUE THREAD

**Issue by Uziel302** [mdn/kuma#6971]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

missing space on footer "© 2005-2020 Mozilla and individual contributors.Content is available under these licenses."

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises

**Comment by chrisdavidmills** [comment]
I was going to try fixing this myself, but I did a bunch of searches on the Kuma repo, and couldn't find this line (or subsections of it) anywhere in the repo...

**Comment by peterbe** [comment]
The problem is that `.contentinfo p` is set to `display:inline` here: https://github.com/mdn/kuma/blob/5883afa1b539a5622ecadbf85c6fdc4f88971050/kuma/static/styles/components/structure/_contentinfo.scss#L4-L8
Seems like an old hack before we had the footer in React (JSX)
