### ISSUE TITLE
T - Add opt-in checkbox for marketing email to the Edit Profile Page. 

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6996]
**Acceptance Criteria**

- [ ] Add opt-in checkbox for marketing email to the Edit Profile Page
- [ ] Saves user's selection (opt-in/out) to the database
- [ ] Stub out functionality: add user to correct email group in sendinblue (*feedback needed from Kadir)
- [ ] Update 'Publish' button to read 'Save', see comps
- [ ] Update 'Delete Account' to be a button, see comps
- [ ] This functionality should be behind a waffle flag allowing us to turn on once sendinblue is official

**Comps**
[https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/sprints/3136](https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/sprints/3136)

**Comment by Gregoor** [comment]
I think the wrong issues are linked here, 3136 seems super unrelated 🙃

**Comment by tobinmori** [comment]
right you are, it was in the sprints repo. updated the link above!

**Comment by Gregoor** [comment]
what about this?

> Also it's imo missing the tasks:
> 
>     * add/remove user from sendinblue contacts when the subscribe/unsubscribe
> 
> 
> isn't that what this is about as well?

**Comment by tobinmori** [comment]
Good point @Gregoor!

@atopal - should we add the sendinblue integration here (or at least stub it out?) - since we are not _officially_ using them yet?

**Comment by atopal** [comment]
it should be implemented behind a flag, so that we can turn it on the moment the contract is signed.

**Comment by Gregoor** [comment]
Heyall, I've made an executive logistical engineering decision: Downgraded this to an estimate of 1, moving all of the sendinblue stuff to #7024

Why? It neatly separates frontend changes from sendinblue synchronization. The latter of which should be reviewed in bulk, to make sure we're not missing any edge cases. And just like the newsletter signup during registration, the one in edit profile can go up without sendinblue being there yet. So imo it makes a lot of sense to treat it separately (and makes my life easier yay)

**Comment by tobinmori** [comment]
Makes sense. Thanks for doing that @Gregoor.
