### ISSUE TITLE
Remove document v1 API endpoints

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#7000]
**Summary**
We built `/api/v1/doc/:locale/:slug` when we started the React re-write in hopes that subsequent clicks would load the new necessary document state via an XHR request alone. 
Turns out we never used it. And it's now extremely unlikely that we ever will. ...in Kuma. 

**Rationale**
The v1 API is here to stay and it helps to keep it not slowly deteriorating. And faster CI builds helps everyone. 

**Audience**
Devs.

**Proposal**
Things like https://developer.mozilla.org/api/v1/doc/en-US/Web/HTML/Element/progress will 404.

**Additional context**
Perhaps it's used by the linter in `stumptown-content`??
Acting on this issue is bound to clash with https://github.com/mdn/kuma/issues/6999 if done in parallel.

**Comment by peterbe** [comment]
@wbamberg @Elchi3 @ddbeck Is stumptown-content's linter code using the v1 API for documents?

**Comment by ddbeck** [comment]
I have never used it and I can't find any evidence that stumptown-content uses it generally. (I have so far used only used the `$json` and `?raw&macros` page URLs to do the scraping and linting.)

**Comment by wbamberg** [comment]
I am a bit confused about what the v1 API is and how it relates to the other API we have used in the past to get stuff out of Kuma (https://developer.mozilla.org/en-US/docs/MDN/Contribute/Tools/Document_parameters). I think I've only ever used the latter, and we continue to use it.

**Comment by peterbe** [comment]
@wbamberg We're using it for a bunch of other things. See https://github.com/mdn/kuma/blob/master/kuma/api/v1/urls.py
But I'm arguing that we can potentially ditch the `^doc/(?P<locale>[^/]+)/(?P<slug>.*)$` one.
