### ISSUE TITLE
T - Implement new main menu for mobile

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#7010]
In https://github.com/mdn/kuma/issues/6784 a new hamburger style menu have been designed for mobile devices.

![79573164-315a4e00-808c-11ea-82b7-86dfc6bab7c6](https://user-images.githubusercontent.com/10350960/81073174-864cef80-8ee7-11ea-9d10-7bfb510820af.png)

## Interaction on mobile

1. Menu is initially collapsed behind a hamburger style trigger icon
2. When tapped, the icon changes slightly and the menu is shown with the signin/avatar menu entry as well as the other top-level main menu entries
3. Tapping on any of these will expand the relevant submenu
4. Tapping again will collapse the submenu.
5. Tapping a different top-level menu item will expand its submenu and collapse all other
6. Tapping the 🍔 again, will collapse the entire menu and switch the icon back to the standard 🍔 menu icon.

For tablet and desktop the main aspects of the menu remain the same with some subtle design updates. See https://github.com/mdn/kuma/issues/6784 for details.

## Acceptance Criteria

- [ ] Mobile version of menu is implemented as described above
- [ ] Relevant design changes made to main menu on tablet and desktop
- [ ] Ensure menu is keyboard accessible
- [ ] instrumentation matches desktop events or implements new events

**Comment by schalkneethling** [comment]
Ran into a challenge with the new main menu on mobile.

For the new mobile main menu to function as designed the main menu and user menu need to be wrapped in the same container. Currently this is not the case. They are in separate containers and also separated by the search form.

We have two options. The first is to change the header structure to be \[logo, main nav, user nav, search\] as shown below:

![](https://user-images.githubusercontent.com/10350960/82423384-f9c43480-9a83-11ea-9661-75d84b3313ee.png)

Alternatively, we can keep the same HTML structure but then the header on mobile will look something like the following on initial load:

![](https://user-images.githubusercontent.com/10350960/82423848-a999a200-9a84-11ea-9a3d-13f94a3b302d.png)

And then as follows when the main menu is expanded:

![](https://user-images.githubusercontent.com/10350960/82423969-cfbf4200-9a84-11ea-995c-86826dd03719.png)

@atopal Thoughts?

**Comment by atopal** [comment]
Hmm, I'm not a fan of either option, but as stop gap, I'd go with the changes to the mobile menu.

**Comment by malqinneh** [comment]
@schalkneethling 

Thanks for bringing this up - indeed the UI does break the container structure as you pointed out. 

Apologies for the late reply here, but what do you think about accommodating [Sign in] to the right of [Search icon]? Any concerns? See below:

<img width="446" alt="image" src="https://user-images.githubusercontent.com/4819906/82847484-4e204780-9ebc-11ea-9320-0b2fbe9c2d0e.png">

**Comment by schalkneethling** [comment]
> Apologies for the late reply here, but what do you think about accommodating \[Sign in\] to the right of \[Search icon\]? Any concerns? See below:

I reckon this can totally work. Thanks @malqinneh,  I will open an issue for making this change.

**Comment by schalkneethling** [comment]
Issue opened https://github.com/mdn/kuma/issues/7146
