### ISSUE TITLE
T - Implement header search component

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#7011]
In https://github.com/mdn/kuma/issues/6784 a new interaction model has been designed for the search input field in the header.

## On Mobile

![79573164-315a4e00-808c-11ea-82b7-86dfc6bab7c6](https://user-images.githubusercontent.com/10350960/81072057-dcb92e80-8ee5-11ea-95fe-f35cf22d52f7.png)

1. The search input is initially collapsed and only shows the magnifying glass at the top right.
2. Once a user taps/activates the search input, it expands to fill the entire header area
3. The user can exit out of the active state by either click/tapping the `x`
4. This will then collapse the input back to the icon only and reveal the rest of the header
5. Optional: The back arrow would clear the search that was recently submitted and take the user back to the previous page, before the search query was submitted (essentially behaving like a browser's back button). Example: https://material.io/ 

## On Tablet

1. Keep styling and interaction as on desktop

NOTE: Because users often resize their browsers we need to ensure that the search input is keyboard accessible at tablet viewport sizes.

## On Desktop

![79573189-38815c00-808c-11ea-8062-81543f561b87](https://user-images.githubusercontent.com/10350960/81072598-aa5c0100-8ee6-11ea-8de4-8d7d0da3fea9.png)

Styling and interaction are similar to the current desktop experience.

**Comment by mindy** [comment]
@atopal from the parent story #6784:  
> [Instrumentation](https://docs.google.com/spreadsheets/d/1plvnK5gBcrpmSwVwaVMFVvPK8ihrDL4LzObhZOtlj2Y/edit#gid=741534874) on [tap] events - desktop instrumentation is on [hover] events, need to make sure we register the same events for [tap]

What GA events should we record for the search field? I looked at the spreadsheet but didn't see anything that I could recycle, and for the React search field, we do not register any GA events at the moment.

**Comment by atopal** [comment]
Not necessary to instrument. GA keeps track of site search automatically.
