### ISSUE TITLE
U - As a user I want a user-friendly Account Settings page so that I can access all of the settings pertaining to my MDN account

### ISSUE THREAD

**Issue by malqinneh** [mdn/kuma#7012]
# User story
As a user I want a user-friendly Account Settings page so that I can access all of the settings pertaining to my MDN account.

# Acceptance criteria

- [ ] Users can access the new Account Settings on Desktop
- [ ] Users can access the new Account Settings on Mobile
- [ ] Users can update their profile information from their Account Settings
- [ ] Users can become monthly member from their Account Settings
- [ ] Users can cancel their monthly subscription from their Account Settings
- [ ] Users can access their contribution history from their user menu
- [ ] Users can delete their accounts.

# Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
2. - [x] Team understands acceptance criteria 
3. - [x] Team has defined solution / steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable 
5. - [x] External / 3rd Party dependencies identified

# Design
[Accounts Settings Design - Abstract ](https://app.abstract.com/projects/9decc480-70fc-11e9-9453-4f3fbffea7ce/branches/10ce2c1c-129f-4379-877f-133962b86641/commits/9c73ba49eb0260cdd4fb2e99ee71d1ec1da90e57/files/4ffa74d7-ce7c-4f32-a6ea-7f1baa52572f/layers/1524D969-BB98-4475-8DB6-EC143F8DE079?collectionId=885f7b0e-f211-4ba1-8442-7fb435e5312b&collectionLayerId=520f7b19-0b6a-41c5-ac44-ade0d9eb3ed3)

**Comment by atopal** [comment]
Here's the link to the designs in abstract: https://share.goabstract.com/565c4ce0-9be9-4ddf-9475-ad562aa06752

**Comment by chinikes** [comment]
@tobinmori - Wanted to follow up on this story. With designs done, Does Team plan to implement in this sprint?

**Comment by tobinmori** [comment]
Yes, I believe we can start next week. I passed a vetting doc to @atopal with some questions/feedback. Once we have those issues figured out I can task it out.

**Comment by schalkneethling** [comment]
> Users can become monthly member from their Account Settings

I believe we changed this so that we direct users to the "payments" landing page instead?

**Comment by atopal** [comment]
Yeah, that's fine.

**Comment by tobinmori** [comment]
Update: Spoke with @peterbe about this and we can continue to use the old wiki acct delete page from the new acct settings page. (and table the API approach since that seems wasteful at this point)

E.g.: https://developer.mozilla.org/en-US/profiles/{USERNAME}/delete

Sound good @atopal and @schalkneethling?

**Comment by atopal** [comment]
Sounds good to me Tobin!
