### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by joteks** [mdn/kuma#7031]
# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:

# Details

Przyj**ż**yjmy się nieco dokładniej jak tworzymy paragraf.
It should be:
Przyj**rz**yjmy się nieco dokładniej jak tworzymy paragraf.

**Comment by joteks** [comment]
https://developer.mozilla.org/pl/docs/Learn/Getting_started_with_the_web/HTML_basics

**Comment by chrisdavidmills** [comment]
Updated! Thanks for reporting.
