### ISSUE TITLE
Remove speedcurve from wiki

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#7046]
**Summary**
We use Speedcurve to measure performance for end users. It should only be loaded on MDN pages that are facing end users, but we are currently also including it on wiki pages.

**Actual behavior**
speedcurve.js is loaded on wiki pages

**Expected behavior**
speedcurve.js should not be loaded on the wiki

**Comment by peterbe** [comment]
@atopal I know I did this one without waiting for a triage and sprint planning but I reckon just talking about it would take longer than it would to just fix it. Look at the PR how easy it was. I hope you don't mind.

**Comment by atopal** [comment]
Hey Peter, thanks for fixing this and yes, that's fine, but in general, let's just use our triage process to prioritize, unless it's an urgent thing of course.
