### ISSUE TITLE
Hide "IRC nickname" in profile page

### ISSUE THREAD

**Issue by jmswisher** [mdn/kuma#7058]
**Rationale**
IRC is no longer being used by Mozilla, so this field is no longer useful information.  It may confuse newer users, and makes MDN look outdated.

**Audience**
MDN members. 

**Proposal**
Users would no longer see the "IRC nickname" field or value on profile pages, or on the profile editing page. Existing values for this field would no longer be present.

**Additional context**
I realize we're minimizing work on the wiki while developing new things, so I'm not asking to replace the field with Matrix info.

**Comment by tobinmori** [comment]
This will be going away with the new acct settings page, so we'll close this.
