### ISSUE TITLE
HTML ordered list numbering is not resumed when coming back from a sublist

### ISSUE THREAD

**Issue by fsx-rwt** [mdn/kuma#7070]
**Summary**
_What is the problem?_ With Firefox (76.0.1), Ordered list numbering is not resumed when exiting from a sublist

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_The following code will reproduce it

		<ol>
			<li>Level #1 #1.</li>
			<li>Level #1 #2.</li>
			<li>Level #1 #3.</li>
			<ol>
				<li>Level #2 #1.</li>
				<li>Level #2 #2.</li>
			</ol>	
			<li>Level #1 #4.</li>
			<li>Level #1 #5.</li>
		</ol>

`**Actual behavior**
_What actually happened?_
 
" 1. Level #1 Item #1 "
" 2. Level #1 Item #2 "
" 3. Level #1 Item #3 "
".......1. Level #2 Item #1 "
".......2. Level #2 Item #2 "
" 3. Level #1 Item #4 "
" 4. Level #1 Item #5 "

**Expected behavior**
_What did you expect to happen?_

 1. Level #1 Item #1
 2. Level #1 Item #2
 3. Level #1 Item #3
          1. Level #2 Item #1
	  2. Level #2 Item #2`
4. Level #1 Item #4
5. Level #1 Item #5

**Additional context**
_Is there anything else we should know?_
In the actual behavior section I had to put extra character " and . to prevent automatic reformating of the text I entered. Just browse the HTML code submitted and you will see immediately that when you end an order sublist, the numbering continue base on the sublist instead of resuming with the parent list.

Chrome and Edge have no problem numbering order list

**Comment by escattone** [comment]
@fsx-rwt Thanks, but this git repo is for [MDN Web Docs](https://developer.mozilla.org) only, and I think you wanted to file a bug with Firefox, which you can do at https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox.

**Comment by fsx-rwt** [comment]
Sorry, you are right, I had a hard time to find where to report a bug to 
Firefox.  I thought I had it.

------ Original Message ------
