### ISSUE TITLE
T - Acct Settings: 'email addresses' mgmt component

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#7074]
# Acceptance Criteria 
- [ ] User form with name/username/email/lang
- [ ] User Can Save/Update/Delete manage email subscriptitons
- [ ] User can click on what looks like a refresh button next to their email addr and goto Email mgmt screen
- [ ] Clicking on 'email addresses' loads this component

# Note:
- Confirmation modal popup on delete is fine. 

# Design

- NOTE: The design comps are now out of date. See Acct Settings Gdoc.
- all screens here should have the side nav (like the rest of acct settings) 
- slide 9 does not need to be implemented

https://app.abstract.com/projects/9decc480-70fc-11e9-9453-4f3fbffea7ce/branches/10ce2c1c-129f-4379-877f-133962b86641/commits/9c73ba49eb0260cdd4fb2e99ee71d1ec1da90e57/files/4ffa74d7-ce7c-4f32-a6ea-7f1baa52572f/layers/679AE3F0-2CB1-4FFF-A5E5-76576DBF5DF2?collectionId=885f7b0e-f211-4ba1-8442-7fb435e5312b&collectionLayerId=770db0c7-d5e4-486e-ad50-ae05e2304e63

**Comment by tobinmori** [comment]
status: not started

**Comment by schalkneethling** [comment]
We are going to stick with the existing views and merely link to it from the new account settings. Closing this until we possibly revisit this in future.
