### ISSUE TITLE
T - Acct Settings: 'email preferences' list management 

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#7075]
# Acceptance Criteria
- [ ] Email list mgmt page appears when 'Email' subnav is clicked
- [ ] User can toggle lists and save settings
- [ ] Click on 'email preferences' subnav opens this component

# Important Note:
- The design comps are now out of date. See Acct Settings Gdoc/comments in this issue:

# Design
https://app.abstract.com/projects/9decc480-70fc-11e9-9453-4f3fbffea7ce/branches/10ce2c1c-129f-4379-877f-133962b86641/commits/9c73ba49eb0260cdd4fb2e99ee71d1ec1da90e57/files/4ffa74d7-ce7c-4f32-a6ea-7f1baa52572f/layers/71577ED1-D14E-4E61-89B5-76517FEAA1EF?collectionId=885f7b0e-f211-4ba1-8442-7fb435e5312b&collectionLayerId=8268df5a-8c7c-4800-b8ff-d8ca24459e87

**Comment by tobinmori** [comment]
status: not started

**Comment by schalkneethling** [comment]
In the latest design, newsletter preferences have changed to a single checkbox that forms part of account settings.

![Screenshot 2020-06-01 at 09 44 40](https://user-images.githubusercontent.com/10350960/83387336-d33fbb00-a3ec-11ea-920b-56d0a2a66628.png)

Rolling this work into https://github.com/mdn/kuma/issues/7097
