### ISSUE TITLE
T - Acct Settings: subscription component

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#7076]
# Acceptance Criteria

- [ ] An active subscriber can see the status of their subscription on account settings
- [ ] A user can cancel their subscription from the account settings page

# Design 

![Screenshot 2020-06-01 at 09 50 28](https://user-images.githubusercontent.com/10350960/83387798-9fb16080-a3ed-11ea-9f67-857c07613a03.png)

**Comment by mindy** [comment]
@atopal if the user does not have the waffle flag set, should we hide the subscription link in the sidebar nav?

**Comment by atopal** [comment]
No, that's okay, since the subscription button is supposed to link to the subscription landing page anyway, and we won't launch this new account settings page without having launched the subscription option.

**Comment by tobinmori** [comment]
status: 1/2 complete: component and logic, but based on original designs.

**Comment by schalkneethling** [comment]
Acceptance criteria and design has been updated:
https://github.com/mdn/kuma/issues/7076#issue-618982588

**Comment by schalkneethling** [comment]
Currently, on the payment management page the detail and layout is as follows:

![Screenshot 2020-06-18 at 14 22 35](https://user-images.githubusercontent.com/10350960/85019887-ce5e6380-b16f-11ea-80b3-ec97fbb39b1c.png)

On the same section on account details, the designs call for the following:

![Screenshot 2020-06-18 at 14 22 49](https://user-images.githubusercontent.com/10350960/85019903-d4ecdb00-b16f-11ea-894c-a827d3ea796b.png)

Seeing that we can share components and functionality here, it makes sense to me for these to match from a UI perspective as well. The alternative is that we need to create two variants based on the main component that uses the sub-components.

We _can_ do that, but it seems wasteful. Will the component on account setting not replace the payment management page in the end anyway?

Thoughts @malqinneh and @atopal?

**Comment by atopal** [comment]
That's a good question, I don't think it's a good idea to cancel immediately after people click that button, that can easily happen by accident. For cancelling your account we have an overlay for you to confirm, but I haven't seen that for subscriptions. Mustafa?

**Comment by schalkneethling** [comment]
> That's a good question, I don't think it's a good idea to cancel immediately after people click that button, that can easily happen by accident. For cancelling your account we have an overlay for you to confirm, but I haven't seen that for subscriptions. Mustafa?

The management page does do that and so, sharing the components and as such the functionality, we would inherit the same flow.

**Comment by malqinneh** [comment]
Here is the updated UX for 1) closing an account and 2) canceling subscription that Schalk, Kadir, and I talked about.

![8CD1ECD6-E0B4-4625-8EC1-53368E5BEDB7](https://user-images.githubusercontent.com/4819906/85056096-9efa2780-b16c-11ea-935b-9dfae6ace2b2.png)

**Comment by schalkneethling** [comment]
@tobinmori This turned out to be more a 4 point issue than a 1 point issue 😱 Not sure how we handle that. Do we simply add a comment such as this one, or do we "officially" change the estimate?

**Comment by tobinmori** [comment]
Thanks for the heads up @schalkneethling.

@chinikes we have a change in scope for this issue - should we update the estimate on this issue? (and notify you whenever this happens?)

**Comment by chinikes** [comment]
> Thanks for the heads up @schalkneethling.
> 
> @chinikes we have a change in scope for this issue - should we update the estimate on this issue? (and notify you whenever this happens?)

Hi @tobinmori - Yes please. Many thanks

**Comment by schalkneethling** [comment]
> > Thanks for the heads up @schalkneethling.
> > @chinikes we have a change in scope for this issue - should we update the estimate on this issue? (and notify you whenever this happens?)
> 
> Hi @tobinmori - Yes please. Many thanks

Updated estimate.

**Comment by tobinmori** [comment]
thanks @schalkneethling
