### ISSUE TITLE
T - Acct Settings: move email list management to API

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#7078]
# Acceptance Criteria

- [ ] Functionality to manage email lists is available in the API

# Design
This is old:
https://app.abstract.com/projects/9decc480-70fc-11e9-9453-4f3fbffea7ce/branches/10ce2c1c-129f-4379-877f-133962b86641/commits/9c73ba49eb0260cdd4fb2e99ee71d1ec1da90e57/files/4ffa74d7-ce7c-4f32-a6ea-7f1baa52572f/layers/71577ED1-D14E-4E61-89B5-76517FEAA1EF?collectionId=885f7b0e-f211-4ba1-8442-7fb435e5312b&collectionLayerId=8268df5a-8c7c-4800-b8ff-d8ca24459e87

The new design has the email signup checkboxes on the user detail page, like it is on the existing site.

**Comment by Gregoor** [comment]
It's straightforward and for most actions it should just work™. I also just realized that the only two actions where newsletter sync is tied to the old kuma views are user signup and user edit. Both of which don't exist in the new frontend yet, anyway. So there's nothing to do here just yet, I think.

**Comment by tobinmori** [comment]
@Gregoor can you talk to @schalkneethling to verify the api needs based on the latest design?

**Comment by schalkneethling** [comment]
> @Gregoor can you talk to @schalkneethling to verify the api needs based on the latest design?

This changed a lot but, got simpler. The only newsletter related item that remains is a single checkbox that will be part of user details:

See screenshot here: https://github.com/mdn/kuma/issues/7097#issuecomment-638046677

**Comment by schalkneethling** [comment]
There is no work remaining here as we decide to stick with the current Jinja based flow and functionality.
