### ISSUE TITLE
T - Subscription receipt imperfections

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#7080]
<img width="1210" alt="Screen Shot 2020-05-15 at 10 08 27 AM" src="https://user-images.githubusercontent.com/26739/82072675-10464680-96a6-11ea-86b2-d5caf3f7fe73.png">

* Can we make it come from a real name rather than just email?
* That's not really a sentence "Cancel any time." I think it's obvious that you can cancel at any time. If it's not the sentence should read "You can cancel at any time." then it becomes a real sentence. 
* The page is called "Manage monthly subscription" not "manage monthly subscription" because it's the name of the page.

**Comment by atopal** [comment]
Hey Peter, 

1. I'd rather make it clear that that email is not monitored. 
2. The sentence was provided by legal and is a sentence. 
3. Yes, let's change that.
