### ISSUE TITLE
CI is too slow

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#7081]
**Summary**
It's not unusual that our kuma CI builds take over 20 minutes. That's much too long. 

**Rationale**
In a perfect world, you'd push your commits to a PR and ask for a review. Then, you and the reviewer would completely ignore the results of the CI and go and work on something else. And for both you and the reviewer, when you do come back much later you reflect on the CI passing. If it failed, the author needs to address it with more code changes. If it failed, the reviewer will mentally say "Ok, seems she hasn't got CI to work yet. I'll wait with my review". 

But that's not reality. It's distracting to have to wait long for finding out if CI passes on a PR build. (master builds are different because there's almost never a reason to care *when* they finish because they almost never break anyway). 

**In the real world, you can't mentally context-switch that perfectly.** If your PR isn't passing in CI you want to find about it quick so you can square it away before you move on to your next task with a clear mind. 

Yari will make the Kuma CI build & test suite smaller but not by much. 
The pytest suite takes about 200 seconds. If it didn't have to do the `kuma.wiki` stuff, this might drop to 100 seconds. But 100 seconds reduction on 20 minutes isn't much. 

In a far future. I.e. Yari 2 where Kuma only does, exclusively, backend stuff, we won't need any `webpack` or `django-pipeline` but it's likely not the biggest culprit anyway. 

Even Yari 1 is many months away and docker for the all-backend Kuma is here to stay. We'll be doing less code changes to kuma but far from so few that this isn't going to be a problem. 

**Audience**
Devs.

**Proposal**
1. Find out the biggest bottlenecks. Is it the docker build, the pytest, the webpack, the locale builds?
2. Use caching in CI. Either use volume mounts to benefit from `pypi` and `npmjs` downloads, or cache the whole docker build itself wholesale. 
3. Find out if GitHub Actions is better/faster. Especially in terms of how to use the CI platform's caching infra.

**Additional context**
@callahad Got started and left some breadcrumbs. We might be able to ask him to dump more of this brain on this topic.

**Comment by tobinmori** [comment]
Needs investigation and then tasking out.

**Comment by peterbe** [comment]
Fixed now!
