### ISSUE TITLE
browser.tabs.query({currentWindow: false}) not always returns all tabs

### ISSUE THREAD

**Issue by Willmish** [mdn/kuma#7085]
**Summary**
_What is the problem?_
When  a browser.tabs.query() request gets sent, with the boolean currentWindow set to false, it will, sometimes return an Array of all tabs from all windows, but on occasion (and this is quite often) it will return an Array of all tabs apart from the currentWindow.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. send multiple browser.tabs.query({currentWindow: false}) in a row
2. look at the number of received elements in the returned array, it should oscillate between two values
3. 

**Actual behavior**
_What actually happened?_
the returned array is inconsistent, sometimes containing all tabs from all windows, sometimes tabs from all windows with the exception of the current window

**Expected behavior**
_What did you expect to happen?_
Get an array of all tabs from all windows.

**Additional context**
_Is there anything else we should know?_
This happens when my plugin request two arrays of tabs, one from all windows and one from the current one, but the first array is inconsistent (though not specifying the currentWindow property seems to be working everytime)

**Comment by escattone** [comment]
@Willmish Thank you for reporting, but this git repo is for [MDN Web Docs](https://developer.mozilla.org/en-US/) only, and I think you wanted to report this to the Firefox team? You can do that at https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox.
