### ISSUE TITLE
Huge X at the bottom of doc pages

### ISSUE THREAD

**Issue by mimi89999** [mdn/kuma#7086]
**Summary**
_What is the problem?_

There is a huge X at the bottom of doc pages

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Visit https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
2. Scroll to the bottom

**Actual behavior**
_What actually happened?_

See a huge X

**Expected behavior**
_What did you expect to happen?_

No huge X should be there

**Additional context**
_Is there anything else we should know?_

![Capture d’écran du 2020-05-16 16-14-19](https://user-images.githubusercontent.com/8530546/82121840-537ce400-9790-11ea-8d46-4f1892244017.png)

**Comment by schalkneethling** [comment]
Thank you for reporting @mimi89999
