### ISSUE TITLE
Void tag br is closed polish doc

### ISSUE THREAD

**Issue by mimi89999** [mdn/kuma#7087]
# Content Issue

- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:
https://developer.mozilla.org/pl/docs/Web/HTML/Element/br
# Details

On the br element page in polish that tag is closed, but in all other languages it isn't:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br
https://developer.mozilla.org/fr/docs/Web/HTML/Element/br

https://html.spec.whatwg.org/multipage/syntax.html#void-elements says:
> Void elements only have a start tag; end tags must not be specified for void elements.

In the `<br>` example the tag also isn't closed: https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-br-element

I think that the polish translation of the br element should be changed to also not close that tag.

**Comment by chrisdavidmills** [comment]
Fixed it. Thanks for reporting!
