### ISSUE TITLE
Can't use Б key when adding tags to a page.

### ISSUE THREAD

**Issue by HImichun** [mdn/kuma#7089]
**Summary**
Can't use `Б` key when adding tags to a page.
Some keyboard layouts have letters on the English `,` key, and typing those letters acts as if `,` is pressed. For example, I can't use Russian letter `Б` because it shares a key with English comma.

Russian keyboard layout:
![image](https://user-images.githubusercontent.com/16974379/82152000-3e26b900-9867-11ea-9c40-b451096e4531.png)

What happens is I type "проблема":
![image](https://user-images.githubusercontent.com/16974379/82152266-aa55ec80-9868-11ea-8892-d5a69a1e705b.png)

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Open translation page (e.g. https://wiki.developer.mozilla.org/ru/docs/Web/CSS/box-sizing$edit)
2. Scroll to tags editor
3. Try typing `Б`

**Actual behavior**
If it's the first letter, nothing
If it's not the first, tag is considered complete, and is separated from the input

**Expected behavior**
Letter `Б` is typed.

**Additional context**
Also Russian `,`, which shares the key with English `/`, is an acceptable tag character.
![image](https://user-images.githubusercontent.com/16974379/82152322-fb65e080-9868-11ea-9ab8-2043dbb80c28.png)

**Comment by atopal** [comment]
Thanks for filing this, we are moving away from Tag in the future, so this should be less of a problem
