### ISSUE TITLE
Page "titles" aren't displaying correctly in Google results

### ISSUE THREAD

**Issue by aarongeorge** [mdn/kuma#7098]
**Summary**
When Googling "mdn html option" the search results show the title of `- HTML: Hypertext Markup Language | MDN` despite the title tag having the value `<option> - HTML: Hypertext Markup Language | MDN`

**Steps To Reproduce (STR)**

1. Google `mdn html option`
2. Look at the title `- HTML: Hypertext Markup Language | MDN`
3. Visit [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option)
4. Look at the `title` meta tag value `<option> - HTML: Hypertext Markup Language | MDN`

**Actual behavior**
When looking at the results for the Google search `mdn html option` the title that Google shows is missing the html tag, making the title seem not relevant in some cases.

Note: This isn't with all tags, searching for `mdn html input` show the html tag just fine.

**Expected behavior**
Google should be showing the html tag in the results title as that is what is in the title meta tag of the page

**Additional context**
If this is an issue with Google sanitizing some of the titles then I would recommend replacing the `<` with `&lt;` and the `>` with `&gt;`

**Comment by peterbe** [comment]
This is what I see. in Firefox based in the US. 
<img width="741" alt="Screen Shot 2020-05-18 at 12 41 18 PM" src="https://user-images.githubusercontent.com/26739/82238225-f0608e00-9904-11ea-919a-29d1b587e798.png">

**Comment by atopal** [comment]
Thanks for filing this aarongeorge, but I think this is a case where Google is experimenting with what to show. I couldn't reproduce this either.

**Comment by aarongeorge** [comment]
My apologies, it's DuckDuckGo doing it, not Google 🤦‍♂️

<img width="775" alt="image" src="https://user-images.githubusercontent.com/1924496/82269942-82749f00-99b6-11ea-853d-2db0943ee5fe.png">
