### ISSUE TITLE
Code snippets gets translated by Google Translate

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#7101]
This should not happen. 
<img width="598" alt="Screen Shot 2020-05-18 at 2 28 21 PM" src="https://user-images.githubusercontent.com/26739/82250854-3bd16700-991a-11ea-932c-6b394f7980ad.png">

From: https://translate.google.com/translate?sl=auto&tl=sv&u=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FLearn%2FCSS%2FFirst_steps%2FWhat_is_CSS

**Comment by peterbe** [comment]
I'm editing the title because the issue should be about the problem and not the solution. 
And I'm bumping the estimate because I need to do some research to better understand it and it's hard to test things with Google Translate without doing a prod release and waiting a week.

**Comment by peterbe** [comment]
Interestingly, there's an HTML5 attribute [`translate=no`](https://html.spec.whatwg.org/multipage/dom.html#the-translate-attribute) but it didn't work. 
However, using this tip worked: https://stackoverflow.com/a/9629628/205832
When I turn make it this:
```html
<pre class="brush: css notranslate">h1 {
    color: red;
    font-size: 5em;
}</pre>
```
it now worked:
<img width="888" alt="Screen Shot 2020-06-02 at 2 47 48 PM" src="https://user-images.githubusercontent.com/26739/83557901-6ad20600-a4e0-11ea-9caf-ca2ec72d76ad.png">

And it works with the Chrome extension too:
<img width="892" alt="Screen Shot 2020-06-02 at 2 53 21 PM" src="https://user-images.githubusercontent.com/26739/83558333-dfa54000-a4e0-11ea-8452-2dc6a956d67b.png">

Now, in my site, that I used for preliminary testing, I don't have `prism` installed to mutate the DOM. My next task is to try this whole thing using actual Kuma. Let's see!

**Comment by peterbe** [comment]
Interestingly, I can't reproduce the original bug with the Chrome extension:
<img width="1173" alt="Screen Shot 2020-06-02 at 3 04 20 PM" src="https://user-images.githubusercontent.com/26739/83559339-69a1d880-a4e2-11ea-9d50-2eeae250acac.png">

But I can definitely reproduce it with their web service:
<img width="1091" alt="Screen Shot 2020-06-02 at 3 05 01 PM" src="https://user-images.githubusercontent.com/26739/83559386-7f170280-a4e2-11ea-9a73-ee7daa07da76.png">

**Comment by peterbe** [comment]
@atopal FYI, this has been implemented in Yari too so we get that feature when we upgrade too.
