### ISSUE TITLE
incorrect operation of input with type number

### ISSUE THREAD

**Issue by hallaMahyn** [mdn/kuma#7104]
While use Firefox browser can add string character to  input with type="number"

<img width="1034" alt="изображение" src="https://user-images.githubusercontent.com/31703093/82346081-b5428580-99fe-11ea-98c8-4a7d2d4c232e.png">

**Comment by peterbe** [comment]
If you believe this is incorrectly/buggy implemented in Firefox, I would advice you use https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox instead. 

I'm not sure which page on MDN you're referring to but it might be interesting that you add to the content, a warning about this browser vendor implementation.
