### ISSUE TITLE
Django User admin not working related to stripe_customer_id

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#7115]
**Summary**
<img width="1450" alt="Screen Shot 2020-05-20 at 1 01 52 PM" src="https://user-images.githubusercontent.com/26739/82475221-28e5a080-9a9a-11ea-948f-be97bf2c15d6.png">

There *exists* a user with that username. 
The user is there. I can manually type in the URL http://localhost.org:8000/admin/users/user/1311/change/ and it works. 

It's related to `IsStripeCustomer` in `kuma/users/admin.py`.

**Steps To Reproduce (STR)**

1. Have a user with and without a `stripe_customer_id`
2. Go to http://localhost.org:8000/admin/users/user/
3. Is the user appearing?

**Actual behavior**
_What actually happened?_

**Expected behavior**
_What did you expect to happen?_

**Additional context**
Pretty sure it's the `IsStripeCustomer` thing that's filtering on the empty string even if you didn't filter on it.

**Comment by peterbe** [comment]
I suspect that in here https://github.com/mdn/kuma/blob/f9206d32e598d3661af90bf33b1dd41b9d8aad5b/kuma/users/admin.py#L31-L35 we need to look at `self.value()` more closely.

**Comment by peterbe** [comment]
@atopal I think we'll probably turn this one into a P1 and have a resolution before we launch Stripe/Subscriptions but I think the Django User admin is busted at the moment. Users are simply not showing up. I think you work around it by filtering on "Yes" and "No" on the "By is Stripe Customer" filter.

**Comment by atopal** [comment]
Yeah, would be nice, but not urgent. I don't really have a use case for this for now. Let me know if you do.
