### ISSUE TITLE
Boomark Sync up

### ISSUE THREAD

**Issue by rajeshraj159** [mdn/kuma#7138]
**Summary**
_Whenever I update or switch devices, the bookmark content is not getting Synchronize, If I login into firefox account? In chrome browser as soon as we sign in to our account, all the bookmark get automatically synchronize._

**Proposal**
_Can you add this feature, as soon as we sign in to firefox account, all the bookmarks will be synchronized automatically? Also see the chrome browser and implement some of the features. As firefox is very good browser._

**Comment by escattone** [comment]
@rajeshraj159 This repo is for [MDN Web Docs](https://developer.mozilla.org) only and I suspect you wanted to submit your request to the Firefox team? You might want to try https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox instead. Cheers.
