### ISSUE TITLE
Recovery Key

### ISSUE THREAD

**Issue by JenLoA1** [mdn/kuma#7143]
**Summary**
_What support task would you like completed by the team?_
I would like my passwords and websites recovered!

**Rationale**
_What problems would this solve?_

It would solve me having a great loss of a lot of information, websites and passwords that I have been using for a very long time and trusted Mozilla to retain. 
**Due Date**
_When would you like this task completed by?_
NOW please! Today

**Additional context**
_Is there anything else we should know?_
I put in my correct password for Mozilla and used the last recovery key that was generated. I used the code I was sent via email from the site. Nothing worked and yet again I had to reset my password and lose everything. It's like this happens once a year or every other year and this has to be fixed. If you give keys and codes, they should work! I need that information back please.

**Comment by peterbe** [comment]
This repository is for the website https://developer.mozilla.org
If you have trouble with your Firefox Accounts try https://support.mozilla.org/en-US/ or https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox

**Comment by peterbe** [comment]
> ultimately lead me to your website to put in a ticket!

That cannot be. Neither Bugzilla or support.mozilla.org says to solve the problem by using [MDN Web Docs](https://developer.mozilla.org) 's GitHub repo. 
I suspect what you're experiencing is, but possibly a user error, that your Firefox isn't working as expected. If you file a bug on Firefox, the triaging people there might say you're using it wrong and they'll send you to the support site to learn more about how to use Firefox.
