### ISSUE TITLE
URL correction request

### ISSUE THREAD

**Issue by laampui** [mdn/kuma#7144]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The url of this page is not correct.
[https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/async允许声明一个函数为一个包含异步操作的函数](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/async%E5%85%81%E8%AE%B8%E5%A3%B0%E6%98%8E%E4%B8%80%E4%B8%AA%E5%87%BD%E6%95%B0%E4%B8%BA%E4%B8%80%E4%B8%AA%E5%8C%85%E5%90%AB%E5%BC%82%E6%AD%A5%E6%93%8D%E4%BD%9C%E7%9A%84%E5%87%BD%E6%95%B0)

It should be like this one. This url will redirect to the above url. werid...
[https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/async_function](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/async_function)

**Comment by caugner** [comment]
This has meanwhile been fixed.
