### ISSUE TITLE
E - Increase payment options

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#7155]
# User story
As a ..., I want to ..., so I can ...

*Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.*

# Acceptance criteria

- [ ] This is something that can be verified to show that this user story is satisfied.

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by bensternthal** [comment]
Closing as no longer valid.
