### ISSUE TITLE
Add telemetry for every MDN feature

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#7158]
**Summary**
We have a very limited view into how people used MDN, because we don't have telemetry for most features of MDN. Page View data is way too coarse in most cases.

**Audience**
The MDN product team. 

**Rationale**
When we make decisions about removing features, it's often not based on data, but perceived value.

**Workaround**
Without data the fallback is gut feeling, common sense or asking for instrumentation, which takes not only the time to implement the instrumentation, but time to gather data.

**Proposal**
Add instrumentation (events) for every new MDN feature, and as many existing features as possible.

**Additional context**
It would probably make sense to come up with a framework for instrumentation (naming, hierarchy, etc) that we can just re-use instead of ad-hoc decisions.

**Comment by peterbe** [comment]
> Add instrumentation (events) for every new MDN feature, and as many existing features as possible.

I think this is a bad idea. It leads to bloat. Before you know it you have a bunch of heavy JS causing CPU drain that nobody actually looks at anymore. I've been there myself when I discovered how easy it was to add metrics that get sent to Datadog. Granted, the Datadog agent speaks UDP so the cost is fractional. 



> It would probably make sense to come up with a framework for instrumentation

I like this a lot!
It means there might be a lag between "Oh I wonder how many people ever click that thing" until you can start collecting. But the lag might be healthy inertia that proves that it's important enough to measure. 

And speaking of frameworks, I think...

A) There should be a protocol for experimentation where every aspect starts with a **document** and the document needs to have a name/identifier, hypothesis, motivation, population, github issue, and end date. And in the code, as we write the JS to support it we *have* to mention that name/identifier. 

B) We'll need to investigate using something other than Google Analytics. If we roll "our own" we might be getting 100% of users. Perhaps Segment has a product we can leverage?

Instrumentation should be an implementation detail of the experiment. Not the other way around.
