### ISSUE TITLE
Re-render pages for fresh compat data

### ISSUE THREAD

**Issue by Elchi3** [mdn/kuma#7160]
**Summary**
Run [this gist](https://gist.github.com/escattone/2f1a27a16ebd4233b0f1197a58eb9c0a) within a `./manage.py shell_plus` on a celery-worker pod, and scale-up the **api** and **kumascript** pods to six (6) pods each (`kc scale --replicas=6 deploy api kumascript`) before I make the run. It usually takes about 1-2 hours to render about 20K documents.

**Rationale**
MDN users need to see the latest mdn-compat-data (v1.0.23).

**Due Date**
Until end of May.

**Acceptance Criteria**
- [x] All documents that use the `compat` macro have been successfully re-rendered on prod

**Additional context**
Previously: https://github.com/mdn/sprints/issues/3196
Previously: https://github.com/mdn/sprints/issues/3024

**Comment by escattone** [comment]
I re-rendered 21,647 documents that use the `compat` macro in 67 minutes.
