### ISSUE TITLE
T - Sendinblue webhook for users unsubscribing through the mail

### ISSUE THREAD

**Issue by Gregoor** [mdn/kuma#7171]
Schalk made me aware that this wasn't implemented yet. It means the user profile wouldn't accurately show a user's subscription status, if they unsubscribe through the link in the email. And worse, they'd get re-subscribed if they changed their email / payment status.

API docs (relevant for implementation):
https://developers.sendinblue.com/reference#createwebhook

**Comment by peterbe** [comment]
I know there's https://github.com/mdn/kuma/issues/7172 as well so these two issues are possibly interlinked. 
I wonder if we could do what we did with Stripe in that the Webhook is a luxury but you can kinda live without it. I.e. if you ever click the "Accounts Settings", on that React page, we trigger an XHR request to `/api/v1/account/newsletter-subscription/?sync=true` or something that async fetches your newsletter status but also talks to Sendinblue's API to make sure things are synchronized.
