### ISSUE TITLE
T - Acct Settings: Subscriptions CTA

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#7175]
## Acceptance Criteria

- [ ] Non-subscribers see a link in the user navigation menu titled "Support MDN"
- [ ] Clicking the link takes the user to the subscriptions landing page
- [ ] Subscribers see a link in the user navigation menu title "Member Perks"
- [ ] Clicking the link takes the user to the subscriptions thank you page

### Non-subscribers

![Screenshot 2020-06-01 at 10 02 00](https://user-images.githubusercontent.com/10350960/83388617-084d0d00-a3ef-11ea-92ec-4b261fed5ea4.png)

## Subscribers

![Screenshot 2020-06-01 at 09 37 13](https://user-images.githubusercontent.com/10350960/83388643-126f0b80-a3ef-11ea-8065-d3404c49a21f.png)

**Comment by tobinmori** [comment]
Note: we'll do this post-subscription launch.

**Comment by bensternthal** [comment]
Closing as no longer valid.
