### ISSUE TITLE
T - Identify suboptimal use of Sass mixins

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#7183]
SASS is powerful but, if one is not careful you can shoot yourself in the foot :) This task is to have a look through our existing SASS and see if there are places where could be using features such as `mixins`, `extends` etc. more effectively to avoid unnecessary bloat.

**Comment by tobinmori** [comment]
@atopal - @schalkneethling has taken a look at this and is thinking that this will be better fixed by the new design system over time (rather than a concrete implementation). is it ok if we close this for now?

**Comment by atopal** [comment]
Okay, but can we get a summary of that assessment in here from Schalk, before we close this?
