### ISSUE TITLE
Web Console remoting page is outdated

### ISSUE THREAD

**Issue by farhan-sauce** [mdn/kuma#7195]
# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:
https://developer.mozilla.org/en-US/docs/Tools/Web_Console/remoting

# Details
- `listTabs` method response is changed, it doesn't contain `consoleActor` anymore after Firefox v75. Please update this document and let me know where `consoleActor` is moved.

I have created bug as well before few weeks https://bugzilla.mozilla.org/show_bug.cgi?id=1639842 but nobody responded there yet. 

Please Help me out. Thank you.

**Comment by chrisdavidmills** [comment]
This is not something I can really help with; it is outside my sphere of knowledge. It would be better to perhaps start by asking the devtools folks about this. If they can provide information, then maybe we can update this page, or maybe there is more up to date info somewhere else already, in which case we can retire this page.

There's a lot of useful info on https://firefox-dev.tools/, in terms of who to contact.

**Comment by farhan-sauce** [comment]
Thanks a lot @chrisdavidmills :-)
