### ISSUE TITLE
Changing UI language is gone?

### ISSUE THREAD

**Issue by obrousseau** [mdn/kuma#7197]
**Summary**
Hello team!

I am definitely interested in testing out the DEveloper Edition of Firefox. But something seems off in the language section of the Options menu.

The option to change the UI language is not there, compared to the standard Firefox edition. Is this a desired/upcoming change?

**Rationale**
Switching UI language in the Developer Edition of Firefox. Currently, it seems to default to one of my Windows keyboard setting (Canadian French) instead of my Windows language (which is in English) and my standard Firefox language (English too).

**Due Date**
It's not a dealbreaker, just an answer would be very fine :)

**Additional context**

**Comment by peterbe** [comment]
Which locale are you viewing the home page in?

**Comment by schalkneethling** [comment]
@obrousseau Hey, thank you for reaching out. Sounds like your particular problem related to the Firefox browser itself and not the MDN Web Docs website. I would recommend having a look at our official support website at https://support.mozilla.org/en-US/
