### ISSUE TITLE
A - Shortlist solutions for "Reduce Payment Friction with monthly subscription" 

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#7201]
# Action Item 
A - Shortlist solutions with the product team

**Comment by malqinneh** [comment]
Completed product team [ideation session](https://miro.com/app/board/o9J_krxH90g=/) and added shortlist solutions to [opportunity solution tree](https://miro.com/app/board/o9J_kxyeXQQ=/). Closing :)
