### ISSUE TITLE
Menu looks very odd on mobile iOS

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#7203]
**Summary**
See screenshot:
![IMG_3F0D76AD5140-1](https://user-images.githubusercontent.com/26739/83883133-13ff4300-a711-11ea-869d-d67ebd879fd3.jpeg)

* There's a LOT of empty whitespace. 
* The little triangle arrows point down. 
* Clicking items in the menu closes the menu

Here's how it looks like with one of them clicked
![IMG_ED58C4A20345-1](https://user-images.githubusercontent.com/26739/83883301-4f9a0d00-a711-11ea-9e75-14e06e20e8e6.jpeg)

**Steps To Reproduce (STR)**
Use your iOS browser

Note that it's hard to take a screenshot of what happens when you click one of these links. But the effect is the same as if you had just closed one of the menus and then suddenly a second later the page reloads. 

**Additional context**
There are a lot of balls in the air with the nav and the design of it but I tested inside the branch of https://github.com/mdn/kuma/pull/7196 and I tested against prod.

**Comment by atopal** [comment]
I get your first two points Peter, but not the last. What would you expect to happen?

**Comment by tobinmori** [comment]
Todo: break up these into individual issues.

**Comment by schalkneethling** [comment]
> Todo: break up these into individual issues.

I am happy to do this @tobin and @peterbe - The breaking up and the fixing 😺

**Comment by schalkneethling** [comment]
Closing in favor of:

- https://github.com/mdn/kuma/issues/7220
- https://github.com/mdn/kuma/issues/7221
