### ISSUE TITLE
Articles don't get updated

### ISSUE THREAD

**Issue by DariaErmakova** [mdn/kuma#7204]
**Summary**
I've updated two articles, but cannot see changes, they are only visible in edit mode
https://wiki.developer.mozilla.org/uk/docs/Web/JavaScript/Reference/Statements/for...in
https://wiki.developer.mozilla.org/uk/docs/Web/JavaScript/Reference/Statements

**Steps To Reproduce (STR)**

1. Open articles: https://wiki.developer.mozilla.org/uk/docs/Web/JavaScript/Reference/Statements/for...in
https://wiki.developer.mozilla.org/uk/docs/Web/JavaScript/Reference/Statements
2. Open History and select to compare two latest versions

**Actual behavior**
New content isn't displayed.

**Expected behavior**
New content should be visible.

**Comment by DariaErmakova** [comment]
updated

**Comment by escattone** [comment]
@DariaErmakova Thanks for reporting! We had a problem that started last night and lasted until this morning with too many open connections on our database instance, and I suspect that is what caused your issue. Sorry for the inconvenience!
