### ISSUE TITLE
A - Reached an agreement with product team on solution(s) to implement (Call to Action)

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#7208]
# A - Reached an agreement with product team on solution(s) to implement (Call to Action)

**Comment by malqinneh** [comment]
> * [Non-dismissible banner](https://share.goabstract.com/8d952c8f-e412-49e8-bdb8-9b6ff515e45d?collectionLayerId=294b40bf-4071-41e2-841a-c88898f08894&mode=design)
> * [CTA below article pages](https://share.goabstract.com/0b291bae-5f42-4a78-8df2-547f02bd9a72?collectionLayerId=83b85d61-aa4d-4ecf-9639-59e1c802fba2&mode=design)
> * [CTA in header](https://share.goabstract.com/828dda83-6e21-4e56-b3d3-5a7125384223?collectionLayerId=475ad950-4da4-408b-b461-816418545692&mode=design)

There are a couple of alternate options within the Abstract collection. Need to decide on which solution we will implement for next sprint cc @atopal @tobinmori. I'll schedule a meeting to discuss tomorrow.

**Comment by malqinneh** [comment]
Discussed with the product team and the decision is to launch MDN subscriptions with:

- [CTA below article pages](https://share.goabstract.com/0b291bae-5f42-4a78-8df2-547f02bd9a72)
- [CTA in header](https://share.goabstract.com/828dda83-6e21-4e56-b3d3-5a7125384223)

We will then add the banner if engagement is low/to increase engagement.
