### ISSUE TITLE
Fake site

### ISSUE THREAD

**Issue by avi12** [mdn/kuma#7210]
**Summary**
I found via a Google search [webassembly instantiatestreaming](https://www.google.com/search?q=webassembly+instantiatestreaming&newwindow=1&sxsrf=ALeKk035bw1BYNqk65o--oKCRsUkYJwBTg:1591538584883&source=lnt&tbs=qdr:y&sa=X&ved=2ahUKEwjm8_2f7-_pAhUqVRUIHanTD8cQpwV6BAgNEB4&biw=1918&bih=2039) a [fake site](http://s0developer0mozilla0org.icopy.site).

**Comment by peterbe** [comment]
That's unfortunate. They're stealing our content and displaying it under their own domain without the appropriate `canonical` head tag. 
Thankfully Google is pretty good at weeding out sites like this. Nothing we can do anything about. 

By the way, my Google search isn't linking to that page in any of the search results on the first page.
