### ISSUE TITLE
T - The PreviousMenu and NextMenu macro link styling on learning area articles is broken

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/kuma#7216]
**Summary**

On pages such as https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals, https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Introduction, and https://wiki.developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Your_own_automation_environment, the styling of the previous/menu links has gone really wrong. This happened at some point since the React front end was launched. The links are being given all kinds of weird inline styles.

In newer pages, they look OK (e.g. https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Introduction)

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Go to https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals

**Actual behavior**

The previous/next links look problematic

**Expected behavior**

they look OK, and consistent across different pages.

**Comment by Elchi3** [comment]
Also broken on the JavaScript guide. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

**Comment by schalkneethling** [comment]
Here is another identified by @peterbe - https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/What_is_CSS
