### ISSUE TITLE
T - Reduce height of mobile navigation 

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#7220]
**Summary**

Originally reported in https://github.com/mdn/kuma/issues/7203

When the navigation menu is shown on mobile it takes over the entire height of the viewport. Our menu has very few initial entries when shown and so we can do without all the additional white space.

Interaction with the menu is also a bit jarring on a slow connection as it is not immediately clear that a new page load has been triggered.

**Steps To Reproduce (STR)**

1. Load any page on a mobile device
2. Expand the navigation
3. Expand one of the top-level entries
4. Tap on an individual entry

**Actual behavior**
The submenu collapses but, the overall overlay remain and it is not immediately clear that the tap event was captured.

**Expected behavior**
Reducing the amount of whitespace initially shown and improving the behavior of the menu on tap events will make for better overall user experience.

**Comment by schalkneethling** [comment]
This issue will be addressed as part of https://github.com/mdn/mdn-fiori/issues/170

**Comment by schalkneethling** [comment]
@malqinneh in reducing the height of the nav I am wondering, should we add a bit of a box-shadow or no?

## With a shadow

![with-shadow](https://user-images.githubusercontent.com/10350960/88278658-09116980-cce3-11ea-8ade-38aa6a1047c0.png)

## Without a shadow

![no-shadow](https://user-images.githubusercontent.com/10350960/88278681-13cbfe80-cce3-11ea-847c-0e9caec9bbbf.png)

**Comment by malqinneh** [comment]
Thanks for sharing these @schalkneethling. Can you please remind me whether we are able to add a shadow on the underlying page? Ie:

![shadow](https://user-images.githubusercontent.com/4819906/88294069-cee79e00-ccc9-11ea-8c22-dfc2d9fffe73.png)

**Comment by schalkneethling** [comment]
@malqinneh Nice idea, let me look into this.

**Comment by schalkneethling** [comment]
This has landed in minimalist and fiori

**Comment by tobinmori** [comment]
Exists in Yari/Design System but needs to be ported to Kuma.
