### ISSUE TITLE
Typo in spread operator page?

### ISSUE THREAD

**Issue by Keming-Z** [mdn/kuma#7224]
**Summary**
_What is the problem?_
Looks like there is a type in new revision

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax$compare?locale=en-US&to=1627917&from=1626894 

at Line 72

**Actual behavior**
_What actually happened?_
Title text: "Apply for new operator<"

**Expected behavior**
_What did you expect to happen?_
Title text: "Apply for new operator"

**Additional context**
_Is there anything else we should know?_

**Comment by Elchi3** [comment]
Thanks, typo fixed.
