### ISSUE TITLE
U - Implement additional payment options

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#7238]
# User Story 
U - Implement additional payment options 

# Acceptance Criteria 
- [ ] 

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [x] External / 3rd Party dependencies identified

**Comment by bensternthal** [comment]
Closing as no longer valid.
