### ISSUE TITLE
Username and Passwoed glitch

### ISSUE THREAD

**Issue by ggr4321** [mdn/kuma#7249]
**Summary**
_What support task would you like completed by the team?_
I am trying to login with a web site that I am a member and have money and although my username and password are correct it says Incorrect Username and Password. I can change the password and have secret code but still won't let me in

**Rationale**
_What problems would this solve?_
I have money in there which I am relying on and host isn't contactable despite numerous attempts. I am very anxious about the situation and require assistance

**Due Date**
_When would you like this task completed by?_
asap

**Additional context**
_Is there anything else we should know?_
![image](https://user-images.githubusercontent.com/59052493/85082892-b7476200-b1bf-11ea-985a-fcc567235005.png)

**Comment by escattone** [comment]
@ggr4321 The issues in this repo are for https://developer.mozilla.org only. You'll have to contact the support team of the website you're trying to log into for help.
