### ISSUE TITLE
Searching for <a> does not return <a> in results

### ISSUE THREAD

**Issue by joallard** [mdn/kuma#7251]
**Summary**
Searching for `<a>` does not return `<a>` in results.

Now I'm not exactly sure this qualifies as a bug report, but I thought I'd report it to let you know.

**Steps To Reproduce (STR)**
1. Type `<a>` in search field
2. Submit

**Actual behavior**
Page for `<a>` is not on first page of results. (Ah there it is, page 2)

**Expected behavior**
`<a>` is either first result or I get redirected to it.

(As a user, I find `<a>` easily)

**Comment by atopal** [comment]
I just checked a couple other short ones <b> doesn't work well, <em> is fine <div> is fine, etc. One letter tags are apparently not handled well.

**Comment by peterbe** [comment]
Yari's autocomplete search has the same problem :(
<img width="459" alt="Screen Shot 2020-06-22 at 10 00 48 AM" src="https://user-images.githubusercontent.com/26739/85296391-4fb73e00-b46f-11ea-8e0c-d7fbda75276b.png">

That's more of a note-to-self.

**Comment by peterbe** [comment]
https://developer.mozilla.org/en-US/search?q=%3Ca%3E now works.

**Comment by caugner** [comment]
I can confirm that this is fixed now:

<img width="601" alt="Screenshot 2022-03-17 at 15 33 11" src="https://user-images.githubusercontent.com/495429/158829073-8d3cd316-d7bf-4e7d-bfa9-a89ba888e913.png">
