### ISSUE TITLE
Text in image not centered

### ISSUE THREAD

**Issue by oregev** [mdn/kuma#7252]
# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:
https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works

# Details
The text inside the the Circle is not centered.

<img width="759" alt="Screen Shot 2020-06-19 at 18 19 00" src="https://user-images.githubusercontent.com/60711866/85188242-0e9a1080-b25a-11ea-8781-15f3ad78e1dd.png">

**Comment by oregev** [comment]
btw .. im no specialist so no advice on how to fix

**Comment by chrisdavidmills** [comment]
It was just an image, albeit not a very well drawn one. I've created a better diagram and uploaded it.
