### ISSUE TITLE
Page is in russian even though language says en-us

### ISSUE THREAD

**Issue by sportshead** [mdn/kuma#7253]
# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Hit_regions_and_accessibility
# Details
The article is in Russian. The link says `en-us`. Am I doing something wrong?

**Comment by sportshead** [comment]
And spanish is english https://developer.mozilla.org/es/docs/Web/Guide/HTML/Canvas_tutorial/Hit_regions_and_accessibility

**Comment by chrisdavidmills** [comment]
Ack, this is because someone incorrectly placed a Russain translation over the top of the English version. I've reverted that now; thanks for reporting.

And someone else started to create a Spanish translation, but then gave up pretty quickly.
