### ISSUE TITLE
Use i10n url not en-US on LocalizationStatusInSection

### ISSUE THREAD

**Issue by Ende93** [mdn/kuma#7273]
Such as [this page](https://wiki.developer.mozilla.org/zh-CN/docs/MDN/Doc_status/API/DOM), the links use `en-US`. So if i want to translate one page, I have to change url `en-US` to `zh-CN` manually and frequently which make me trouble. Please change the url.

**Comment by atopal** [comment]
Hey Ende93,  can you help me understand this one. When you click on a link like https://wiki.developer.mozilla.org/en-US/docs/Web/API/AbstractRange$translate?tolocale=zh-CN it's true that it has en-US in the URL, but once you're done on that page the zh-CN version will be created. Why do you have to change the URL in this case?

**Comment by Ende93** [comment]
Not that case of create new one, but the pages that need update.

**Comment by Ende93** [comment]
Sorry, I just notice the links that go to edit. Close it.
