### ISSUE TITLE
WebExtensions compat table and Safari

### ISSUE THREAD

**Issue by freaktechnik** [mdn/kuma#7274]
I'm not sure if this is the right place for this bug, it is quite likely in the repo for the compat table generation scripts, which I believe is a different one.

Either way, it appears that in the compat tables for webextensions with safari the border styles are messed up, especially on mobile. Between the desktop and mobile browsers, there is a wider border to make the separation clear.

![Mobile compat table](https://user-images.githubusercontent.com/640949/85468707-12f16100-b5ad-11ea-9168-31881b6d03ca.png)

However, on desktop you also get the little icons on top of the browser names, which makes it clear, that the divider line should actually be to the right of safari, and not to the left:
![Desktop compat table](https://user-images.githubusercontent.com/640949/85468633-ffde9100-b5ac-11ea-80ac-811ab9491c59.png)

**Comment by peterbe** [comment]
@schalkneethling Can you help figure out if @Elchi3 is right about @ExE-Boss 's PR?

**Comment by schalkneethling** [comment]
Thank you for catching and reporting this @freaktechnik - So subtle and easy to miss.
