### ISSUE TITLE
Password Required prompt needs to chill-out

### ISSUE THREAD

**Issue by mas-co** [mdn/kuma#7275]
**Summary**
The Password Required prompt is too eager.  Countless times I have opened Firefox, browsed to a page, and started typing on a webpage that doesn't even have a username and password and the next think I know is that the last XX letters were input into the "Password Required-Mozilla Firefox" popup.  Firefox should not change the focus away from the user's input page to the Firefox password when users are typing---especially when no passwords or logins are anywhere in sight.

**Rationale**
Changing the focus of the user from the current webpage entry form to the password-required popup disrupts user input.  Time is wasted.  Trains of thought are derailed.  

**Audience**
Every touch typist who doesn't spend 100% of the time looking at the screen when typing.

**Proposal**
Several ideas come to mind:
  1.  Wait until the user stops typing (e.g. 10 or 15 seconds), or
  2.  Do not prompt users for Firefox passwords until a username or password is sensed on the page, or
  3.  Require Firefox password to be entered when you start Firefox, or
  4.  Never show the popup window for the Firefox password without pressing a button on the toolbar (i.e. the enter "Firefox Password" button).  Perhaps make this button blink if a Firefox password has not been entered yet.

Additionally, allow users to add a Firefox Password button (or even the logins and passwords menu) from the toolbar.  (Perhaps make this button blink if a Firefox password has not been entered yet.)

**Additional context**
That's all, folks!

**Comment by escattone** [comment]
@mas-co Thanks for your detailed report, but this repo is solely focused on issues for [MDN Web Docs](https://developer.mozilla.org), and I suspect you wanted to report this to the Firefox team? You can go to https://bugzilla.mozilla.org to see how to report your issue to the Firefox team. Cheers.

**Comment by mas-co** [comment]
Sorry, my mistake.
