### ISSUE TITLE
T - Wire up UI and backend for account details

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#7279]
In https://github.com/mdn/kuma/pull/7271 the majority of the backend pieces of the user details API have landed. There is a piece that is dependant on some SendInBlue work that @Gregoor is working on. Once everything has landed, we can wire up the frontend and back end for the new user details component on the new account settings page.

## Acceptance Criteria

- [ ] A user can view their current user details
- [ ] A user can update their details(excluding email address) from the account settings page

**Comment by Gregoor** [comment]
While I'm confident that #7267 will land soon let me just in case state: It doesn't block using the user_details API as the changes made won't affect the interface of that endpoint (just some of the sendinblue innards, which no kuma instance apart from Peter's and mine are wired up to use yet anyway)

**Comment by schalkneethling** [comment]
> While I'm confident that #7267 will land soon let me just in case state: It doesn't block using the user_details API as the changes made won't affect the interface of that endpoint (just some of the sendinblue innards, which no kuma instance apart from Peter's and mine are wired up to use yet anyway)

Awesome, thanks for clarifying @Gregoor

**Comment by tobinmori** [comment]
@schalkneethling - i think the final step is that we'll need to wire up the delete button to be an href that points to the old wiki delete page here:

https://developer.mozilla.org/en-US/profiles/{USERNAME}/delete
