### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by aekarahan** [mdn/kuma#7285]
**Summary**
Please provide a dark theme for mdn documentations

**Audience**
Programmers

**Rationale**
Switching from my editor (dark mode) to your pages with white background is a torture for my eyes. Yes I have very sensitive eyes but I think I'm not the only one.  

**Workaround**
I use the browser dark mode plugin, but the result is not optimal for all colors on your pages.

**Proposal**
Provide a dark theme switch button at the right top.

Thank you

**Comment by atopal** [comment]
Thanks for filing, we have an issue for this already, so I'm closing this one: https://github.com/mdn/yari/issues/6973
