### ISSUE TITLE
T - Acct Settings: Delete Account Backend

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#7302]
The front-end of the delete account component will land in https://github.com/mdn/kuma/pull/7301

This is a partial implementation that implements the front-end but, there are some pieces missing that to tie it up. Thie following needs to be added to the API:

1. `revisions.exists()` and `attachment_revisions.exists()`
2. The `user_delete` function that currently exists here https://github.com/mdn/kuma/blob/e3809735bc7bcba3b0282478c4de46834f038620/kuma/users/views.py#L500

**Comment by peterbe** [comment]
What I had in mind is that you do: `GET /api/v1/users/delete/` and that gives you something like:
```json
{
  "revisions": 123,
  "attachment_revisions": 0
}
```

And if you do `POST /api/v1/users/delete/` you *need* to do it with a JSON request body that looks like either one of these:

```
curl -d '{"attributions": "donate"}' -H 'content-type: application/json' $URL/api/v1/users/delete/
```
or 
```
curl -d '{"attributions": "keep"}' -H 'content-type: application/json' $URL/api/v1/users/delete/
```

anything else is a 400 Bad Request.

**Comment by tobinmori** [comment]
Need an issue for wiring up front-end (close accts).

**Comment by tobinmori** [comment]
Closing this as it's unnecessary for now.
