### ISSUE TITLE
T - l10n survey

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#7315]
Need to add the l10n survey to MDN using the same banner mechanics as needs assessment and subscriptions.

Wording and layout provided by @malqinneh via Slack:

![988D72B8-5116-4CCB-9D3D-37C7735035B9](https://user-images.githubusercontent.com/10350960/86890396-8d69c700-c0fd-11ea-9490-e58a60bb5a4e.png)

## Acceptance Criteria

- [ ] l10n survey live on all MDN pages as a dismissable banner in the footer of the viewport
- [ ] Able to turn the survey on and off via the waffle flag l10n-survey

**Comment by chinikes** [comment]
Hi @schalkneethling , @malqinneh - What Story / epic is this task step related to?

**Comment by malqinneh** [comment]
> Hi @schalkneethling , @malqinneh - What Story / epic is this task step related to?

https://github.com/mdn/kuma/issues/6736
