### ISSUE TITLE
Newsletter sign-up button looks odd

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#7323]
**Summary**

It looks oddly large. Much larger than the input field above. 
And it right-arrow icon isn't aligned with the text (that's why I put that red guide line in the screenshot). I think it used to be. 
<img width="1009" alt="Screen Shot 2020-07-08 at 8 26 06 AM" src="https://user-images.githubusercontent.com/26739/86944367-a9796280-c115-11ea-997f-02385e0ca0a0.png">

**Steps To Reproduce (STR)**

1. Go 
2. to
3. https://developer.mozilla.org

**Additional context**

See https://github.com/mdn/kuma/issues/7310 which was triaged to a P3. 
But that P3 was motivated about the fact that the "Edit in wiki" button only appear the small handful of people who sign in.

**Comment by schalkneethling** [comment]
The width has been resolved. The hover color not yet :) - We need to launch our new, consistent button styles across the site.

**Comment by peterbe** [comment]
This is what it looks like now. In production. When hovering over the button. 
<img width="409" alt="Screen Shot 2020-07-10 at 9 34 33 AM" src="https://user-images.githubusercontent.com/26739/87160233-a951a200-c290-11ea-907e-bc51371123b7.png">

**Comment by peterbe** [comment]
My screenshot contradicts that you said so I dare not close this :)

**Comment by schalkneethling** [comment]
> This is what it looks like now. In production. When hovering over the button.
> <img alt="Screen Shot 2020-07-10 at 9 34 33 AM" width="409" src="https://user-images.githubusercontent.com/26739/87160233-a951a200-c290-11ea-907e-bc51371123b7.png">

It is for sure not fixed. but it is better :)
