### ISSUE TITLE
broken link on "Styling web forms"

### ISSUE THREAD

**Issue by wesleyjellis** [mdn/kuma#7336]
# Content Issue

- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:

https://developer.mozilla.org/en-US/docs/Learn/Forms/Styling_web_forms

# Details

The "in the next article" link at the bottom of the page points to nothing, I believe it should point to https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling

![image](https://user-images.githubusercontent.com/29041658/87183229-b2079f80-c2b3-11ea-88f1-1121cc810e27.png)

**Comment by chrisdavidmills** [comment]
Hi @wesleyjellis !

Thanks for pointing out this error; I've fixed it now in the source code, and the change should propagate to the final published version soon.
