### ISSUE TITLE
Searching for operators returns no results

### ISSUE THREAD

**Issue by jparker324** [mdn/kuma#7348]
**Summary**
Searching MDN for operators is not useful.  For example, searching for Javascript's [Logical nullish assignment operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment) using the operator itself `??=` as the search term provides no [Results](https://developer.mozilla.org/en-US/search?q=%3F%3F%3D)

_0 documents found for "??=" in en-US._

**Rationale**
Searching for operators by their syntax is straightforward and should return results.  Some operators are used less frequently, are new to a language, or have names that are simply difficult to remember.  The example above fits all three of these conditions.

**Audience**
Developers

**Proposal**
Search results should contain links to operator pages containing the search term.

**Additional context**
I tried a some different operators, some simple (`=`, `!`, `>`) and some complicated (`>>>`, `**`, `===`).  All have no results.

I didn't see any ability to support this on the [Search on MDN](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Tools/Search) page either.

**Comment by ccbonacci** [comment]
Hi, 
I had the same experience : no results
Not long ago, I needed to find the difference between two operators, I couldn't find a result without names.

I would like to help solve this problem but I never did that!
I don't know how to do it, but I'm willing to learn and maybe to help.
Small clarification : I'm beginner :)

It'll be great for others, that they can find a result only with operator.
I will think about this problem; How to do that ? 

So see you soon
Carole

**Comment by tobinmori** [comment]
Thanks @ccbonacci. This is a known issue. Unfortunately, searching on short strings is a challenge with search, but we'll add it to our backlog.

**Comment by peterbe** [comment]
https://developer.mozilla.org/en-US/search?q=%3F%3F%3D now works.
