### ISSUE TITLE
"What are we missing?" not able to be filled due to hidden content

### ISSUE THREAD

**Issue by Nicd** [mdn/kuma#7352]
**Summary**
_What is the problem?_

Try to fill the "what are we missing" browser compatibility report for flex layout section on this page: https://developer.mozilla.org/en-US/docs/Web/CSS/gap

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Go to page
2. Click on "What are we missing?" under "Support in Flex layout" table
3. Observe form

**Actual behavior**
_What actually happened?_

Form looks like this, there are duplicate browsers and I cannot see a way to continue:

  
<img width="1050" alt="Screenshot 2020-07-15 at 8 45 11" src="https://user-images.githubusercontent.com/273137/87508803-d929ec80-c678-11ea-8687-58459693fd2e.png">

**Expected behavior**
_What did you expect to happen?_

I assume there is some way to continue the form that is hidden because the drawer doesn't open far enough. With inspector I can see that this is the case. Also the browsers should not be duplicated.

**Additional context**
_Is there anything else we should know?_

Occurs on Firefox 78.0.1 and Chrome 83 on macOS 10.14.6.

**Comment by atopal** [comment]
Thanks for filing this Nic. 

Maybe the code doesn't expect more than one compat table on a page.
