### ISSUE TITLE
Empty code results sections on page about heading styles

### ISSUE THREAD

**Issue by Ayrum1158** [mdn/kuma#7353]
# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:
https://developer.mozilla.org/ru/docs/Web/HTML/Element/Heading_Elements

# Details
Empty code results

![image_2020-07-15_13-50-16](https://user-images.githubusercontent.com/48748868/87536670-23739380-c6a2-11ea-8c04-cfc8d3e385ab.png)

**Comment by chrisdavidmills** [comment]
This is because the page was translated, but the live sample macro calls still referenced the English heading IDs, e.g.

```
{{ EmbedLiveSample('All_headings', '280', '300', '') }}
```

I updated them so that they referenced the new Russian heading IDs, and problem solved.

Thanks for reporting!
