### ISSUE TITLE
Re-render /Learn and /Tools

### ISSUE THREAD

**Issue by Elchi3** [mdn/kuma#7355]
**Summary**
Please re-render all pages under 
https://developer.mozilla.org/en-US/docs/Learn
https://developer.mozilla.org/en-US/docs/Tools

**Rationale**
@chrisdavidmills updated the sidebars and readers should see the updated sidebars

**Due Date**
Within this month should be enough I reckon.

**Additional context**
No additional comments for me. Keep up the great work, Ryan!

**Comment by escattone** [comment]
I've completed the re-rendering of both https://developer.mozilla.org/en-US/docs/Learn and https://developer.mozilla.org/en-US/docs/Tools, their translations, all of their descendants, and all of the translations of their descendants.
