### ISSUE TITLE
minor improvement to MDN javascript documentation

### ISSUE THREAD

**Issue by BKSpurgeon** [mdn/kuma#7356]
# Content Issue
- [x] Correction or update

# URL of page you are seeing the problem on:
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Timeouts_and_intervals

# Details
Refer to this line: 

> Insert` a <script> element just above the </body> tag.

It might not be altogether clear to readers. the problem is that if you put it above the <body> tag (and not the </body> tag, then the script won't work, because the dom will not have loaded. 

I could not find where to make the Pull request to put fwd the proposed changed. If you could point me to that, I will put in a PR and save you the trouble.

rgds

Ben

**Comment by chrisdavidmills** [comment]
Hi @BKSpurgeon !

I'm not 100% sure what you mean here — can you clarify?

I'm saying that the reader should insert a script element above the closing `</body>` tag, and by that I mean `<script></script>`. When the example JS is inserted inside the script tags, the dom will have loaded before it is run, so the example works fine.

Ideally for modern best practices, we should use `<script src="main.js" defer>` in the head of the document, but from experience I find it is just easier to get readers to insert the script all in one file, instead of trying to get them ot create separate files.

Are you worried that readers might confused about what I mean when I say `<script>` element, i.e. just the opening tag, or both tags, etc.?

**Comment by BKSpurgeon** [comment]
> I'm not 100% sure what you mean here — can you clarify?

Here are the instructions:

> Insert a <script> element just above the </body> tag.

And here's what I did (incorrectly):

```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <title>My test page</title>

<script> <-- I inserted it here above the body tag. Actually I had misread the instructions. The dom will not have loaded. I was wondering why it wasn't working. I inserted it above the body tag, right? -->
</script>
  </head>
  <body>
    <p>This is my page</p>
  </body>
</html>
```
I propose a PR which shows where to add the script: e.g. instead of this: 

> Insert a <script> element just above the </body> tag.

to instead add these instructions in a format like so (hopefully reducing the chances of confusion creeping in).

```html
  <body>
<---- INSERT THE SCRIPT HERE ---->
  </body>
```
I would have submitted the PR directly to the maintainers of the repo for review, but I could not find the repo. 

rgds

Ben

**Comment by chrisdavidmills** [comment]
Hi @BKSpurgeon , thanks for the clarification.

So you've put it above the closing `</head>` tag, whereas the instructions say to put it above the `</body>` tag.

I've updated it slightly, to say put it above the closing `</body>` tag, hopefully making it a bit more obvious. there is also a note at the end of the section pointing at the finished code, so people can check it if things are not working.

I don't really want to add a comment into the starter template to talk about where to add the script element, as that is a generic starter template that is used in many different examples.

**Comment by BKSpurgeon** [comment]
> So you've put it above the closing </head> tag, whereas the instructions say to put it above the </body> tag.

Exactly. 

> I've updated it slightly, to say put it above the closing </body> tag, hopefully making it a bit more obvious.

the ideas put fwd are by no means prescriptive - i just put them fwd for consideration to the maintainers, to be accepted or rejected as the maintainers see fit. i hope it helped.

thank you for the work put into this guide.

rgds

Ben
