### ISSUE TITLE
git link not working

### ISSUE THREAD

**Issue by kpilkk** [mdn/kuma#7369]
# Content Issue

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# URL of page you are seeing the problem on:
https://developer.mozilla.org/en-US/docs/Python/Virtualenv
![firefox](https://user-images.githubusercontent.com/18394739/87972260-3cd27080-cae4-11ea-9683-99f1a9291c3f.jpg)

# Details

I've changed the link of `setup_development.py`, but git link is deprecated. I don't know the latest link or how to find it. But, I've found the latest link of `setup_development.py`, which I've updated.

**Comment by chrisdavidmills** [comment]
I've just deleted that section, as it will no longer work, given that mozbase is not longer on GitHub.

I've also moved this page to https://developer.mozilla.org/en-US/docs/Mozilla/Virtualenv, as it was a child of a section that no longer exists.
