### ISSUE TITLE
Download file on "Top sites"

### ISSUE THREAD

**Issue by amidmm** [mdn/kuma#7371]
**Summary**
If a URL which refers to a file gets into the "Top sites", it will get repeatedly downloaded.

**Actual behavior**
Downloads the file instead of showing thumbnail

**Expected behavior**
Don't show the thumbnail for the file's URL

**Comment by peterbe** [comment]
@amidmm What page are you referring to?

**Comment by atopal** [comment]
"Top sites" is a Firefox feature. I'm assuming this is not MDN related. Please feel free to ask for this to be reopened, if that is wrong, amidmm.
