### ISSUE TITLE
T - Implement banner for users to sign up for a user interview

### ISSUE THREAD

**Issue by malqinneh** [mdn/kuma#7380]
# Description
Implement banner for users to complete a screener and participate in a user interview with MDN team.

## Screener link
Please embed this link in [Sign up] button:
https://validately.com/moderated/e9086e05-092b-4453-8efd-360f434bf820

## Mock-up
![banner.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/79f9bb66-b342-4ea8-bb71-fb5cb9347a3c)

## Follow-up

Mustafa to monitor number of participants scheduled for interviews in the coming months and create a separate issue for turning off the banner once we've filled enough users.

**Comment by malqinneh** [comment]
@schalkneethling @tobinmori @atopal please double-check the description above and let me know if I missed anything.

**Comment by atopal** [comment]
Thank you Mustafa. Schalk, I'd suggest taking this in as another P1 for this sprint.

**Comment by peterbe** [comment]
Yari already has a duplicate implementation of the same banner code as Kuma has. (Except it's in TypeScript). It was part of the `kumastyles` project which is more than just `.scss` files.

This is the first fork where they've diverged. 

We need to either not do anything. Or we need to file an issue in Yari to implement it there too. Or, we do something even smarter. 

It all depends on when Yari 1 launches (roughly end of year 2020) and how long this banner needs to live. 
Or, if we don't need this banner ever in Yari (if Yari launches around end of the year) then we need a new issue in the Yari repo about deleting the banner code for `L10NSurveyBanner`.

PS. This task doesn't link to its user story. So I'm going to hijack this task issue to raise the topic.

**Comment by schalkneethling** [comment]
@peterbe This is similar in nature to the l10n banner i.e. short lived.
