### ISSUE TITLE
Page "Arithmetische Operatoren" (German) broken

### ISSUE THREAD

**Issue by strenkel** [mdn/kuma#7388]
**Summary**
The page https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators shows 404 in a section.

**Steps To Reproduce (STR)**
Just open https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators

**Actual behavior**
In the first section you see:

404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: pages/js/expressions-arithmetic.html
    RequestId: 56F5B5F5324929A0
    HostId: 2L0E5Y/DwBLaEo6N9m3foSAv6/UWZrLGOuXcNj9HBFiBKlKIcfh9F4kpDAbrG6s9e0yWwDZA/h4=

An Error Occurred While Attempting to Retrieve a Custom Error Document

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: error.html

**Expected behavior**
No 404.
![screenshot-developer mozilla org-2020 07 31-11_07_12](https://user-images.githubusercontent.com/7606054/89020132-b35e4200-d31e-11ea-9ba0-ffd5cdbfc81e.png)

**Additional context**
_Is there anything else we should know?_

**Comment by escattone** [comment]
This page should have redirected to https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Operators, which I've modified it to do now. Thanks for letting us know @strenkel!
