### ISSUE TITLE
A - Communicate L10n decision to larger community

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#7397]
We want to make sure that whatever decision we arrive at regarding L10n on MDN has been vetted and informed by the community. We also want to give everyone ample time and ensure that the community is not surprised by the action we'll take later this year.

Acceptance Criteria:
- [ ] L10n decision is shared with core community
- [ ] L10n decision is updated after meeting with core community
- [ ] Comms team is notified
- [ ] L10n decision is posted to public forum

**Comment by peterbe** [comment]
We've long ago sent those communications.
