### ISSUE TITLE
Inconsistency between navigator.mediaDevices in http and https mode

### ISSUE THREAD

**Issue by matjung** [mdn/kuma#7404]
**Summary**
_What problem would this solve?_
A http hosted web page / JS could access the Web Cam or Microphone

**Audience**
_Who has this problem? Everyone? Article authors? Etc._
People who write javascript software for web conferencing solutions.
People who do not have the money for a SSL/TLS certificate or don't know how to handle it
Some Webhoster in frontier level countries

**Rationale**
_How do you know that people identified above actually have this problem?_
While a lot of people work with https there are still plenty of web servers with http around

**Workaround**
_How are the people identified above currently handling this problem?_
People use stand alone clients like Skype, Whatsapp, Yahoo, ICQ, Zoom, TeamViewer, etc.

**Proposal**
_Do you have suggestions for solving this problem?_
Maybe some settings in about:profile could address that topic.
Maybe there is already a setting around that I do not know
I think the User should decide if he permits or rejects Webcam Request independently from loading the document securely or unsecurly.

**Additional context**
_Is there anything else we should know?_
Firefox is not the only one that distinguishes between http and https, so does Chrome.
Edge provides navigator.mediaDevices in both http and https mode

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Security

If the current document isn't loaded securely, navigator.mediaDevices will be undefined, and you cannot use getUserMedia(). See Security for more information on this and other security issues related to using getUserMedia().

Note: The security model for getUserMedia() is still somewhat in flux. The originally-designed security mechanism is in the process of being replaced with Feature Policy, so various browsers have different levels of security support, using different mechanisms. You should test your code carefully on a variety of devices and browsers to be sure it is as broadly compatible as possible

**Comment by peterbe** [comment]
I very much doubt that the major browser vendors is going to ever allow things like `navigator.mediaDevices.getUserMedia` on `http` (unless the hostname is `localhost`). 

HTTPS is free thanks to LetsEncrypt. More and more websites are hosted by somebody else who takes care of the certificates and stuff. E.g. Heroku. 

Either way, there's nothing wrong with the content and if you genuinely want to convince the major browser makers to reverse the security policy about non-trivial browser APIs on insecure sites then I think you freely can but it might serve to do a little deeper research into the underlying justifications they used for this policy.
