### ISSUE TITLE
Shutting down wiki.develop.mozilla.org gracefully

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#7406]
In Yari 1, the idea is quite simple:

1. We shut down `wiki.developer.mozilla.org`
2. All `/$locale/docs/*` views are served exclusively from S3 (via CDN) and the docs got put into S3 by Yari. 
3. All other non-document things are served from Django (via CDN)

But exactly how should we shut down the wiki? Perhaps we can put in a redirect to something like:
https://github.com/mdn/yari/blob/master/docs/wiki-is-no-more.md independent of the pathname. 
Or, if people are still using it a lot for viewing documents, perhaps we can simply redirect to `$request_url.replace('wiki.', '')` so that you end up on the read-only site plain and simple. 

Food for thought.

**Comment by tobinmori** [comment]
Needs technical discussion/plan.

**Comment by almaceleste** [comment]
I, like many other developers, have spent so much energy translating and writing articles on wiki.developer.mozilla.org - and where is it all now ?! Previously, I could show my contribution to the project to a potential employer - now it is almost impossible. so sad...

**Comment by chrisdavidmills** [comment]
@almaceleste I'm sorry that you are sad about this. None of your previous contributions have been lost — in the new MDN platform, you can still access all the localized content from the language drop-down select at the top of each page. The only difference in the current situation is that the localed docs are frozen — they can't currently be edited.

Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for more information on our localization strategy.

**Comment by peterbe** [comment]
> I, like many other developers, have spent so much energy translating and writing articles on wiki.developer.mozilla.org - and where is it all now ?! Previously, I could show my contribution to the project to a potential employer - now it is almost impossible. so sad...

First of all, please subscribe to https://github.com/mdn/yari/issues/1753 
It will become a record that your potential/future employer can trust. If your name is in that CSV dump, they can genuinely see that you've made a great amount of contributions. It's certainly clunkier than a dashboard or any other pretty report and we're sorry about that. But we're a limited team and we've been busy with the migration. But the future is bright. 
By the way, this file will include contributions across different localizations.

Moving to GitHub actually means we can do so much more with the highlighting of your contributions. To start with, when you make PRs and they get merged, this will correctly be reflected on your GitHub user profile page and it's a trusted record because you can audit this trail perfectly.

**Comment by escattone** [comment]
We redirect wiki.developer.mozilla.org/*/docs/* -> developer.mozilla.org/$1/docs/$2

**Comment by almaceleste** [comment]
@peterbe, @chrisdavidmills, thank you for your responses.  
it will be great if the dump of the old revision database is publicly available. thank you for not forgetting about it and including it in the plan.
