### ISSUE TITLE
Unable to sign up/log in using github auth

### ISSUE THREAD

**Issue by ktec** [mdn/kuma#7415]
**Summary**
Unable to sign up/log in using Github auth

**Steps To Reproduce (STR)**
Using Chrome:
1.  visit https://developer.mozilla.org/en-US/users/account/signup-landing?next=%2Fen-US%2Fprofile
2. select github auth
3. enter the TFA code

Browser crashes and renders a
This page isn’t workingdeveloper.mozilla.org redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

Tried deleting all cookies for *.mozilla.org and repeated process multiple times with same result.

End up with this:

This page isn’t working developer.mozilla.org redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

Unable to sign up/log in using github auth

**Expected behavior**

To be able to sign in

**Additional context**

User Agent | Mozilla/5.0 (Macintosh; 
Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/84.0.4147.105 Safari/537.36

**Comment by ktec** [comment]
I assume this is result of the shutdown

**Comment by peterbe** [comment]
This is not the result of the shutdown. MDN Is not shutting down. Let's look into this. (although finding the time to look into this is going to get harder for sure)

**Comment by escattone** [comment]
@ktec Thanks so much for reporting this! As @peterbe said, MDN is not shutting down. I was able to reproduce this as well. We'll look into this.

**Comment by escattone** [comment]
I've been looking into this, and I suspect it's an issue with our CloudFront configuration on both stage and prod. More soon.

**Comment by escattone** [comment]
@ktec (cc @peterbe) I just fixed this, so https://developer.mozilla.org/en-US/users/signin?next=/en-US/profile should work just fine now. The source of the problem was that our CloudFront configuration missed the case of `/en-US/profile` (i.e., no forward slash at the end of the URL). The URL `/en-US/profile/` worked just fine. Thanks again for reporting this, cheers!
