### ISSUE TITLE
About android studio prompt box

### ISSUE THREAD

**Issue by audreylin999** [mdn/kuma#7418]
About android studio writing HTML program prompt box: "The HTML <script> element is used to embed executable code or data; this is typically used to embed or refer to JavaScript code.
By Mozilla Contributors, CC BY-SA 2. "It appears too often, it appears in front of the mouse button. This is really troublesome, and it affects the operation.
I can't find the relevant options that can be set, I hope to get a reply, thank you very 
![P_20200814_183718_1](https://user-images.githubusercontent.com/44116510/90245343-1397cc80-de65-11ea-99c8-9de409dfec06.jpg)
much

**Comment by peterbe** [comment]
Not related to MDN.
