### ISSUE TITLE
Remove Janet Swisher's name from account welcome emails

### ISSUE THREAD

**Issue by jmswisher** [mdn/kuma#7419]
**Summary**
When a user signs up, the welcome email message they receive should not contain Janet Swisher's name.

**Rationale**
Janet will no longer be on MDN staff.

**Audience**
Users signing up for accounts

**Proposal**
Remove Janet's name from the "From" field, and from the body of the message. Your call on what to do instead. You could use someone else's name, or "MDN team", or something else. Might want to switch back to a no-reply address if no one will be responding to people who reply to the welcome email.

**Additional context**
I'll miss y'all very much.

**Comment by peterbe** [comment]
I think it'd be to time-complex to pick another human's name so I'll go with "MDN team" for now. I think it's a bit better than "MDN" or anything else really that doesn't feel human.

**Comment by atopal** [comment]
Makes sense Peter.

**Comment by jmswisher** [comment]
Don't forget about the email body.
