### ISSUE TITLE
Search Bar Problem

### ISSUE THREAD

**Issue by iBOWEN7196** [mdn/kuma#7423]
**Summary**
_What is the problem?_
Search box won't work after clicking on drop-down menus in top navigation bar.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Click on any of the three drop-down menu buttons;
2. then click in the search box;
3. and try typing something in.
It doesn't work and I have to reload the page.

**Actual behavior**
_What actually happened?_
I couldn't type anything into the search box.

**Expected behavior**
_What did you expect to happen?_
I expected characters to appear.

**Additional context**
_Is there anything else we should know?_
The cursor in the text box showed up as long as I held down the mouse button while the arrow was in the text box, but disappeared whenever I let go of the mouse button and instead the last drop-down menu button I clicked on would be outlined.

**Comment by schalkneethling** [comment]
Thank you for reporting @iBOWEN7196 - Fix is in the pipeline:
https://github.com/mdn/kuma/pull/7425
