### ISSUE TITLE
"Submit as: spam" throws error

### ISSUE THREAD

**Issue by alattalatta** [mdn/kuma#7424]
**Summary**
When trying to report a spam, `TypeError` is thrown.

**Steps To Reproduce (STR)**
1. Revisions Dashboard.
2. Report a revision with "Submit as: spam"

**Actual behavior**
`Uncaught TypeError: can't access property "getCookie", mdn.utils is undefined`

**Expected behavior**
The revision is reported as a spam.

**Additional context**
After manually setting `window.mdn.utils`, I can report one successfully:
```js
// partial copy of wiki.js
window.mdn.utils = {
  getCookie: function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
        var cookie = jQuery.trim(cookies[i]);
        if (cookie.substring(0, name.length + 1) === name + '=') {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break
        }
      }
    }
    return cookieValue
  }
};
```

I had reported this one a while ago (#6573) which were (I _think_) fixed by #6550. If my memory is correct, this is a reappearance.

**Comment by peterbe** [comment]
The Wiki is no longer maintained. Sorry. This probably won't be fixed.

**Comment by alattalatta** [comment]
I assumed it as well since I saw Yari and such. 😞

**Comment by peterbe** [comment]
That functionality is now long gone.
