### ISSUE TITLE
Scroll x mozila dev website downloade page

### ISSUE THREAD

**Issue by Alishahidi** [mdn/kuma#7429]
**Summary**
_What is the problem?_
Scroll from x in downloade firefox dev page 

![Screenshot_2020-08-17-22-58-26](https://user-images.githubusercontent.com/63677039/90431258-fd487580-e0dd-11ea-8a78-1c500e6a8fb7.png)

**Comment by escattone** [comment]
@Alishahidi This repo is for [MDN Web Docs](https://developer.mozilla.org/fa/) issues only. I think https://github.com/mozilla/bedrock/issues would be the right place to file your issue.
