### ISSUE TITLE
if Vxml can use spidermonkey 52.9.1 pre properly?

### ISSUE THREAD

**Issue by zhaoqilong123** [mdn/kuma#7431]
# Request type
question:If spidermonkey 52.9.1 support Voice Extensible Markup Language (VoiceXML) 2.1 and Voice Extensible Markup Language (VoiceXML) Version 2.0?
# Details
Inside Voice Extensible Markup Language (VoiceXML) Version 2.0, at **5.3.12 script element** section, it say ECMAscript can be used embeded inside Vxml message. Like following:
```
<?xml version="1.0" encoding="UTF-8"?>
<vxml version="2.0" xmlns="http://www.w3.org/2001/vxml"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3.org/2001/vxml
http://www.w3.org/TR/voicexml20/vxml.xsd">
<script> <![CDATA[
function factorial(n)
{
return (n <= 1)? 1 : n * factorial(n-1);
}
]]> </script>
<form id="form">
<field name="fact">
<grammar type="application/srgs+xml" src="/grammars/number.grxml"/>
<prompt>
Tell me a number and I'll tell you its factorial.
</prompt>
<filled>
<prompt>
<value expr="fact"/> factorial is
<value expr="factorial(fact)"/>
</prompt>
</filled>
</field>
</form>
</vxml>
```
I can see for VXML，related ECMA standard is released at December 1999. so I guess it's third edition of ECMA.
before, I used spidermonkey 1.7, I guess it obey to ECMA 3, but now I upgraded to spidermonkey 52.9.1 pre. i guess it obey to ECMA 6, right?
And for 1.7, it can handle "factorial(fact)" successfully, but for 52.9.1 pre, call will fail.
I don't know if such usage is not supported by spidermonkey or by ECMA 6.

**Comment by escattone** [comment]
@zhaoqilong123 The issues in this repo are for [MDN Web Docs](https://developer.mozilla.org) only. You might want to go to https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=JavaScript%20Engine and submit your question there. Cheers.
