### ISSUE TITLE
Minor Correction required on self-assessment exercise on css selectors

### ISSUE THREAD

**Issue by BKSpurgeon** [mdn/kuma#7432]
firstlly, thank you for your work on this project: i appreciate it.

# Content Issue
- [x ] Correction or update

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Selectors_Tasks

# Details
* Please scroll down to the "Selectors Three" example. A couple of things to note: (i) there are no links in the worked example (we should expect links to be there) - given that is what the exercise specifies.
* Also the final solution presented is too large on the screen, forcing users to scroll up and down to view the effects in the css/html sandbox, which can be quite cumbersome.

Am happy to submit a PR to address these concerns - but I do not know where the original repo is.

any questions, please let me know. 

chrs

Ben

**Comment by escattone** [comment]
@BKSpurgeon Thanks for your kind words. If you'd like, you can submit a PR within the https://github.com/mdn/css-examples repo, and I believe the `Selectors Three` example is https://github.com/mdn/css-examples/blob/master/learn/tasks/selectors/pseudo.html. Cheers!

**Comment by BKSpurgeon** [comment]
@escattone thanks for the pointer, I can put in a PR.
rgds
Ben
