### ISSUE TITLE
Rendered example blank on viewBox page

### ISSUE THREAD

**Issue by usdaproved** [mdn/kuma#7437]
**Summary**
The example showing rendered SVG's on the viewBox page is empty.
The html isn't hooked in properly. Selecting the "view on JSFiddle" and CodePen show the HTML is empty.

**Steps To Reproduce (STR)**
1. visit [viewBox page](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox)
2. scroll down to view the rendered example beneath the HTML

**Actual behavior**
Example empty

**Expected behavior**
View the example

**Comment by escattone** [comment]
@usdaproved Fixed now, thanks for reporting!
