### ISSUE TITLE
Allow admins to give users permission to revert revisions 

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/kuma#7452]
**Summary**

It is currently not clear how "revert revision" permissions are assigned to users that are not super users — by this, I mean access to the "Revert to the revision" buttons you get on article history pages, and the "Revert" buttons you get on the revision dashboard.

We would like the creation of a permission group in the Django admin along the lines of "Revisionists", which people can be put in to give them this permission.

**Rationale**

There are a number of new MDN community participation programs being spun up to help out with day-to-day work now the writers team is at reduced capacity. It would be very useful to be able to assign community members revert permissions for when they help out with moderating page edits.

**Audience**

MDN contributors

**Proposal**

Users given this permission would have access to the revert buttons described above.

**Comment by peterbe** [comment]
I've created a group call https://developer.mozilla.org/admin/auth/group/22/change/ that have the "Can delete revision" permission. 
If you put a user into this group, the "Revert to this revision" button will appear and should work. 
For example, pick a user [like this](https://developer.mozilla.org/admin/users/user/751227/change/) and scroll down to the "Groups:" widget and find "Revisionists" and press the right-arrow and then the "SAVE" button.

**Comment by peterbe** [comment]
I don't think we need to triage this since at the moment it's only a matter of Django Admin *data*. 
And perhaps the next actions are:
1. @chrisdavidmills you test it with some user that it's you (can be a test account)
2. Close this issue.

**Comment by chrisdavidmills** [comment]
I've tested this, and it works perfectly, thanks @peterbe !

**Comment by escattone** [comment]
Thanks @peterbe!
