### ISSUE TITLE
Long delay collecting mail - js error?

### ISSUE THREAD

**Issue by Webmech** [mdn/kuma#7453]
Sometimes I get along delay collecting mail. Looking at the debug pages I see a js variable naming error which may be connected?
![tberr](https://user-images.githubusercontent.com/393375/91203088-9e48b900-e6fa-11ea-90bd-2af0d0ebd383.jpg)

**Comment by peterbe** [comment]
This repo is for the website [MDN Web Docs](https://developer.mozilla.org).
