### ISSUE TITLE
 perefernces home custom urls and and pined tabs

### ISSUE THREAD

**Issue by elmbeech** [mdn/kuma#7460]
**Summary**
_What should be changed? (Please provide a URL if applicable)_

I use the preferences custom URLs functionality  (about:preferences#home  / Homepage and new windows / Custom URLs), 
to have a hand full of URLs opened that I often use. 

When I pin this tabs (right click on the tab and select 'Pin Tab'), close and browser and open it again, 
these URLs get a second time opened.

There should be a way to say to Firefox that he should only open these Custom URLs if they are not already open.

**Rationale**
_What problems would this solve?_

Unwanted multiple opening of pinned custom URLs tabs, when the browser is restarted.   

**Audience**
_Who would use this changed feature?_

Users who use the "Custom URLs" and "Pin Tab" functionality.

**Proposal**
_What would users see and do? What would happen as a result?_

It would be nice if there is a setting e.g. checkbox at "about:preferences#home  / Homepage and new windows"  where can be selected that, that "Custom URLs" only load the page is not already loaded (e.g. as pinned tab).
If this option is checked the pages would simply not be opened an additional time if they are already open.

**Additional context**
_Is there anything else we should know?_

Thank you for Firefox! It is definitely my favorite browser.

**Comment by peterbe** [comment]
Try [filing a bug on Firefox](https://bugzilla.mozilla.org/) or perhaps [Firefox Support](https://support.mozilla.org/en-US/).

This repo is about the [MDN Web Docs website](https://developer.mozilla.org).

**Comment by elmbeech** [comment]
oh. sorry! 
I thought this is the firefox repo. all the best!
