### ISSUE TITLE
Firefox profile icons in KDE

### ISSUE THREAD

**Issue by jayadevanraja** [mdn/kuma#7461]
**Summary**
_What is the problem?_
After Upgrading Ubuntu 16.04 to 18.04 and then to 20.04, I changed from Unity Desktop to KDE. My Unity Desktop task manager has different icons for each Firefox profile. But my KDE Plasma Desktop uses the default icon for all the profiles in the task manager. If I start in a non-default profile, I get the the profiles grouped into one in the task manager.

How to get the icons displayed in the task manager? 

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Go to KDE Plasma in Ubuntu 20.04
2. Open Firefox Multiple Profiles
3. They all open in the same icon and same window group in the task bar.

**Actual behavior**
_What actually happened?_
User (that is me) can not distinguish between the profiles, since all of them are grouped into the same window group in the task bar.

**Expected behavior**
_What did you expect to happen?_
Just like in Unity, all profiles should open in their own window group in the task bar, as if they were separate browsers.

**Additional context**
_Is there anything else we should know?_
Please see this:
https://forum.kde.org/viewtopic.php?f=289&t=167506&p=436666#p436666

**Comment by peterbe** [comment]
[Try filing a bug on Firefox](https://bugzilla.mozilla.org/)

This repo is about the [MDN Web Docs website](https://developer.mozilla.org).
