### ISSUE TITLE
Link injection payload (XSS?) causing an error for generating the diff (rev. dashboard / $compare view)

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/kuma#7487]
**Summary**

A user attempted some link injection in the content on a page. When investigating and using the revision dashboard, we get a "There was an error generating the content.". 
This issue is there to address any concern that may occur in the backend while parsing/sanitizing this.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Go to https://wiki.developer.mozilla.org/en-US/docs/Web/API/LockedFile/location$compare?locale=en-US&to=1643554&from=1643553

**Actual behavior**
There is an error message in the page maybe indicating some deeper error in the back-end (?).

**Expected behavior**
The diff is sanitized and displayed properly.

**Additional context**
rev. 1643554 (with link injection attempt payload) of provided document for test case https://wiki.developer.mozilla.org/en-US/docs/Web/API/LockedFile/location$revision/1643554

rev 1643553 (before XSS / link) https://wiki.developer.mozilla.org/en-US/docs/Web/API/LockedFile/location$revision/1643553

**Comment by peterbe** [comment]
For those with access, the user is here: https://developer.mozilla.org/admin/users/user/755090/change/

@SphinxKnight I see [here](https://wiki.developer.mozilla.org/en-US/dashboards/revisions?user=sami6671) that you have banned the user. Does that mean that that user can no longer use the Wiki? I can see that they used Google to sign in but not much more.

**Comment by peterbe** [comment]
The revision can be seen here:
```
>>> r=Revision.objects.get(id=1643554)
>>> r.title
'LockedFile.location'
>>> r.content
...
```
It's depressing but unfortunately normal and expected. It's a shame it even allowed it to be saved in the first place. 

But I wonder, what can do to reject content submissions like that? In particular, in Yari. 
In Yari, we have, as a last line of defense, humans that need to eye through edits. What the XSS attempt was a `<a href="..." target="_blank"><img src="data:image/Svg+xml;base64,..."></a>` which is actually a fairly normal piece of HTML.

**Comment by SphinxKnight** [comment]
> @SphinxKnight I see [here](https://wiki.developer.mozilla.org/en-US/dashboards/revisions?user=sami6671) that you have banned the user. Does that mean that that user can no longer use the Wiki?

Well I assume that a banned user can not add a new revision. I've never tested this with an own dummy account to ensure the ban feature works as (I think) intended ^^

**Comment by escattone** [comment]
Thanks for your work on this @SphinxKnight! With the upcoming release of Yari planned in December, this kind of thing will be nearly impossible since all contributions will have to be reviewed and approved via the GitHub pull-request model. In the meantime, we're not going to be able to work on the Kuma backend, so I'm closing this as something that we will not address in Kuma since it will be inherently addressed once we launch https://github.com/mdn/content in December.
