### ISSUE TITLE
Remove or update Security.md

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/kuma#7488]
**Summary**
I was wondering if an issue of mine was security-related and tried "Report a security vulnerability" when filing an issue since it provided a "view policy" button (thinking "this policy might answer my questions about whether or not this is the right category of issue).
The policy (described in https://github.com/mdn/kuma/blob/master/SECURITY.md) was not really helpful.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Go to  https://github.com/mdn/kuma/issues/new/choose
2. Click on the "view policy" on the last option
3. Be directed to https://github.com/mdn/kuma/security/policy

**Actual behavior**
https://github.com/mdn/kuma/blob/master/SECURITY.md was displayed with boilerplate instructions (not about issue filing but about "building a proper security.md file")

**Expected behavior**
I expected this document to provide detailed instructions or directions *related to kuma* whether an issue was "security" related, maybe some info about disclosure, SLA regarding triaging/response, maybe mentions of a bug bounty program, mentions of a potential email address to reach for.

**Comment by peterbe** [comment]
Note that the headline in that Markdown is `TEST Security Policy` :)
I don't know why it got into `kuma`'s `master` when it's clearly not ready.

**Comment by peterbe** [comment]
The simple solution is to point people to https://bugzilla.mozilla.org/enter_bug.cgi?product=developer.mozilla.org&component=Security and nothing else.

**Comment by peterbe** [comment]
Action items:

* Fix the headline in that doc.
* Write about how you have to go to bugzilla.mozilla.org and file it under https://bugzilla.mozilla.org/enter_bug.cgi?product=developer.mozilla.org&component=Security
