### ISSUE TITLE
Previous sent item overwritten by second reply

### ISSUE THREAD

**Issue by TheEndIsNig** [mdn/kuma#7489]
**Summary**
On sending a second, third or any number of replies via reply to sender tab, random copies of the replies are hidden as though they were never sent

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. open a message from the inbox
2. click on the reply tab
3. compose your response
4. click on send
5. repeat the above as many times as you like but with different content
6. only one response is visable in the sent items
7. Search for a a unique word in one of the sent messages
8. notice that all the replies are listed in the search, but that's a painful way to find it especially if you can't remember what it said

**Actual behavior**
Only one of the replies is visable in the sent items. It seems to be random which reply is actually listed in sent items. This means that sent items doesn't reflect the true situation. Obviously, it should record what was sent when. (What You See is What You Sent)

**Expected behavior**
each individual reply shoud appear in the sent items. As it is, proof of sending doesn't exist without a process that few people would expect to perform - Even if they could remember what the missing send items contained.

**Additional context**
See attached screen grabs showing search results against sent items list.

![sent items list](https://user-images.githubusercontent.com/71000531/92565878-4c17a400-f273-11ea-8281-a573716bd7cb.JPG)
![Search results for ignore](https://user-images.githubusercontent.com/71000531/92565887-52a61b80-f273-11ea-9f06-5764861175c6.JPG)

**Comment by peterbe** [comment]
Is that Thunderbird? If so perhaps you should [file a bug](https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird) or [support question](https://support.mozilla.org/en-US/products/thunderbird) on Thunderbird. 

This is the MDN Web Docs repo.
