### ISSUE TITLE
Soapbox banner required for 2020 MDN Web DNA Survey

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/kuma#7492]
# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:

All MDN pages!

# Details

We want to launch the 2020 MDN Web DNA Survey on September 18th, and to coincide with it, we want to put a soapbox banner on MDN, inviting people to fill it out.

Last year's call to action text was:

> We have an opportunity for you to influence how browser vendors like Mozilla, Google, Microsoft, and Samsung prioritize feature development.

> It’s easy to take part, just complete this survey that was designed in collaboration with those browser vendors and the W3C. It will take you approximately 20 minutes — this is your chance to make yourself heard. The results and learnings will be shared publicly on MDN.

> You must be 18 years old or over to participate. We handle your information as described in the Mozilla Privacy Policy.

The actual banner text will probably be similar to last year's, something like:

> MDN Web DNA
> Help us understand the top 10 needs of web designers and developers.
> Take the survey.

Let us know what else you need for this. Thanks!

**Comment by schalkneethling** [comment]
@chrisdavidmills https://github.com/mdn/kuma/pull/7494

Note that we need the URL for the new survey. The above still uses last years

**Comment by chrisdavidmills** [comment]
@schalkneethling thanks!

**Comment by chrisdavidmills** [comment]
One small request; can we change the text of the banner to "Help us understand the top 10 needs of web developers.", ie. remove "designers and"? We've not had time to address designers in this year's survey.
