### ISSUE TITLE
Some of the content disappeared

### ISSUE THREAD

**Issue by qzruncode** [mdn/kuma#7502]
I can only find the web assembly in the search, there is no navigation link on the page to access

**Comment by chrisdavidmills** [comment]
Hi @qzruncode ! So you are saying that a link to https://developer.mozilla.org/en-US/docs/WebAssembly is missing?

Or are you looking for a link to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/WebAssembly?

And what page is the link missing from?

**Comment by qzruncode** [comment]
Yes, it's hard to find, except in the search bar. I remember it was in a very prominent position before? I think it's a great API and should be as easy to find as webaudio, webgl and other APIs

**Comment by qzruncode** [comment]
@chrisdavidmills What do you think of putting it here. https://developer.mozilla.org/en-US/docs/Web
