### ISSUE TITLE
the code in simplified Chinese version have bug

### ISSUE THREAD

**Issue by sunan112** [mdn/kuma#7504]
**Summary**
_What is the problem?_

In the simplified Chinese version, web development technology>javascript>closures> practical closures in the example code
`document.getElementById('size-12').onclick = size12();`
should delete '()' on the onclick function

**Steps To Reproduce (STR)**
in the simplified Chinese version, web development technology>javascript>closures, practival closuers in the example code
`document.getElementById('size-12').onclick = size12();`

**Expected behavior**
_What did you expect to happen?_
should delete '()' on the onclick function

**Comment by peterbe** [comment]
To change it, create an account and edit it yourself. It's a Wiki. Thanks for taking the time!

**Comment by sunan112** [comment]
thanks
