### ISSUE TITLE
Soapbox banner required for MDN browser comatibility report

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/kuma#7505]
# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:

All MDN pages ;-)

# Details

To accompany the launch of the MDN browser compatibility report (see https://github.com/mdn/insights/issues/42), we'd like to put up a soapbox banner to draw people's attention to it.

The wording should be "Check out the MDN Browser Compatibility Report, a deep dive into web compatibility frustrations, with useful insights into how they could be overcome.", and "MDN Browser Compatibility Report" should be linked to the report.

We'd like this banner to run until the day before the soapbox banner for the 2020 Web DNA Survey is published (see https://github.com/mdn/kuma/issues/7492)

Does this sound OK?

**Comment by chrisdavidmills** [comment]
FYI @robnyman

**Comment by schalkneethling** [comment]
@chrisdavidmills Sounds good. We might need to finesse the wording a little to fit into our standard banner. Let me do a mock-up and we can take it from there.

**Comment by chrisdavidmills** [comment]
Sounds good; thanks @schalkneethling !

**Comment by schalkneethling** [comment]
@chrisdavidmills Do we link to the insights website or directly to the PDF from this banner?

**Comment by chrisdavidmills** [comment]
@schalkneethling see my answer in the PR.
