### ISSUE TITLE
Absent sanitizeBody('genre.*').escape() line in the code sample

### ISSUE THREAD

**Issue by BassOfBass** [mdn/kuma#7507]
The code line mentioning it:
https://github.com/mdn/content/blob/4f43953e287f72adbeaab3d1117a4194b854c763/files/en-us/learn/server-side/express_nodejs/forms/create_book_form/index.html#L124
The sample code line:
https://github.com/mdn/content/blob/4f43953e287f72adbeaab3d1117a4194b854c763/files/en-us/learn/server-side/express_nodejs/forms/create_book_form/index.html#L67
The repo code:
https://github.com/mdn/express-locallibrary-tutorial/blob/31a49c021487c14c23a215ce839be2481ac9e21c/controllers/bookController.js#L115

**Comment by peterbe** [comment]
Those are different pages. One is about the Create form and one is about the Update form. 
I can't speak for the business logic within or why they sanitize the inputs differently. 

I haven't actually studied the actual document's content and what they're trying to do. Do you think it's a "bug" in the content?

**Comment by BassOfBass** [comment]
My bad, wasn't meaning about the differences between Update and Create, just me not paying enough attention.
How do you insert a newline in the wiki editor? Shift + Enter still returns the same line in the preview.

**Comment by peterbe** [comment]
> My bad,

Phew! Seems we're all good then in terms of the platform. Now, in terms of content, that might a different story :)

> How do you insert a newline in the wiki editor?

Honestly, I'm not sure. I never use it. And we're actually actively working on getting rid of that editor. 
Perhaps use the source mode.
