### ISSUE TITLE
Input type number accept e as a number

### ISSUE THREAD

**Issue by zhuniqiabedin** [mdn/kuma#7518]
**Summary**
_What is the problem?_
The input type number accept the letter **e** as input.
![Screenshot 2020-09-24 at 21 55 46](https://user-images.githubusercontent.com/48968370/94193598-d46f8900-feb0-11ea-8a61-c9577c11e845.png)

**Steps To Reproduce (STR)**

1. Go to MDN Official page for input type number https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

**Actual behavior**
It accepts the string **e** as a number

**Expected behavior**
Input type number it should only contain numbers not letters.

**Comment by peterbe** [comment]
There's nothing wrong with the documentation. That's how the `<input type=number>` is implemented in the browsers. 
However, I appreciate that it could do with strong explanation to say that it doesn't outright refuse any input that isn't a number. 

The `type="number"` is ultimately just there to help you type. It's not a strict implementation. See it as a `<input type="text">` but with some imaginary JavaScript that does some lightweight validation and little up-and-down arrrows. 

Interestingly, if you type "10x2" the `value` of the target becomes `""` (empty string). But if you type "10e2" the `value` becomes `"10e2"`. 

Sidefact; in JavaScript:
```
>> parseInt("10x2")
10
>> parseInt("10e2")
10
```

https://codepen.io/peterbe/pen/PoNLqoM?editors=1011
