### ISSUE TITLE
Microphone of bluetooth headset not working anymore after upgrade to Firefox 81.0

### ISSUE THREAD

**Issue by cwschmidt** [mdn/kuma#7522]
**Summary**
I updated my Firefox installation from v80.0.1 to v81.0
The microphone of my headset "Sony WH-XB900N" stopped working with web-meeting software like "3cx" and "WebEx" during a call or web-meeting. It does not matter if I grant access to the microphone temporarily or permanently. The issue persists even with not plugins or extensions involved and a new profile. 

**Steps To Reproduce (STR)**
1. Install Firefox 80.0.1
2. Pair/connect the Headset to the computer
3. Go to a web-meeting site and grant access to the microphone of the headset
4. Make a call. Test if speaker and especially microphone is functional (it should be) 
->  speaker works, microphone works!

5. Update Firefox to 81.0
6. Reboot
7. Pair/connect the Headset to the computer
8. Go to a web-meeting site and grant access to the microphone of the headset
9. Make a call. Test if speaker and especially microphone is functional
->  speaker works, microphone does not work (seems to be always muted)! 

10. Downgrade again Firefox to 80.0.1
11. Reboot
12. Pair/connect the Headset to the computer
13. Go to a web-meeting site and grant access to the microphone of the headset
14. Make a call. Test if speaker and especially microphone is functional
->  speaker works, microphone works again!

**Actual behavior**
Upgrade of Firefox 80.0.1 to Firefox 81.0 broke usability of the bluetooth microphone.

**Expected behavior**
Bluetooth microphone of the headset should still work with Firefox 81.0 after upgrading from Firefox 80.0.1

**Additional context**
System:
OS:
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20
DISTRIB_CODENAME=ulyana
DISTRIB_DESCRIPTION="Linux Mint 20 Ulyana"
Linux Laptop 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Version that worked:
Firefox 80.0.1 (no extensions installed, new profile)
Version that has the problem:
Firefox 81.0 (no extensions installed, new profile)

**Comment by cwschmidt** [comment]
Wrong forum, I think, sorry for the inconvenience.
You can delete the issue.

**Comment by escattone** [comment]
Yes, this is not the right forum for Firefox-related issues, but no worries @cwschmidt! Thanks for discovering that yourself. You might want to check out https://bugzilla.mozilla.org/describecomponents.cgi. Cheers.
