### ISSUE TITLE
certutil unable to open .cer file

### ISSUE THREAD

**Issue by swshruti** [mdn/kuma#7533]
**Summary**
_What is the problem?_i tried installing certificates to mozilla db but getting the error "certutil:  unable to open ""C:\Users\swshruti\AppData\Roaming\tempThinClients\desktopplugin.cer"" for reading (-5987, 123)."

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. try installing certificate using certutil in mozilla db
2. 
3. 

**Actual behavior**
_What actually happened?_
getting following error
certutil:  unable to open ""C:\Users\swshruti\AppData\Roaming\tempThinClients\desktopplugin.cer"" for reading (-5987, 123).
**Expected behavior**
_What did you expect to happen?_

certificate should be added in mozilla db
**Additional context**
_Is there anything else we should know?_
no

**Comment by peterbe** [comment]
Might be a [bug in Firefox](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox) or [a matter of support on Firefox](https://support.mozilla.org/en-US/products/firefox). 
But this repo is about [MDN Web Docs](https://developer.mozilla.org).
