### ISSUE TITLE
Cannot use the Menu on MDN Top page with mobile.

### ISSUE THREAD

**Issue by felis392** [mdn/kuma#7534]
**Summary**
_What is the problem?_

When Access with a mobile device.
The menu is covered by  semitransparent backdrop.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. access the [MDN Top page] with mobile device. (or any device with a narrow viewport.)
2. open the menu. (the hamburger icon on left-up.)

**Actual behavior**
_What actually happened?_

The menu is covered. cannot be used.

**Expected behavior**
_What did you expect to happen?_

The menu on the top page can also be used on mobiles.

**Additional context**
_Is there anything else we should know?_

nothing.

[MDN Top page]: https://developer.mozilla.org/en-US/

**Comment by peterbe** [comment]
I can reproduce. 
Both in my browser and on my iPhone

<img width="905" alt="Screen Shot 2020-09-30 at 10 18 25 AM" src="https://user-images.githubusercontent.com/26739/94697548-53781d80-0306-11eb-9747-35b064ef2861.png">


![IMG_73362C462A03-1](https://user-images.githubusercontent.com/26739/94697449-37747c00-0306-11eb-84d4-4f43ff45e93c.jpeg)

**Comment by schalkneethling** [comment]
Thank you for reporting @felis392
