### ISSUE TITLE
requestAnimationFrame is also available in Dedicated Workers

### ISSUE THREAD

**Issue by Kaiido** [mdn/kuma#7543]
# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URLs of page you are seeing the problem on:
 - https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame
 - https://developer.mozilla.org/en-US/docs/Web/API/window/cancelAnimationFrame

# Details

`requestAnimationFrame` and `cancelAnimationFrame` used to be `Window` only methods, but it has recently been added to `DedicatedWorkerGlobalScope` too. https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#animationframeprovider

```webidl
interface mixin AnimationFrameProvider {
  unsigned long requestAnimationFrame(FrameRequestCallback callback);
  undefined cancelAnimationFrame(unsigned long handle);
};
Window includes AnimationFrameProvider;
DedicatedWorkerGlobalScope includes AnimationFrameProvider;
```

I guess the page should now be `Web/API/WindowOrWorkerGlobalScope/requestAnimationFrame`, but I fear this would break any link to the current `/Web/API/window/requestAnimationFrame`. So I'm not sure how it should get handled.

Also, compat-data should probably be updated (currently these methods are supported in Blink only).

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/sprints #3749](https://github.com/mdn/sprints/issues/3749) via [**ZenHub**](https://www.zenhub.com/)
