### ISSUE TITLE
Moz Backup

### ISSUE THREAD

**Issue by ccrocker80** [mdn/kuma#7548]
I backed up my hard drive on May 25 using Moz Backup.  Then I changed my hard drive. By then only the newer version of Moz Backup was available. It is incompatible with the back up. I need help restoring the back up.**Summary**
_What support task would you like completed by the team?_

**Rationale**
_What problems would this solve?_It would restore programs and files that I desperately need.

**Due Date**
_When would you like this task completed by?_I need the data to do my tax return by October 15.

**Additional context**
_Is there anything else we should know?_

**Comment by peterbe** [comment]
Unrelated to [MDN Web Docs](https://developer.mozilla.org)
