### ISSUE TITLE
Examples of using Atomics has wrong return value comment

### ISSUE THREAD

**Issue by Zavtramen** [mdn/kuma#7550]
# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics

# Details

Examples of using Atomics has wrong return value comment:
```
Atomics.compareExchange(ta, 0, 5, 12);
Atomics.load(ta, 0); // 12
```
result here should be 1, not 12, cause previously stored value is 1 not 5
and, another one:
```
Atomics.store(ta, 0, 12); // 12

Atomics.sub(ta, 0, 2);
Atomics.load(ta, 0); // 3
```
result here should be 10, not 3

and where is another error with 'or'
examples should be revised

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/sprints #3782](https://github.com/mdn/sprints/issues/3782) via [**ZenHub**](https://www.zenhub.com/)
