### ISSUE TITLE
I can't find the entrance to developer.mozilla.org/en-US/docs/Mozilla on the home page

### ISSUE THREAD

**Issue by sk-buff** [mdn/kuma#7557]
Hi developers,

Today I was searching documents of SpiderMonkey on Google and found MDN maintained these documents (i.e. https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey). When I wanted to view these documents the second time, I tried to access them form the home page (i.e. https://developer.mozilla.org/en-US) instead of searching on Google. But I didn't find a hyperlink that can navigate me neither to these doucuments nor to the father path (i.e. https://developer.mozilla.org/en-US/docs/Mozilla) of them even if I searched the urls in the Element window in Developer Tools. Then I tried to browse https://developer.mozilla.org/en-US/docs directly to see whether I can find a hyperlink of https://developer.mozilla.org/en-US/docs/Mozilla in this page. And I found https://developer.mozilla.org/en-US/docs was redirected to https://developer.mozilla.org/en-US/docs/Web via HTTP 301.

I want to know whether there is an entrance to https://developer.mozilla.org/en-US/docs/Mozilla on the home page? If there isn't, shall we consider adding it to the home page? Or maybe we can add a document root page (e.g. the current https://developer.mozilla.org/en-US/docs page) and list all secondary themes (e.g. /docs/Mozilla, /docs/Web) in that page to make all the documents more organized, just like a tree structure. Of course, if there is an entrance to developer.mozilla.org/en-US/docs/Mozilla just that I didn't it, this is a meaningless question. Please let me know if so and I will close this issue :)

Thank you!

**Comment by escattone** [comment]
@sk-buff We are going to archive most of the Mozilla specific documents on MDN into their own repository (https://github.com/mdn/archived-content), since MDN is emphasizing open web development and de-emphasizing Mozilla-specific documents. So we are not planning on adding an entrance to the Mozilla documents on the home page. Thanks for your question though.
