### ISSUE TITLE
Ctrl + J incorrectly documented

### ISSUE THREAD

**Issue by Nikhil1O1** [mdn/kuma#7559]
# Content Issue

- [ ] Correction or update

# https://developer.mozilla.org/en-US/docs/Tools/Keyboard_shortcuts

# Details
 ``ctrl + j``  focuses address bar for web search and writes ``?`` in the bar.
This action is working with my firefox and is documented in the below link as well
https://support.mozilla.org/1/firefox/78.3.0/Linux/en-US/keyboard-shortcuts
(This link is given in the Firefox's help -> Keyboard Shortcuts)

If you confirm this issue i would like to fix the documentation myself

I'm using Firefox 78.3.0esr (64-bit) on debian Buster

**Comment by chrisdavidmills** [comment]
Hi @Nikhil1O1 ! the MDN page you are pointing to is specifically for Firefox DevTools keyboard shortcuts, whereas the support page is for general Firefox UI shortcuts. |I think this is where the confusion lies.

I'm going to close this now, but feel free to comment further if you think there is still a problem here.
