### ISSUE TITLE
case-insensitive search

### ISSUE THREAD

**Issue by ongardie** [mdn/kuma#7561]
**Summary**
_What should be changed? (Please provide a URL if applicable)_

Right now when I do a search on MDN, if I'm careless about my capitalization, I may get fewer or no results. Ideally, the search would return relevant results, perhaps ranking case mismatches lower than perfect case matches.

For example: https://developer.mozilla.org/en-US/search?q=scrollmaxx currently returns no results,
but https://developer.mozilla.org/en-US/search?q=scrollMaxX returns over 2500.

**Rationale**
_What problems would this solve?_

This would make it easier to find the relevant documentation when I don't know exactly what I'm looking for.

**Audience**
_Who would use this changed feature?_

All MDN users.

**Proposal**
_What would users see and do? What would happen as a result?_

Users would continue to search in the same way, but now they would see additional results.

**Additional context**
_Is there anything else we should know?_

Sorry if this has already been discussed in the past. I wasn't able to find anything after a few minutes of digging.

**Comment by peterbe** [comment]
Note-to-self; in my `yari-search` prototype, this gets resolved. It's case-insensitive by default.

**Comment by escattone** [comment]
@ongardie Thanks. Yes, our current search definitely has problems, and it's something we've thought about addressing for some time, but other priorities have always prevailed. Hopefully, we can address this soon.

**Comment by peterbe** [comment]
It works now.
