### ISSUE TITLE
Docs for Reflect.deleteProperty is not right.

### ISSUE THREAD

**Issue by SIGUSR97** [mdn/kuma#7566]
# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/deleteProperty
# Details

The docs page for Reflect.deleteProperty is the same as Reflect.defineProperty. 
I think there is probably a problem here.
![image](https://user-images.githubusercontent.com/52692296/96400891-88d8a280-1204-11eb-9ac3-e4ace08036d3.png)
![image](https://user-images.githubusercontent.com/52692296/96400899-8fffb080-1204-11eb-852d-94034af442cd.png)

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/sprints #3811](https://github.com/mdn/sprints/issues/3811) via [**ZenHub**](https://www.zenhub.com/)
