### ISSUE TITLE
Content related to method chaining in Javascript

### ISSUE THREAD

**Issue by deepanshu44** [mdn/kuma#7567]
# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:

# Details

I wanted to understand how method chaining work in classes but unfortunately I can't find any links to it on MDN. If its there, please tell me. 
Also other problem I've found is that program for optional chaining operator is not giving expected output.
![Screenshot_2020-10-19 Optional chaining ( )](https://user-images.githubusercontent.com/62979448/96405060-08ad3f80-11fa-11eb-96aa-3c603eff2f1c.png)
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining](url)

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/sprints #3810](https://github.com/mdn/sprints/issues/3810) via [**ZenHub**](https://www.zenhub.com/)
