### ISSUE TITLE
Unclosed brackets error makes no sense

### ISSUE THREAD

**Issue by TheCowMooooo** [mdn/kuma#7576]
**Summary**
I am testing a website I designed, and when I use `true` is comes back fine, but when i use `this` it gives me an error that is not even locatable.

**Actual behavior**
Uncaught SyntaxError: missing ] after element list
note: [ opened at line 1, column 25

**Expected behavior**
It was suppose to output the img object

**Additional context**
The program is run on Node JS.
[home.html.txt](https://github.com/mdn/kuma/files/5412447/home.html.txt)

**Comment by peterbe** [comment]
Not related to MDN Web Docs.
