### ISSUE TITLE
Sign In anchors overflow

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/kuma#7578]
![Screenshot_20201018-124744.png](https://user-images.githubusercontent.com/44380480/96365369-5c5b5280-1140-11eb-9f34-c600bd8fe708.png)

**Comment by 332406** [comment]
#7578

**Comment by 332406** [comment]
tetapan tidak betul

**Comment by mattiapontonio** [comment]
> tetapan tidak betul

Can You please translate?

**Comment by peterbe** [comment]
"332406 has been blocked from the mdn organization and will receive an email notification. "
from https://github.com/mdn/kuma/issues/7607

**Comment by mattiapontonio** [comment]
I don't understand if this Is really Open or everyting should be addressed ti Yari.
