### ISSUE TITLE
Fingerprint in Android devices should not be accepted as 'Master password'

### ISSUE THREAD

**Issue by zegsta** [mdn/kuma#7580]
**Summary**
_What should be changed? (Please provide a URL if applicable)_
In Android 9.0 (and probably other versions) fingerprint should not be accepted as a master password, or else, users should be asked before if they would like their fingerprint to be accepted as it, and be required to input their master passwords as a security measure.

**Rationale**
_What problems would this solve?_
If fingerprint is accepted as a substitute of master password, this may lead to several risks of hacking. While this may not be true for many people, in cases in which crimes may be committed, this security failure may allow offenders to easily access passwords for many websites, without the need to obtain any password from the main user. Also, the reason of having a 'Master password' is supposed to prevent this kind of easily access to critical information. As well, compared to the action conscious consent (in comparison: willingly sharing the password) the need to access this information will require only having the fingerprint of the user. Settings in which the abuse of this privilege may be abused could be in 1) celebrations and events: if the users gets drunk, it will be an easy target for unknown people, 2) travelers, who may stay in hostel or shared room settings 3) jealousy young-adult relationships. In conclusion, information could be compromised.

**Audience**
_Who would use this changed feature?_
For every user using the Firefox app in Android (unknown versions).

**Proposal**
_What would users see and do? What would happen as a result?_
A simple way to solve this and leave the user to decide what to do could be ask the user if they would like their fingerprint to work as a substitute of their master password. If they decide this, they should be required to input their master password and be informed about possible risks associated with this action. By default, this option should be disabled, creating a defense wall for any possible misuse. 

**Additional context**
_Is there anything else we should know?_
If you do this, I will be grateful. You will possibly the one preventing a misuse of technology.

**Comment by peterbe** [comment]
Interesting points but the wrong forum. 
This is the issue tracker for [MDN Web Docs](https://developer.mozilla.org).

**Comment by zegsta** [comment]
Hello.

Would you kindly let me know at least which is the right forum? @peterbe 

I believe this should be attended anyway.

**Comment by peterbe** [comment]
> Would you kindly let me know at least which is the right forum? @peterbe

https://github.com/mozilla-mobile/fenix/issues

Perhaps it's been mentioned already so do a little searching (included closed issues) first. 
Much appreciated!!
