### ISSUE TITLE
Error in translation on javascritp spanish page

### ISSUE THREAD

**Issue by Tonatew** [mdn/kuma#7585]
# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:
https://developer.mozilla.org/es/docs/Web/JavaScript

# Details

There is an "and" word in this spanish translation page(must be an "y"), just in the first paragraph before the Adobe Acrobat link.
![image](https://user-images.githubusercontent.com/42447015/97096119-38f74280-162d-11eb-8817-346fd8d344ae.png)

**Comment by chrisdavidmills** [comment]
Apologies, but we don't have the bandwidth to maintain translations. You are welcome to edit this yourself (please ask me if you need any help figuring this out).

**Comment by Tonatew** [comment]
Well, yeah, i can try, how can i do it?

**Comment by chrisdavidmills** [comment]
@Tonatew to start wth, you need an MDN account — for instructions on creating one, see here: https://wiki.developer.mozilla.org/en-US/docs/MDN/Contribute/Getting_started#Step_1_Create_an_account_on_MDN

Once you have an MDN account and have logged in to MDN, you can fix the page by pressing the "Editar en la wiki" button to get to the Wiki version of MDN, and then pressing the "Editar" button on that page to go into edit mode.

From there, use the WYSIWYG editor to fix the problem, then press the "Publicar" button to publish your change.

**Comment by Tonatew** [comment]
Done, now is fine, thanks <3
![image](https://user-images.githubusercontent.com/42447015/97237162-4424ac80-17ac-11eb-9c4d-e5c68e87f892.png)

**Comment by chrisdavidmills** [comment]
@Tonatew perfect, thanks for your help on this!
