### ISSUE TITLE
"CamelCase" shoud likely be "PascalCase"

### ISSUE THREAD

**Issue by jnields** [mdn/kuma#7590]
# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:
https://developer.mozilla.org/en-US/docs/Web/API/DOMException

# Details
The documentation lists: 

> Each exception has a name, which is a short "CamelCase" ...

I believe this should be "PascalCase"?

**Comment by chrisdavidmills** [comment]
Yeah, I think you're probably right here. I've also heard it called "upper camel case", but I think pascal case is more common. Page updated as you suggested.
