### ISSUE TITLE
BackGround color mdn is white, can i change to dark? Hard to see at night

### ISSUE THREAD

**Issue by iedriver** [mdn/kuma#7593]
**Summary**
_What problem would this solve?_

**Audience**
_Who has this problem? Everyone? Article authors? Etc._

**Rationale**
_How do you know that people identified above actually have this problem?_

**Workaround**
_How are the people identified above currently handling this problem?_

**Proposal**
_Do you have suggestions for solving this problem?_

**Additional context**
_Is there anything else we should know?_

**Comment by peterbe** [comment]
@schalkneethling Where's the original feature request for dark mode? It keeps coming back.

**Comment by schalkneethling** [comment]
@peterbe @iedriver https://github.com/mdn/kuma/issues/6880
