### ISSUE TITLE
Why "chrome" in your documantation?

### ISSUE THREAD

**Issue by kvishnivetsky** [mdn/kuma#7595]
# Content Issue

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# URL of page you are seeing the problem on:
https://developer.mozilla.org/en-US/docs/Mozilla/Gecko/Embedding_Mozilla

# Details

You can even construct whole new applications using **chrome.**

**Comment by chrisdavidmills** [comment]
Lower-case "chrome" refers to browser chrome, as in the browser UI, the bit around the viewport.
