### ISSUE TITLE
Get Started button link broken

### ISSUE THREAD

**Issue by uncannyjish** [mdn/kuma#7606]
**Summary**
The link on the "Get Started" button under Front End Developer course takes you to a shady website.

**Steps To Reproduce (STR)**
1. Go to the wiki - https://developer.mozilla.org/en-US/docs/Learn
2. Click on the "Get Started" button under the What's new section
3. The link associated - http://thefilmyseries.com/

**Actual behavior**
It tooks me to this website "http://thefilmyseries.com/" which clearly seems to be a shady website 

**Expected behavior**
It should have take me to the course put up my mdn for Getting started as a front end developer

**Additional context**
It seems security has been compromised of this site and hackers have managed to tamper the website
![mdn](https://user-images.githubusercontent.com/43221561/98439535-64c4fe80-20ea-11eb-913a-895606285081.png)

**Comment by chrisdavidmills** [comment]
Thanks for reporting this. The button was vandalised by a spammer last night, so I've banned them and vreverted the change this morning.

**Comment by uncannyjish** [comment]
> 
> 
> Thanks for reporting this. The button was vandalised by a spammer last night, so I've banned them and reverted the change this morning.

No problem. I love this site a lot. Was really surprised to see such an issue. Thank you for fixing it at the earliest.
