### ISSUE TITLE
Page title overflow on mobile

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/kuma#7608]
**Summary**
The container overflows in mobile due to the title lenght

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Visit from a mobile phone a page that has a long title.

**Actual behavior**

**Expected behavior**
A solution that fix the max with to 100% and breacks the title in multiple lines.

**Additional context**
![Screenshot_20201108-060109.png](https://user-images.githubusercontent.com/44380480/98457555-f2efc200-2188-11eb-9265-259b61f811c8.png)

**Comment by peterbe** [comment]
Thank you but that design is not going to be fixed. Instead, we're moving our attention to Project Yari. 
Use https://developer.allizom.org/en-US/docs/Web/API/Element/requestFullScreen to test (for example).
