### ISSUE TITLE
The logo is cropped

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/kuma#7609]
**Summary**
When You are in mobile and logged in, the logo is cropped

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Log in from mobile
2. Visit a general page

**Actual behavior**
Logo is cropped

**Expected behavior**
Logo should not be cropped

**Additional context**
If the header is flex try to do not shrink the logo.

![Screenshot_20201108-061508.png](https://user-images.githubusercontent.com/44380480/98457673-15cea600-218a-11eb-8019-8bac15f71d99.png)

**Comment by escattone** [comment]
@mattiapontonio I don't see this problem when using Firefox or Chrome on my iPhone. Can you specify the platform (Android?) and browser(s) you're seeing this on? Thanks!

**Comment by mattiapontonio** [comment]
Chrome 86 on Android 10
Motorola Moto G

**Comment by peterbe** [comment]
I think we should close this. It's unlikely that we'll have the time and energy to fix styling issues, for mobile, on Kuma. It's only 15% of our traffic and the future lies with Yari instead. What do you say @escattone ?

**Comment by mattiapontonio** [comment]
I didnt understand.
Yari Is the new Front End that Will replace the actual one?

**Comment by peterbe** [comment]
> I didnt understand.
> Yari Is the new Front End that Will replace the actual one?

It's a rewrite of MDN but to make the transition easier, there should be very little visual difference. So same outside, entirely different inside.

**Comment by escattone** [comment]
Yes, we won't fix this in Kuma, but we will fix it in Yari if it exists there. @mattiapontonio does this issue still exist for you when you visit https://developer.allizom.org/en-US/docs/Web/CSS/flex-shrink (https://developer.allizom.org is Yari)?

**Comment by mattiapontonio** [comment]
@escattone no.
