### ISSUE TITLE
Browser compatibility - button is over the data

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/kuma#7610]
**Summary**
The button is over the data

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Visit from mobile some browser compatibility section

**Actual behavior**
Button Is over the data

**Expected behavior**
Button is near the data

**Additional context**
Should be resolved making them siblings

![Screenshot_20201108-062232.png](https://user-images.githubusercontent.com/44380480/98457929-c6897500-218b-11eb-82a8-c4b59a96c538.png)
![Screenshot_20201108-062253.png](https://user-images.githubusercontent.com/44380480/98457931-c9846580-218b-11eb-9564-c46bea0ae7c2.png)
![Screenshot_20201108-062302.png](https://user-images.githubusercontent.com/44380480/98457932-cc7f5600-218b-11eb-9110-8687cb1c278b.png)

**Comment by peterbe** [comment]
@mattiapontonio 
Can you reproduce this on whichever URL you used but replace `mozilla` for `allizom` (our staging site, the word "mozilla" backwards). Still a problem? If so, let's transfer this issue over to `mdn/yari`.

**Comment by mattiapontonio** [comment]
In `allizom` there is no table.

**Comment by peterbe** [comment]
We fixed that. Hours ago. But I guess we'll have to wait for the new build which I suspect will come in tomorrow.

**Comment by mattiapontonio** [comment]
I did see that if logged in is present.
