### ISSUE TITLE
Link Not Working

### ISSUE THREAD

**Issue by uncannyjish** [mdn/kuma#7614]
**Summary**
_What is the problem?_
The following link is not working - https://teach.mozilla.org/activities/web-lit-basics/

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Open the link - https://teach.mozilla.org/activities/web-lit-basics/
2. It would fail loading.
3. 

**Actual behavior**
_What actually happened?_
The browser would end up failing to load the page.

**Expected behavior**
_What did you expect to happen?_
The browser should open the page.

**Additional context**
_Is there anything else we should know?_

**Comment by peterbe** [comment]
@uncannyjish Does that have anything to do with [MDN Web Docs](https://developer.mozilla.org)?

**Comment by uncannyjish** [comment]
> 
> 
> @uncannyjish Does that have anything to do with [MDN Web Docs](https://developer.mozilla.org)?

This link is provided as reference at multiple places.

**Comment by chrisdavidmills** [comment]
I've tried the link, and it works for me. Well, it goes through to https://foundation.mozilla.org/en/initiatives/web-literacy/, which is the new location of this resource.

**Comment by peterbe** [comment]
Seems like a content problem. Perhaps the link was failing there temporarily but seems to work now. 
If the link is the wrong link, it can be fixed in the content.
