### ISSUE TITLE
Thunderbird can NOT send emails from Microsoft Products - word

### ISSUE THREAD

**Issue by double2dodge** [mdn/kuma#7616]
**Summary**
Thunderbird can not be activated from Microsoft word to send a doc as an email ...

**Actual behavior**
Word tries to open a outlook option ;....  even Thunderbird is designated email program in Windows

**Expected behavior**
_What did you expect to happen?_  expected to be able to send email via Thunderbird

**Additional context**
Yes...   When will Thunderbird be able to be used as email sender from Microsoft programs ...

**Comment by chrisdavidmills** [comment]
Hi there @double2dodge .

This repo has nothing to do with Thunderbird — this is related to the https://developer.mozilla.org/en-US/ website.

I'd suggest you refile your query under a Thunderbird-related repo, or other help mechanism.
