### ISSUE TITLE
Navigator.share only working once in iOS, second click throws error

### ISSUE THREAD

**Issue by erensogut543** [mdn/kuma#7618]
**Summary**
Navigator.share only working once in iOS, second click throws error “request is not allowed by the user agent…”

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. You should try to call navigator.share() method twice on IOS

**Actual behavior**
_What actually happened?_
Throws an error

**Expected behavior**
Shoul be opened sharing popup

**Additional context**
You should look at the stackoverflow issue: https://stackoverflow.com/questions/64055853/navigator-share-only-working-once-in-ios-second-click-throws-error-request-is

**Comment by peterbe** [comment]
Is this related to a specific page on https://developer.mozilla.org?
