### ISSUE TITLE
nsILoginManager is not storing passwords

### ISSUE THREAD

**Issue by lbphp** [mdn/kuma#7619]
**Summary**
_What support task would you like completed by the team?_

Please take a look at the issue i posted on bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1676873
They don't give dev support on bugzilla, so i am writing here on github

**Due Date**
_When would you like this task completed by?_
By December 2020

**Comment by peterbe** [comment]
Try https://support.mozilla.org/en-US/ if you have a support question.
