### ISSUE TITLE
there is a black block problem after latest update

### ISSUE THREAD

**Issue by mehdisafavi** [mdn/kuma#7628]
**Summary**
_What is the problem?_
there is a black box problem after latest update and it shown in random places.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_
it is random behavior . 
1. 
2. 
3. 

**Actual behavior**
_What actually happened?_
display black box inside of page content

**Expected behavior**
_What did you expect to happen?_

   
**Additional context**
_Is there anything else we should know?_
it may related to page input fields . when i use inputs it di
![blackBlock](https://user-images.githubusercontent.com/9512026/99629998-52ce4e80-2a4e-11eb-8257-547381248876.jpg)
splays again .

**Comment by chrisdavidmills** [comment]
@mehdisafavi are you saying this is a problem after the latest update of Firefox?

This repo contains the code for Kuma, the current engine that powers https://developer.mozilla.org. I has nothing to do with Firefox.

I'll suggest you report this bug in the Mozilla Bugzilla site: https://bugzilla.mozilla.org/home
