### ISSUE TITLE
history.back and history.forward more modular buttons

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/kuma#7632]
# Content Issue
- [X] Correction or update

https://developer.mozilla.org/en-US/docs/Web/API/History/forward
https://developer.mozilla.org/en-US/docs/Web/API/History/back

# Details
We could add ore replace the existing ones with these 2 examples even simpler than the present ones since the current listeners only perform 1 statment.

```html
<button onclick="history.back()">back</button>
<button onclick="history.forward()">forward</button>
```

**Comment by chrisdavidmills** [comment]
True, but MDN code guidelines generally accept inline element handler attributes as a bad practice, so we don't use them.

**Comment by mattiapontonio** [comment]
Ok, with respect It depends. 
They exists. 🙂
