### ISSUE TITLE
Floats are not cleared on https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function

### ISSUE THREAD

**Issue by myakura** [mdn/kuma#7641]
**Summary**

Floats are not cleared on https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function 

![screenshot](https://user-images.githubusercontent.com/413984/100214482-4a48ad00-2f53-11eb-9375-225939865690.png)

**Steps To Reproduce (STR)**

1. go to https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function#Keywords_for_common_cubic-bezier_easing_functions
2. look at the graphs and the following paragraphs

**Actual behavior**

Floats set on images are not cleared.

**Expected behavior**

They should be cleared for readability.

**Additional context**

Each heading has the [`.cleared` class](https://github.com/mdn/kuma/blob/32d287e8d7dd8229cc46007b729bc8650c14befe/kuma/static/styles/components/wiki/_customcss.scss#L118-L120) so they should be cleared... I don't know what's happening.

Also, awkwardly it works as expected on the editing page.

**Comment by escattone** [comment]
@schalkneethling Can you check this out. Do we need this in Yari?

**Comment by schalkneethling** [comment]
Hey @myakura,

Thank you for filing an issue. I had a look and here is my feedback/suggestion.

I notice that the paragraph elements that contain the `img` elements have an inline style of `float: left;` set. We will not be accepting this at all once we launch our new platform. If we need styling like this in the future it should be managed via utility classes provided by the MDN codebase. This is to avoid hard to debug issues and is also an anti-pattern.

I removed those inline styles, and I believe the end result displays well visually. Thoughts?

![Screenshot 2020-12-07 at 14 12 17](https://user-images.githubusercontent.com/10350960/101349920-bce05380-3896-11eb-969b-e1d2d4197d56.png)

/cc @chrisdavidmills

**Comment by myakura** [comment]
Hi @schalkneethling, thanks for investigating.

> I notice that the paragraph elements that contain the `img` elements have an inline style of `float: left;` set. We will not be accepting this at all once we launch our new platform. If we need styling like this in the future it should be managed via utility classes provided by the MDN codebase. This is to avoid hard to debug issues and is also an anti-pattern.
> 
> I removed those inline styles, and I believe the end result displays well visually. Thoughts?

Yeah that looks good. Can't wait to see Yari :)
