### ISSUE TITLE
Positive Feedback

### ISSUE THREAD

**Issue by lvisnaw** [mdn/kuma#7645]
I just wanted to leave positive feedback. I am new to learning Javascript and this site has provided much support in an easy to understand format. I just wanted to say thank you for creating a wonderful resource. It is greatly appreciated. I hope to keep learning and one day be able to contribute to the conversation. You've got my accolades when it comes to suggesting your site as a very useful resource. 

Sorry if this is not the correct place to send my thanks.

**Comment by chrisdavidmills** [comment]
Hi @lvisnaw !

Thank you for your positive feedback — I am so glad that you've found our site useful ;-)

To clarify, are you talking about our learning content at https://developer.mozilla.org/en-US/docs/Learn/JavaScript ? I'd love to hear which parts you liked the most, and if you think anything could be improved upon.
