### ISSUE TITLE
Firefox destroyed Flex box behavior

### ISSUE THREAD

**Issue by kaimakcalan** [mdn/kuma#7646]
**Summary**
Firefox destroyed the way Flex Box is working. Especially the way images are stretched inside a Flex box.
Until recently (at least until 26/10/2020) all images were inserted INSIDE a Flex box in a neat way. Despite their sizes all are stretched INSIDE the Flex box. Firefox was the only browser which accomblished this in a perfect way.
Yesterday (27/11/2020) I discovered that Firefox (version 83.0) lost its ability to stretch the images inside the Flex box. The images overflow out of the Flex box. I'm dissapointed.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Just visit my [TEST](http://users.sch.gr/kodulis/quizJS/testBrowsers.html) page http://users.sch.gr/kodulis/quizJS/testBrowsers.html
2. Click "Insert bull"
3. Click "Insert Hopper"

**Actual behavior**
Inserting more than one images inside the blue box they overflow outside of the box.

**Expected behavior**
I was expecting to see all the images stretched INSIDE the blue box. This was the behavior until recently and only in Firefox.

**Additional context**
Firefox was the last browser which supported this behavior.

**Comment by chrisdavidmills** [comment]
Hi there @kaimakcalan .

This repo contains the platform code for the https://developer.mozilla.org/en-US/ site; it has nothing to do with the Firefox browser.

You'd be better off reporting your Flexbox issue on Mozilla's main bugzilla site: https://bugzilla.mozilla.org
