### ISSUE TITLE
Canvas drawImage documentation errors in optional arguments declaration

### ISSUE THREAD

**Issue by emilfihlman** [mdn/kuma#7650]
**Summary**
The syntax section for drawImage says the last two arguments are optional. They apparently are not.

See for further discussion and marked as wontfix
https://bugs.chromium.org/p/chromium/issues/detail?id=1153479#c3

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @emilfihlman . I've removed the "optional" labels from those arguments, and included comments at the end of the argument descriptions to specify where they are or are not included (e.g. "Note that this argument is not included in the 3- or 5-argument syntax.")

I think that solves this problem, but please feel free to come back to me if you think it needs anything else.

All the best.
