### ISSUE TITLE
Dark mode please

### ISSUE THREAD

**Issue by jdc866** [mdn/kuma#7654]
**Summary**
_What problem would this solve?_
Almost every coding environment supports a dark mode. All white pages are hard on the eyes at night.

**Audience**
_Who has this problem? Everyone? Article authors? Etc._
I'm sure a fair majority would appreciate this option.

**Rationale**
_How do you know that people identified above actually have this problem?_
I see this request all the time for other websites such as social media, etc.

**Workaround**
_How are the people identified above currently handling this problem?_
Dealing with it

**Proposal**
_Do you have suggestions for solving this problem?_
Add a toggle somewhere? Might get a few more folks to sign in if you require that to enable it/make it a profile option

**Additional context**
_Is there anything else we should know?_

**Comment by schalkneethling** [comment]
Thank you for filing an issue @jdc866 - This has been brought up many times before and is something we are considering for the future.

https://github.com/mdn/kuma/issues?q=is%3Aissue+is%3Aclosed+dark+mode+sort%3Acreated-asc
