### ISSUE TITLE
Documentation status and Review pages are not found

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/kuma#7664]
**Preconditions:**
Create and sign in with a contributor account. 

**Steps to reproduce:** 
1. Go to the edit profile page and then select to View profile. 
2. View the Tools menu and select it. 
3. Afterwards, also select the "Review and localize docs" and the "Documentation status" links.

**Expected result:** 
Redirect to https://developer.allizom.org/en-US/docs/MDN/Doc_status and page content is loaded. 
ex: https://developer.mozilla.org/en-US/docs/MDN/Doc_status

**Actual result:**
Page not found message. 

![Doc status Page not Found ](https://user-images.githubusercontent.com/53306802/101513338-bb8d5480-3984-11eb-8b1d-9bae663451af.gif)

**Comment by peterbe** [comment]
@escattone @schalkneethling What do you think, we simply delete the whole "Site Tools" section from that popup?

**Comment by escattone** [comment]
> @escattone @schalkneethling What do you think, we simply delete the whole "Site Tools" section from that popup?

@peterbe @schalkneethling I think we should remove the entire `Tools` menu from the Kuma header. Let's create and merge a Kuma PR to do that, and I'll deploy that on Thursday or Friday. I don't think anyone is going to miss that menu over the weekend, and after that it makes no sense.
