### ISSUE TITLE
New locale isn't redirected to when editing profile

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#7687]
**Summary**
E.g. Go to https://developer.mozilla.org/en-US/profiles/peterbe/edit (use your username) and change your locale to something else. When you hit "Save" it doesn't redirect to the new locale. E.g. https://developer.mozilla.org/sv-SE/profiles/peterbe

**Comment by peterbe** [comment]
I'm tempted to just build the new accounts settings page and ignore this issue.

**Comment by escattone** [comment]
The MDN Web Docs dev team decided to resolve this when we move the account settings page into Yari.
