### ISSUE TITLE
Search results' URLs provide incorrect information about localized page being unavailable / absence of redirect

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/kuma#7688]
Steps to reproduce: 
1. Go to https://developer.mozilla.org/fr/search?q=startsWith (or start a search with "startsWith" from https://developer.mozilla.org/fr/ ) 
2. Click the first link (I got "Getting started with the Web" / https://developer.mozilla.org/fr/docs/Learn/Getting_started_with_the_web

Actual result: 

*  Read the page stating "Page not found ... The page you requested doesn't exist in French but it exists in English" 

Expected result: 

* If we go to https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web and use the locale selector, we can access https://developer.mozilla.org/fr/docs/Apprendre/Commencer_avec_le_web
* Thus, https://developer.mozilla.org/fr/docs/Apprendre/Commencer_avec_le_web should be displayed as available or https://developer.mozilla.org/fr/docs/Learn/Getting_started_with_the_web should redirect

Can also be reproduced with the second link (https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith  which should redirect to https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/String/startsWith ) 

Screenshots: 

![mdn_links_01](https://user-images.githubusercontent.com/2413436/102487747-582db180-406b-11eb-902f-cfec675d681c.png)
![mdn_links_02](https://user-images.githubusercontent.com/2413436/102487750-58c64800-406b-11eb-9ee7-9b563a02b1fa.png)
![mdn_links_03](https://user-images.githubusercontent.com/2413436/102487749-58c64800-406b-11eb-82fa-593edc520ee4.png)

**Comment by peterbe** [comment]
What happened is that it's not a new problem. But with Yari, it becomes a lot more highlighted. 
What Kuma does, is that it takes the `locale` from the current URL and combines it with the `slug` from the (Elasticsearch) search result object. You can see it here: https://github.com/mdn/kuma/blob/3d52c833d35e28b079f3ec252d986915d275ecc0/kuma/javascript/src/search-results-page.jsx#L97

Basically does this:

```javascript
function Results({currentLocale, searchResults}) {
  return {searchResults.map(searchResult => {
     return <a href={`/${currentLocale}/docs/${searchResult.slug}`}>{searchResult.title}</a>
   })
}
```

The reason nobody really noticed before was that Kuma was so forgiving. If you take a one locale string and combine it with a slug, if that combo didn't actually exist in the database, Kuma would quickly just fix it by taking the slug and combining it with `en-US` and most of the time, that would work. 

https://github.com/mdn/kuma/pull/7689 fixes it pretty well. It does this (pseudo code):

```diff
-function Results({currentLocale, searchResults}) {
+function Results({searchResults}) {
  return {searchResults.map(searchResult => {
-    return <a href={`/${currentLocale}/docs/${searchResult.slug}`}>{searchResult.title}</a>
+    return <a href={`/${searchResult.locale}/docs/${searchResult}.slug`}>{searchResult.title}</a>
   })
}
```

In Yari, if you mix and match a `locale` with a `slug`, and that combo doesn't actually exist in `mdn/content`, you get a 404 page. 
And if it can "salvaged" by switching the locale to hardcoded `en-US` you, at least, get that green "Good news!" message.

**Comment by SphinxKnight** [comment]
Let me know if this should be filed under another issue.
Now I get the following result when browsing https://developer.mozilla.org/fr/search?q=startsWith
"2 601 documents trouvés pour « startsWith » dans fr. Affichage des résultats 1 à 10."  (2601 documents found for "startsWith" under fr...)

The thing is none of the results are under /fr/

If there is no easy way to get localized content on that page, I think it would be best to at least remove the mention of the locale.

![image](https://user-images.githubusercontent.com/2413436/102582570-2ec06480-4103-11eb-9fe6-32147d75713e.png)
