### ISSUE TITLE
Add support for Cross-Origin search requests

### ISSUE THREAD

**Issue by Matsuuu** [mdn/kuma#7703]
## Description

I would like to be able to query the MDN Docs as documented [here](https://developer.mozilla.org/en-US/docs/MDN/Tools/Search#Search_query_format)

## Reason

I am currently developing a front-end component which would be able to search the MDN docs, and as it's hosted on a different domain from the MDN docs, a CORS error ensues

## Steps to re-produce:

- Open Dev Console on a page that isn't under `developer.mozilla.org`
- Run `fetch("https://developer.mozilla.org/api/v1/search/en-US?q=History%20Api")`

#### What should happen

A successful request should go through and return JSON data

#### What happens

An error in the request with the classic CORS error message

```
Access to fetch at 'https://developer.mozilla.org/api/v1/search/en-US?q=History%20Api' from origin 'https://matsu.fi' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by peterbe** [comment]
I see no reason *not* to do this. Any objections @escattone ?

**Comment by escattone** [comment]
@peterbe I agree. I think we should do this.

**Comment by Matsuuu** [comment]
Thanks so much for the fast update!

Is there any estimate when this is going to hit prod? @peterbe

**Comment by escattone** [comment]
@Matsuuu This is on production as of around 7:30am Pacific time.

**Comment by mir863** [comment]
Me interesa llame

1234
