### ISSUE TITLE
Search finds results in English only (following up #7688)

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/kuma#7704]
**Summary**
When browsing https://developer.mozilla.org/fr/ (resp. <locale>) and using the search form, every result points to an English even though matching pages exist in fr (resp. <locale>).

This issue is opened after #7688 has been closed.

**Steps To Reproduce (STR)**

1. Go to https://developer.mozilla.org/fr/search?q=startsWith
 

**Actual behavior**

* The results' page displays "2 601 documents trouvés pour « startsWith » dans fr." (aka 2 601 documents found for "startsWith" under fr)
* All of the results are under /en-US/

**Expected behavior**

* Results matching the query in the locale (e.g. having https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/String/startsWith in the list of found pages)

**Additional context**

This issue is a kind of follow-up for https://github.com/mdn/kuma/issues/7688#issuecomment-747898813

**Comment by peterbe** [comment]
I'm working on this and I have a prototype. But it depends on https://github.com/mdn/yari/issues/2410 and

**Comment by peterbe** [comment]
https://developer.mozilla.org/fr/search?q=startsWith works now!
