### ISSUE TITLE
Some pages on MDN Web Docs are not displayed correctly (blank page) in Firefox v56

### ISSUE THREAD

**Issue by Lumox100** [mdn/kuma#7711]
**Summary**
_What is the problem?_
I was looking for information on the property currentSrc for images but when I open the page
          https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/currentSrc
it flashes up and then goes to a blank page.
But other MDN docs display correctly
          https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API

The web page displays correctly in the latest version of Firefox but I use Firefox v56 still because it has legacy add-ons that do not work in the latest version of Firefox. But why do some web pages work correctly but others do not?

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Open Firefox v56
2. Go to page https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/currentSrc
3. 

**Actual behavior**
_What actually happened?_
Blank page

**Expected behavior**
_What did you expect to happen?_
Web page should be diaplayed correctly.

**Additional context**
_Is there anything else we should know?_

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/yari #2353](https://github.com/mdn/yari/issues/2353) via [**ZenHub**](https://www.zenhub.com/)
