### ISSUE TITLE
Is 'ngx-image-cropper' supports camera functionality in Firefox for angular7-ionic4?

### ISSUE THREAD

**Issue by sunakshiUIDeveloper** [mdn/kuma#7714]
I am using ngx-image-cropper plugin for crop functionality.Its working fine for camera and gallery both in chrome and in opera browsers.But camera is not working with Firefox. I am using Angular 7 and ionic 4. It doesn't load any image if i click from camera.In case of gallery ,it is working fine.

**Comment by peterbe** [comment]
Has nothing to do with MDN Web Docs.
