### ISSUE TITLE
 'ngx-image-cropper' does not supports camera functionality in Firefox for angular7-ionic4

### ISSUE THREAD

**Issue by sunakshiUIDeveloper** [mdn/kuma#7715]
I am using ngx-image-cropper plugin for crop functionality.Its working fine for camera and gallery both in chrome and in opera browsers.But camera is not working with Firefox. I am using Angular 7 and ionic 4. It doesn't load any image if i click from camera.In case of gallery ,it is working fine.

In some phones,its is not even showing camera option.Even if camera access is allowed

**Comment by escattone** [comment]
@sunakshiUIDeveloper These issues are for MDN (https://developer.mozilla.org), but I suspect you wanted to report this issue to the Firefox team? If so, you should go to https://bugzilla.mozilla.org/describecomponents.cgi.
