### ISSUE TITLE
Delete BCSignal data

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma#7728]
**Summary**
Delete the model, the Admin model, and all the data. 

Since https://github.com/mdn/kuma/issues/7721 we shut down the ability to collect more [BC Signals](https://developer.mozilla.org/admin/wiki/bcsignal/). As time passes, the (good/valid) records in there are slowly getting less and less relevant.

**Comment by escattone** [comment]
@Elchi3 @ddbeck What do you think about this data? The data is backed-up, so there's no question about losing it. Is it useful to keep for a while longer, or might we be able to delete it?

**Comment by Elchi3** [comment]
Peter is right about the feedback to outdate over time.

Also, as said in https://github.com/mdn/kuma/issues/7721#issuecomment-757452921, the data isn't really meant to be public (I guess it is PII data as you could identify people given some of the info they provide in free form). So, I guess I would need to sign an NDA or so with the Mozilla Corporation and so that seems not worth it for me ;-)

I'd say delete it or export it to a google spreadsheet and let it live there until it gets archived or so.

**Comment by peterbe** [comment]
A Google Spreadsheet is a great idea! Much more convenient than a CSV file and Google has a great system for authorization. Let's do that!

**Comment by peterbe** [comment]
@Elchi3 let me know, by email, which email I should use for you to give you outside-Mozilla access to 
https://docs.google.com/spreadsheets/d/1Hg6jvOYl4t3MgNlGFRJuP95vyA9aNWxODskNm8QyVXQ/edit#gid=616112047

With that exported, we can at least know that the data is safe (in double meaning: secure and not lost).

**Comment by Elchi3** [comment]
> @Elchi3 let me know, by email, which email I should use for you to give you outside-Mozilla access to
> https://docs.google.com/spreadsheets/d/1Hg6jvOYl4t3MgNlGFRJuP95vyA9aNWxODskNm8QyVXQ/edit#gid=616112047

As I said above, please don't share it and treat me as a third party with whom you aren't supposed to share this with. (When I was still with the Mozilla Corporation I was advised to not share this data with third party either as MDN users who provided this signal data have not agreed to share it with external people).

> With that exported, we can at least know that the data is safe (in double meaning: secure and not lost).

I'm glad to hear that!

**Comment by peterbe** [comment]
> > @Elchi3 let me know, by email, which email I should use for you to give you outside-Mozilla access to
> > https://docs.google.com/spreadsheets/d/1Hg6jvOYl4t3MgNlGFRJuP95vyA9aNWxODskNm8QyVXQ/edit#gid=616112047
> 
> As I said above, please don't share it and treat me as a third party with whom you aren't supposed to share this with. (When I was still with the Mozilla Corporation I was advised to not share this data with third party either as MDN users who provided this signal data have not agreed to share it with external people).
> 
> > With that exported, we can at least know that the data is safe (in double meaning: secure and not lost).
> 
> I'm glad to hear that!

I put a big loud note in the spreadsheet as a reminder, basically, to all Mozilla corp authenticated people to not share it.
