### ISSUE TITLE
Http error bad request (400) on the api key page

### ISSUE THREAD

**Issue by SirMishaa** [mdn/kuma#7744]
**Summary**
When I log in and go to my profile and click on the gear and then click on "Keys api", I get an http 400 error.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Log in
2. Go to your profile
3. Click on the gear then click on "Keys api"

**Actual behavior**
Bad request error (400)

**Expected behavior**
This should display the page that allows you to manage api keys and return an http code 200

**Additional context**
I am connected with Github, under Firefox 85.0. 
![image](https://user-images.githubusercontent.com/42717232/105378472-254b8000-5c0c-11eb-8ac6-2c06f3812a7b.png)

**Comment by escattone** [comment]
@SirMishaa Thank you for reporting this! We're already in the process of changing the user profile page, so this will be fixed soon. In the new non-Wiki world of MDN, we no longer use API keys, so that functionality will be removed.

**Comment by SirMishaa** [comment]
Okay, thanks for the prompt response. 

Will it still be possible to recover data from the api? 

For my part, I need to retrieve accurate information about Javascript and having an api available is very convenient.

**Comment by escattone** [comment]
> Will it still be possible to recover data from the api?

@SirMishaa I'm sorry, but we no longer support the `$api` endpoint as well as all of the other `$` endpoints, like the `$json` document endpoint. You probably already know this, but https://github.com/mdn/yari is the new platform for MDN Web Docs and https://github.com/mdn/content is where the content is now managed.

**Comment by SirMishaa** [comment]
Okay, no problem.

Thanks for the answer.
