### ISSUE TITLE
🧹 Remove hompage related frontend code

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#7749]
Once https://github.com/mdn/yari/issues/2438 lands, we need to go into the Kuma forest and find all things related to the homepage frontend code, chop it down, and clear it out.

**Comment by peterbe** [comment]
I think we should instead delete ALL front-end code. Absolutely everything. Every .scss and every .js and all the hacky solutions in `settings/common.py` related to django-pipeline. 
The only "HTML'y" thing worth keeping is the Django Admin and I think that's not using any tricky tricks.

**Comment by schalkneethling** [comment]
> I think we should instead delete ALL front-end code. Absolutely everything. Every .scss and every .js and all the hacky solutions in `settings/common.py` related to django-pipeline.
> The only "HTML'y" thing worth keeping is the Django Admin and I think that's not using any tricky tricks.

Agreed, but I was thinking of doing it carefully and piece by piece as we implement and roll out the relevant pieces on Yari.

**Comment by peterbe** [comment]
What we can do is what Ryan did here: https://github.com/mdn/kuma/pull/7746
Just many little PRs (which is sane) that deal with some small little slice and just keep saying `Part of #7740`
