### ISSUE TITLE
Footer On Sign In Page Does Not Match The Rest Of The Site

### ISSUE THREAD

**Issue by bensternthal** [mdn/kuma#7808]
**Summary**
The footer on the sign in page looks very different from the rest of the site.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Visit https://developer.mozilla.org/en-US/users/account/signup-landing

**Additional context**
<img width="1493" alt="Screen Shot 2021-03-09 at 1 27 28 PM" src="https://user-images.githubusercontent.com/198507/110540573-83a8c100-80db-11eb-90c6-f80aab80c630.png">

**Comment by escattone** [comment]
@bensternthal That page (and the sign-up and account setttings pages) are the only remaining pages that use the Kuma front-end. We're currently working on the Yari-built version of each of these pages, which should go live sometime next week. I'll keep this open until that time.

**Comment by peterbe** [comment]
https://developer.mozilla.org/en-US/users/account/signup-landing is actually still working. The only way to get to that page would be to know that URL (or, ironically clicking on it here in this issue). 
But we shouldn't be showing I don't think. 

@escattone what do you think about hardcoding a redirect on that page to `/$locale/sign-in`? Perhaps in fundamental-redirects so it just works everywhere. 
We just have to careful to make sure it's only for that exact suffix (`signup-landing`) and not `/*/users/` or `/users/*`.

**Comment by escattone** [comment]
@peterbe I think we shouldn't work on this, because my kuma de-construction work removes this endpoint altogether, and I'd rather not redirect unless you think we have to.
