### ISSUE TITLE
Relevant results not being found in MDN Docs search

### ISSUE THREAD

**Issue by johnbotris** [mdn/kuma#7816]
**Summary**
When searching for WebAPI APIs in MDN, I'm not getting relevant results, regardless of whether sorting by popular/relevance/best

**Steps To Reproduce (STR)**
Search for some JS API such as Array, Map, String etc in MDN docs

**Actual behavior**
The most relevant page is not returned as a result, rather a bunch of results which just have the search term somewhere in the body

**Expected behavior**
The exactly matching page should be the one that is returned first, or at least near the top

**Additional context**

Example: 
![Screenshot from 2021-03-29 10-35-07](https://user-images.githubusercontent.com/22109738/112809601-76e41100-907a-11eb-8e95-f58a576137d4.png)

trust that none of the omitted results are the page for Array either

Some work better than others, such as Document which is the first result when sorted by relevance

**Comment by peterbe** [comment]
Yep. We're working on it. It started going wrong on Friday of last week and hasn't managed to get it working yet. 
It's our top priority right now. 

Also, https://github.com/mdn/yari/issues/3359 is the same problem.

**Comment by escattone** [comment]
@johnbotris Thanks for reporting this (as others have done as well). This should be resolved now.
