### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by gsnedders** [mdn/kuma#7982]
The README.md claims:

> Kuma is the platform that powers MDN (developer.mozilla.org)

This isn't true. The README should be accurate and describe the current status of Kuma and any usage of it (I presume there is usage given some people appear to still be contributing?), and probably should link to Yari too.

People asking about how to do things in Kuma for the live MDN sites happens every so often in https://matrix.to/#/#mdn:mozilla.org, so there's definitely some degree of people being confused by this.

**Comment by escattone** [comment]
@gsnedders Thanks, yes, we definitely need to update the README. Kuma is still used, but now instead of being the "platform that powers MDN", it's the platform that provides MDN's API services.

**Comment by caugner** [comment]
Kuma has been replaced by [Rumba](https://github.com/mdn/rumba) in the mean-time, and the README is now updated accordingly.
