### ISSUE TITLE
dennis: end-of-life

### ISSUE THREAD

**Issue by willkg** [mdn/kuma#8063]
I'm the current maintainer of [dennis](https://github.com/willkg/dennis). I'm maintaining too many things and I haven't used Dennis in years, so I'm looking at either:

1. passing maintenance to someone else
2. or, ending the project

Dennis is used in this project to lint PO files. If you're interested in taking over maintenance, that'd be great! If no one takes over, I'll shut down the project in May 2022.

**Comment by caugner** [comment]
FYI Kuma is deprecated, so MDN no longer depends on [dennis](https://github.com/willkg/dennis).
